### PR TITLE
Bump protobuf to 3.19.2

### PR DESCRIPTION
**Pull request by nipunn1313**

### CODE REVIEW

**Comment by nipunn1313** [comment]
pulling easy part of #6677 into a separate diff

**Review by JelleZijlstra — APPROVED** [review]

**Review by srittau — COMMENTED** [review]
Minor nit: `ByteString` in argument types can be abbreviated as `bytes`.

**Comment by nipunn1313** [comment]
I took a look and it seemed like they were slightly different. It seemed that ByteString was anything impling `Sequence[int]`

Seems like the source specifically describes that it could be anything impling that
https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/message.py#L171

I might be missing something, but that's why I left it that way.

**Comment by srittau** [comment]
For typing purposes they are identical in argument positions:

> class typing.ByteString(Sequence[int])
> A generic version of collections.abc.ByteString.
> 
> This type represents the types bytes, bytearray, and memoryview of byte sequences.
> 
> As a shorthand for this type, bytes can be used to annotate arguments of any of the types mentioned above.

From https://docs.python.org/3/library/typing.html?highlight=bytestring#typing.ByteString

**Comment by nipunn1313** [comment]
Updated! Thanks for the tip @srittau

**Review by srittau — APPROVED** [review]

**Pull request merged**
