### PR TITLE
zip: add some overloads for heterogeneous tuples

### PR DESCRIPTION
**Pull request by hauntsaninja**
Technically this is a lie, since we return a heterogeneous iterator, not
a tuple. But since we don't have a way of typing heterogeneous
iterators, this is the best we can do.

Fixes https://github.com/python/mypy/issues/8454

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Could you fix the various CI failures?

**Comment by hauntsaninja** [comment]
Suspected we'd see some issues. I think the best option here is to type ignore...

**Comment by hauntsaninja** [comment]
Gentle bump!

**Comment by ilevkivskyi** [comment]
> Technically this is a lie

It looks like this needs to be reverted because lies break mypyc, see [CI failure](https://travis-ci.org/github/python/mypy/jobs/683363097) (unless @msullivan has an idea for workaround).

**Comment by hauntsaninja** [comment]
Would changing the return type to `Union[Any, <...>]` work?

**Comment by ilevkivskyi** [comment]
For now we are using `cast(Any, zip)` just to unblock the situation, see https://github.com/python/mypy/pull/8780. But we need to find a better long-term solution.

**Comment by hauntsaninja** [comment]
Note, this was reverted in https://github.com/python/typeshed/pull/4254

**Pull request merged**
