### PR TITLE
Add 'nis' to stubtest allowlist

### PR DESCRIPTION
**Pull request by srittau**
It doesn't exist on Ubuntu 24.04.

### CODE REVIEW

**Review by AlexWaygood — COMMENTED** [review]
Can't you just add a single allowlist entry to https://github.com/python/typeshed/blob/main/stdlib/%40tests/stubtest_allowlists/linux.txt?

**Comment by srittau** [comment]
The module was removed in 3.13 and this prevents us from forgetting to remove the entry. (Since the regexp shouldn't trigger stubtest's unnecessary stubtest entry warning.)

**Comment by AlexWaygood** [comment]
Stubtest would complain about it on 3.13 if the allowlist entry was just `nis`, but `(nis)?` shouldn't trigger a stubtest complaint on 3.13, because of the question mark (I believe)

**Comment by srittau** [comment]
> Stubtest would complain about it on 3.13 if the allowlist entry was just `nis`, but `(nis)?` shouldn't trigger a stubtest complaint on 3.13, because of the question mark (I believe)

Exactly.

**Comment by AlexWaygood** [comment]
Oh, sorry, now I see what you mean.

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
