### PR TITLE
Improve distutils

### PR DESCRIPTION
**Pull request by tharvik**
Add the whole distutils hierarchy. Also, merge py2 and py3 version of old stubs.

There is a bunch of empty file, it is because the documentations advertise the module but there isn't any definition in it, so importable but useless (let's respect the doc).

Currently failling because of [pytype#30](https://github.com/google/pytype/issues/30).

### CODE REVIEW

**Comment by matthiaskramm** [comment]
We'll export a fix for https://github.com/google/pytype/issues/30 today.

**Comment by tharvik** [comment]
Nice! I won't be able to update the PR for some days, so feel free to take over.

**Comment by matthiaskramm** [comment]
Closing and reopening, to force a Travis rebuild.

**Comment by matthiaskramm** [comment]
Travis is still broken, seems we need to remove some unwarranted `# type: ignore` directives.

**Comment by tharvik** [comment]
I rebased it on master, as 4c20cd6 removed the `type: ignore` in mmap; there is still this issue about having `@abstractmethod` which isn't supported by pytype, just opened [pytype#32](https://github.com/google/pytype/issues/32).

**Comment by tharvik** [comment]
[pytype#32](https://github.com/google/pytype/issues/32) is fixed and this part is working, but [pytype#33](https://github.com/google/pytype/issues/33) happened.

**Comment by alvarocaceres** [comment]
my fault -- a pytype update broke travis.. Will check next time. PR #430 should make travis green...

**Comment by tharvik** [comment]
#430 indeed makes it work.

**Pull request merged**
