### PR TITLE
paramiko - A Python implementation of SSHv2

### PR DESCRIPTION
**Pull request by pmhahn**
paramiko - A Python implementation of SSHv2

Code: <https://github.com/paramiko/paramiko>
Doc: <http://docs.paramiko.org/en/stable/index.html>

The API documentation is still from the Python 2 and uses `str` in many
cases where in Python it is `bytes`: There may be more error. I
generated and verified most of them using
    SSH_AUTH_SOCK= python3 -m pytest --annotate-output=./annotate.json
but I may have missed several cases.

Do to the use of the internal `py3compat.py` many functions also accept
`unicode()` and `bytes()`: How to best handle this?

The Windows API may need more work: I only had a short look; at least
`pytype` fails for `_winapi.pyi` as it declares a sub-class of
WindowsError which is only available on platform "win32", while the test
runs on Linux.

The `paramiko.*key` files all declare a `generate(…,process_func)` function ready to
accept a callable for progress reporting, which is currently unused. I
declares the options as `Optional[Callable[..., Any]]`

### CODE REVIEW

**Comment by srittau** [comment]
Do you personally need the Python 2 version? Otherwise, I'd suggest to just support Python 3, which makes a lot of things easier.

> Do to the use of the internal py3compat.py many functions also accept
unicode() and bytes(): How to best handle this?

What do you mean? `Union[Text, bytes]` is usually used when `str` and `bytes` is accepted in Python 3, otherwise just `Text` is fine.

**Comment by pmhahn** [comment]
> Do you personally need the Python 2 version? Otherwise, I'd suggest to just support Python 3, which makes a lot of things easier.

Some of my project are still Python 2 based.

> > Do to the use of the internal py3compat.py many functions also accept
> > unicode() and bytes(): How to best handle this?
> 
> What do you mean? `Union[Text, bytes]` is usually used when `str` and `bytes` is accepted in Python 3, otherwise just `Text` is fine.

I'll do another review of my code and use `Unicode[Text, bytes]` where appropriate.

Already thank your for the feedback @srittau

**Comment by hauntsaninja** [comment]
stubtest has some complaints, many of which look worth fixing:

<details>

```
(typeshed) ~/dev/typeshed paramiko λ stubtest paramiko --custom-typeshed-dir ~/dev/typeshed 
error: paramiko.ConfigParseError is not present in stub
Stub:
MISSING
Runtime: at line 211 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/ssh_exception.py
<class 'paramiko.ssh_exception.ConfigParseError'>

error: paramiko.CouldNotCanonicalize is not present in stub
Stub:
MISSING
Runtime: at line 201 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/ssh_exception.py
<class 'paramiko.ssh_exception.CouldNotCanonicalize'>

error: paramiko.ECDSAKey is not present in stub
Stub:
MISSING
Runtime: at line 95 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/ecdsakey.py
<class 'paramiko.ecdsakey.ECDSAKey'>

error: paramiko.Ed25519Key is not present in stub
Stub:
MISSING
Runtime: at line 30 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/ed25519key.py
<class 'paramiko.ed25519key.Ed25519Key'>

error: paramiko.PKey.BEGIN_TAG is not present in stub
Stub:
MISSING
Runtime:
re.compile('^-{5}BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-{5}\\s*$')

error: paramiko.PKey.END_TAG is not present in stub
Stub:
MISSING
Runtime:
re.compile('^-{5}END (RSA|DSA|EC|OPENSSH) PRIVATE KEY-{5}\\s*$')

error: paramiko.SFTPServer.__init__ is inconsistent, runtime argument "sftp_si" has a default value but stub argument does not
Stub: at line 20
def (self: paramiko.sftp_server.SFTPServer, channel: paramiko.channel.Channel, name: builtins.str, server: paramiko.sftp_si.SFTPServerInterface, sftp_si: Type[paramiko.sftp_si.SFTPServerInterface], *largs: Any, **kwargs: Any)
Runtime: at line 94 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/sftp_server.py
def (self, channel, name, server, sftp_si=<class 'paramiko.sftp_si.SFTPServerInterface'>, *largs, **kwargs)

error: paramiko.SSHConfig.TOKENS_BY_CONFIG_KEY is not present in stub
Stub:
MISSING
Runtime:
{'controlpath': ['%h', '%l', '%L', '%n', '%p', '%r', '%u'], 'hostname': ['%h'], 'identityfile': ['~', '%d', '%h', '%l', '%u', '%r'], 'proxycommand': ['~', '%h', '%p', '%r'], 'match-exec': ['%d', '%h', '%L', '%l', '%n', '%p', '%r', '%u']}

error: paramiko.SSHConfigDict is not present in stub
Stub:
MISSING
Runtime: at line 623 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/config.py
<class 'paramiko.config.SSHConfigDict'>

error: paramiko.util is not present in stub
Stub:
MISSING
Runtime: in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/util.py
<module 'paramiko.util' from '/Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/util.py'>

error: paramiko._winapi failed to import: _type_ 'v' not supported
Stub: at line 1
MypyFile:1(
  /Users/shantanu/dev/typeshed/third_party/2and3/paramiko/_winapi.pyi)
Runtime:
MISSING

error: paramiko.config.SSHConfig.TOKENS_BY_CONFIG_KEY is not present in stub
Stub:
MISSING
Runtime:
{'controlpath': ['%h', '%l', '%L', '%n', '%p', '%r', '%u'], 'hostname': ['%h'], 'identityfile': ['~', '%d', '%h', '%l', '%u', '%r'], 'proxycommand': ['~', '%h', '%p', '%r'], 'match-exec': ['%d', '%h', '%L', '%l', '%n', '%p', '%r', '%u']}

error: paramiko.ecdsakey.EllipticCurve is not present at runtime
Stub: at line -1
Any
Runtime:
MISSING

error: paramiko.hostkeys.MM is not present at runtime
Stub: at line 436
<TypeInfo typing.MutableMapping>
Runtime:
MISSING

error: paramiko.kex_ecdh_nist.EllipticCurve is not present at runtime
Stub: at line -1
Any
Runtime:
MISSING

error: paramiko.kex_ecdh_nist.EllipticCurvePrivateKey is not present at runtime
Stub: at line -1
Any
Runtime:
MISSING

error: paramiko.kex_ecdh_nist.EllipticCurvePublicKey is not present at runtime
Stub: at line -1
Any
Runtime:
MISSING

error: paramiko.kex_group1.b0000000000000000 variable differs from runtime type Literal[bb'\x00\x00\x00\x00\x00\x00\x00\x00']
Stub: at line 15
builtins.int
Runtime:
b'\x00\x00\x00\x00\x00\x00\x00\x00'

error: paramiko.kex_group1.b7fffffffffffffff variable differs from runtime type Literal[bb'\x7f\xff\xff\xff\xff\xff\xff\xff']
Stub: at line 14
builtins.int
Runtime:
b'\x7f\xff\xff\xff\xff\xff\xff\xff'

error: paramiko.pkey.PKey.BEGIN_TAG is not present in stub
Stub:
MISSING
Runtime:
re.compile('^-{5}BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-{5}\\s*$')

error: paramiko.pkey.PKey.END_TAG is not present in stub
Stub:
MISSING
Runtime:
re.compile('^-{5}END (RSA|DSA|EC|OPENSSH) PRIVATE KEY-{5}\\s*$')

error: paramiko.py3compat.builtins is not present in stub
Stub:
MISSING
Runtime:
<module 'builtins' (built-in)>

error: paramiko.py3compat.bytes is not present in stub
Stub:
MISSING
Runtime:
<class 'bytes'>

error: paramiko.py3compat.bytestring is not present at runtime
Stub: at line 22
def (s: Any) -> Any
Runtime:
MISSING

error: paramiko.py3compat.decodebytes is not present in stub
Stub:
MISSING
Runtime: at line 535 in file /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py
<function decodebytes at 0x10e0a21f0>

error: paramiko.py3compat.encodebytes is not present in stub
Stub:
MISSING
Runtime: at line 524 in file /usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/base64.py
<function encodebytes at 0x10e0a2550>

error: paramiko.py3compat.input is not present in stub
Stub:
MISSING
Runtime:
<built-in function input>

error: paramiko.py3compat.long is not present in stub
Stub:
MISSING
Runtime: at line 114 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/py3compat.py
<class 'paramiko.py3compat.long'>

error: paramiko.py3compat.next is not present in stub
Stub:
MISSING
Runtime:
<built-in function next>

error: paramiko.sftp_server.SFTPServer.__init__ is inconsistent, runtime argument "sftp_si" has a default value but stub argument does not
Stub: at line 20
def (self: paramiko.sftp_server.SFTPServer, channel: paramiko.channel.Channel, name: builtins.str, server: paramiko.sftp_si.SFTPServerInterface, sftp_si: Type[paramiko.sftp_si.SFTPServerInterface], *largs: Any, **kwargs: Any)
Runtime: at line 94 in file /Users/shantanu/.virtualenvs/typeshed/lib/python3.9/site-packages/paramiko/sftp_server.py
def (self, channel, name, server, sftp_si=<class 'paramiko.sftp_si.SFTPServerInterface'>, *largs, **kwargs)

error: paramiko.ssh_gss.GSS_EXCEPTIONS variable differs from runtime type Tuple[]
Stub: at line 6
builtins.str
Runtime:
()

error: paramiko.win_pageant failed to import: _type_ 'v' not supported
Stub: at line 1
MypyFile:1(
  /Users/shantanu/dev/typeshed/third_party/2and3/paramiko/win_pageant.pyi)
Runtime:
MISSING
```
</details>

**Comment by pmhahn** [comment]
> stubtest has some complaints, many of which look worth fixing:
Is it okay to ignore `py3comat`, which contains several internal helper functions for handling the Python 2/3 differences, which are a pain to get right?

**Comment by hauntsaninja** [comment]
Yeah, ignoring py3compat seems fine to me

**Review by srittau — APPROVED** [review]
Looks good on a cursory glance.

**Pull request merged**
