### PR TITLE
pkg_resources is part of setuptools

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by Akuli** [comment]
What's going to happen to https://pypi.org/project/types-pkg-resources/ ?

**Comment by JukkaL** [comment]
> What's going to happen to https://pypi.org/project/types-pkg-resources/ ?

I assume it will stay on PyPI indefinitely but won't get any updates. Probably it's being used already, and we don't want to break things for users.

**Review by JukkaL — APPROVED** [review]
Yeah, `pkg_resources` seems to be installed by `setuptools` and there is no PyPI package called `pkg_resources.

**Comment by JelleZijlstra** [comment]
But if people install both `pkg_resources-types` and `setuptools-types`, both packages will install into the same directory (`pkg_resources-stubs`). That could lead to confusing behavior.

**Comment by JukkaL** [comment]
@JelleZijlstra That's a fair point. The original project name was plain wrong though, so perhaps we just need to live with it. Alternatively, we could upload a new version of `types-pkg-resources` that is empty and just depends on `types-setuptools`.

**Comment by srittau** [comment]
I was thinking about this before, especially in relation to the other packages we renamed, and basically had the same idea as Jukka. We should probably add a small script to stub_uploader which we can use to generate "renamed" packages consistently. Maybe something similar for removed packages, where types are now shipped upstream.

**Pull request merged**
