### PR TITLE
Added object.__sizeof__

### PR DESCRIPTION
**Pull request by vlasovskikh**

### CODE REVIEW

**Comment by ambv** [comment]
Would you be willing to clean up the following while you're at it?
```
stdlib/2/sqlite3/dbapi2.pyi
232:    def __sizeof__(self): ...

stdlib/3/decimal.pyi
227:    def __sizeof__(self) -> int: ...

stdlib/3/sqlite3/dbapi2.pyi
232:    def __sizeof__(self): ...
```

**Comment by vlasovskikh** [comment]
@ambv Sure, fixed.

**Comment by ambv** [comment]
All changes very useful, thank you!

**Comment by vlasovskikh** [comment]
@ambv Thanks for your quick reviews!

**Pull request merged**
