### PR TITLE
fix(`stdlib.xml`): re-export ContentHandler

### PR DESCRIPTION
**Pull request by raprocks**
fixes python/typeshed#8107

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
The documentation only mentions it as `xml.sax.handler.ContentHandler` (https://docs.python.org/3.10/library/xml.sax.handler.html#xml.sax.handler.ContentHandler), but it's imported in `xml.sax.__init__` even though it doesn't get used there directly, so I think we can assume the re-export is intentional.

Should we also re-export ErrorHandler?

**Comment by raprocks** [comment]
i think we should, should i commit with the changes?

**Comment by AlexWaygood** [comment]
> i think we should, should i commit with the changes?

Go for it!

**Comment by raprocks** [comment]
Done!

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
