### PR TITLE
gmtime(None) works

### PR DESCRIPTION
**Pull request by onnokort**
Timeout can be None.

### CODE REVIEW

**Comment by gvanrossum** [comment]
It looks like some other functions here also take None instead of a float. Can you do those as well, instead of just doing one function? And what about the Python 3 stubs?

**Comment by gvanrossum** [comment]
@onnokort Are you interested in improving this PR or not?

**Comment by onnokort** [comment]
Ok, ctime(), localtime() and gmtime() are fixed now to have optional floats in Python2.

Python3 already has Union[float, None] definitions.

**Comment by gvanrossum** [comment]
Thanks! Looking forward for more PRs from you.

**Pull request merged**
