### PR TITLE
Add defaults for third-party stubs Q-T

### PR DESCRIPTION
**Pull request by AlexWaygood**
I skipped `six`, because stubdefaulter crashed when parsing the stubs for `six` (the issue is with stubdefaulter's `typeshed_client` dependency, which is used for parsing the stubs, not stubdefaulter itself). I also skipped `termcolor`, because in order to add stubs for `termcolor` stubdefaulter needs to install `termcolor<2` (as that's what we have in the `METADATA.toml` file for `termcolor`), but stubdefaulter itself depends on `termcolor>=2`.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
If you open an issue on typeshed-client with the crash report I'll fix it.

**Comment by Avasam** [comment]
`termcolor==1.1.0`'s defaults are all `None` anyway. incoming PR

**Comment by AlexWaygood** [comment]
> If you open an issue on typeshed-client with the crash report I'll fix it.

- https://github.com/JelleZijlstra/typeshed_client/issues/78

**Comment by AlexWaygood** [comment]
I tried commenting out the problematic line and running stubdefaulter on `six`, but it turns out stubdefaulter actually makes 0 changes to our stubs for `six` `¯\_(ツ)_/¯`

**Pull request merged**
