### PR TITLE
atomicwrites: add pyi file

### PR DESCRIPTION
**Pull request by DarwinAwardWinner**
There are a few bits I'm not sure about with the type declarations: 

* The module's code uses `f.name` on some "IO" type objects (they're using NamedTemporaryFile). Is there a more specific type for an IO object with a name attribute that I could use here?
* I'm not sure about the type annotations on the context manager function `AtomicWrites._open`, or the method that calls it, `AtomicWrites.open`. Please check my work. 

Authorized by atomicwrites author here:
https://github.com/untitaker/python-atomicwrites/pull/23#issuecomment-260422021

### CODE REVIEW

**Comment by JukkaL** [comment]
We don't verify that the stub file is consistent with the implementation (unlike what the discussion in the python-atomicwrites repo implies). As this module does not seem to be very widely used, there's some risk that the stub will get out of sync with the implementation, especially if the module doesn't have a stable API (not sure if this is the case). We are a little reluctant to include very specialized modules in typeshed, since it's unlikely that any of the typeshed maintainers has the knowledge and/or bandwidth to keep it up to date. However, the API here seems simple enough that this might be okay.

@untitaker Do you believe that the API will likely remain backward compatible?

Other notes:

* We use a special style for stubs -- for example, no empty lines between functions, `...` on the same line as `:`, usually no class docstrings, etc. Please update the stub to follow conventions used elsewhere.
* There's probably no better type than `IO` for now. We can't say 'anything with a `name` attribute', for example, since structural subtyping is not supported.
* The return types of `open` and `_open` may be reasonable, but I'm not familiar with the module.

**Comment by untitaker** [comment]
open() just returns self._open, so its return type is also a context manager. I guess the API won't really change, it's just a general problem I see with typeshed.

**Comment by gvanrossum** [comment]
I've asked for clarification of the permission on untitaker/python-atomicwrites#23.

**Comment by gvanrossum** [comment]
@DarwinAwardWinner Can you answer the questions? If we don't see activity on this issue we'll close it in a few weeks.

**Comment by DarwinAwardWinner** [comment]
Yes, I'll take a look at this right now.

**Comment by DarwinAwardWinner** [comment]
Ok, I've removed all blank lines and removed all newline before ellipses. Since `atomic_write` returns the value of `AtomicWriter.open` which in turn returns the result of `AtomicWriter._open`, I've given them all the same return type: `contextlib.ContextManager[IO], (which is the type I originally had for `AtomicWriter._open`. This seems like the right type to me, but I'm not very familiar with the inner workings of the `contextlib.contextmanager` decorator that is used here, so I'm not 100% certain about this type. (Here is the context: https://github.com/untitaker/python-atomicwrites/blob/master/atomicwrites/__init__.py#L144-L159)

**Comment by gvanrossum** [comment]
OK, merged! Thanks for your work.

**Pull request merged**
