### PR TITLE
stub for imaplib (2and3)

### LINKED ISSUE #295: Stub for imaplib
It is a PR to track the evolution of the imaplib stub, if anyone already started. I will commit by parts, it will be easier for review/corrections.

### PR DESCRIPTION
**Pull request by mcepl**
Fixes #295

### CODE REVIEW

**Comment by mcepl** [comment]
OK, I give up. Could I ask for help, please, how to fix these remaining validation errors? What does ``Invalid type "typing.AnyStr"`` mean? I am lost.

**Comment by gvanrossum** [comment]
You can't use `AnyStr` the way you tried. If you replace it with `Union[bytes, Text]` it should have the effect you want. (`AnyStr` is really a type variable, so only applicable in generic class and function definitions.)

**Comment by mcepl** [comment]
Thanks for the hint. So, what do you think?

**Comment by gvanrossum** [comment]
I think you amended your commit. Please don't do that in the future.

**Comment by mcepl** [comment]
Of course, I did. Sorry, I live in other worlds where it is [the right thing to do](http://who-t.blogspot.cz/2014/03/using-git-next-level.html). Did I miss it in the Contributing.md? Actually, even you are pointing to [this blogpost](https://github.com/blog/2141-squash-your-commits). You should probably clarify it somewhere, if you don't want clueless newbies to screw up your workflow. Sorry again.

**Comment by gvanrossum** [comment]
The recommendation to squash commits is for *core devs* who are merging PRs -- we should use the Squash-and-merge button. (As I will do shortly.) But PR authors should not squash.

**Comment by mcepl** [comment]
> we should use the Squash-and-merge button. (As I will do shortly.)

OK, then I really don't understand. So, in the end you want to have just one commit per topic? Why then insist on messy squashed commit messages instead of the hand-crafted ones? I don't see any other difference.

**Comment by mcepl** [comment]
OK, that's true. Not completely persuaded, but that makes at least some sense.

**Comment by gvanrossum** [comment]
Please stop arguing and just do as we ask. We've thought about this process.

The point of not squashing commits is the review workflow, not the final
commit (I always just clean up the commit message, and that's what our core
devs instructions say). When you amend your commit and git push -f, GitHub
doesn't send any notification, and doesn't have a way to tell me what
changed since I last saw your PR. When you add a new commit it's clear what
changed and the review is simpler.

**Comment by mcepl** [comment]
I am sorry, I was not trying to argue. Anyway, shutting up.

**Pull request merged**
