### PR TITLE
Enable pyright for Python 3.11

### PR DESCRIPTION
**Pull request by Akuli**
If this works, the CI should fail because of #6902.

### CODE REVIEW

**Comment by Akuli** [comment]
I'm confused about why this is an error `__new__ override should take a "cls" parameter` on Python 3.11, but not on earlier versions:

```python3
    if sys.version_info >= (3, 11):
        def __new__(
            metacls: type[Self],
            cls: str,
            bases: tuple[type, ...],
            classdict: _EnumDict,
            *,
            boundary: FlagBoundary | None = ...,
            _simple: bool = ...,
            **kwds: Any,
        ) -> Self: ...
    elif sys.version_info >= (3, 9):
        def __new__(metacls: type[Self], cls: str, bases: tuple[type, ...], classdict: _EnumDict, **kwds: Any) -> Self: ...  # type: ignore
    else:
        def __new__(metacls: type[Self], cls: str, bases: tuple[type, ...], classdict: _EnumDict) -> Self: ...  # type: ignore
```

**Comment by JelleZijlstra** [comment]
The other lines are `# type: ignore`d.

**Comment by Akuli** [comment]
I can't believe I missed that. Thanks!

**Comment by AlexWaygood** [comment]
It's cos it's already `type: ignored` on the other branches, but not on the one branch that only runs on 3.11. My mistake.

**Review by srittau — APPROVED** [review]

**Pull request merged**
