### PR TITLE
LoggerAdapter.extra is not immutable

### PR DESCRIPTION
**Pull request by signe**
LoggerAdapter.extra is not immutable — the property and __init__ method need to hint MutableMapping

It is possible to modify .extra after it has been initialized.

Documentation for .extra specifies only that it be "dict-like," and the actual code in `__init__` simply takes the passed `extra` and assigns it blindly without any type-hinting present at all.

```
class LoggerAdapter(object):
    """
    An adapter for loggers which makes it easier to specify contextual
    information in logging output.
    """

    def __init__(self, logger, extra):
        """
        Initialize the adapter with a logger and a dict-like object which
        provides contextual information. This constructor signature allows
        easy stacking of LoggerAdapters, if so desired.

        You can effectively pass keyword arguments as shown in the
        following example:

        adapter = LoggerAdapter(someLogger, dict(p1=v1, p2="v2"))
        """
        self.logger = logger
        self.extra = extra
```

### CODE REVIEW

**Comment by Akuli** [comment]
Can you give a practical example of when mutating `extra` would be useful? To me, it seems like it would be better to make a new adapter instead of changing `extra`. Different and unrelated code could still use the old adapter, and mutating it would confusingly affect that too.

**Comment by JelleZijlstra** [comment]
Also, this change would break typechecking for code that passes an immutable Mapping as `extra`, even though such code should work fine at runtime.

**Comment by signe** [comment]
@Akuli The issue isn't whether you would personally use a class in a particular way.  It's to ensure that it's _documented correctly_.

In this particular case, I was initializing the adapter with a default transaction-id, parsing the data passed from the client (logging debug data, parsing failures, etc.), and then setting the transaction-id from the passed data to enable tracing of a particular transaction's flow.  Creating an adapter and then creating a new adapter 10-15 lines later would be silly.

@JelleZijlstra How is this different than any other situation where a piece of code accepts a dict-like object/MutableMapping?  If code legitimately accepts a mutable and you pass it an immutable, that's on you (or your IDE performing intelligent, non-static type checking) to recognize.  It's not a fault in the static type checking that you chose to pass something that matches the function definition and then chose to use it in an invalid way.

-- 

The type hinting should accurately reflect the definition of the code, not just the way that someone thinks it "should" be used.

**Comment by JelleZijlstra** [comment]
If the type hint is Mapping, a mutable mapping is still accepted. If the type hint is MutableMapping, an immutable mapping will not be accepted even though it works fine.

**Comment by signe** [comment]
@JelleZijlstra Hrm.  Ok.  I get what you're saying, now.  I apologize for coming off short.

I created the PR because PyCharm developers indicated that it was a type-hinting issue with typeshed and I didn't sit down and analyze it.  I wasn't properly thinking about how `MutableMapping` is an extension of `Mapping` because of how it was being treated in the IDE — For some reason, I was going backward in my head (Mutable -> Immutable).

I'll need to [re-open the issue on PyCharm](https://youtrack.jetbrains.com/issue/PY-49842) because you're correct, just because the function is defined as `Mapping` should not cause a type-checking error when modifying `.extra`, as `Mapping` doesn't preclude a `MutableMapping` from being valid.

For reference, PyCharm interpreted the type-hint of `Mapping` to be definitive, so when a plain dict was passed it refused to recognize either `.update()` or `['field'] = 'val'` as valid.  It saw `.extra` as being immutable because it didn't explicitly indicate that it _was_ mutable.

**Comment by JelleZijlstra** [comment]
No problem!

The type checker is arguably correct there: the type hints do say the attribute is a `Mapping`, and you can't modify an arbitrary `Mapping`. The only solution I can think of in typeshed is to make the class generic over the Mapping it receives.

In your code, the easiest workaround is probably to put an `assert isinstance(extra, dict)`.

**Comment by Akuli** [comment]
Another option would be to rely on mutable aliasing:

```
extra = {"foo": 1}
adapter = logging.LoggerAdapter(..., extra=extra)
...
extra["bar"] = 2
...
```

Modifying the dict from a local variable will affect the already existing `LoggerAdapter`, because it has the same dict. It is not copied.

**Pull request closed without merging**
