### PR TITLE
Update `typing.NamedTuple.__init__` to support fields passed through kwargs

### PR DESCRIPTION
**Pull request by sproshev**
from typing import NamedTuple

    nt1 = NamedTuple("nt1", [("x", str), ("y", int)])
    nt1_instance = nt1(x="str", y=5)
    assert nt1_instance.x == "str"
    assert nt1_instance.y == 5

    nt2 = NamedTuple("nt2", x=str, y=int)
    nt2_instance = nt2(x="str", y=5)
    assert nt2_instance.x == "str"
    assert nt2_instance.y == 5

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This shouldn't do anything to mypy; I assume it helps PyCharm? I'm happy to merge it if so.

**Comment by sproshev** [comment]
Yes, it fixes false positive from inspection that analyzes passed arguments. This inspection raised a warning on `NamedTuple("nt2", x=str, y=int)` before update.

**Comment by gvanrossum** [comment]
Hm, interesting. It seems mypy doesn't understand the verbose and rename special keywords anyway. But just in case it will understand them in the future, could you keep them? The syntax is legal:
```
def foo(x: int, *, kw: bool = False, **kwds: str) -> Any:
```

**Comment by sproshev** [comment]
Done.

**Comment by gvanrossum** [comment]
Note that unless @JukkaL approves another typeshed sync this won't be in the 0.510 release.

**Pull request merged**
