### PR TITLE
Update `emoji` stubs to version 1.2.0

### PR DESCRIPTION
**Pull request by jack1142**
There's been a bunch of changes between 0.6 and 1.0+ versions so here's an update to stubs.

### CODE REVIEW

**Comment by jack1142** [comment]
Welp, looks like there are some issues with imports, I look it up in a few hours.

**Review by hauntsaninja — COMMENTED** [review]
You probably need to re-export from `emoji/unicode_codes/__init__.pyi `, with either `from X import Y as Y` or `from X import *`

**Comment by jack1142** [comment]
Oh ye, I missed that, thanks! Should be ready for review now.

**Review by hauntsaninja — APPROVED** [review]
Thanks, looks great

**Pull request merged**
