### PR TITLE
[WIP] Add stubs for Hammurabi

### PR DESCRIPTION
**Pull request by gabor-boros**
Hammurabi is an extensible CLI tool responsible for enforcing user-defined rules on a git repository. As it is a Python 3 only package should be used by other projects, we would like to provide `.pyi` files for our users to make sure they have proper hints and mypy integration.

Repository URL: https://github.com/gabor-boros/hammurabi

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Just curious, since it sounds like you're involved in the project, why don't you want to distribute the stubs as part of the package itself using PEP 561?

Also, CI is currently failing on this PR.

**Comment by gabor-boros** [comment]
Hello @JelleZijlstra,

Apart from that I was not aware of that PEP (thanks for linking), is the following statements of mypy documentation:

> Mypy ships with stubs from the typeshed project, which contains library stubs for the Python builtins, the standard library, and selected third-party packages. - https://mypy.readthedocs.io/en/stable/getting_started.html#stubs-intro

> Mypy uses stub files stored in the typeshed repository to determine the types of standard library and third-party library functions, classes, and other definitions. You can also create your own stubs that will be used to type check your code. - https://mypy.readthedocs.io/en/stable/stubs.html#stub-files

It can happen that I misunderstood the goal of typeshed repo but I assumed that it is for 3rd party and standard libraries to store their `pyi` files.

Regarding CI is currently failing, right now we have 3rd party dependencies which has no pyi files at all. For mypy it is easy to ignore those errors raised by that, but for pytype I can not find a solution to ignore  those 3rd parties. Could you please advise? 

Also, if I misunderstood some concepts or if I should ship the package with `pyi` files instead of putting those here please let me know.

Thank you in advance

**Comment by srittau** [comment]
@gabor-boros We are happy to host the stubs here on typeshed if you want that. We recommend distributing the stubs with the library itself, though, for several reasons:

* The stubs and implementation match. When using typeshed, the stubs will always lag behind the implementation.
* It is easier to make changes to the stubs, since they don't have to through our review process.

If you want to include the stubs with the library itself, but still want a review from typeshed maintainers, you can open an issue here and link the PR you would like reviewed.

**Comment by srittau** [comment]
I see two possibilities to fix the pytype problems: Add dummy packages to typeshed (just containing `def __getattr__(self, name: str) -> Any: ...  # incomplete`.) Or remove the imports from the stubs for now and just add aliases like `BaseSettings: Any  # from pydantic` to the stubs.

**Comment by gabor-boros** [comment]
Hello @srittau,

Thank you for your quick response. The. I think we will ship the pyi files together with the package. I’ll read the PEP you linked next week to get familiar with the best practices of shipping pyi.

Thank you again

**Pull request closed without merging**
