### PR TITLE
contextmanager decorators require Generators

### LINKED ISSUE #2772: contextlib.contextmanager allows `Iterator[T]` -- should probably be `Generator[T, None, None]`?
For instance, this script passes mypy:

```python
import contextlib
from typing import Iterator

@contextlib.contextmanager
def f() -> Iterator[int]:
    return iter([1])


with f():
    pass


with f():
    raise TypeError('wat')
```

but fails at runtime (and not in the expected way):

```console
$ python t.py 
Traceback (most recent call last):
  File "t.py", line 14, in <module>
    raise TypeError('wat')
TypeError: wat

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "t.py", line 14, in <module>
    raise TypeError('wat')
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
AttributeError: 'list_iterator' object has no attribute 'throw'
```

### PR DESCRIPTION
**Pull request by asottile**
Resolves #2772

### CODE REVIEW

**Comment by asottile** [comment]
the sample from the issue now fails with:

```
$ mypy --custom-typeshed . t.py 
t.py:4: error: Argument 1 to "contextmanager" has incompatible type "Callable[[], Iterator[int]]"; expected "Callable[..., Generator[<nothing>, Any, Any]]"
```

I wasn't sure what to put for the other generic parameters for `Generator` / `AsyncGenerator` so I set them as `Any`

Also wasn't sure how else to test this so hopefully CI points me in the right direction if I've messed it up 😆

**Comment by asottile** [comment]
hmmm, CI is failing -- looks like `AsyncGenerator` was introduced in 3.5.4 -- I don't know what to do to resolve that though :(

**Comment by ilevkivskyi** [comment]
Will this allow:
```python
@contextmanager
def func() -> Iterator[int]:
    yield 1  # explicit
```
If not, then there is no way this can be merged. There are thousands existing annotations like this, and we can't make them all fail because of a false negative in rare corner case.

**Comment by msullivan** [comment]
> Another way forward could be to add special-casing in mypy that detects when a generator function has `Iterator[T]` as its declared return type and changes it to `Generator[T, None, None]`.

This seems like a good idea to me

**Comment by srittau** [comment]
I have marked this as deferred for now. While I think that in general typeshed should have exact types, but backwards compatibility is an issue. Until that is solved/worked around we can't merge this.

**Pull request closed without merging**
