### PR TITLE
Create SQLalchemy stubs using stubgen

### PR DESCRIPTION
**Pull request by srittau**
stubgen + isort + black + import cleanup + fixes

### CODE REVIEW

**Comment by srittau** [comment]
@JukkaL Actually, `METADATA.toml` mentions them. In my ideal future, we'd mention the stubs from `sqlalchemy-stubs` here and keep the plugin in that package.

**Comment by srittau** [comment]
@rchen152 FYI, I believe pytype crashes due to `...foo` imports. I will work around this.

**Comment by srittau** [comment]
There are many possible improvements, mainly due to the age of the codebase (the imports are a mess, for example), and partly due to the dynamic nature during import. As stated earlier, I want to eventually improve these stubs with annotations from the other existing stubs.

**Comment by Akuli** [comment]
How about the mypy plugin? Is it surely a good idea to add stubs for something that is so dynamic that using it requires a mypy plugin? The mypy plugin won't be in typeshed anyway, and to me, it would make sense for the mypy plugin and the related stubs to be in the same place.

**Comment by srittau** [comment]
The mypy plugin in not required for all use cases (we've never used it and have a well-typed code base using SQLAlchemy) and won't work on pyright, pyre, pytest etc. anyway.

**Comment by JelleZijlstra** [comment]
I didn't read it closely but I trust you, stubgen, and our CI. We can add more types in later PRs.

**Comment by srittau** [comment]
> I didn't read it closely but I trust you, stubgen, and our CI. We can add more types in later PRs.

Thanks. I expect there to be quite a lot of issues. The SQLAlchemy code base is quite dynamic and "historic" and therefore fairly convoluted. But that's one of the reasons I wanted to get a "minimal" version in first. That makes it easier to recognize and address issues and see why exactly a change was made.

**Pull request merged**
