### PR TITLE
codecs: allow str to bytes decoding for "hex", fix overloads

### PR DESCRIPTION
**Pull request by hauntsaninja**
Fixes https://github.com/python/typeshed/pull/7115

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
You'll have to type ignore some mypy complaints away.

**Comment by hauntsaninja** [comment]
The mypy complaints were valid, there was also a preexisting issue with overload default values, which I've now fixed.

**Comment by hauntsaninja** [comment]
Oh I should also do hex_codec

**Comment by PabloLION** [comment]
Also codecs has a `escape_encode` and a `escape_decode`. Both are not covered by this stubs

**Comment by hauntsaninja** [comment]
Re: `escape_encode` and `escape_decode` aren't in `codecs.__all__`, which is why stubtest doesn't care. We should probably make it look more like the runtime and do `from _codecs import *`, since we do have `escape_encode` and `escape_decode` in `_codecs`.

**Comment by PabloLION** [comment]
@hauntsaninja  Thanks for teaching me this 🙏🏻

**Pull request merged**
