### PR TITLE
Bump pyright to v1.1.360

### PR DESCRIPTION
**Pull request by AlexWaygood**
Closes #11780

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Well, I still don't think this is exactly a _pretty_ solution 😄 But it's ready for review -- and after the next pyright release, we'd be able to change them all to `pyright: ignore[reportInvalidTypeVarUse]` following the changes Eric just made in https://github.com/microsoft/pyright/commit/f22576f0f895a3d505eef94b65fbafccddfbbad2.

**Review by srittau — APPROVED** [review]

**Comment by AlexWaygood** [comment]
I'll wait until the next pyright release (which I think will be tonight or tomorrow, according to the usual schedule), since it will presumably include https://github.com/microsoft/pyright/commit/f22576f0f895a3d505eef94b65fbafccddfbbad2 in it, and that will mean we can update all the ignores to `reportInvalidTypeVarUse`.

**Comment by AlexWaygood** [comment]
Ugh, what on earth is going on with third-party stubtest and GitHub Actions right now?

**Comment by srittau** [comment]
Stubtest failures are unrelated.

**Pull request merged**
