### PR TITLE
Fix CI failure when no third-party stubs were updated

### PR DESCRIPTION
**Pull request by sobolevn**
Testing the CI after https://github.com/python/typeshed/actions/runs/3445520575/jobs/5749332275

### CODE REVIEW

**Comment by AlexWaygood** [comment]
One weird trick to get CI to pass: make sure you update at least one line of code in the `stubs/` directory in every PR

**Comment by sobolevn** [comment]
It should be `{ egrep '^stubs/' || echo '' }`

**Comment by sobolevn** [comment]
So, github tried to substitute `{ egrep '^stubs/' || echo '' }` with some actions specific logic. I had to use function instead.

**Review by JelleZijlstra — APPROVED** [review]
Using a function is a good idea, thanks!

**Pull request merged**
