### PR TITLE
add ast, _ast

### PR DESCRIPTION
**Pull request by tharvik**
add typechecking for asd, _ast

### CODE REVIEW

**Comment by gvanrossum** [comment]
@ddfisher can you review this? Seems related to your typed_ast.

**Comment by matthiaskramm** [comment]
What are the key differences between `2.7/_ast.py` and `3/_ast.py`? Would it be possible to merge both into `2and3/_ast.py`?

**Comment by gvanrossum** [comment]
The key differences between the ast modules in the two versions (or in any two versions) represent the key differences in grammar -- there's a class for each node in the grammar. While there's lot of overlap, there are enough significant differences between 2.7 and 3.5 that I think it's best to keep them separate. (Examples: in 2.7 def/lambda arguments take tuple unpacking, in 3.x they don't; 3.x has more *-unpacking, it has yield-from, async-def/for/with, and so on.)

**Comment by matthiaskramm** [comment]
OK, sounds like the two `_ast.pyi` versions should be kept seperate.

How about the two `ast.pyi` files? They're mostly just importing things from `_ast.pyi`.

**Comment by gvanrossum** [comment]
I think the intention is that ast.pyi exports (almost) everything it
imports from _ast.pyi. To export something imported, you have to use "from
... import ... as ...", and that doesn't support "import *". So I don't see
how it could work.

**Comment by ddfisher** [comment]
This reads to me like you can't access any member vars of the AST classes.  Is that right?

**Comment by matthiaskramm** [comment]
Add no-ops for `arg`, `Bytes`, `NameConstant`, `Nonlocal`, `Starred`, `Try`, `YieldFrom` and `withitem` to `2.7/_ast.pyi` and no-ops for `Exec`, `Print`, `Repr`, `TryExcept` and `TryFinally` to `3/_ast.pyi`, and then have `2to3/ast.pyi` import all node classes from either?

**Comment by gvanrossum** [comment]
I'm  going to leave this up to @ddfisher.

**Comment by ddfisher** [comment]
My inclination would be to bias towards accuracy of the stubs over lack of repetition.  I could imagine e.g. someone porting code from Python 2's ast to Python 3's, and, in that case, it'd be pretty undesirable to have non-existent nodes.

I actually have a more complete version of this in the pipeline that I was planning to put up this afternoon.  Maybe @tharvik can take a look at that PR once I have it up and see if it meets his needs?

**Comment by JukkaL** [comment]
from m import * exports everything from m in a stub file?

**Comment by matthiaskramm** [comment]
It does:
 
https://github.com/python/typing/commit/abe3bafdb861fc1d464c245da97bb1a3b1c6c8cd

**Comment by gvanrossum** [comment]
> from m import * exports everything from m in a stub file?

Oh, yeah, I forgot about that special case in PEP 484. :-(

**Comment by ddfisher** [comment]
PR that I was working on here: #170.  This has names and types for all the class memebers.

**Comment by tharvik** [comment]
@ddfisher good for me, I'm closing this one then.

**Pull request closed without merging**
