### PR TITLE
Improve selenium stubs

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This fixes a few default values that were not ... and adds some missing types. I think there's a lot of other potential improvements; this stub heavily uses `basestring` in Python 2.

Worked off https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/webelement.py

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
@matthiaskramm @gvanrossum @ambv this PR has been open since November; could any of you take a look?

**Comment by ambv** [comment]
Looks like none of us are actually using Selenium. Given the changes are rather just making the stubs well formed, I'm going to merge that.

**Comment by JelleZijlstra** [comment]
Thanks! I'll make sure we got rid of all non-... defaults now and make a change to flake8-pyi to enforce this rule.

**Comment by gvanrossum** [comment]
That's just what I was proposing. We use Selenium but I'm not sure we statically check any of our code yet, so I have no easy way to test this either.

**Pull request merged**
