### PR TITLE
Add _typeshed.Sentinel

### PR DESCRIPTION
**Pull request by srittau**
Closes: #10480

### CODE REVIEW

**Comment by srittau** [comment]
This PR has a bit of a hen and egg problem: It doesn't really make sense to start using `Sentinel`, until stubtest handles it, because it introduces more problems than it solves. If this gets accepted, I'd prepare a PR for stubtest, which will hopefully make it into the next mypy version.

**Comment by srittau** [comment]
I'll prepare a PR this week. But basically stubtest would just skip checking the default value if it recognizes `Sentinel` in the argument types. This allows us to use "moral" defaults like `None` in the argparse example linked in #10480: https://github.com/python/cpython/blob/832c37d42a395d4ea45994daffa5e41bd74ac1bb/Lib/argparse.py#L887-L898

**Comment by AlexWaygood** [comment]
I don't _love_ the idea of special-casing something typeshed-specific in stubtest, but I could live with it if the implementation isn't too hacky. I agree there's a problem to be solved here. (But @hauntsaninja will obviously have the final word when it comes to stubtest changes.)

I really wish we could have PEP-661; it would solve all of this in a much more elegant way. But it honestly seems unlikely to happen any time soon, if ever.

**Comment by hauntsaninja** [comment]
For cases where the sentinel is not ever meant to be user passed, I agree that `= _typeshed.sentinel_value` is the best spelling. I think this wouldn't require type checker changes if we do `_typeshed.sentinel_value: Any`. I think it might not even need a stubtest change:
```
λ cat z.py
def f(x: int = object()): ...

λ cat z.pyi
from typing import Any
_sentinel: Any
def f(x: int = _sentinel): ...

λ python -m mypy.stubtest z
Success: no issues found in 1 module
```

**Comment by srittau** [comment]
Huh, that's actually much neater. I'll open a separate PR to try this.

**Comment by srittau** [comment]
Closing in favor of #10582.

**Pull request closed without merging**
