### PR TITLE
[WIP] mark some types as non-hashable

### LINKED ISSUE #2148: Non-hashable types should declare __hash__: None in typeshed
Currently this passes mypy:
```python
from typing import Hashable

def f(x: Hashable):
    pass

f([])
```
A possible solution may be to add `__hash__: None` to non-hashable types like `list`.

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #2148.

I went over the builtins manually and grepped for other classes in the standard library that declare `__hash__ = None`.

Some interesting things I learned:
- `slice` is not hashable, even though it is immutable.
- In Python 3, `decimal.Context` is hashable but `_pydecimal.Context` is not. We don't have a stub for `_pydecimal`, so I made no changes in typeshed.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
> So IIUC this requires a mypy change first?

Yes, see the comment in #2148

**Comment by srittau** [comment]
Reopening per discussion in #2148. @JelleZijlstra

**Comment by JelleZijlstra** [comment]
The merge conflict looks bad, I won't have time to fix it right now.

**Comment by srittau** [comment]
Closing in favor of #3219, which is based on this PR.

**Pull request closed without merging**
