### PR TITLE
Use `ParamSpec` in `unittest.case`

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by sobolevn** [comment]
That's all I can find in `stdlib` 🎉

**Comment by JelleZijlstra** [comment]
I think these can also return object, like with the asyncio one.

**Comment by sobolevn** [comment]
Oh, I've also missed cases like `assertRaises` / etc

**Comment by sobolevn** [comment]
I will double check that I've covered everything tomorrow with a better regex (that counts possible multiline func definitions).

Thanks a lot for your reviews! 👍

**Comment by JelleZijlstra** [comment]
protip: reformat the codebase with `black --line-length=999999999` to make greps and codemods simpler.

**Comment by sobolevn** [comment]
Idea: maybe we don't need to type `assertRaises`?

Some people might send some intentionally bad arguments 🤔

**Comment by sobolevn** [comment]
@srittau @JelleZijlstra friendly ping 😉

**Review by srittau — APPROVED** [review]

**Pull request merged**
