### PR TITLE
`ctypes.POINTER(None)` returns `ctypes.c_void_p`

### LINKED ISSUE #12736: ctypes POINTER invalid incompatible type with None
With type checkers (PyCharm's, MyPy) I get the error:
`mypy_test.py:6: error: Argument 1 to "POINTER" has incompatible type "None"; expected "type[Never]"  [arg-type]`

Using this simple example:
```
from ctypes import POINTER
void = None
POINTER(void)
```
`POINTER(None)` in ctypes is equivalent to `c_void_p` and is valid when ran. Minor issue but is technically a compatible type.

### PR DESCRIPTION
**Pull request by junkmd**
Fixes #12736.

### CODE REVIEW

**Comment by Avasam** [comment]
As per the discussion in the the issue, it might be worth adding some tests (in `stdlib/@tests/test_cases/check_ctypes.py` ?) to show the expected return type as per common usage. If you are correct, then the return type isn't obvious. If not, then it'll show though `isinstance`/`assert_type` checks. It would be a good place to eternalize your reasoning and insight in a comment too !

**Comment by junkmd** [comment]
@Avasam 

I read your comment and https://github.com/python/typeshed/blob/main/tests/REGRESSION.md.

I have committed what I thought should be added to `stdlib/@tests/test_cases/check_ctypes.py`, so could you check if my understanding is correct?

And it seems there's already a `stdlib/@tests/test_cases/multiprocessing/check_ctypes.py`, and the name `check_ctypes.py` is duplicated, causing an error.
Could you also advise on how to resolve this?

**Comment by Avasam** [comment]
> Could you also advise on how to resolve this?

Oh that's an easy fix. Just gotta make sure the filename is different. You could rename it `ctypes/check_pointer.py` (imo the one in multiprocessing should be renamed, but let's avoid touching it in your PR).

**Review by srittau — APPROVED** [review]
The primer output is just changed error messages.

**Comment by junkmd** [comment]
@Avasam 

> Oh that's an easy fix. Just gotta make sure the filename is different. You could rename your test `ctypes/check_pointer.py`

After following your advice and using `git mv`, the error no longer occurred.  
Thank you.

> (imo the one in multiprocessing should be renamed, but let's avoid touching it in your PR).

No objection.

**Pull request merged**
