### PR TITLE
Remove unused import statements

### PR DESCRIPTION
**Pull request by ymyzk**
I found some unused import statements, so I propose removing them.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks for the PR!

How did you find these? It would be good to set up CI to catch more of these in the future.

**Comment by ymyzk** [comment]
Hi, let me share the background of this PR.

First, I tried enabling `F401` of flake8 to find these problems.  But, I find that enabling `F401` cause many false positives because pyflakes, which is used to check `F401`, does not support type hints comments like`# type: ...`. PyCQA/pyflakes#247

A happy news is that flake8 supports variable annotations. So, if we replace all type comments with variable annotations, we can enable `F401` and check these errors automatically on CI.  I'm now investigating how to do this automatically or easily.

During this investigation, I fixed some of stubs manually and sent them as this PR.  It seems that some unused import statements still remain in typeshed.

**Comment by JelleZijlstra** [comment]
Thanks for the explanation!

There is a tool for converting type comments into annotations, com2ann, but it's a bit tricky to do it safely everywhere, especially for class attributes. We would like to get rid of type comments in typeshed but doing it all at once may not be safe.

There'a few other things we'll have to be careful about with unused imports in typeshed:
- Forward references, which are occasionally written in quotes, although this is never necessary in stubs.
- `from x import y as y`, which has special meaning in stubs but may be flagged as unused by a linter.

**Comment by ymyzk** [comment]
I didn't know [com2ann](https://github.com/ilevkivskyi/com2ann). I could understand more deeply what we need to care thanks to your comment!

When I check the usage of type comments in typeshed quickly using `git grep "# type:"`, it seems that many type comments are very simple like `int` or `Optional[str]`.  I think it is safe to replace type comments which only use builtin types and types in typing module with annotations. And, it seems a good starting point.

**Comment by JelleZijlstra** [comment]
I don't think it matters whether the type comments contain built-in or more complex types; it's more relevant whether it's at the module top-level or within a class.

**Comment by ymyzk** [comment]
Okay, then I'll experiment on replacing type comments with annotations first. If I get a good result, I'l send a PR.

**Comment by gvanrossum** [comment]
> it's more relevant whether it's at the module top-level or within a class.

How does that affect whether it's safe to replace the type comment with a (PEP 526) type annotation?

**Comment by JelleZijlstra** [comment]
At the module level, as far as I understand it's always equivalent to do `X = ... # type: T` -> `X: T`. At the class level, we should have `X: T = ...` instead if the attribute exists on the class, not just on instances.

**Pull request merged**
