### PR TITLE
Now `winreg` is platform specific

### PR DESCRIPTION
**Pull request by sobolevn**
It is only available for Windows.

Related https://github.com/python/typeshed/issues/6734

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]

**Comment by sobolevn** [comment]
For some reason all jobs fail with:

```
Run pip install $(grep tomli== requirements-tests.txt) $(grep mypy== requirements-tests.txt)
Collecting tomli==1.2.2
  Downloading tomli-1.2.2-py3-none-any.whl (12 kB)
ERROR: Could not find a version that satisfies the requirement mypy==0.930 (from versions: 0.1, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.221, 0.222, 0.223, 0.224, 0.225, 0.226, 0.227, 0.228, 0.229, 0.230, 0.231, 0.232, 0.233, 0.234, 0.235, 0.236, 0.237, 0.238, 0.239, 0.240, 0.241, 0.250, 0.251, 0.252, 0.253, 0.254, 0.255, 0.256, 0.470, 0.471, 0.501, 0.510, 0.511, 0.520, 0.521, 0.530, 0.540, 0.550, 0.560, 0.570, 0.580, 0.590, 0.600, 0.610, 0.620, 0.630, 0.641, 0.650, 0.660, 0.670, 0.700, 0.701, 0.710, 0.711, 0.720, 0.730, 0.740, 0.750, 0.760, 0.761, 0.770, 0.780, 0.781, 0.782, 0.790, 0.800, 0.812, 0.900, 0.901, 0.902, 0.910, 0.920)
ERROR: No matching distribution found for mypy==0.930
```

Looks like a broken cache.

**Comment by AlexWaygood** [comment]
CI seems to be working again, if you want to close and reopen!

**Comment by Akuli** [comment]
This unfortunately breaks the following pattern, with no clear way to make things work other than `# type: ignore` on many lines:

```py
        try:
            import winreg
        except ImportError:
            pass
        else:
            many lines of code that uses winreg
```

**Comment by hauntsaninja** [comment]
Isn't the workaround the same as usual?
```
if sys.platform == "win32":
    import winreg
    ...
```

**Comment by Akuli** [comment]
We can merge, if other maintainers think that having to switch to `sys.platform` checks is fine.

**Comment by sobolevn** [comment]
@Akuli thanks for the feedback! 

I don't think that this module is special. We already have several Windows-only modules:
- `msilib`: https://github.com/python/typeshed/blob/master/stdlib/msilib/schema.pyi
- `winsound`: https://github.com/python/typeshed/blob/master/stdlib/winsound.pyi
- `msvcrt`: https://github.com/python/typeshed/blob/master/stdlib/msvcrt.pyi

They look the same to me.

**Comment by sobolevn** [comment]
I've opened a PR with a fix to Werkzeug: https://github.com/pallets/werkzeug/pull/2308
Now it should be fine for them.

**Pull request merged**
