### PR TITLE
`subprocess.(check_)call`: add `text` argument new in 3.7

### LINKED ISSUE #7777: `subprocess.call()` is missing `text` argument (in Python >=3.7)
The type annotation for `subprocess.call()` is missing the `text` argument (introduced in Python 3.7).

The type annotation for `call()` is accompanied by a comment that says `# Same args as Popen.__init__` but is not Python-version-specific and does not include the `text` argument:
https://github.com/python/typeshed/blob/b1ccd03d51f5efe5f600e8ede1810a253d35e1cd/stdlib/subprocess.pyi#L446-L467

The annotation for `Popen.__init__`, nay `Popen.__new__`, on the other hand, is in a Py >=3.7 branch to include `text`:
https://github.com/python/typeshed/blob/b1ccd03d51f5efe5f600e8ede1810a253d35e1cd/stdlib/subprocess.pyi#L807-L833

I guess `call()` needs a similar 3.7+ branch?

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #7777

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Huh, I guess this was missed because passing `text` to check_call is a little unusual given there's check_output.

Lgtm, except that it's missing the version gate to 3.7

**Review by hauntsaninja — COMMENTED** [review]
Could also consider adding the new 3.11 Popen args everywhere

**Comment by AlexWaygood** [comment]
> Could also consider adding the new 3.11 Popen args everywhere

There's still some from 3.9 that haven't yet percolated through the stub: #7524. But I'd prefer to leave those (and the new 3.11) arguments) to future PRs.

**Comment by hauntsaninja** [comment]
Oh missed that comment. I'm fine with whatever!

**Comment by AlexWaygood** [comment]
> Oh missed that comment. I'm fine with whatever!

Well I've added the version guard now, so let's go with an accurate stub I guess 😆

**Pull request merged**
