### PR TITLE
Fix return type of pow to make it more restrictive.

### LINKED ISSUE #285: pow function return type overly broad
I happened to be reading through the `typeshed` code because of a completely unrelated issue I was tracking down, and noticed that the `pow` function return type seems to be overly broad:

https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L703

```
def pow(x: int, y: int) -> Any: ...  # The return type can be int or float, depending on y
```

Should that be?

```
def pow(x: int, y: int) -> Union[int, float]: ...
```

### PR DESCRIPTION
**Pull request by johnthagen**
Fixes #285.

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Thanks for the PR! Could you fix the 2.7 version, as well?

**Comment by JukkaL** [comment]
As mentioned elsewhere this will potentially be bad for mypy users.

**Comment by johnthagen** [comment]
@matthiaskramm Fixed 2.7 as well.

**Comment by matthiaskramm** [comment]
Jukka, I leave it up to you to merge this or not - pytype is fine with `Union[float, int]`, but pytype overrides `__builtin__.pyi` with its own `pyi`, hence is unaffected by this change.

**Comment by gvanrossum** [comment]
Let's close this unmerged. I'll leave @285 open though, since it has important discussion.

**Pull request closed without merging**
