### PR TITLE
Add some redis types

### PR DESCRIPTION
**Pull request by pvalsecc**

### CODE REVIEW

**Comment by pvalsecc** [comment]
@srittau, the checks were failing because of that...

**Comment by JelleZijlstra** [comment]
@pvalsecc what exactly were the problems that you ran into with the `_Str` alias?

**Comment by pvalsecc** [comment]
Trying to put `_Str` back...

**Comment by pvalsecc** [comment]
OK, @srittau, I've put back `_Str`.

**Pull request merged**
