### PR TITLE
Improve overloads of parse_args() -- it never returns None

### LINKED ISSUE #2641: argparse.ArgumentParser.parse_args() overload misfire
I had some code calling `parse_args(args, ns)` where the type of `ns` was `Optional[Namespace`. It then deduced that the return type was also `Optional[Namespace]`. I think this is a mistake -- I don't think `parse_args()` ever returns `None`. Perhaps `_N` should be constrained by `bound='Namespace'`?

### PR DESCRIPTION
**Pull request by gvanrossum**
Fixes #2641

### CODE REVIEW

**Comment by gvanrossum** [comment]
Argh! The self-tests cause
```
mypy/typeshed/stdlib/2and3/argparse.pyi:128: error: Overloaded function signatures 2 and 3 overlap with incompatible return types
mypy/typeshed/stdlib/2and3/argparse.pyi:132: error: Overloaded function signatures 4 and 5 overlap with incompatible return types
```
even though type-checking something (like my example above) that imports argparse does not give this.

Any ideas?

**Comment by ilevkivskyi** [comment]
The signatures are overlapping if `--strict-optional` is `False`.

**Comment by ilevkivskyi** [comment]
Hm, it fails even with strict optional, a simple repro:
```python
from typing import overload, TypeVar
  
T = TypeVar('T')

@overload
def f(x: None) -> int: ...
@overload
def f(x: T) -> T: ...
def f(x):
    pass
```
I would say this is a bug.

**Comment by ilevkivskyi** [comment]
Well this is not a bug, sorry, if `T` is `Optional[str]`, there is an unsafe overlap, there must be a bound for `T`.

**Comment by ilevkivskyi** [comment]
I remember we discussed this with @Michael0x2a and were at the boundary of allowing this, because in practice the unsafety is quite minor. So I think it is fine to just `# type: ignore` this, if there is no way to put a bound on variable.

**Pull request merged**
