### PR TITLE
Return Union type for `List.__add__`

### PR DESCRIPTION
**Pull request by kaste**
In Python, lists of union types are just common. We want to support easy
construction of lists e.g.

    `[1, 2] + ['3']` or
    `['foo' if p else None, 'bar'] + ['zoo']`

We adjust `__iadd__` accordingly. Although returning a union here too looks
strange, it has the effect that

    l = [1,2]
    l += ['3']  # ERR: Result type of + incompatible in assignment

 correctly fails.

### CODE REVIEW

**Comment by bluetech** [comment]
My opinion: while this indeed describes the dynamic behavior more precisely, such occurrences in real code are often bugs, and I therefore prefer the current behavior that rejects it.

For the `__iadd__` case, I think the list should be annotated with the union type ahead of time.

The `__add__` case is a bit harder to annotate. A safe upcast operation would have been nice (see https://github.com/python/typing/issues/565), although `List` is invariant so the cast is not actually safe. You might be able to use `Sequence` instead. Also the following alternative seems to typecheck fine so you might be able to use `[*a, *b]` instead of `a + b`:

```py
from typing import List, TypeVar, Union

S = TypeVar('S')
T = TypeVar('T')

def add_lists(a: List[S], b: List[T]) -> List[Union[S, T]]:
    return [*a, *b]                                        
```

> `['foo' if p else None, 'bar']

This does work as you expect already - `List[Union[str, None]]`. However it seems it is unique to `None`. If you change `None` to have some other type like `5`, then it takes the common base class, so `List[object]`.

**Comment by ilevkivskyi** [comment]
Please note last time this was attempted (see https://github.com/python/typeshed/pull/2404) it caused severe regressions elsewhere and was ultimately reverted.

**Comment by kaste** [comment]
@ilevkivskyi Sorry for not seeing this. Following #2404 and its linked issues, there aren't any good, easy to grok examples of the regressions. I considered the following before the PR.

Given

    class Animal: ...; class Cat(Animal): ...; class Dog(Animal): ...
    def get_cats() -> List[Cat]: ...
    def get_dogs() -> List[Dog]: ...

Situation in master

    a = get_cats() + get_dogs() # ERRS surprisingly
    c: List[Animal] = get_cats() + get_dogs() # ERRS
    e: List[Animal] = get_cats() # ERRS invariant message
    f: List[Animal] = [Cat(), Dog()] # OK
    h: List[Union[Cat, Dog]] = get_cats() # ERRS also invariant message
    j: List[Union[Cat, Dog]] = list(get_cats()) # OK
    k: List[Union[Cat, Dog]] = list(get_cats()) + list(get_dogs()) # ERRS

After PR

    a = get_cats() + get_dogs() # OK
    c: List[Animal] = get_cats() + get_dogs()  # ERRS surprisingly
    e: List[Animal] = get_cats() # ERRS invariant message
    f: List[Animal] = [Cat(), Dog()] # OK
    h: List[Union[Cat, Dog]] = get_cats() # ERRS also invariant message
    j: List[Union[Cat, Dog]] = list(get_cats()) # OK
    k: List[Union[Cat, Dog]] = list(get_cats()) + list(get_dogs()) # OK

    # This always works
    d: List[Animal]
    d = list(get_cats())
    d.extend(get_cats())


So still, after this PR, there are a lot of confusing statements, but I don't see where I flip from 'OK' in master to 'FAIL' in PR. 🤷‍♂ 

I also don't see/have a workaround for 'a', 'c' or 'k' in master to get '+' (concat) to actually work. 

@bluetech Apple/bananas examples like `[1] + ['2']` usually don't make sense. `concat/+` though is a main constructor of lists. There is nothing really fishy when you consider `[customers] + their_salesman() + some_managers()` and then send these to someone.

**Comment by ilevkivskyi** [comment]
@kaste 
> but I don't see where I flip from 'OK' in master to 'FAIL' in PR.

Have you tried
```python
a: Sequence[object]
b1: List[Any]
b2: List[int]

a = b1 + b2
```

**Comment by kaste** [comment]
I actually have. And yes it flips. But then I could not make any sense of it, so I did not consider it. Probably nobody writes something like this, but mypy could infer such a situation. But then, it is not type-safe t.i. in master `b1 + b2 != b2 + b1`. So I thought it's an interesting bug, or the internals of mypy shine through the code... again 🤷‍♂

**Comment by kaste** [comment]
When we implement `__radd__` as well we can trick mypy so that your example now passes. T.i. both

		a = b1 + b2
		a = b2 + b1

from your testcase now pass.

**Comment by srittau** [comment]
@ilevkivskyi @JukkaL As the ones handling the fallout from #2404 do you think we should try this approach? Is there a good test case for making sure this doesn't cause regressions?

**Comment by JukkaL** [comment]
I don't think that we have good test cases for checking that this doesn't cause any regressions, other than type checking some big enough codebase with the change. I can try this against Dropbox internal codebases (not sure exactly when though).

**Comment by srittau** [comment]
FWIW, I just ran this against a code-base with ~2000 files without error.

**Comment by JukkaL** [comment]
That's promising!

**Comment by lovasoa** [comment]
Has there been any progress on this ? I was hit by this bug today.

**Comment by kaste** [comment]
With the newer mypy this "hacky" approach is probably outdated because we can now annotate/give a hint about self itself.

**Comment by srittau** [comment]
Closing per last comment by @kaste. Thank you for the effort!

**Comment by kaste** [comment]
Is there another PR? T.i. I couldn't get my idea to work actually. Should we just try harder?

**Comment by lovasoa** [comment]
Since the issue is still there, it should probably be tracked somewhere

**Comment by srittau** [comment]
Sorry, I think I misunderstood. We still need to try this against other large codebases.

**Comment by JelleZijlstra** [comment]
@JukkaL would you mind trying this PR on your codebase?

**Comment by JelleZijlstra** [comment]
Also stubtest is now complaining because `list.__radd__` doesn't exist at runtime. We should probably whitelist it.

**Comment by JukkaL** [comment]
I've been a bit distracted but managed finally to check this against our big internal codebase. 

It generated about 50 new errors, mostly of form `Unsupported operand types for + ("List[str]" and "List[str]")`. It wasn't immediately clear what was going on here, but it looks like an issue with mypy type inference.

**Comment by Akuli** [comment]
It would be nice if you could add `List[pathlib.Path]` and `List[str]` together for `subprocess.call` arguments, but `List[str] + List[int]` is probably a bug imo.

**Comment by JelleZijlstra** [comment]
This has been open for a while (and now has a merge conflict). Do people think we should merge this? The errors @JukkaL found seem concerning.

**Comment by hauntsaninja** [comment]
I fixed the merge conflict / we'll see what mypy_primer has to say, although given what Jukka says I wouldn't merge until the mypy kinks are worked out (hopefully we can remove the `__radd__` lie as well)

**Comment by srittau** [comment]
I am going to close this for now due to the upcoming reshuffle. I still think this is generally worthwhile, though, although it obviously needs more investigation.

**Comment by mrkmndz** [comment]
Is there any interest in reopening this?

**Comment by JelleZijlstra** [comment]
Reopening directly won't work because of the change in file structure. It still seems worth fixing but tricky to get right.

**Pull request closed without merging**
