### PR TITLE
Fix blake2 binding

### PR DESCRIPTION
**Pull request by i80and**
Currently calling `hashlib.blake2b` results in the following type errors:

```
<...>: error: Cannot instantiate abstract class '_BlakeHash' with abstract attributes 'copy', 'digest', 'hexdigest' and 'update'
<...>: error: Missing positional arguments "data", "key", "salt", "person", "fanout", "depth", "leaf_size", "node_offset", "node_depth", "inner_size", "last_node" in call to "_BlakeHash"
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Would it be better to instead correct the definition of `_BlakeHash`? At the very least, we should add a default for the `data` argument.

**Comment by JelleZijlstra** [comment]
Ping on the above.

**Comment by quantsini** [comment]
Any objection to me taking over this change?
Happy to make a new branch, cherrypick this commit, and addressing @JelleZijlstra's comment in a new PR.

**Comment by i80and** [comment]
No objection from me! Sorry, I just don't have time immediately to take a look at this.

Thanks :)

**Pull request closed without merging**
