### PR TITLE
Merge 3.4 and 3.5 pathlib stubs

### PR DESCRIPTION
**Pull request by phouse512**
@gvanrossum this pull merges stdlib/3.4 and 3.5 as discussed in the #659 .

I used this small test file to make sure that 3.5 code still was being validated correctly:

```
from pathlib import Path, PurePath

# test Path.home
test = Path.home()


# test Path.samefile
dumb_path = Path('eggs')
samefile_test = test.samefile(dumb_path)

# test Path.read_bytes
read_byte_test = dumb_path.read_bytes()  # type: bytes

# test Path.read_text
read_text_test = dumb_path.read_text()  # type: str

# test Path.write_bytes
dumb_path.write_bytes(b'binary contents')

# test Path.write_text
dumb_path.write_text('more binary contents')

# test Path.expanduser
test_expand = dumb_path.expanduser()  # type: Path

# test Path.mkdir
new_path = Path('spam')
new_path.mkdir(exist_ok=True)
```

### CODE REVIEW

**Comment by ambv** [comment]
This is nice! The test failure is a legitimate problem. If you look there, it fails on 3.6 alone because stubs for the `os` modules don't include `PathLike` yet. Opportunity for more impact for you :)

**Comment by gvanrossum** [comment]
There are errors with the 3.6 run:
```
stdlib/3.4/pathlib.pyi:10: error: "module" has no attribute "PathLike"
stdlib/3.4/pathlib.pyi:14: error: Invalid type "pathlib._PurePathBase"
stdlib/3.4/pathlib.pyi:14: error: Invalid base class
```
I guess you need to make the import conditional too.

**Comment by gvanrossum** [comment]
I changed the issue title since I can't remember what issue numbers mean. :-) When merging I will need to remember to add "Fixes #764" to the commit message.

**Comment by phouse512** [comment]
Ah yes, I didn't realize `PathLike` didn't exist, I'll work on adding a conditional stub for it!  Also @gvanrossum I can make my next commit have that message to auto close that issue.

**Comment by phouse512** [comment]
@ambv @gvanrossum I've updated the PR with a conditional [PathLike](https://docs.python.org/3.6/library/os.html#os.PathLike) depending on version 3.6.  It looks like the checks have passed as well. 

I noticed while reading the documentation for 3.6 that there are a decent number of changes to the `os` module, but that should probably be addressed in another PR.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
