### PR TITLE
chore: remove stubs related to stripe package

### LINKED ISSUE #10966: Remove stripe (not until May 2024)
Stripe 7.1.0 (released 2023-10-27) includes type hints.

### PR DESCRIPTION
**Pull request by steve148**
Fixes #10966

Based on stripe 7.1.0 releasing with type hints on October 27, 2023, the stub files related to stripe can be dropped.

### CODE REVIEW

**Comment by LaurierMantel** [comment]
:fire:

**Comment by srittau** [comment]
Could you also please remove the stripe entry from `pyright.stricter.json`?

**Comment by steve148** [comment]
@srittau of course, amended the commit to remove the reference to stripe from the `pyrightconfig.stricter.json` file as well.

**Review by srittau — APPROVED** [review]

**Comment by srittau** [comment]
Thanks!

**Pull request merged**
