### PR TITLE
Add stdlib/2.7/traceback._print

### PR DESCRIPTION
**Pull request by fyquah95**
```
import traceback
traceback._print.__code__.co_varnames
=> ('file', 'str', 'terminator')
traceback._print.__defaults__
=> ('', '\n')
traceback._print.__code__.co_argcount
=> 3
```

I can't find this the _print function in python 3, neither can I
find any official docs on this function.

### CODE REVIEW

**Comment by gvanrossum** [comment]
I'm sorry, this is an internal, undocumented function and should not have a stub.

**Comment by matthiaskramm** [comment]
We have code in our codebase that uses this function.

Sure, that code should be fixed, but IMHO it's not the type-checkers job to complain about that. (Linters should be the ones to warn you about using module._symbol)

**Comment by matthiaskramm** [comment]
(54 occurrences of `traceback._print`, all over our codebase)

**Comment by gvanrossum** [comment]
Hm, it's a slippery slope. But go ahead and merge it. I wonder if we should have a feature to mark deprecated or undocumented/internal functions, so type checkers can choose to be more picky...

**Comment by matthiaskramm** [comment]
Yeah, maybe we need something like `@deprecated` or `@internal`.

On the other hand, these functions (typically) have a leading underscore, so typecheckers can filter or complain based on that.

**Pull request merged**
