### PR TITLE
contextvars.Context doesn't inherit from Mapping

### PR DESCRIPTION
**Pull request by tungol**
It's not a subclass, it's not registered to Mapping, and Mapping isn't protocol-like, so at runtime:

```
>>> issubclass(Context, Mapping)
False
```

It does have all the necessary methods to be Mapping, it just isn't.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
That's kind of interesting that we don't do the `collections.abc.Mapping.register(Context)` thing at runtime; feels like an omission over at CPython

**Review by srittau — APPROVED** [review]
Interesting, but the primer hits are encouraging.

**Comment by tungol** [comment]
Yeah, I was wondering if maybe the right thing to do here was add the registration to cpython?

I haven't looked at them in detail yet, but two others in a somewhat similar boat are `multiprocessing.managers.DictProxy` and `multiprocessing.managers.BaseListProxy`. They're MutableMapping and MutableSequence in typeshed, respectively, but neither is actually registered to the ABC at runtime. They're on my "investigate" list coming up.

**Comment by AlexWaygood** [comment]
> Yeah, I was wondering if maybe the right thing to do here was add the registration to cpython?

Very possibly. In theory of course, we could do this change and the CPython change, though it might lead to some annoying branching in the stubs if the CPython change is only accepted for Python 3.14+

**Comment by tungol** [comment]
This is now fixed in cpython for 3.12 and up. It probably doesn't make sense to branch for the sake of 3.8 to 3.11.

**Pull request closed without merging**
