### PR TITLE
Add options to tkinter widgets

### PR DESCRIPTION
**Pull request by Akuli**
Tkinter options now have type hints that describe which values are valid when setting the options. For example, `tkinter.Label(relief='sunkenn')` now creates a mypy error. The correct types for the options come from Tk's manual pages as described in `__init__.pyi`. This affects `__init__`, `config`, `configure`, `cget`, `__setitem__` and `__getitem__` methods because those are the methods that deal with widget options.

Looking up the value of an option always returns `Any`, because tkinter doesn't make much effort to ensure that the return values have consistent type. In practice, they can be pretty much anything in funny corner cases, and figuring out which of the possible types actually come up frequently enough for type hints would be a lot of work.

In tkinter, `widget['foo'] = bar` and `widget.config(foo=bar)` do the same thing, but they type-check differently: the `widget['foo'] = bar` syntax allows `'foo'` to be any string (e.g. a variable, not necessarily a `Literal`) and `bar` to be any object, while `widget.config(foo=bar)` checks the existence of the option and the type of `bar`. Similarly, `cget` takes a `Literal` argument but `__getitem__` takes a string. This is done because:
- It halves the amount of required copy/pasta in stubs files.
- The type of a variable defined with `foo = 'sunken'` is `str` rather than `Literal['sunken']`, so fixing code that does `widget.config(relief=foo)` can be done without a `# type: ignore` comment by changing it to `widget['relief'] = foo`.
- Similarly, setting `bar = 'relief'` and doing `widget[bar] = 'sunken'` works.

~This also includes a script that checks whether the types of widget options actually work at runtime (stubtest doesn't work well with the generous `**kwargs` usage in tkinter) and the travis configuration to make that part of the CI build. Usually it takes about 22 seconds to run, which is a lot quicker than any of the other CI things. The script creates tkinter widgets, parses a small subset of type hint syntax with `ast`, creates possible values of the options based on those type hints and tries to set the options of the widgets.~

~Some classes in `tkinter/ttk.py` inherit from other classes and break the Liskov substitution principle by not having all the widget options of the base class. In those cases, I made the stubs not inherit and instead used `method = BaseClass.method`.~

~I added a `--verbose` option to `tests/pytype_test.py` for finding pytype issues more easily, but that's disabled in the travis config.~

This pull request contains a lot less copy/pasta than I initially thought it would contain, but there's still a lot of it. The copy/pasta is quite readable even though I used a script to initially generate it. The script is not included in this pull request because I think the copy/pasta is maintainable as is, and learning to use my script to maintain it would be more work than with copy/pasta. I added comments about the trickiest options to the stubs.

### CODE REVIEW

**Comment by Akuli** [comment]
@Hawk777 What do you think about the difference between `__setitem__` and `config`? Is it too confusing or surprising?

**Comment by Akuli** [comment]
Rebasing on top of latest master because there's not yet any conversations that could be lost by doing that

**Comment by Hawk777** [comment]
I’m uncertain how I feel about the `configure`-vs-`__setitem__` and `cget`-vs-`__getitem__` thing. It does have a nice technical benefit that, if you’re not doing any indirection (i.e. you’re using literals), you can just always use `configure` and `cget` and you get awesome type checking, and if you *are* doing indirection, well, there’s still a way to do that. I think there are two big concerns though. First, as far as I can tell (and I could very well be wrong as I’m not a Typeshed expert), it seems like most of Typeshed is developed with the intention of reflecting reality as accurately as possible within the type hint system; in other words, Typeshed seems to try not to be super-opinionated about how people write their code, rather some theoretical “perfect Typeshed” would be one where every valid program is accepted and every invalid program is rejected. This is definitely a change of direction, since it’s saying, “even though it’s totally legal to pass a non-literal string to `cget`, even though it will work properly at runtime, and even though we *could* have made your program typecheck if you do that, we chose to reject it instead.”

Second, I worry about discoverability; where would all these Typeshed-specific rules be documented? You have this stronger type checking, but how will people ever know that it exists? Certainly not from reading the Python documentation for tkinter, which explicitly states that `__getitem__` and `cget` are exactly the same thing. What’s even going to prompt people to look for special tkinter-specific, Typeshed-specific documentation where they learn that they can get this extra type-checking?

Neither of these is necessarily a reason to reject, but I think they need to be thought through.

**Comment by Akuli** [comment]
Tkinter stubs have other things that need documentation too:

- which widget class to use: https://github.com/Akuli/typeshed/blob/cbeab827a3e6afd1e09c8684c51b729e99b22344/stdlib/3/tkinter/__init__.pyi#L17-L22
- `tkinter.Event` is generic and bind callbacks should return `None` or `Optional[Literal['break']]` (#4347)

I think having to look up these things from typeshed pull request and issues history would be pretty bad. Has there been similar "type hints of this library need documentation" problems with other libraries in the past? If so, has the documentation went to `docs.python.org`, someone's unofficial `username.github.io` site, comments in stub files, or just nowhere?

**Comment by Akuli** [comment]
Looking at [tkinter documentation on docs.python.org](https://docs.python.org/3/library/tkinter.html), there's already a big list of references that people should look at, and maybe another item in the list for using type hints with tkinter would be a good idea. Who should maintain that though? I don't think that `akuli.github.io/tkinter-type-hints` or something is a good idea.

**Comment by Akuli** [comment]
Maybe I'll mention another idea: put a markdown file into this typeshed repo and link to that from python docs. Maybe that would be a little weird, but it would be very easy to keep it updated as pull requests get merged to typeshed.

**Comment by Akuli** [comment]
Even though this pull request requires some conversation before getting merged, I'd like to make progress with this. The tkinter stubs won't be usable to me before this (or some similar pull request) gets merged.

@srittau @hauntsaninja It's been quiet for a while, and CONTRIBUTING.md seems to say that it's ok to ping after "more than a few days".

**Comment by Akuli** [comment]
>Typically, it's the responsibility of the library to ensure LSP, and if it doesn't, the stubs should reflect that and type ignore.

I'll do that tomorrow. The only way I can see that going wrong is someone writing code that expects a `tkinter.Entry`, for example, and then somewhere a `tkinter.ttk.Entry` is passed instead. In practice, most tkinter projects don't mix `tkinter.Entry` and `tkinter.ttk.Entry` at all, because the Ttk widgets are intended to fully replace the non-Ttk widgets.

**Comment by Akuli** [comment]
Should I delete the `--verbose` option of tests/pytype_test.py from this PR because it's not really related to tkinter in any way?

Also, what about the option testing script? Is using ast acceptable or is there some more preferred way to do that?

**Comment by Akuli** [comment]
Maybe I should also delete the options testing script. It sets options on the widgets based on the type hints, which is something that anyone creating or reviewing the type hints should do anyway. The script is also likely to cause annoyance in the future with type hints that it doesn't understand.

**Comment by Akuli** [comment]
Those things are gone now. What remains is just the options on the widgets, and nothing more.

Is this still too much work to review? I don't expect the reviewers to check every possible option with Tk's manual pages and try to set different values to it.

**Comment by Akuli** [comment]
I mypyed a large-ish tkinter project with stubs from this PR

```
$ wc -l $(find -name '*.py') | tail -1
  8952 total
```

Checklist of problems I found and I need to fix before merge:
- [ ] make sure that all options in the latest Tk 8.7 docs are supported (such as `font` of `ttk::entry`)
- [ ] add `border` as an alias for `borderwidth`
- [ ] replace `_TkinterSequence[str]` with `Union[str, _TkinterSequence[str]]` when appropriate (at least `_FontDescription` and `show` option of `ttk.Treeview`)

**Comment by Akuli** [comment]
I created #4453 to fix `_FontDescription` because that's already on master and not really related to this PR. Everything else is done.

**Pull request merged**
