### PR TITLE
inheritance for multiprocessing.managers.DictProxy

### PR DESCRIPTION
**Pull request by tungol**
Similar to https://github.com/python/typeshed/pull/12873 and https://github.com/python/typeshed/pull/12892

DictProxy doesn't inherit from MutableMapping and it isn't registered to it either. It does have all the relevant methods.

### CODE REVIEW

**Comment by tungol** [comment]
I'm honestly kind of surprised all three of these turned out to be "no effect".

**Comment by AlexWaygood** [comment]
> I'm honestly kind of surprised all three of these turned out to be "no effect".

I think they're used somewhat rarely; I wouldn't be surprised if there's no mypy_primer coverage for them. They are used, though; we've had bug reports in the past about them when I caused a regression.

**Comment by tungol** [comment]
That makes sense.

**Review by srittau — APPROVED** [review]
I'm in favor of changes like this, especially when there's no primer impact. It's also a chance to steer users towards using protocols. (In the long term we should also look into adding some "mapping light" protocols to `typing`. Similar to what [I suggested for  Reader/Writer protocols](https://discuss.python.org/t/simple-reader-and-writer-protocols/61510) (which I need to prepare a PR for).)

**Comment by AlexWaygood** [comment]
I'm a bit nervous about this, because sort-of the whole point of this class is that it's meant to be basically drop-in compatible with `dict`. I think it almost certainly _should_ be registered to the ABC at runtime :/

**Comment by tungol** [comment]
I've opened a cpython issue and MR to get this and BaseListProxy registered to their ABCs at runtime. 

https://github.com/python/cpython/issues/126417

https://github.com/python/cpython/pull/126419

**Comment by tungol** [comment]
This is now fixed in cpython for 3.12 and up. It probably doesn't make sense to branch for the sake of 3.8 to 3.11.

**Pull request closed without merging**
