### PR TITLE
Rename nmap to python-nmap

### PR DESCRIPTION
**Pull request by cdce8p**
Following the feedback in https://github.com/python/typeshed/pull/5930#issuecomment-899872393
Rename `nmap` to `python-nmap`.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Thanks, this is great!

1) stubtest says `__scan_progressive__` also gets a timeout argument
2) Delete the stubtest_allowlist, since we now have no need for it
3) Update the version field in python-nmap/METADATA.toml to `0.6`

**Comment by cdce8p** [comment]
Seems like all the issues are fixed now

**Review by hauntsaninja — APPROVED** [review]
Thank you!

**Comment by cdce8p** [comment]
@hauntsaninja Shouldn't there now be a package called `types-python-nmap` on PyPI? Did I miss something when I did the move?

https://pypi.org/search/?q=types-python-nmap

**Comment by srittau** [comment]
@cdce8p: Indeed, that's build where it should have been picked up, but wasn't: https://github.com/typeshed-internal/stub_uploader/runs/3345836794?check_suite_focus=true

Investigating.

**Comment by srittau** [comment]
@cdce8p I've forced an upload of the package, it's now on pypi. typeshed-internal/stub_uploader#22 has a fix for future package renames.

**Comment by cdce8p** [comment]
> @cdce8p I've forced an upload of the package, it's now on pypi. [typeshed-internal/stub_uploader#22](https://github.com/typeshed-internal/stub_uploader/pull/22) has a fix for future package renames.

@srittau Thank you for taking a look!

**Pull request merged**
