### PR TITLE
Add stubs for qrcode

### PR DESCRIPTION
**Pull request by srittau**
This is best reviewed commit by commit. The first commit is just the result of create_baseline_stubs. The other commit were the minimum required to make the tests pass.

I plan to go over the stubs manually in a future PR, but I tried to keep this initial PR as minimal as possible, trusting the existing annotations and the tools.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
It seems like the runtime package is already quite heavily annotated. Is it worth asking upstream if they'd consider adding a `py.typed` file, before we add stubs to typeshed?

**Comment by srittau** [comment]
> It seems like the runtime package is already quite heavily annotated. Is it worth asking upstream if they'd consider adding a `py.typed` file, before we add stubs to typeshed?

I would call it "lightly annotated", so I think there is quite some room for improvement in the stubs for now.

**Review by AlexWaygood — COMMENTED** [review]
The PR looks fine, but I still feel like this might be an unnecessary duplication of effort, given that it looks like the runtime package has several PRs open to improve their type annotations. I don't want to block the PR if others disagree with me, however :)

**Comment by srittau** [comment]
Considering that the last upstream commit was in February and the PR has been open since March, I would prefer to have the types in typeshed for now.

**Comment by AlexWaygood** [comment]
No other maintainer has chimed in over the last three weeks, and I don't feel strongly about it, so feel free to merge.

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
