### PR TITLE
Slice attributes can be of any type.

### PR DESCRIPTION
**Pull request by brandtbucher**
```py
>>> slice([], object(), type)
slice([], <object object at 0x7f2e0e522120>, <class 'type'>)
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
They theoretically can be, but is it actually useful to construct slices like the one in your comment? I'm worried that this will sacrifice some type safety for code that uses standard integer slices for little real benefit.

See python/typing#159 for prior discussion on slices.

**Comment by brandtbucher** [comment]
I agree that it's uncommon (even impossible) to use when slicing the built-in types. In data processing libraries, however, it is not unusual to slice on any key type. I encountered this false-positive when working on StaticFrame, which allows slicing by index values:

https://static-frame.readthedocs.io/en/latest/api_selection.html?highlight=slice#frame 

The widely used Pandas library allows this as well:

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#selection-by-label

**Comment by brandtbucher** [comment]
So is this something that can be considered?

**Comment by brandtbucher** [comment]
Bump. Is there anything keeping this from being merged?

**Comment by rushabh-v** [comment]
It gives error: Slice index must be an Integer of None for below kind of code. 
`pd.IndexSlice[:"b":-1]`
`pd.IndexSlice["m":"m":-1]`
see https://github.com/pandas-dev/pandas/pull/29188

**Pull request merged**
