### PR TITLE
Stubs for braintree

### PR DESCRIPTION
**Pull request by exemplary-citizen**
A library that provides integration access to the Braintree Gateway.

I started with stubgen, then cleaned up to address missing functions. Testing plan is to keep an eye on CI and fix any issues that arise.

cc: @JukkaL @srittau

### CODE REVIEW

**Comment by exemplary-citizen** [comment]
CI failure seems related to https://github.com/google/pytype/issues/611
@srittau do you remember the workaround for this?

**Comment by JukkaL** [comment]
> CI failure seems related to google/pytype#611

I think that it's fine to add a pytype exclusion for now, in `tests/pytype_exclude_list.txt`. A workaround for pytype can be figured out later.

**Comment by srittau** [comment]
The re-exports should be removed from non-__init__-stubs anyway, this should reduce the pytype errors to something more easily fixable.

**Comment by JukkaL** [comment]
Thanks! This looks good overall. There are probable some re-exports that are not needed. Can you check if some of them are clearly not needed? It looks like it might be a tricky generally, since some of the re-exports could plausibly be included in the public API (I'm talking of things like `from foo import bar as bar`).

**Review by JelleZijlstra — APPROVED** [review]
I'm pretty sure many of the re-exports can be removed, but that can wait.

**Pull request merged**
