### PR TITLE
Add a type: ignore as a hacky workaround for some mypy bazel issues

### PR DESCRIPTION
**Pull request by msullivan**

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I'm OK with this, but pytype apparently doesn't like `# type: ignore` in this position.

**Comment by gvanrossum** [comment]
We noticed. :-) Maybe pytype doesn't like `# type: ignore` on `import *`? Because there are non-star imports with `# type: ignore`.

**Comment by rchen152** [comment]
Looks like pytype doesn't like `# type: ignore` on import lines at all. (Maybe the ones you saw were in the parts of third_party that pytype ignores?) I've mailed a fix out for review, will hopefully be able to release it tomorrow.

**Comment by rchen152** [comment]
The pytype issue was fixed in pytype 2019.03.27.

**Comment by JelleZijlstra** [comment]
Thanks @rchen152!

**Pull request merged**
