### PR TITLE
Added Optional annotation for first parameter of object.isinstance

### PR DESCRIPTION
**Pull request by erictraut**
Added Optional annotation for first parameter of object.isinstance because it's able to accept None as a value.

### CODE REVIEW

**Comment by srittau** [comment]
This is a no-op, since `None` is a valid instance of `object`. Do you have an example where this leads to problems?

**Comment by erictraut** [comment]
Why would None be a valid instance of object? Is this documented? I don't see where in the specs (pep 484 or elsewhere) where this is documented.

If None is a valid instance of object, is it possible to specify that a parameter must be an object but not None?

**Comment by srittau** [comment]
`None` being an instance of `object` is just the result of Python's type system, where 'object' is at the root of the type hierarchy:

```python
>>> isinstance(None, object)
True
>>> type(None)
<class 'NoneType'>
>>> type(None).__bases__
(<class 'object'>,)
```

I don't think it's currently possible to allow any value except `None`. Cf. python/typing#614

**Comment by erictraut** [comment]
Thanks for the explanation. I was under the impression that None was a specialized type not derived from object. Closing the PR.

**Pull request closed without merging**
