### PR TITLE
Added @overload decorator in missed places

### PR DESCRIPTION
**Pull request by Lemon4ksan**
That should fix editors from not seeing documentation for function aliases.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hi! I'm afraid these changes don't look correct as they currently stand. Could you explain a bit more about what problem you're trying to fix here, exactly?

**Comment by Lemon4ksan** [comment]
Well when I edit my Tkinter code, function aliases (e.g .place .pack) are missing their documentation, because my editor tries to find function outside of the class. I was very wrong in using overload decorator. I could just use class name instead. It also solves the issue. Gonna fix it asap

**Comment by AlexWaygood** [comment]
If I understand correctly, it sounds like your IDE doesn't support aliases like this when you hover your mouse over a symbol and it attempts to render documentation for the symbol:

https://github.com/python/typeshed/blob/c4f7a72e50694b9a8b2d0ce4be7a14251c465d88/stdlib/tkinter/__init__.pyi#L878-L879

That sounds like a bug/feature request you should make to your IDE rather than something we should fix in typeshed. Our job in typeshed is to accurately emulate what happens at runtime, and we're doing that correctly here.

**Comment by Lemon4ksan** [comment]
PyCharm supports aliases. By using place = place_configure it searches for place_configure outside of the class (since there's no pointer to the class) and counts it as an unresolved reference. I want to add that pointer. So it will look like place = Place.place_configure

**Comment by AlexWaygood** [comment]
> By using place = place_configure it searches for place_configure outside of the class

but that sounds like incorrect behaviour from PyCharm :-) PyCharm should follow Python's semantics here, and it's perfectly legal to assign an object in a class body to another object in that class body. The local namespace (the class namespace) should take priority over the global namespace when it's trying to resolve the `place_configure` symbol on the right-hand side.

**Comment by Lemon4ksan** [comment]
I think these are 2 sides of the same coin.

**Comment by Lemon4ksan** [comment]
Guess my changes are irrelevant. I will close this PR

**Pull request closed without merging**
