### PR TITLE
Add full Python 2 type stubs for OpenSSL.crypto

### PR DESCRIPTION
**Pull request by rra**
This tries to use AnyStr in places the module seemed to accept either
str or unicode, bytes in places where the module documentation
emphasized that this was opaque bytes, and str for arguments and
return values that the module seemd to be treating as regular Python
strings.

### CODE REVIEW

**Comment by rra** [comment]
It's been a while since I've done one of these, and mypy has changed a bit.  I tried to update to the new way of expressing things, but I may have gotten some of that wrong.  I'm also not sure if the way I handled `str` vs. `bytes` vs. `AnyStr` is correct (or useful).

I had to use `Union[str, unicode]` for class attributes that normally contain `unicode` initialized by the library but can take `str` on assignment (the library figures it out, so far as I can tell).  Not sure why `AnyStr` didn't work.

**Comment by rra** [comment]
Also not really sure how to handle the types that come from `cryptography.hazmat.primitives`, which apparently cause test failures?  I'm pretty confused by what's going on there.

**Comment by ambv** [comment]
Ci is yelling at you for not having cryptography stubs. Yeah, we'd need them, too. But overall this is a very comprehensive expansion, I'm impressed. AnyStr is useful when you have multiple declarations of bytes and strings within the same signature and you want to keep them in sync. In other words:
```
def func(a: AnyStr, b: AnyStr) -> AnyStr
```
is equivalent to
```
@overload
def func(a: str, b: str) -> str
@overload
def func(a: bytes, b: bytes) -> bytes
```

If `a` and `b` can be independently either `str` or `bytes`, you need to use a regular union. And if there's just one string declaration within a signature, it doesn't matter.

**Comment by rra** [comment]
Oh, I had misunderstood `AnyStr` entirely.  Will fix.

And doh, of course, it's missing stubs.  That makes sense now.  My inclination is to just add types for those two cryptography files rather than tackling all of cryptography at the moment, since this is a detour from what I'm supposed to be working on, if that's okay.  :)

**Comment by ambv** [comment]
Of course, partial stubs are totally fair game. Scratch your own itch, somebody will come later and build on that. Maybe even you ;-)

**Comment by rra** [comment]
Okay, I think this is ready for review.  It both passes tests and correctly typechecks the code I'm working on.

The `cryptography.hazmat.primitives.asymmetric` stubs are going to be a bit irritating to anyone trying to typecheck actual code that uses it, since they are missing nearly everything in those files, but that seems to be the normal way of doing partial stubs?

**Comment by ambv** [comment]
Thanks! ✨ 🍰 ✨

**Pull request merged**
