### PR TITLE
Fix readline usages

### LINKED ISSUE #7003: tokenize.generate_tokens/tokenize doesn't accept readline with int arg
[tokenize.generate_tokens](https://docs.python.org/2.7/library/tokenize.html#tokenize.generate_tokens) documents it as taking a callable with the interface for `readline`, which https://github.com/python/typeshed/blob/master/stdlib/%40python2/builtins.pyi#L1160 (and similarly https://github.com/python/typeshed/blob/master/stdlib/io.pyi#L129) documents as `Callable[[int], str]`, but `generate_tokens` and `tokenize` (https://github.com/python/typeshed/blob/master/stdlib/tokenize.pyi#L49) document it as `Callable[[], str]` (or bytes, depending) both without the size arg

### PR DESCRIPTION
**Pull request by palfrey**
Fixes #7003

### CODE REVIEW

**Comment by Akuli** [comment]
What problem does this fix? As far as I can tell, none of the tokenize functions call the `readline` function with an argument, so there's no need to require it to work.

**Comment by palfrey** [comment]
> What problem does this fix? As far as I can tell, none of the tokenize functions call the `readline` function with an argument, so there's no need to require it to work.

Right now, there's a line of code in https://github.com/gristlabs/asttokens that's basically `tokenize.generate_tokens(io.StringIO(text).readline)` and mypy complains because the `readline` func and the `generate_tokens` disagree on the types. Replacing it with `tokenize.generate_tokens(cast(Callable[[], str], io.StringIO(text).readline))` works around that, but I'd like to fix it properly.

**Comment by Akuli** [comment]
Can you give me exact instructions for reproducing the problem? What type checker (mypy?), what version of the type checker, what branch in the repo, and so on. The following code gives no errors with mypy 0.931:

```python3
import tokenize
import io

def f() -> None:
    tokenize.generate_tokens(io.StringIO("asd").readline)
```

**Comment by JelleZijlstra** [comment]
I think @hauntsaninja diagnosed it as a Python 2 problem in the linked issue.

**Comment by hauntsaninja** [comment]
I think something like the following is what you actually want:
```
diff --git a/stdlib/@python2/tokenize.pyi b/stdlib/@python2/tokenize.pyi
index 98ec01a6..9461fd1f 100644
--- a/stdlib/@python2/tokenize.pyi
+++ b/stdlib/@python2/tokenize.pyi
@@ -1,4 +1,4 @@
-from typing import Any, Callable, Dict, Generator, Iterable, Iterator, List, Tuple
+from typing import Any, Callable, Dict, Generator, Iterable, Iterator, List, Tuple, AnyStr
 
 __author__: str
 __credits__: str
@@ -112,7 +112,7 @@ _Pos = Tuple[int, int]
 _TokenType = Tuple[int, str, _Pos, _Pos, str]
 
 def any(*args, **kwargs) -> str: ...
-def generate_tokens(readline: Callable[[], str]) -> Generator[_TokenType, None, None]: ...
+def generate_tokens(readline: Callable[[], AnyStr]) -> Generator[_TokenType, None, None]: ...
 def group(*args: str) -> str: ...
 def maybe(*args: str) -> str: ...
 def printtoken(type: int, token: str, srow_scol: _Pos, erow_ecol: _Pos, line: str) -> None: ...
```

**Comment by hauntsaninja** [comment]
Might also need some changes to `_TokenType`, but I've purged my head of Python 2 and the subtyping rules for unicode and str

**Comment by Akuli** [comment]
`AnyStr` isn't correct, and the type checker is pointing out a bug in the code. Python 2 expects `readline()` to return `str` (aka `bytes`), so if you feed it unicode strings instead, it ends up doing implicit conversions that will fail when not everything is ASCII.

The correct fix is to use `BytesIO` instead, and let `generate_tokens()` take in `str` (aka `bytes`). And also, if you want strings to just work, consider not supporting Python 2 :)

**Comment by hauntsaninja** [comment]
It might not be quite that simple. IIRC the `str` annotation doesn't actually mean `bytes`. I think Python 2 type checkers treat `str` as a subtype of `unicode`, not as incompatible (like `str` and `bytes`)

**Comment by Akuli** [comment]
From the runtime's point of view, passing in a unicode object might work. In general, operations like `u"foo" + "bar"`, the non-unicode string is what gets converted to unicode (with ASCII). And if that's hard-coded strings inside the tokenize module, and the unicode string is the input, everything should be fine.

There might be some corner case where this reasoning fails, but it seems unlikely to me that someone is:
- using Python 2
- uses a type checker
- writing non-ASCII code **AND**
- happens to hit a rare corner case.

So I'm fine with just accepting `AnyStr` here.

**Comment by palfrey** [comment]
I think there's maybe some thoughts on changing the return type, but the core problem I think here is the argument i.e. it should be an optional int positional arg, and the definition of `readline` seems to vary in different places, and sometimes it's required, and sometimes it's optional!

**Comment by Akuli** [comment]
Where exactly is the argument required? All relevant readline definitions I can find have `= ...`

**Comment by hauntsaninja** [comment]
Optional just means that None is a valid value for the argument. What specifies whether it's okay to omit the argument is whether it has a default value.

As I mentioned here and in the other issue, your case is not caused by problems with readline, but rather the types in `tokenize`. There's a diff above^ that changes `tokenize` to not complain about your case.

**Pull request closed without merging**
