### PR TITLE
Fix _patch.__call__()

### LINKED ISSUE #4566: Recent changes to mock.pyi incompatible with legimate uses of patch decorator
The recent changes to mock.pyi have caused spurious errors for legitimate code.

The code for the `@patch` decorator no longer supports idioms like the following:
```python
from mock import patch
import math

@patch("math.pi", 3.14)
def func():
    print(math.pi)

func()
```

The implementation seems to assume that the second argument, if provided, is always a callable, so the above code causes the type checker to emit errors.

Also, it doesn't support the following common case:
```python
@patch("internal_module.send_message", Mock())
def test_func(self):
     do_something_to_trigger_send_message()
```

The above code is flagged as an error because the `__call__` method in `Mock` has a var-arg parameter, and the decorated function does not, so the latter cannot be assigned to the former.

In short, the changes to mock.pyi have broken many cases where an argument is passed for the `new` parameter to `patch`. 

@srittau, perhaps these changes should be reverted until a fix is identified?

### PR DESCRIPTION
**Pull request by srittau**
_patch.call() reused the type variable _T, which is generic over
_patch. It was meant to use a separate type variable for the argument,
which is returned.

Fixes #4566

### CODE REVIEW

**Comment by srittau** [comment]
@erictraut I can't request you as reviewer via GitHub's function, so I'll do it via ping.

**Review by hauntsaninja — COMMENTED** [review]
Should this use the bounded and already defined `_F`?

**Comment by erictraut** [comment]
I confirmed that this change addresses the issue. Thanks for the fast fix!

**Comment by srittau** [comment]
@erictraut Sorry for the hassle. I changed the PR slightly per @hauntsaninja's suggestion. Could you retest? I will merge if everything works as expected.

**Comment by erictraut** [comment]
@srittau I confirmed that the updated change addresses the issue. Thanks!

**Comment by hauntsaninja** [comment]
Yay! Thanks Sebastian!

**Pull request merged**
