### PR TITLE
Now `add=` in `tkinter.pyi` can be `''` or `'+'`

### LINKED ISSUE #6332: tkinter: bind() method type-hint incorrectly has 'add' argument as a bool
The documentation for the `bind()` method https://docs.python.org/3/library/tkinter.html#bindings-and-events shows that the `add` parameter is a string.

The work from https://github.com/python/typeshed/pull/4347 made `add` be type-hinted as a `bool`.

So type-checking fails if doing: `add=""` or `add="+"` which is the documented way to use `add` in the `bind()` method.

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #6332
Docs https://docs.python.org/3/library/tkinter.html#bindings-and-events

### CODE REVIEW

**Comment by sobolevn** [comment]
СС @Akuli

**Comment by Akuli** [comment]
`bool` should also be accepted, because it works at runtime. Tkinter does `add and '+' or ''` which is an older way to spell `'+' if add else ''`.

**Comment by sobolevn** [comment]
So, `Literal['', '+'] | bool | None` it is?

**Comment by Akuli** [comment]
Yes, I'm fine with that. The documentation still doesn't make any sense to me, but if you prefer to change typeshed rather than documentation, that's fine with me.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by Akuli** [comment]
There's still a lot missing. This is on your branch:

```
akuli@akuli-desktop:~/typeshed$ git grep 'add: bool' stdlib/tkinter/
stdlib/tkinter/__init__.pyi:        self, sequence: str | None = ..., func: Callable[[Event[Misc]], Any] | None = ..., add: bool | None = ...
stdlib/tkinter/__init__.pyi:    def bind_all(self, sequence: str | None, func: str, add: bool | None = ...) -> None: ...
stdlib/tkinter/__init__.pyi:    def bind_all(self, *, func: str, add: bool | None = ...) -> None: ...
stdlib/tkinter/__init__.pyi:        self, className: str, sequence: str | None = ..., func: Callable[[Event[Misc]], Any] | None = ..., add: bool | None = ...
stdlib/tkinter/__init__.pyi:    def bind_class(self, className: str, sequence: str | None, func: str, add: bool | None = ...) -> None: ...
stdlib/tkinter/__init__.pyi:    def bind_class(self, className: str, *, func: str, add: bool | None = ...) -> None: ...
stdlib/tkinter/__init__.pyi:        add: bool | None = ...,
stdlib/tkinter/__init__.pyi:    def tag_bind(self, tagOrId: str | int, sequence: str | None, func: str, add: bool | None = ...) -> None: ...
stdlib/tkinter/__init__.pyi:    def tag_bind(self, tagOrId: str | int, *, func: str, add: bool | None = ...) -> None: ...
stdlib/tkinter/__init__.pyi:        self, tagName: str, sequence: str | None, func: Callable[[Event[Text]], Any] | None, add: bool | None = ...
stdlib/tkinter/__init__.pyi:    def tag_bind(self, tagName: str, sequence: str | None, func: str, add: bool | None = ...) -> None: ...
```

**Comment by sobolevn** [comment]
Is it the same for all `bind_*` methods and `add` parameter? Or are there any exceptions?
Looks like docs only cover `'+' | '-'` and `bind`: https://docs.python.org/3/library/tkinter.html#bindings-and-events

I am not really familiar with the internals.

**Comment by Akuli** [comment]
All `bind_foo` and `foo_bind` methods call `_bind`, which contains the `add and '+' or ''` code.

**Comment by sobolevn** [comment]
Or basically all method that call `._bind()` inside: https://github.com/python/cpython/blob/32959108f9c543e3cb9f2b68bbc782bddded6f42/Lib/tkinter/__init__.py#L1420

Thanks! I'm on it.

**Comment by Akuli** [comment]
`tkinter.Canvas.tag_bind` and `tkinter.Text.tag_bind` still use `bool | None`.

**Review by JohnVillalovos — APPROVED** [review]
Looks good to me. Thanks for doing this so fast!

**Comment by sobolevn** [comment]
Oh my, GitHub totally needs `black` integration 😒

**Comment by Akuli** [comment]
> Oh my, GitHub totally needs `black` integration

Related: #5552

**Review by Akuli — APPROVED** [review]
I still think the docs are insane and should be changed instead, but this looks good to me.

**Pull request merged**
