### PR TITLE
Add correct optional default start/end parameters to str count, find,…

### LINKED ISSUE #1108: str.count annotation is missing optional parameters.
```
s = "abc"
c = s.count('b', 0, 0) # x.py:2:4: error: Too many arguments for "count" of "str"
```
The code is valid; the error is spurious. As discussed in PR #1107, it appears that fixing this is a bit complex due to the type definition of Sequence.count.

### PR DESCRIPTION
**Pull request by gwk**
… index, rfind, rindex.

This supersedes PR #1107, and fixes #1108.

I reviewed the corresponding annotations for `byte` and `bytearray`; they look correct but use the `x: int = None` style which @JelleZijlstra says is discouraged. Perhaps those should be cleaned up separately?

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks, this looks fine to me but I'll wait for @gvanrossum before merging.

**Comment by gwk** [comment]
Also filed #1110 for the remaining `__index__` concern, which I cannot take on at this point in time.

**Comment by gvanrossum** [comment]
OK, but...
- This also needs to happen for Python 2
- These functions only take keyword args -- by convention we'd use `__start` etc.

**Comment by gwk** [comment]
@gvanrossum just pushed an updated commit addressing your concerns.

**Comment by gvanrossum** [comment]
Thanks for the quick response!

**Pull request merged**
