### PR TITLE
Third-party stubs: fix several fictitious type aliases

### LINKED ISSUE #7954: Stubtest failed on Thu May 26 2022
Stubtest runs are listed here: https://github.com/python/typeshed/actions/workflows/daily.yml

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #7954

I also did some driveby `TypeAlias` fixes.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Not sure why stubtest is failing to import `google-cloud-ndb`.

**Comment by AlexWaygood** [comment]
For some reason, it looks like stubtest for this PR is installing a different version of protobuf than the one it did for the daily test last night.

---

**Last night**
`protobuf==3.20.1` was installed for testing `google-cloud-ndb`

**This PR**
`protobuf==4.21.0` is being installed for testing `google-cloud-ndb`

---

I've no idea if that's what's causing the CI failure here, or why a different version of `protobuf` is being installed now.

**Comment by AlexWaygood** [comment]
> For some reason, it looks like stubtest for this PR is installing a different version of protobuf than the one it did for the daily test last night.
> 
> **Last night** `protobuf==3.20.1` was installed for testing `google-cloud-ndb`
> 
> **This PR** `protobuf==4.21.0` is being installed for testing `google-cloud-ndb`
> 
> I've no idea if that's what's causing the CI failure here, or why a different version of `protobuf` is being installed now.

Manually pinning the version of `protobuf` that stubtest uses seems to have fixed it, so I guess this was the problem.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Note that protobuf 4.21.0 was just released yesterday: https://pypi.org/project/protobuf/#history

**Comment by AlexWaygood** [comment]
> Note that protobuf 4.21.0 was just released yesterday: https://pypi.org/project/protobuf/#history

Ahh, makes sense. I was searching through the `google-cloud-ndb` source code for changes, and couldn't see anything.

**Pull request merged**
