### PR TITLE
fix Why is the __val argument to the Generator.throw() method annotated as BaseException | object instead of just object?

### LINKED ISSUE #6040: Why is the `__val` argument to the `Generator.throw()` method annotated as `BaseException | object` instead of just `object`?
Sorry if I miss something. In my understanding of the type hinting system, `BaseException | object` is just reduced to `object`. But below line shows that the `__val` argument of the `Generator.throw()` method is annotated as `BaseException | object`. I wonder if this is intended or just a typo?

https://github.com/python/typeshed/blob/e4c2c0f3021abac1078854da92a9ec14848b32f4/stdlib/typing.pyi#L208

### PR DESCRIPTION
**Pull request by Rohan-Salwan**
fix #6040

### CODE REVIEW

**Comment by srittau** [comment]
I am not sure this is the right way forward. Maybe @milapsheth or @JelleZijlstra have more insight why this was types like it is in the first place. As I wrote in #6040, maybe `BaseException | Any` is better than `BaseException | object`, though.

**Comment by Rohan-Salwan** [comment]
@milapsheth and  @JelleZijlstra please share your views.

**Comment by milapsheth** [comment]
Added a comment to #6040 :)

**Comment by srittau** [comment]
Based on the comments in #6040, I don't think we should do this. Thank you for the PR! The renewed discussion helped to resolve the issue. :)

**Pull request closed without merging**
