### PR TITLE
Fix pos-only params in `tkinter` module

### PR DESCRIPTION
**Pull request by sobolevn**
Same as https://github.com/python/typeshed/pull/11505

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Same comment as https://github.com/python/typeshed/pull/11505#discussion_r1507197242 ;)

**Review by AlexWaygood — APPROVED** [review]

**Comment by Akuli** [comment]
This is less readable. What problem does this solve?

**Comment by AlexWaygood** [comment]
> This is less readable. What problem does this solve?

See conversation in https://github.com/python/typeshed/pull/11505#discussion_r1507197242

**Comment by Akuli** [comment]
I still don't see a practical problem being solved. Type checkers will generally tolerate small issues in stubs as long as stubs are somewhat understandable. On the other hand, IDE users will not be happy trying to decipher the new `Unpack` contraption.

**Comment by AlexWaygood** [comment]
> > it's valid at runtime to pass default using a keyword argument
> 
> It's not. This method cannot be called so that you pass a keyword argument for `default`. If you try to do it, python will complain that you're passing two values for it:

Got it -- my mistake. In that case, we should be able to simply update the signature to the much-simpler

```py
def wm_iconphoto(self, default: bool, image1: _PhotoImageLike | str, /, *args: _PhotoImageLike | str) -> None: ...
```

**Comment by Akuli** [comment]
> FWIW, I did test locally, but obviously not thoroughly enough :)

To be honest, the whole `wm_iconphoto()` method is a mess. A positional-only boolean parameter is just a bad idea for readability, but it's too late to change it now: that would break every tkinter program that sets a custom icon for the app.

**Pull request merged**
