### PR TITLE
Docutils.utils.roman

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Review by srittau — COMMENTED** [review]
Thanks! Should we also include the exceptions in this file or are they not useful outside it?

**Comment by danieleades** [comment]
> Thanks! Should we also include the exceptions in this file or are they not useful outside it?

i didn't even look at them to be honest, scoped this only the functions. I can possibly take a look this evening

**Comment by danieleades** [comment]
> > Thanks! Should we also include the exceptions in this file or are they not useful outside it?
> 
> i didn't even look at them to be honest, scoped this only the functions. I can possibly take a look this evening

@srittau had a quick look now. I'm not sure what adding type stubs for the exceptions would add over and above the package itself. They define no additional attributes or methods, and the inheritance is already captured in the implementation.

What would be the benefit of including type stubs for these exceptions in typeshed?

**Comment by srittau** [comment]
Without defining them, a type checker would complain about the following code:

```python
from docutils.utils.roman import toRoman, OutOfRangeError  # unknown import OutOfRangeError

try:
    toRoman(...)
except OutOfRangeError:
    ...
```

**Comment by danieleades** [comment]
> Without defining them, a type checker would complain about the following code:
> 
> ```python
> from docutils.utils.roman import toRoman, OutOfRangeError  # unknown import OutOfRangeError
> 
> try:
>     toRoman(...)
> except OutOfRangeError:
>     ...
> ```

you're revealing my ignorance of the type checker!

i find this surprising, i would have thought a type checker would be happy with this because while not defined in the type stub, it would absolutely be defined in the `docutils.utils.roman` package. I didn't realise you needed the information redundantly in both places. I guess that also means you can't incrementally migrate annotations from type stubs into a code base?

**Comment by srittau** [comment]
> I guess that also means you can't incrementally migrate annotations from type stubs into a code base?

Not really. You can add `def __getattr__(self, name: str) -> Incomplete: ...` to stubs (like some docutils modules have) to say: "This module has more stuff." But that means that this is not only completely untyped, it also means that type checkers will happily import typos. This is why our current recommendation for new packages is to use stubgen to add all elements, even if they are untyped.

**Comment by danieleades** [comment]
> > I guess that also means you can't incrementally migrate annotations from type stubs into a code base?
> 
> Not really. You can add `def __getattr__(self, name: str) -> Incomplete: ...` to stubs (like some docutils modules have) to say: "This module has more stuff." But that means that this is not only completely untyped, it also means that type checkers will happily import typos. This is why our current recommendation for new packages is to use stubgen to add all elements, even if they are untyped.

got it. I'd always assumed (with no basis) you were getting a union of the concrete implementation and stub type information.

I'll update to add the exceptions

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
