### PR TITLE
python3: remove _subprocess

### PR DESCRIPTION
**Pull request by hauntsaninja**
This doesn't seem to exist in Python 3.5, which is the earliest Python3
we support, and this folder is in stdlib/3

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
The stubs look like they're Windows-only. I found release notes saying the module was removed in 3.3.0a3, so we can safely get rid of it.

**Comment by JelleZijlstra** [comment]
Apparently there's some mypy unit test relying on this module. Would you mind submitting a PR to mypy to resolve it?

**Comment by hauntsaninja** [comment]
Opened a PR against mypy in https://github.com/python/mypy/pull/8838

**Comment by hauntsaninja** [comment]
#8838 is merged now, so maybe we can re-run CI

**Pull request merged**
