### PR TITLE
Remove mypy excludes

### PR DESCRIPTION
**Pull request by srittau**
The list hasn't been used since 2016 and I don't think we should add files that mypy can't parse anyway at this point.

This simplifies `mypy_test.py` quite a bit.

### CODE REVIEW

**Comment by srittau** [comment]
Depends on #6229.

**Comment by JelleZijlstra** [comment]
I merged the other PR, going to mark this one as ready.

**Comment by JelleZijlstra** [comment]
There is a merge conflict that's beyond my current pay grade.

**Comment by srittau** [comment]
I force pushed this after a rebase against master. Basically all commits except the last were from #6229, so this just reapplied the last commit. Ready for review.

**Review by Akuli — APPROVED** [review]

**Pull request merged**
