### PR TITLE
Overhaul `socket` stubs on Windows and MacOS

### PR DESCRIPTION
**Pull request by AlexWaygood**
Helps with #8101.

This PR reduces the `(_)socket` allowlists for win32 and darwin to only a handful of missing constants/functions.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Thanks, this is a pretty heroic PR. I'd want to double check there aren't any Linux regressions before merging.

Can confirm stubtest also looks good on my Mac laptop (in case there were OS version or hardware specific things we're missing). For what it's worth, I have `socket.MSG_NOSIGNAL` on 3.8 and above — curious what you were seeing.

**Comment by AlexWaygood** [comment]
> For what it's worth, I have `socket.MSG_NOSIGNAL` on 3.8 and above — curious what you were seeing.

I was using GH Actions on my fork to run stubtest, and it _seemed_ like it varied from one stubtest run to the next as to whether it existed at runtime.

**Comment by AlexWaygood** [comment]
> I'd want to double check there aren't any Linux regressions before merging.

Here's a failing Ubuntu stubtest run from yesterday on my fork, before I added the allowlist back for linux, if that's helpful: https://github.com/AlexWaygood/typeshed/runs/6955971392?check_suite_focus=true

**Comment by hauntsaninja** [comment]
Confirmed that we didn't accidentally regress availability of some constants on Linux on Python 3.9

**Review by hauntsaninja — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> Confirmed that we didn't accidentally regress availability of any constants on Linux on Python 3.9 (same set of "is not present in stub" errors)

Awesome, thanks for checking!

**Pull request merged**
