### PR TITLE
PEP 604: Add ror operator and modify isinstance and subclass

### PR DESCRIPTION
**Pull request by mano7onam**
Add operators or and ror for types.Union and ror to the type class.
Also, add modified isinstance and issubclass signatures to support old-style and new-style unions inside.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Generally looks good, but there's a few CI failures to address.

**Comment by mano7onam** [comment]
> Generally looks good, but there's a few CI failures to address.

Yep, I see, I'll fix it

**Comment by mano7onam** [comment]
It looks like pyright considers Union as typing.Union but not as types.Union and claims to have unnecessary generic parameters.

**Comment by jakebailey** [comment]
FWIW if you merge or rebase master, the pyright errors should go away.

**Pull request merged**
