### PR TITLE
Fix generic types aliases in requests stubs

### PR DESCRIPTION
**Pull request by vrslev**
This fixes Pyright type checking. When creating an alias of Generic type it is not interpreted correctly.
Reference: https://github.com/microsoft/pyright/issues/2799#issuecomment-1005042304

### CODE REVIEW

**Comment by vrslev** [comment]
[Test](https://github.com/python/typeshed/runs/4705762349?check_suite_focus=true) did not pass. `RecentlyUsedContainer` is no longer used by requests. Also `Session` doesn't have `redirect_cache` attribute. Should I remove them?

**Comment by srittau** [comment]
@vrslev Thanks for the PR. #6838 was just merged and updated requests's version number. Can you merge `master` into your branch and push? We will then see what effects this will have on our tests.

**Comment by vrslev** [comment]
@srittau Test still fails. I think my PR has conflicts with this one: https://github.com/python/typeshed/pull/6840. And changes made there should fix issue that my PR tries to fix.

**Comment by JelleZijlstra** [comment]
Thanks for your contribution! I merged the other more comprehensive PR.

**Pull request closed without merging**
