### PR TITLE
Re-enable stdlib stubtest on macos

### LINKED ISSUE #6616: Re-enable stubtest on macOS
Temporarily disabled in https://github.com/python/typeshed/pull/6604

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #6616

### CODE REVIEW

**Comment by Akuli** [comment]
This is more difficult than expected, because of tkinter.

If I just add `"stubtest-macos"` to the matrix, stubtest will fail to import tkinter. This is because for whatever reason, the Python 3.10.1 that github actions uses is compiled in a way that makes it depend on Tcl/Tk 8.6.x, but only Tcl/Tk 8.5.x is installed. Tcl programming language, and its gui library Tk, are what tkinter uses internally.

By "installed", I mean `/System/Library/Frameworks/Tcl.framework/Versions/8.5` exists but `/System/Library/Frameworks/Tcl.framework/Versions/8.6` doesn't exist. According to `otool -L /Users/runner/hostedtoolcache/Python/*/x64/lib/*/lib-dynload/_tkinter.*.so`, `_tkinter` links to files that are in those folders.

If I run `brew install tcl-tk`, it says `Warning: tcl-tk 8.6.12 is already installed and up-to-date` even though `/System/Library/Frameworks/Tcl.framework/Versions/8.6` doesn't exist?

If someone has more experience about how dynamic libraries work on mac, please let me know if I'm being really dumb and not noticing some easy solution :)

**Comment by Akuli** [comment]
This PR has the weirdest problem I have seen in a long time.

On this repo, if I run `ls /usr/local/lib` on macos-latest, I get a list of files that does NOT include `libtcl8.6.dylib` or `libtk8.6.dylib`. If I make a new repo, Akuli/testing2, and run the same exact command there, with the same exact github actions config file, the files exist.

**Comment by Akuli** [comment]
Ready for review, once CI passes. Feel free to ignore my mess above, got it sorted now and it wasn't that complicated in hindsight :)

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
