### PR TITLE
Add partial.__new__

### PR DESCRIPTION
**Pull request by NeilGirdhar**
* Add `partial.__new__`: `__new__` is necessary for any derived classes that
  override `__new__` and want to call super since `__new__` instead of `__init__` is
  defined in the base class.
* Remove `partial.__init__` since it's not defined.
* Make the func parameter positional-only by naming it with
  double-underscore, as per PEP 484.

See: https://github.com/python/cpython/blob/main/Lib/functools.py#L283

### CODE REVIEW

**Review by Akuli — APPROVED** [review]
This looks correct, although I'm not sure how much practical effect it has. Type checkers special-case `functools.partial`.

**Comment by Akuli** [comment]
Nit for future reference: Avoid amending and force-pushing when contributing to typeshed, because after a force-push, it's harder to see what has changed since the previous review. When merging the PR, we will use Github's "Squash and merge" button to combine the whole PR into a single commit on master.

**Comment by NeilGirdhar** [comment]
@Akuli I tested that this change fixes my MyPy error here: https://github.com/NeilGirdhar/tjax/blob/master/tjax/_src/partial.py#L57

**Comment by Akuli** [comment]
Nice! You may want to add the project to https://github.com/hauntsaninja/mypy_primer so that instead of getting the above "no effect" comment from mypy_primer, we would get something along the lines of "unused type: ignore comment".

**Pull request merged**
