### PR TITLE
[April 2023] `D3DShot` is an archived repo

### PR DESCRIPTION
**Pull request by sobolevn**
Link: https://github.com/SerpentAI/D3DShot

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Thanks!

**Comment by AlexWaygood** [comment]
This one's a bit of a special case -- we only added these stubs a few weeks ago, and we knew it was archived at the time (https://github.com/python/typeshed/pull/8652#issuecomment-1237727896, and following discussion).

It feels a bit harsh on @Avasam to delete the stubs from typeshed only a month after he put a lot of work into adding them!

**Comment by srittau** [comment]
Maybe we should delete them after six months if there haven't been major updates to the stubs since then? I'd expect possible kinks having been worked out by then, so the last published version on PyPi of the types should be in a good state by then.

**Comment by AlexWaygood** [comment]
> Maybe we should delete them after six months if there haven't been major updates to the stubs since then? I'd expect possible kinks having been worked out by then, so the last published version on PyPi of the types should be in a good state by then.

Yeah, that sounds like a good plan to me!

**Pull request merged**
