### PR TITLE
Reformatted all files with black and isort

### PR DESCRIPTION
**Pull request by srittau**
A few comments between imports were removed or moved to the top of the
import block, due to behavioral differences between black and isort. See
https://github.com/psf/black/issues/251 for details.

In two instances `@overloads` at the top of the file needed to be moved
due to https://github.com/psf/black/issues/1490.

### CODE REVIEW

**Comment by srittau** [comment]
Now pytype fails. It was fine with the previous commit, but bails when moving the `# type: ignore` comments to the first line. Cc @rchen152

**Comment by srittau** [comment]
The problem is only with the second commit, which only touches three files. I will see whether I can work around this later.

**Comment by rchen152** [comment]
Sorry, just saw this. At a glance, it looks like pytype doesn't expect a `# type: ignore` after the opening parenthesis in a function definition? I'll take a look.

**Comment by rchen152** [comment]
I pushed a pytype change to allow `# type: ignore` after the opening parenthesis in a function definition. (Sorry this issue keeps coming up! We've been wanting to fix our pyi parser for a long time, but there's always something more urgent to do...) If all goes well, a release containing this change should go out sometime next week.

**Comment by srittau** [comment]
Closing. I will open a new PR when the new pytest version is released. In the meantime, #4228 contains a few changes from this PR to address black and isort incompatibilities that will ease the Big Reformat.

**Comment by JelleZijlstra** [comment]
Looks like the pytype release hasn't gone out just yet.

**Pull request closed without merging**
