### PR TITLE
Fix initialization params for hashlib functions

### PR DESCRIPTION
**Pull request by karolyi**
Et voilà.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Could you explain what problem this fixes? It appears that the _Hash class doesn't actually exist, but a number of module-level functions return an object with a similar interface, which we represent as `_Hash`. However, these objects cannot be directly instantiated, and perhaps we should instead remove the `__init__` method.

**Comment by karolyi** [comment]
`sha256`, `md5` and the likes are aliases to that hash function, at least in typeshed. When initializing those, the `data` parameter is invalid. in fact, here's the built-in help for `sha256`, by which I updated the code:

```python
>>> from hashlib import sha256
>>> help(sha256)
Help on built-in function openssl_sha256 in module _hashlib:

openssl_sha256(string=b'', *, usedforsecurity=True)
    Returns a sha256 hash object; optionally initialized with a string
```

Also, here's the generic function signature:
```python
>>> sha256.__text_signature__
"($module, /, string=b'', *, usedforsecurity=True)"
```

[The official documentation](https://docs.python.org/3/library/hashlib.html#constructors) about the constructor behind these functions states that it's `data` but as it shows above, it's not. The python documentation is erroneous in this regard, and if you try to initialize with the data keyword, it'll fail.

Hope it makes sense now.

**Comment by JelleZijlstra** [comment]
What you say applies to the module-level `sha256` function, not to the `_Hash.__init__` method. Could you give an example of code that is currently not accepted by a type checker but would be fixed by this change?

**Comment by hauntsaninja** [comment]
Something like `hashlib.sha3_224(b"asdf", usedforsecurity=True)`

**Comment by karolyi** [comment]
Ah, I started to get upset as to what you don't understand, but then I realized there was information I (unintentionally) omitted.

I am using the `sha3_256` function that links back to `_Hash` and thus its signature (and everything else's that links back to that class) is invalid.

That's what I've corrected here.
image

**Comment by JelleZijlstra** [comment]
Sorry for that! I saw that several hash functions were defined as functions returning `_Hash`:

```
def sha512(string: ReadableBuffer = b"", *, usedforsecurity: bool = True) -> _Hash: ...
```

But I hadn't scrolled down far enough in the file to see that a few are also defined as aliases for `_Hash`:

```
sha3_224 = _Hash
```

At runtime, `hashlib.sha3_256` is a function, not a class, so I think it should be refactored to look like `sha512`.

**Comment by karolyi** [comment]
Fine with me. Just don't expect me to do it, as I'm knee deep in work.

**Comment by JelleZijlstra** [comment]
Replaced with #12906, thanks @karolyi and @brianschubert!

**Pull request closed without merging**
