### PR TITLE
[WIP] Add docutils/nodes stubs

### LINKED ISSUE #1269: type annotation for docutils is incomplete
It seems `third_party/3/docutils` contains only very few classes and modules of docutils.
https://github.com/python/typeshed/tree/master/third_party/3/docutils

For example, the only one class `reference` is defined at `nodes.pyi`. But actual `docutils.nodes` module provides many classes and functions:
```
>>> import docutils.nodes
>>> dir(docutils.nodes)
['Admonition', 'BackLinkable', 'Bibliographic', 'Body', 'Decorative', 'Element', 'FixedTextElement', 'General', 'GenericNodeVisitor', 'Inline', 'Invisible', 'Labeled', 'Node', 'NodeFound', 'NodeVisitor', 'Part', 'PreBibliographic', 'Referential', 'Resolvable', 'Root', 'Sequential', 'SkipChildren', 'SkipDeparture', 'SkipNode', 'SkipSiblings', 'SparseNodeVisitor', 'Special', 'StopTraversal', 'Structural', 'Targetable', 'Text', 'TextElement', 'Titular', 'TreeCopyVisitor', 'TreePruningException', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_add_node_class_names', '_call_default_departure', '_call_default_visit', '_non_id_at_ends', '_non_id_chars', '_non_id_translate', '_non_id_translate_digraphs', '_nop', 'abbreviation', 'acronym', 'address', 'admonition', 'attention', 'attribution', 'author', 'authors', 'block_quote', 'bullet_list', 'caption', 'caution', 'citation', 'citation_reference', 'classifier', 'colspec', 'comment', 'compound', 'contact', 'container', 'copyright', 'danger', 'date', 'decoration', 'definition', 'definition_list', 'definition_list_item', 'description', 'docinfo', 'doctest_block', 'document', 'dupname', 'emphasis', 'ensure_str', 'entry', 'enumerated_list', 'error', 'field', 'field_body', 'field_list', 'field_name', 'figure', 'footer', 'footnote', 'footnote_reference', 'fully_normalize_name', 'generated', 'header', 'hint', 'image', 'important', 'inline', 'label', 'legend', 'line', 'line_block', 'list_item', 'literal', 'literal_block', 'make_id', 'math', 'math_block', 'node_class_names', 'note', 'option', 'option_argument', 'option_group', 'option_list', 'option_list_item', 'option_string', 'organization', 'os', 'paragraph', 'pending', 'problematic', 'pseudo_quoteattr', 'raw', 're', 'reference', 'reprunicode', 'revision', 'row', 'rubric', 'section', 'serial_escape', 'sidebar', 'status', 'strong', 'subscript', 'substitution_definition', 'substitution_reference', 'subtitle', 'superscript', 'sys', 'system_message', 'table', 'target', 'tbody', 'term', 'tgroup', 'thead', 'tip', 'title', 'title_reference', 'topic', 'transition', 'types', 'unicodedata', 'version', 'warning', 'warnings', 'whitespace_normalize_name']
```

As a result, mypy fails for hinting.
```
from docutils import nodes

def hello(node):
    # type: (nodes.Node) -> None
    pass
```
```
$ mypy foo.py
foo.py:3: error: Name 'nodes.Node' is not defined
```

### PR DESCRIPTION
**Pull request by danieleades**

### CODE REVIEW

**Comment by danieleades** [comment]
@Akuli, @srittau
i could really use some mentoring on this

- is it preferable to leave the autogenerated `Any` types, or remove these entirely?
- is there a way to check these are consistent with the source files (or do any of the CI jobs do that automagically?)

note that this is still very much a work in progress. i've only manually added types to a small subset of the total file. i *may* not attempt to do the whole file in this one pull request (it's a big'un)

**Comment by hauntsaninja** [comment]
Yup, it's preferable to remove autogenerated `Any` types (unless you've confirmed that they should be `Any`)

You can check consistency with source using:
```
python -m pip install git+https://github.com/python/mypy.git
MYPYPATH=stubs/docutils python -m mypy.stubtest --custom-typeshed-dir ~/path_to_typeshed docutils --concise
```
(CI jobs only do this automagically for stdlib, currently)

**Comment by srittau** [comment]
Thank you for this! I haven't looked at it in depth, but I have a minor style nit: Defaults (`= ...`) are redundant for module and class fields and should be omitted.

**Comment by danieleades** [comment]
> Thank you for this! I haven't looked at it in depth, but I have a minor style nit: Defaults (`= ...`) are redundant for module and class fields and should be omitted.

when *are* defaults required?

**Comment by srittau** [comment]
Defaults are only useful for function and method arguments.

**Comment by danieleades** [comment]
> Yup, it's preferable to remove autogenerated `Any` types (unless you've confirmed that they should be `Any`)
> 
> You can check consistency with source using:
> 
> ```
> python -m pip install git+https://github.com/python/mypy.git
> MYPYPATH=stubs/docutils python -m mypy.stubtest --custom-typeshed-dir ~/path_to_typeshed docutils --concise
> ```
> 
> (CI jobs only do this automagically for stdlib, currently)

i think i'm doing this wrong.

```
cd /path/to/typeshed/repo
MYPYPATH=stubs/docutils python -m mypy.stubtest --custom-typeshed-dir . docutils --concise
```
```
error: failed mypy build.
stubs/docutils/docutils/parsers/rst/__init__.pyi:2: error: Skipping analyzing "typing_extensions": found module but no type hints or library stubs
stubs/docutils/docutils/parsers/rst/__init__.pyi:2: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

am i using this correctly? can i limit the consistency check to only `docutils/nodes`?

**Comment by danieleades** [comment]
so i'm a little surprised to discover that adding `def __getattr__(self, name: str) -> Any: ...  # incomplete` to a class doesn't appear to suppress warnings about missing stubs for that class.

is that expected?

**Comment by hauntsaninja** [comment]
For stubtest? Yeah, that's expected. stubtest is meant to help you complete and check stubs and if something is not-dynamic enough that stubtest can find it, it really should be in the stubs. If you want stubtest to shut up about things you haven't added yet and just check the things that you have, run with `--ignore-missing-stubs`. If you want more customised ignoring of errors, use stubtest's allowlisting functionality.

**Comment by Akuli** [comment]
Before merging, I think we should compare this with @tk0miya's stubs (mentioned in #1269), or somehow combine the stubs together.

**Comment by danieleades** [comment]
> Before merging, I think we should compare this with @tk0miya's stubs (mentioned in #1269), or somehow combine the stubs together.

I concur

**Comment by danieleades** [comment]
@tk0miya how do you feel about opening a pull request to merge your work in docutils stubs?

**Comment by JelleZijlstra** [comment]
Any updates here?

**Comment by JelleZijlstra** [comment]
Going to close this as stale for now to keep the list of open PRs manageable. If you're still interested in seeing this through, feel free to reopen or open a new PR.

**Pull request closed without merging**
