### PR TITLE
Depend on Pillow instead of types-Pillow

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by srittau** [comment]
The PIL imports are trivial in all those packages: `from PIL import Image`. This doesn't prevent users from installing types-Pillow in addition to Pillow.

The PyAutoGUI stubs don't import PIL directly. But they depend on types-PyScreeze, which itself depends on Pillow, so any indirect "Pillow" needs in types-PyAutoGUI should be handled by indirect dependency.

**Comment by srittau** [comment]
Cf. #11688.

@AlexWaygood Considering we should start depending on Pillow instead of types-Pillow, working around the problems in the stubs instead of our test infrastructure seems to be the easiest solution.

**Comment by AlexWaygood** [comment]
> Cf. #11688.
> 
> @AlexWaygood Considering we should start depending on Pillow instead of types-Pillow, working around the problems in the stubs instead of our test infrastructure seems to be the easiest solution.

If the Pillow inline type annotations are complete enough for us to depend on them, that sounds great to me!

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Looks great, thanks!

**Comment by srittau** [comment]
Some annotations in the Pillow annotations are still lacking, compared to typeshed. But they are enough for the stubs that depend on it, since they only use the `Image` class, which obviously exist in Pillow as well. By using the dependency on Pillow instead of types-Pillow, our users can now decide whether Pillow is enough or they still want to use types-Pillow.

**Comment by AlexWaygood** [comment]
Note that this does mean that we will no longer have any pyright coverage for our Pillow stubs in CI (it will only see the inline Pillow types, not our stubs). Still, if we now plan on contributing improvements upstream to Pillow and marking our stubs obsolete soon, that shouldn't be a major issue. (I endorse the plan, though I'm afraid I can't commit to helping out with it much over the next few weeks ☹️)

**Comment by srittau** [comment]
This stub uploader check seems to be overzealous. In this case, python-xlib doesn't need to depend on Pillow to be able to work with Pillow's Image objects. Our stubs would need to depend on it though.

I'll try a different solution, although I'm not sure that works in stubs.

**Comment by srittau** [comment]
Yeah, that's the best solution for now. I'll open a discussion about conditional imports in stub files, though.

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
