### PR TITLE
typed-ast: fix kw_defaults arg

### PR DESCRIPTION
**Pull request by hauntsaninja**
Following the redundant-expr change, mypy self check is broken when run
using Python 3.8 (mypy CI runs self check with 3.7)

### CODE REVIEW

**Comment by AlexWaygood** [comment]
This PR has 0 lines changed relative to typeshed master :)

**Comment by JelleZijlstra** [comment]
Yes, we already did this in #8645.

**Comment by AlexWaygood** [comment]
You might need to run `pip install -r test-requirements.txt` again locally in your mypy virtual environment — I bumped the `types-typed-ast` requirement in https://github.com/python/mypy/pull/13547

**Comment by hauntsaninja** [comment]
Sounds like this PR is good to merge then?

**Pull request closed without merging**
