### PR TITLE
Make NoReturn a SpecialForm

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This is consistent with the runtime definition: https://github.com/python/cpython/blob/main/Lib/typing.py#L434.

The previous definition was wrong; NoReturn is not and should not be equivalent to None. This fixes an issue in pyanalyze where it was interpreting NoReturn as equivalent to None.

cc @erictraut in case this affects pyright. mypy-primer will tell us what mypy thinks about it.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks!

**Comment by erictraut** [comment]
I've made the necessary changes in pyright, and I'll be publishing a new version within the next few hours. We can then update your PR to point to the new version, which should eliminate the CI errors.

**Comment by erictraut** [comment]
I've published pyright 1.1.187, which fixes this issue. Typeshed currently uses 1.1.184. If you update this version (in both workflows/tests.yml and tests/pyright_test.py) within your PR, the CI errors should disappear.

**Comment by JelleZijlstra** [comment]
Thanks for the very quick fix! CI passes now.

**Review by srittau — APPROVED** [review]

**Comment by KotlinIsland** [comment]
I think the original authors intent would be much more accurately described with:
```py
NoReturn = Union[()] # "<nothing>" 
```
# 😳😳😳😳😳😳😳😳😳😳😳😳

Too bad this doesn't actually work:
```py
Never: TypeAlias = Union[()]

# incorrect
a: Never = 1  # error: Variable "__main__.Never" is not valid as a type
# correct
b: Union[()] = 1  # error: Incompatible types in assignment (expression has type "int", variable has type <nothing>)
```

**Pull request merged**
