### PR TITLE
move request.packages.urllib3 to urllib3

### PR DESCRIPTION
**Pull request by tharvik**
[requests bundle urllib3](https://github.com/kennethreitz/requests/tree/master/requests/packages), to ease installation, but it can be (and on some system, is) unbundle at installation time.

Currently, we have `urllib3` bundle in the stubs, in [`requests.packages.urllib3`](https://github.com/python/typeshed/tree/master/third_party/3/requests/packages).

IMO, we should move `urllib3` to `third_party/3`, fix some imports and then we will have a nicer structure.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Have you asked the authors of urllib3 about this? See the typeshed README.md.

**Comment by tharvik** [comment]
The package was already in the tree, so I tough it was already agreed upon.
btw, I'm adding type annotation directly to [urllib3](https://github.com/shazow/urllib3/issues/867), that might be a better design, thus removing the need to have urllib3 at all in here.

**Comment by gvanrossum** [comment]
AFAIK requests has agreed, and they have control over their vendored
packages. Also, nobody ought to use those vendored APIs except tequests
itself. But urllib3 has separate authorship who might care about the stubs
outside requests.

On Tuesday, May 24, 2016, Valérian Rousset <notifications@github.com> wrote:

> The package was already in the tree, so I tough it was already agreed upon.
> btw, I'm adding type annotation directly to urllib3
> <https://github.com/shazow/urllib3/issues/867>, that might be a better
> design, thus removing the need to have urllib3 at all in here.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/python/typeshed/pull/209#issuecomment-221478980>
>


-- 
--Guido (mobile)

**Comment by tharvik** [comment]
Ok, closing it for now, we will see how the typechecking PR at urllib3 is handled.

**Pull request closed without merging**
