### PR TITLE
make itertools.ifilter predicate parameter Optional

### PR DESCRIPTION
**Pull request by matthiaskramm**
Patch from @sfreilich: In Python 2, the predicate parameter in itertools.ifilter and
itertools.ifilterfalse can be None, indicating that true or false values
should be retained (functionally equivalent to passing "bool" as the
predicate). In Python 3, filter and itertools.filterfalse have
the same behavior.

### CODE REVIEW

**Comment by sfreilich** [comment]
I appreciate that you're merging my patch, but I would also appreciate if the commit message mentioned that I wrote the change.

**Comment by matthiaskramm** [comment]
Done. Sorry. Didn't mean to steal your work. ;)

**Comment by gvanrossum** [comment]
[Is there a reason @sfreilich couldn't just submit their own Pull Request? Those automatically get credit.]

**Comment by sfreilich** [comment]
Just a matter of timing. I'm on vacation and mostly away from my computer this week.

**Comment by JelleZijlstra** [comment]
Confirmed in 2.7 and 3.6 that the patch is right.

**Pull request merged**
