### PR TITLE
Revert "Bump jsonschema to 4.19.*"

### PR DESCRIPTION
**Pull request by AlexWaygood**
Reverts python/typeshed#10583. See #10772: the PR makes `types-jsonschema` incompatible with Python 3.7, since `types-jsonschema` now depends on the `referencing` library, which requires Python 3.8+ (but _didn't_ state as much in its `setup.py`/`pyproject.toml` in early versions released to PyPI).

We should be able to revert the revert once https://github.com/typeshed-internal/stub_uploader/pull/103 is merged, which will allow us to properly declare that the stubs package requires Python 3.8+.

### CODE REVIEW

**Comment by srittau** [comment]
I don't think this is a good idea. I'm not sure the stub uploader will handle this case gracefully.

**Comment by AlexWaygood** [comment]
> I don't think this is a good idea. I'm not sure the stub uploader will handle this case gracefully.

Ah. Well, you know better than me when it comes to that.

What will the stub-uploader do if we yank v4.19.0.0 without doing this revert? Will it simply stop pushing new versions to PyPI for the time being, or will it push v4.19.0.0 again?

**Comment by srittau** [comment]
I'll just merge the changes to the stub uploader and kick off a new release of types-jsonschema. Then we should be safe.

**Comment by AlexWaygood** [comment]
Okay, great!

**Pull request closed without merging**
