### PR TITLE
Add missing overload for `operator.getitem`

### PR DESCRIPTION
**Pull request by max-muoto**
Add missing overload when accessing a sequence with an individual index. Fixes https://github.com/python/typeshed/issues/10519.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This overload looks redundant with the next one.

I wonder if the real problem is that `Sequence.__getitem__` is annotated as taking only `int`, not `SupportsIndex`.

**Comment by AlexWaygood** [comment]
> I wonder if the real problem is that `Sequence.__getitem__` is annotated as taking only `int`, not `SupportsIndex`.

IIRC, that's a deliberate decision, because — although the vast majority of sequences provided by the stdlib do indeed accept any object with an `__index__` method — we don't want to necessarily mandate that any arbitrary subclass of Sequence needs to support non-integers for it to be considered a valid Sequence

**Comment by JelleZijlstra** [comment]
Yes, that sounds reasonable. In that case, we should close the original issue as it is not a bug: `getitem(Sequence, SupportsIndex)` indeed won't work for arbitrary sequences.

**Comment by AlexWaygood** [comment]
Closing as per my rationale in https://github.com/python/typeshed/issues/10519#issuecomment-2180239992

**Pull request closed without merging**
