### PR TITLE
Add __defaults__ to types.MethodType

### LINKED ISSUE #5691: types.MethodType missing `__defaults__` attribute

### PR DESCRIPTION
**Pull request by gruebel**
Fixes #5691

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
What's actually happening here is that MethodType's `__getattr__` implementation delegates to the underlying function. This is in `instancemethod_getattro` at https://github.com/python/cpython/blob/main/Objects/classobject.c#L425 . Method itself doesn't have `__defaults__`, but function does. For the same reason, you'll also see that `.__closure__` works on a method object.

What that means for typeshed is that this change is incomplete: there are other attributes you can use on methods that this change doesn't support. Perhaps we should add these (with a comment explaining what's going on), or just add a `__getattr__`.

**Comment by JelleZijlstra** [comment]
This is actually also true for `__name__` and `__qualname__`: they don't exist on the method but are inherited from the function.

**Comment by gruebel** [comment]
@JelleZijlstra thanks for the feedback!
I also added the type hints for `__closure__`, but when I add `__getattr__(...)` then stubtest complains
```shell
types.MethodType.__getattr__ is not present at runtime
```

**Comment by JelleZijlstra** [comment]
Let's just add `__closure__` and add a comment to all of the inherited attributes. We can add more or add `__getattr__` if more users complain.

**Comment by gruebel** [comment]
@JelleZijlstra I also added comments to the appropriate attributes, I hope that's how you wanted it :)

**Pull request merged**
