### PR TITLE
mypy test suite is broken, disable temporarily

### PR DESCRIPTION
**Pull request by srittau**
I don't have the bandwidth to fix this, at the moment, but this is a less important test anyway.

### CODE REVIEW

**Comment by srittau** [comment]
Example: https://github.com/python/typeshed/pull/5501/checks?check_run_id=2621645919

**Review by Akuli — APPROVED** [review]

**Comment by srittau** [comment]
Cc @JukkaL: Could this be related to the mypy_extensions change?

**Comment by JukkaL** [comment]
> Could this be related to the mypy_extensions change?

This seems possible (even likely), but it's unclear to me what is happening exactly.

**Comment by hauntsaninja** [comment]
It's the mypy_extensions change. The issue is https://github.com/python/typeshed/blob/1547035a95d132ba1c95a768cd344a8c39fd5821/tests/mypy_test_suite.py#L20

**Comment by JukkaL** [comment]
Ah I bet `--custom-typeshed-dir` is broken. It shouldn't be hard to fix, though. I can look at it tomorrow.

**Comment by hauntsaninja** [comment]
Yup, custom typeshed dir is broken as I mentioned in the PR, but we'll also need to change the mypy_test_suite.py code I linked^

**Comment by JukkaL** [comment]
@hauntsaninja Yes, that's the issue. One way to fix this and `--custom-typeshed-dir` would be to include `typeshed/mypy-extensions` (not just `typeshed/stdlib`) in the mypy repo, and add `typeshed/mypy-extensions` into the mypy module search path. In any case we need to copy the stub for `mypy_extensions` into the mypy copy of typeshed when running tests.

**Pull request merged**
