### PR TITLE
paramiko.SSHClient.open_sftp never returns None

### PR DESCRIPTION
**Pull request by andresdelfino**
open_sftp is documented to only return a SFTPClient, and as far as I read that's what th code actually does: it raises an exception if the result is to be None.

Thanks for these hints by the way!

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
If I'm reading the code right, this ultimately calls `SFTPClient.from_transport`, which can in fact return None: https://github.com/paramiko/paramiko/blob/master/paramiko/sftp_client.py#L167.

**Comment by JelleZijlstra** [comment]
... but that branch appears to be dead code, since it ultimately calls `Transport.open_channel`, and that method indeed raises an exception if it's about to return None (https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L1012).

**Comment by andresdelfino** [comment]
> ... but that branch appears to be dead code, since it ultimately calls `Transport.open_channel`, and that method indeed raises an exception if it's about to return None (https://github.com/paramiko/paramiko/blob/master/paramiko/transport.py#L1012).

Right, that's the same path I walked :)

**Comment by JelleZijlstra** [comment]
Sounds good, might be worth reporting this to the paramiko project so they can remove the unnecessary `if chan is None` branch.

**Comment by andresdelfino** [comment]
Upstream PR: https://github.com/paramiko/paramiko/pull/1803

**Pull request merged**
