### PR TITLE
Add the remaining builtin comparison methods to object

### PR DESCRIPTION
**Pull request by YoungMind1**

### CODE REVIEW

**Comment by YoungMind1** [comment]
I think failing tests are due to the comparison of the new `object` with the old one, and are fine; though I am not entirely sure.

**Comment by AlexWaygood** [comment]
> I ran the pre-commit hook and all tests passed. 

I'm afraid we only use pre-commit for linting; our _tests_ are executed via separate scripts in the `tests/` directory, and are run in CI via separate workflows. You can see some documentation on our tests at https://github.com/python/typeshed/blob/main/tests/README.md.

What's the purpose of this PR? While it's true that at runtime there exists a `__lt__` slot on `builtins.object`, you cannot actually compare two instances of `object` with the `<` operator:

```pycon
>>> object() < object()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'object' and 'object'
```

In typeshed, we generally only include methods if they are actually usable at runtime; methods that always throw an exception are not particularly interesting when it comes to type-checking :-)

**Comment by JelleZijlstra** [comment]
The methods actually always return `NotImplemented`; they end up calling `object_richcompare` (https://github.com/python/cpython/blob/9bc6045842ebc91ec48ab163a9e1e8644231607c/Objects/typeobject.c#L6232).

This PR seems to create a lot of problems and it's not clear what problems it solves.

**Comment by YoungMind1** [comment]
I did not see Pyright suggesting comparison methods on objects. (Now after your explanation, seems very reasonable) and thought of adding them. I even first tried to add it directly to Pyright itself :(

Anyways, thanks a lot for the though explanations :heart:

**Pull request closed without merging**
