### PR TITLE
Use explicit type aliases in _typeshed

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by srittau** [comment]
Oh well. 👀

**Comment by srittau** [comment]
Weirdly enough, I can't reproduce the CI failures when running `./tests/mypy_test.py` locally.

**Comment by AlexWaygood** [comment]
> Weirdly enough, I can't reproduce the CI failures when running `./tests/mypy_test.py` locally.

There are also still some pytype errors.

**Comment by JukkaL** [comment]
I'm investigating the mypy errors.

**Comment by srittau** [comment]
Cool, just pytype left, and that has landed a fix as well (unreleased).

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
