### PR TITLE
pyright: Don't report incompatible overrides

### PR DESCRIPTION
**Pull request by srittau**
These overrides are inherited from the implementation and are out of
typeshed's control.

### CODE REVIEW

**Comment by srittau** [comment]
See discussion in #7495.

**Review by AlexWaygood — APPROVED** [review]
(I assume the CI will pass, if it ever wakes up from its slumber)

**Comment by JelleZijlstra** [comment]
We should be able to do this for mypy too by turning off the `override` error code.

Not totally sure we should do this, though; often incompatible override errors can be ignored, but sometimes they also provide a useful nudge to adjust the annotations on a method that's part of a protocol.

**Comment by AlexWaygood** [comment]
> We should be able to do this for mypy too by turning off the `override` error code.
> 
> Not totally sure we should do this, though; often incompatible override errors can be ignored, but sometimes they also provide a useful nudge to adjust the annotations on a method that's part of a protocol.

Personally I'm happy with keeping the mypy errors, but switching off the slightly stricter pyright errors? (I think that's a coherent position?)

**Pull request merged**
