### PR TITLE
Code quality: Introduce and assert `incomplete` flag

### PR DESCRIPTION
**Pull request by srittau**
Part of #11769

This finds 25 more modules with unannotated items (due to `Incomplete`) than our current pyright stricter config.

### CODE REVIEW

**Comment by srittau** [comment]
Currently, this script checks on third-party stubs. stdlib stubs would be a next step.

**Comment by JelleZijlstra** [comment]
I'd rather not include a large amount of untested AST-processing code in our CI scripts. Perhaps we could instead use pyright's library completeness score, or the similar logic from https://github.com/alexwaygood/typeshed-stats.

**Comment by Avasam** [comment]
May I suggest something less vague than `incomplete` ? Maybe `incomplete_annotations` ? (since the concepts of completeness/partialness can mean different concrete things depending on the context: pyright (`Unknown`), mypy (un/annotated and incomplete defs), stubtest (check for missing symbols), stubs (partially typed), etc.

**Comment by AlexWaygood** [comment]
typeshed-stats exposes a library interface as well as a CLI. It should be possible to have it as a test dependency here and use a small wrapper script to assert that 100% of parameters have annotations. It has 100% test coverage.

API documentation, with code examples, is here: https://alexwaygood.github.io/typeshed-stats/gather/

**Comment by hauntsaninja** [comment]
Closing since there are many merge conflicts and there isn't agreement on the implementation

**Pull request closed without merging**
