### PR TITLE
regex: add support for RegexFlag class

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Thanks!

**Comment by AlexWaygood** [comment]
The failing `stub-uploader` test is nothing to worry about -- the same test is failing on the `stub-uploader` master branch:

- https://github.com/typeshed-internal/stub_uploader/actions/runs/3226338425/jobs/5279737323
- https://github.com/typeshed-internal/stub_uploader/pull/61#issuecomment-1274522326

(Cc. @hauntsaninja)

**Comment by srittau** [comment]
The test failure seems unrelated, probably caused by typeshed-internal/stub_uploader#61.

**Comment by rrthomas** [comment]
Thanks for merging this PR, @srittau! As I understand it, the corresponding type-stubs package (here, regex-types) should be automatically released after the change, but it has not been. Is some other change (like a version bump) needed?

**Comment by srittau** [comment]
Indeed. Actually, this CI run claims that it was uploaded, but it wasn't: https://github.com/typeshed-internal/stub_uploader/actions/runs/3228142124/jobs/5283851894

I'm investigating.

**Comment by srittau** [comment]
typeshed-internal/stub_uploader#68

**Comment by JelleZijlstra** [comment]
I manually triggered a new version of regex and it somehow succeeded.

**Pull request merged**
