### PR TITLE
Add pytest_mock stubs

### PR DESCRIPTION
**Pull request by srittau**
These can certainly be improved in the future, especially since `unittest.mock` can be improved as well.

See pytest-dev/pytest-mock#152 for a discussion on adding stubs to pytest-mock directly: It will most likely happen when they drop support for Python 2.

### CODE REVIEW

**Comment by srittau** [comment]
Another note: While pytest-mock supports Python 2, the stubs do not, since this would have complicated them significantly, due to `unittest.mock` being Python-3-only.

**Comment by srittau** [comment]
It seems that pytest gets stuck at some point, also when testing locally. I will investigate.

**Comment by srittau** [comment]
Contains two workarounds for google/pytype#611 and google/pytype#612.

**Comment by JelleZijlstra** [comment]
Thanks for adding this and working through these pytype quirks.

**Pull request merged**
