### PR TITLE
Provide more complete definition for json function

### PR DESCRIPTION
**Pull request by eykamp**
The missing item was causing a warning with pylance in VS Code

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
We generally prefer leaving arguments for which we don't know the type unannotated.

**Comment by eykamp** [comment]
That is (was) my preference as well, but the pylance static checker disagrees; I don't know how other static checkers behave.

Nonetheless, it is easy enough for me to patch the types on my end to fix the warnings that persist even after installing the types.  I figured it would be easier for others if they didn't have to do the same.

All that said, we do have some type info for the standard *args and **kwargs; they are List[Any] and Dict[str, Any] respectively.  Perhaps annotating with that would be more technically correct than my suggestion, though I don't know if it would make any practical difference.  My sole objective was silencing the warnings.

**Comment by srittau** [comment]
We could just copy the arguments to `json.loads()` over, since the keyword args are just passed on to it.

**Comment by JelleZijlstra** [comment]
> That is (was) my preference as well, but the pylance static checker disagrees; I don't know how other static checkers behave.

That's probably under some very strict settings that try to tell you about all places where you're not using precise types. If you care about such type precision, adding Any here doesn't really solve the problem; it just hides it.

> we do have some type info for the standard *args and **kwargs; they are List[Any] and Dict[str, Any] respectively

That's incorrect; annotations for *args and **kwargs reflect the type of the values aggregated into them, not the type of the whole collection.

> We could just copy the arguments to json.loads() over, since the keyword args are just passed on to it.

Let's do that.

**Comment by eykamp** [comment]
Copying the json.loads() args over would work for me as well.

**Comment by srittau** [comment]
Superseded by #5664. Thanks!

**Pull request closed without merging**
