### PR TITLE
Fixing signature for Mapping.get's default parameter

### PR DESCRIPTION
**Pull request by mrkmndz**
This better reflects the semantics of the method, (i.e. returning either the value type or the default type), synchronizes it with werkzeug.datastructures.TypeConversionDict and werkzeug.datastructures.Headers, and stops making pyre think that _T is free when default is a _VT_co

### CODE REVIEW

**Comment by mrkmndz** [comment]
Test failure seems benign (just changed the signature that was being surfaced in a error message).  How does one update the mypy tests to match a new typeshed version?

**Comment by ilevkivskyi** [comment]
LGTM. The process for such situations is to merge here despite the failure, then make a PR to mypy, that syncs the typeshed commit and updates the error message. After PR is merged in mypy, things will be green here again. It is better minimize time between merging here and making the mypy PR.

**Comment by JelleZijlstra** [comment]
Looks good to me too. Could you make a PR to mypy to make the corresponding change there? I'll then be able to merge both.

**Comment by mrkmndz** [comment]
How do I sync the typeshed commit in my mypy pr if this one isn't merged yet?

**Comment by ilevkivskyi** [comment]
It looks like we will need to revert this PR. This causes significant troubles in real code. Consider this example:

```python
m: Mapping[str, List[str]]

x = m.get('x', [])

reveal_type(x)
```
This used to produce `builtins.list[builtins.str]` but not it produces `Union[builtins.list[builtins.str], builtins.list[<nothing>]]` causing subsequent failures because of invariance.

The old signature provided type context for inference of the default argument, and was not wrong in any sense. I will make a PR to revert this now.

**Pull request merged**
