### PR TITLE
Add datadog stubs

### PR DESCRIPTION
**Pull request by drichardson**

### CODE REVIEW

**Comment by drichardson** [comment]
oops, created in wrong repo, apologies 😅

**Comment by AlexWaygood** [comment]
Looks to me like datadog has a py.typed file FYI, so adding stubs shouldn't really be necessary, I don't think :)

**Comment by drichardson** [comment]
> It looks to me like datadog has a py.typed file FYI, so adding stubs shouldn't really be necessary, I don't think :)

Oh interesting. I see that marker exists, but they don't have type hints anywhere.

**Comment by drichardson** [comment]
Ah actually they are just using the older style comment type hints.

**Comment by drichardson** [comment]
OK so the guidance here would  be to try to get the functions missing type hints appropriately annotated in the datadog repo, correct?

**Comment by AlexWaygood** [comment]
> OK so the guidance here would be to try to get the functions missing type hints appropriately annotated in the datadog repo, correct?

Yup!

**Pull request closed without merging**
