### PR TITLE
[WIP] Add 2and3/redis/ stubs

### PR DESCRIPTION
**Pull request by Daenyth**
I'm starting with just the redis client class(es) and things needed to support them, as an MVP.

One big caveat is that the redis client class would permit a user to add their own response parser that can return any type it wants. I'm not reflecting this at all in the types - instead I'm basing all type stubs on what the implementation returns out of the box. I think the right path is that someone using custom parser should inherit from the base class and override methods with new type signatures, or add new methods with type signatures.

 I'm also not annotating fields and attributes on the client class beyond what I think is the most common interface, for now. I expect that this will change over time as people get a chance to use the stubs.

Currently I need to fix missing stubs that I've referenced in the client class but have not provided.
I also need to settle on a final way to represent the type of "some value stored in redis" - right now I'm using `Any` for this, because it will vary based on client configuration and the values the user inputs. It's a little too dynamic for me to pin down at the moment. Likely this will stay Any, due to Union requiring callers to do lots of type checks for otherwise innocuous code.

I'd be very happy to accept help from others on this, either with
- stub contributions, or
- links to type-annotated codebases that currently use redis, so that I can check how well my stubs work in a typing-aware codebase.

Upstream permission for stubs: https://github.com/andymccurdy/redis-py/issues/870

I also removed `2/redis/` because it appears to be entirely unmodified stubgen output, and (Contributing.md)

> It's strictly better to provide partial stubs that have detailed type information than to submit unmodified stubgen output for an entire library.

TODO:
```
third_party/2and3/redis/__init__.pyi:6: error: No library stub file for module 'redis.connection'
third_party/2and3/redis/__init__.pyi:6: note: (Stub files are from https://github.com/python/typeshed)
third_party/2and3/redis/__init__.pyi:7: error: No library stub file for module 'redis.utils'
third_party/2and3/redis/__init__.pyi:8: error: No library stub file for module 'redis.exceptions'
third_party/2and3/redis/client.pyi:8: error: Module 'redis' has no attribute 'ConnectionPool'
third_party/2and3/redis/client.pyi:9: error: No library stub file for module 'redis.lock'
third_party/2and3/redis/__init__.pyi:5: error: Module 'redis.client' has no attribute 'Redis'
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Any updates here?

**Comment by Daenyth** [comment]
I haven't had the time to work on it lately :(

**Comment by gvanrossum** [comment]
Let's just close this if you're not going to be able to work on it.

**Comment by Daenyth** [comment]
I think that's best - I'm not working in python any more currently so I don't see myself having time for this in the near future

**Comment by gvanrossum** [comment]
Sorry to hear that.

**Comment by bochecha** [comment]
I'm interested in stubs for Redis on Python 3, so I guess I'd be willing to move this forward. :slightly_smiling_face: 

However I'm a bit confused: I just tried a `git mv third_party/2/redis third_party/2and3/redis` and the stubs seem to work just fine for my usage. (create a `Redis` client, call its `brpop` method, …)

Is there really anything more than that to do?

**Comment by srittau** [comment]
Since the redis stubs are not really typed yet, moving them to 2and3 should be fine. Patches welcome! I have a few rudimentary types in [srittau/python-stubs](https://github.com/srittau/python-stubs/tree/master/stubs/redis) which I could merge into it then.

**Comment by bochecha** [comment]
> Since the redis stubs are not really typed yet, moving them to 2and3 should be fine.

Ah right, I hadn't actually looked at them since they were working with Python 3, but indeed they are very incomplete and that might be a big reason why they work. :sweat_smile: 

> I have a few rudimentary types in [srittau/python-stubs](https://github.com/srittau/python-stubs/tree/master/stubs/redis) which I could merge into it then.

So what would the plan be? Should I send a pull request to move them from `third_party/2/` to `third_party/2and3/`?

Or do you want to do it and send your patches at the same time?

**Comment by srittau** [comment]
@bochecha Would you mind sending the moving PR?

**Comment by bochecha** [comment]
@srittau sure, see #3015.

**Pull request closed without merging**
