### PR TITLE
tkinter tk_popup

### PR DESCRIPTION
**Pull request by melassa**
tk_popup permit str and int for all params

### CODE REVIEW

**Comment by Akuli** [comment]
I would have typed `x` and `y` as `int`, even though strings are also accepted. Passing in a string for `x` coordinate of a menu is probably a programming error.

**Comment by melassa** [comment]
python tkinter:
    def tk_popup(self, x, y, entry=""):

tcl manual:
If entry is omitted or an empty string, the menu's upper left corner is positioned at the given point. Otherwise entry gives the index of an entry in menu and the menu will be positioned so that the entry is positioned over the given point.

**Comment by melassa** [comment]
Speaking of x and y: i don't know if some tkinter function returns coordinates as str. Probably not.

**Comment by Akuli** [comment]
Usually coordinates get returned as `int`, even if there is no explicit conversion code in tkinter; in that case, it's because Tcl represents the coordinates as integers, and tkinter just decides to output Python ints because of that. That said, some things behave differently, such as the `x` and `y` of `place_info()`.

However, even if you want to pop up the menu in the left corner of a `place()`d widget, accepting string coordinates in `tk_popup()` doesn't help, because `tk_popup()` needs its coordinates as relative to the screen while `place_info()` coordinates are relative to the parent widget. So you would need to `+` the parent widget coordinates, and that would need conversion to int.

**Comment by melassa** [comment]
I try always to replicate module behaviour. But perhaps it is not the best thing.

**Comment by Akuli** [comment]
It is usually considered to be the best thing, but I think tkinter and strings might be a sane exception to that. Tkinter accepts strings everywhere, and allowing strings everywhere could make mypy catch less errors.

**Review by Akuli — APPROVED** [review]

**Pull request closed without merging**
