### PR TITLE
Awaitable.__await__ should accept an Iterator rather than a Generator

### PR DESCRIPTION
**Pull request by wsanchez**
Fixes https://github.com/python/typeshed/issues/5125

### CODE REVIEW

**Review by srittau — APPROVED** [review]

**Comment by hauntsaninja** [comment]
What's up with mypy primer here? I see a lot of complaints, even on the latest run (https://github.com/python/typeshed/runs/2299845824)

**Comment by JelleZijlstra** [comment]
It looks like this change makes mypy infer `Any` for the result of any await expression. One of the mypy_primer failures is in mypy-primer's own code on a function that looks like this:
```
async def get_revision_for_date(dt: date, repo_dir: Path) -> str:
    proc = await run(
        ["git", "rev-list", "-1", "--before", dt.isoformat(), "HEAD"], output=True, cwd=repo_dir
    )
    return proc.stdout.strip()
```

**Comment by hauntsaninja** [comment]
Revert for now?

**Comment by JelleZijlstra** [comment]
Looks like the issue is here: https://github.com/python/mypy/blob/master/mypy/checkexpr.py#L4036. It assumes that `__await__` returns a generator; it if's not https://github.com/python/mypy/blob/master/mypy/checker.py#L707 will return Any. I agree that we should revert, and fix the mypy code first before we apply this change to typeshed.

**Comment by srittau** [comment]
I reran mypy_primer after its last comment, since I couldn't figure out the problem and assumed the comment referred to the previous commit. It didn't add a comment, which threw me.

I think we should notify mypy_primer to always add a comment, even on runs where nothing changed to avoid confusion.

**Pull request merged**
