### PR TITLE
Update os.path module to use file descriptor where possible

### LINKED ISSUE #1653: Some os and os.path function signatures do not admit legal integer (file descriptor) arguments
From the docs:

>16.1.5. Files and Directories
>On some Unix platforms, many of these functions support one or more of these features:
>
>specifying a file descriptor: For some functions, the path argument can be not only a string giving a path name, but also a file descriptor. The function will then operate on the file referred to by the descriptor. (For POSIX systems, Python will call the f... version of the function.)
>
>You can check whether or not path can be specified as a file descriptor on your platform using os.supports_fd. If it is unavailable, using it will raise a NotImplementedError.

Not sure if we want to widen the types for all platforms, or try to special case just for Posix. Here is a list of offenders (via `suports_fd` on python3.7): chdir, chmod, chown, listdir, pathconf, scandir, stat, statvfs, truncate, utime.

I also looked through os.path manually, and found one more: os.path.exists.

typeshed: `def chdir(path: _PathType) -> None: ...`

typeshed: `def chmod(path: _PathType, mode: int) -> None: ...`

typeshed: `def chown(path: _PathType, uid: int, gid: int) -> None: ...  # Unix only`

typeshed:
```
@overload
def listdir(path: str = ...) -> List[str]: ...
@overload
def listdir(path: bytes) -> List[bytes]: ...
```

typeshed: `def pathconf(path: _PathType, name: Union[str, int]) -> int: ...  # Unix only`

typeshed: `def stat(path: _PathType) -> stat_result: ...`

typeshed: `def statvfs(path: _PathType) -> statvfs_result: ...  # Unix only`

typeshed: `def truncate(path: Union[_PathType, int], length: int) -> None: ...  # Unix only up to version 3.4`

typeshed: `def utime(path: _PathType, times: Optional[Union[Tuple[int, int], Tuple[float, float]]] = ...,`

typeshed: `def exists(path: _PathType) -> bool: ...`

### PR DESCRIPTION
**Pull request by mkurek**
Fix #1653
Use `_FdOrPathType` when possible in `os.path` module.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
(The Travis failure is due to a mypy change. I'll submit a typeshed PR to fix it, but you may end up having to rebase this PR.)

**Comment by mkurek** [comment]
@JelleZijlstra sure, thanks!

**Comment by JelleZijlstra** [comment]
Fixed now (just needed to restart the build).

**Comment by JelleZijlstra** [comment]
Is it documented that these accept fds? They're not in `os.supports_fd` and I don't see anything in https://docs.python.org/3/library/os.path.html#os.scandir.

Looking at the code for `os.path.exists` (https://github.com/python/cpython/blob/master/Lib/genericpath.py#L16), it seems like it accidentally supports fds because it calls `os.stat` directly.

**Comment by mkurek** [comment]
@JelleZijlstra I wasn't aware of `os.supports_fd`. So the question is if support for fds for `os.path` functions is accidentally (and that's why it's undocumented and it could change in the future) or it should be documented. On the other hand https://docs.python.org/3/library/os.path.html#os.path.exists and https://docs.python.org/3/library/os.path.html#os.path.samefile mention using `os.stat` which is allowing fds.

So what do you suggest? If you like, I could prepare some pull requests to update cpython, either adding these functions to `os.supports_fd` or documenting that these functions support fds.

**Comment by gvanrossum** [comment]
My position is that if it isn't documented it's not intentional.

**Comment by JelleZijlstra** [comment]
I agree, so filing a ticket with CPython to clarify whether this behavior is intentional sounds like the right approach.

**Comment by mkurek** [comment]
Ok, I've created ticket to CPython to clarify this: https://bugs.python.org/issue31871

**Comment by JelleZijlstra** [comment]
Serhiy's response on bugs.python.org suggests that the fact that these functions support fd arguments in some platforms is unintentional. Therefore, I'm inclined to not support fd arguments in typeshed.

**Comment by gvanrossum** [comment]
Agreed.

**Pull request closed without merging**
