### PR TITLE
Remove `prettytable`

### LINKED ISSUE #9028: Remove stubs for prettytable (not until April 2023)
`prettytable` has just  incorporated typeshed's stubs as inline annotations and added a `py.typed` file (see https://github.com/jazzband/prettytable/issues/203). We've just marked our stubs as obsolete in #9023; we should remove the stubs in April as per our [policy](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-removal-policy).

### PR DESCRIPTION
**Pull request by sobolevn**
Closes #9028

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
Looks good, will merge on 1 April

**Comment by sobolevn** [comment]
I was never so excited for the Aprils Fools in my life! 😆

**Comment by hugovk** [comment]
Hooray, that's two projects (with https://github.com/python/typeshed/pull/9986) I maintain removed from typeshed today!

Will have to remove Pillow next, but that's a bigger job...

**Comment by AlexWaygood** [comment]
> Hooray, that's two projects (with #9986) I maintain removed from typeshed today!

It was a pleasure providing stubs for your projects, and an even greater pleasure deleting them 😄

**Pull request merged**
