### PR TITLE
make os._wrap_close not inherit from TextIOWrapper

### PR DESCRIPTION
**Pull request by tungol**
Methods are passed through at runtime via `__getattr__`

related to https://github.com/python/typeshed/issues/3968

I think is more correct, but we may be getting into territory where duplication of effort becomes a question. Is getting the inheritance right worth maintaining the extra lines of code in this case?

I could see no reason why TextIOWrapper was imported as _TextIOWrapper, other than that import is extremely old; I didn't check but I suspect the current rules around `as` imports were not as established at the time, and the underscore was added to prevent it appearing in os's namespace. I normalized to just a normal import for that reason.

### CODE REVIEW

**Comment by tungol** [comment]
We could also consider leaving some of the methods out of the stubs since the full scope of what's available on `_wrap_close` is basically undocumented. `reconfigure` in particular seems unlikely to be useful as well as seeking. Actual documentation just says:

```The return value is an open file object connected to the pipe, which can be read or written depending on whether mode is 'r' (default) or 'w'. [...] The returned file object reads or writes text strings rather than bytes.```

**Comment by tungol** [comment]
mypy-primer revealed only `read()`: https://github.com/python/typeshed/pull/12782#issuecomment-2408017838

I'm not too surprised - the primary use of os.popen probably happens in smaller scripts than what make it into mypy-primer's corpus.

**Review by srittau — APPROVED** [review]
I'm fine with proxying all methods, but if you want to go for a smaller subset (at least until someone complains), I'm fine with that, too.

**Comment by tungol** [comment]
I looked through the first five pages of github code search results for `os.popen` and saw examples of `read`, `readline`, and `readlines` being used, as well as iteration, but nothing else.

Let's go with the smaller subset to start and see if anyone notices. I updated to include the `read*` and `write*` methods, but leave out the rest.

**Pull request merged**
