### PR TITLE
Improve classes returned from `OrderedDict.{keys(), items(), values()}`

### PR DESCRIPTION
**Pull request by AlexWaygood**
This is an alternative PR to #8544 (closes #8544). @sobolevn, what do you think? :)

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Ping, @sobolevn -- would be interested to hear your thoughts on this :)

**Review by sobolevn — APPROVED** [review]
I think that we can still keep `_OrderedDict*` classes, but I am pretty sure that nobody will miss them 😆

**Comment by AlexWaygood** [comment]
> I think that we can still keep `_OrderedDict*` classes, but I am pretty sure that nobody will miss them 😆

Ugh, I guess you're right, _somebody_ somewhere is probably relying on them 😆

**Review by sobolevn — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Thanks for the review @sobolevn!

**Pull request merged**
