### PR TITLE
Sadly symlinks don't work on Windows.

### PR DESCRIPTION
**Pull request by gvanrossum**
So I have to make {ntpath,macpath}.pyi real copies of posixpath.pyi.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
`stdlib/2/builtins.pyi` is also a symlink; does that not cause problems? I don't have Windows available to test.

**Comment by gvanrossum** [comment]
That mystified me too, but apparently mypy carefully never follows the symlink -- it always loads `__builtins__.pyi`. There are also a few other symlinks -- I am guessing those don't get tested at all.

Unless I totally misunderstood the error from [AppVeyor](https://ci.appveyor.com/project/gvanrossum/mypy/build/1.0.1171/job/eyt2lvjrs2sq8njv): 

```
typeshed\stdlib\3\ntpath.pyi:1: error: Name 'posixpath' is not defined
typeshed\stdlib\3\macpath.pyi:1: error: Name 'posixpath' is not defined
```

**Comment by gvanrossum** [comment]
FWIW I stack-overflowed this and the situation is dear: http://stackoverflow.com/questions/5917249/git-symlinks-in-windows

I don't really want to write a post-checkout script so I guess we should get rid of the symlinks.

**Comment by JelleZijlstra** [comment]
That's unfortunate, I'm worried that we'll end up with changes being applied to only one of the files. Maybe we can add a test that ensures that the contents of `__builtin__.pyi` and `builtins.pyi` are exactly the same.

**Comment by gvanrossum** [comment]
You're also welcome to write that post-checkout script. :-)

FWIW we also have this problem in our Windows wheels -- I just checked out https://pypi.python.org/pypi/mypy/0.501 and sadly it looks like the file .../stdlib/2/builtins.pyi there is a plain text file containing the text `__builtin__.pyi` (i.e. the text contents of the symlink). I guess we're lucky it hasn't bitten anyone yet so far.

**Pull request merged**
