### PR TITLE
Update proto stubs with latest mypy-protobuf 2.6

### PR DESCRIPTION
**Pull request by nipunn1313**
Updated protobuf version and mypy-protobuf version for newly updated stubs.
All updated stubs were autogenerated by scripts/generate_proto_stubs.sh

### CODE REVIEW

**Comment by srittau** [comment]
Could you please also update the version in the `METADATA.toml` file?

**Comment by Akuli** [comment]
Should we cherry-pick changes that were made manually?

**Comment by nipunn1313** [comment]
> Could you please also update the version in the METADATA.toml file?

Yep! on it

> Should we cherry-pick changes that were made manually?

Let me look through them. I think there's no need.
```
git log -p --follow HEAD^ -- stubs/protobuf/**/*_pb2.pyi
git log -p -- "third_party/2and3/google/protobuf/**/*_pb2.pyi"
```

#5597 - looks like pyright is passing here. The improved mypy-protobuf seems to have made these changes.
#4971 - just reorganized dir structure for stubs
#5252 - ran black, but the generation script already runs black - and tests pass here, so no problem
#4850 - was the last update of mypy-protobuf pin

**Comment by nipunn1313** [comment]
ah - my git command missed things. Trying again with
```
git log -p -- "third_party/2and3/google/**/*_pb2.pyi"
```

Also came across
#4907 - which has since been fixed upstream in mypy-protobuf








That should be comprehensive audit of the cherry-picks. I don't think they're needed any more (all the better!)

**Pull request merged**
