### PR TITLE
Move typing_extensions to stdlib

### PR DESCRIPTION
**Pull request by hauntsaninja**
I'm not sure what the best way to do this is. This effectively orphans
types-typing-extensions, but maybe that's not really a problem. (We can
yank the package too)

See https://github.com/python/typeshed/pull/5229#issuecomment-822234125
for some details, could also help issues like https://github.com/python/typeshed/issues/5065

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Let's try this!

**Comment by JukkaL** [comment]
This makes sense. To fix mypy primer, I think that we'll need to sync typeshed afterwards.

**Comment by JelleZijlstra** [comment]
The hard question might be what to do about `types-typing-extensions` on PyPI. Can we just remove it? Or is it already being used, perhaps by people using other typecheckers than mypy?

**Comment by hauntsaninja** [comment]
Fwiw, https://grep.app/ doesn't really show any usage. Mypy hasn't made a release either. I wouldn't be surprised if most usage was in typeshed and mypy CI. However, we have published other stub packages that declare dependencies on types-typing-extensions, so I wouldn't yank it. I propose merging and making an announcement issue.

**Pull request merged**
