### PR TITLE
`name`, `default`, `kind`, and `annotation` in `Parameter` are read-only

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/python/cpython/blob/82c2b54a35f85d87639201d1431ae6584b079e13/Lib/inspect.py#L2677-L2691

Снимок экрана 2021-12-31 в 0 55 23

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Wait, why'd the CO_FOO constants go back to being `int` — I thought they were only just changed to be `Literal`s?

**Comment by sobolevn** [comment]
@AlexWaygood oh, I am sorry, I guess I've messed up something in GitHub interface. I will send one more PR to restore `Literal` types.

**Comment by AlexWaygood** [comment]
> @AlexWaygood oh, I am sorry, I guess I've messed up something in GitHub interface. I will send one more PR to restore `Literal` types.

No need to apologise, I was just confused 😄

**Comment by hauntsaninja** [comment]
I'm confused, how on earth did I miss that, good catch!!

**Pull request merged**
