### PR TITLE
Add missing `encoding` arg to `check_call` and `call` to match `POpen`

### PR DESCRIPTION
**Pull request by max-muoto**
Fixes https://github.com/python/typeshed/issues/12084

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
`check_call` calls `call`, which does not have `encoding=` in stubs right now.

**Comment by max-muoto** [comment]
> `check_call` calls `call`, which does not have `encoding=` in stubs right now.

Let me fix that.

**Comment by max-muoto** [comment]
> `check_call` calls `call`, which does not have `encoding=` in stubs right now.

Fixed: https://github.com/python/typeshed/pull/12086/commits/d0d2bd4cb8962844a54b5f2be104ed9ffaa5d6da

**Comment by max-muoto** [comment]
@sobolevn Just following up on this one.

**Review by sobolevn — APPROVED** [review]
cc @srittau

**Review by srittau — APPROVED** [review]

**Pull request merged**
