### PR TITLE
[stdlib][unittest] Fix mock.call(...) types

### PR DESCRIPTION
**Pull request by jermenkoo**
#3846 defined `_Call` and `call` from [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html), however the exported types are not correct; as:

- nested calls to a call object (`c = call(), c = c.x(), ...`) always return `_Call` (https://github.com/python/cpython/blob/3.8/Lib/unittest/mock.py#L2468)
- `call` returns `_Call`, not any (https://github.com/python/cpython/blob/3.8/Lib/unittest/mock.py#L2545)

These 2 make `pyre` trip, making code such as `m = Mock(), m.assert_has_calls([<call_list_here>])` not compatible as call list will be refined as `Any` as opposed to `_Call`.

### CODE REVIEW

**Comment by jermenkoo** [comment]
3.8 stubtest was broken regardless and Travis failure complains about pytype forward definition? :x

**Comment by jermenkoo** [comment]
stubtest failure seems unrelated and Travis CI fails with pytype issue I have no idea how to resolve, as forward refs should be supported just fine

**Comment by srittau** [comment]
@jermenkoo You can merge current HEAD to fix the stubtest problem. I think pytype doesn't like the quoted forward reference. It's also not necessary in stubs, so just removing the quotes should fix the problem.

**Comment by jermenkoo** [comment]
Thanks! TIL stubs work fine even without the quoted forward references :)

**Pull request merged**
