### PR TITLE
sqlite3.Cursor is iterator

### PR DESCRIPTION
**Pull request by onnokort**
Cursors can be iterated over. I am not sure that this is the correct fix.

### CODE REVIEW

**Comment by gvanrossum** [comment]
It would be better to be explicit and state Iterator[Any]. Although doesn't a cursor's `__next__` return a tuple of some sort?

Also, what about Python 3?

**Comment by gvanrossum** [comment]
@onnokort Are you interested in improving this PR or not?

**Comment by onnokort** [comment]
I updated it now to include python3 stubs. I also made it an Iterator of Tuples of Any.

**Comment by gvanrossum** [comment]
OK, so this caused some breakage with our internal codebase, and I think I finally understand why. The Cursor class can be customized by assigning a function to row_factory, and `__next__` returns whatever that function returns.

So we'll have to go back to returning Any, alas. And I think the other cursor methods that return tuples are also wrong.

Finally, I think `__iter__` should return `Cursor`, not just another Iterable.

**Comment by onnokort** [comment]
Sure! Changed, hopefully as desired.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
