### PR TITLE
Add missing type hint for AbstractSet._hash()

### PR DESCRIPTION
**Pull request by jab**
`collections.abc.Set` provides a `_hash()` method (see https://github.com/python/cpython/blob/f20ca766/Lib/_collections_abc.py#L677) that includes the following in its docstring:
> Note that we don't define `__hash__`: not all sets are hashable. But if you define a hashable set type, its `__hash__` should call this function.

Following this instruction currently causes mypy to give an `attr-defined` error because `AbstractSet` is missing a type hint for this `_hash()` method.

I've been hitting this for a while in my [bidict](https://github.com/jab/bidict) library, whose `frozenbidict.__hash__()` returns `ItemsView(self)._hash()`, and working around it with a `type: ignore` comment, but I believe the fix is as simple as this PR.

Thanks for your consideration.

### CODE REVIEW

**Comment by jab** [comment]
@elprans @1st1 in case of interest – looks like `AbstractCheckedSet` in EdgeDB is (unintentionally?) overriding the `_hash` method it inherits from `collections.abc.Set`, setting this attribute to an int (changing the type from the inherited attribute), and would therefore need to be updated to type check successfully if this PR is accepted.

(All the best with the upcoming 1.0 launch btw, can't wait to try out EdgeDB sometime!)

**Review by Akuli — APPROVED** [review]
This isn't ideal, because type checkers think that the built-in `set` inherits from `AbstractSet` and also has a `_hash()` method. At runtime, `set` doesn't actually inherit from `AbstractSet` though. So code like `set()._hash()` will type check but fail at runtime.

According to our CONTRIBUTING.md, we usually prefer false negatives (no error for incorrect code, this PR) over false positives (errors for correct code, current situation). But before merging this, I'll leave this open for a while, so other maintainers can decide what to do with this.

**Review by srittau — APPROVED** [review]
Agree with @Akuli

**Comment by elprans** [comment]
> @elprans @1st1 in case of interest – looks like `AbstractCheckedSet` in EdgeDB is (unintentionally?) overriding the `_hash` method it inherits from `collections.abc.Set`, setting this attribute to an int (changing the type from the inherited attribute), and would therefore need to be updated to type check successfully if this PR is accepted.

Thanks for the heads up!  Yes, the shadowing isn't intentional, will fix.

> (All the best with the upcoming 1.0 launch btw, can't wait to try out EdgeDB sometime!)

Thank you!

**Pull request merged**
