### PR TITLE
add types to socketserver for py2

### PR DESCRIPTION
**Pull request by tharvik**
See #238.

Simply moved to `2and3`, also found some missing attributes.

### CODE REVIEW

**Comment by gvanrossum** [comment]
This can't be right, in PY2 it's CamelCase.

--Guido (mobile)

**Comment by gvanrossum** [comment]
Are you going to fix that or should I just close this?

**Comment by tharvik** [comment]
Done, I just added a symlink pointing to the `2and3` version.

**Comment by gvanrossum** [comment]
But that's still not right, it would mean that PY2 code could accidentally write "import socketserver" and things would work -- that should fail. Can you move the real file from 2and3 into 3?

**Comment by tharvik** [comment]
Ho, yea, correct; that should do it then.

**Pull request merged**
