### PR TITLE
Add nmap scan timeout

### PR DESCRIPTION
**Pull request by cdce8p**
The `timeout` argument and `PortScannerTimeout` were added in `0.6.4` with https://github.com/home-assistant-libs/python-nmap/commit/5ee40e3fa7f2985ad3ab71690d9baa248c81fd10#
Current file content: https://github.com/home-assistant-libs/python-nmap/blob/master/nmap/nmap.py

Current version is `0.7.0.2`.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Looks like these are stubs for `python-nmap` (as opposed to the unrelated `nmap`, there's also a `python3-nmap`), so we should move the directory.

**Comment by cdce8p** [comment]
> Looks like these are stubs for `python-nmap` (as opposed to the unrelated `nmap`, there's also a `python3-nmap`), so we should move the directory (and update the version number).
> The distribution confusion also explains why stubtest didn't catch this originally / why it's complaining now

Not sure it's that easy 😅 I wasn't really aware of all of that tbh. Just followed that link in Pylance.
Doesn't the fact that stubtest doesn't raise an error (for the current master branch) mean that the stubs also work for `nmap`? I saw that stubtest only installed that package, so I imaging that it's also only testing it.

As for `python-nmap`: You are right, it seems the stubs were first created for it #4276

Even better the package which added the `timeout` argument is called `netmap`. It's a bit confusing.

--
How do we what to deal with that? Of course I can rename the `nmap` folder but does that solve the issue?
Should I create additional copies so that we have `nmap`, `python-nmap`, and `netmap`?

**Comment by hauntsaninja** [comment]
I think master is just incorrect; the pypi nmap package is totally unrelated. stubtest doesn't complain on master because we silenced it here: https://github.com/python/typeshed/blob/master/stubs/nmap/%40tests/stubtest_allowlist.txt (we only started testing third party packages with stubtest recently, so had to allowlist all the existing errors).

pypistats tells me `python-nmap` is several orders of magnitude more popular than `netmap`. So I think the way forward is: 1) Only keep `python-nmap` and users of `netmap` can install `types-python-nmap` and hope it's compatible enough, or 2) Rename to `python-nmap` and make another copy for `netmap`.
Given that `netmap` seems pretty lightly used and the two seem identical to me, I'd lean towards option 1. But other maintainers might have different opinions.

**Comment by srittau** [comment]
I'd say let's start with moving. We can always create a copy later if it turns out to be necessary.

**Comment by cdce8p** [comment]
Superseded by #5931

**Pull request closed without merging**
