### PR TITLE
Proposed fix for tarfile.add() accepting Path name and arcname

### PR DESCRIPTION
**Pull request by frehoy**
Proposed fix for #4368 

This is quite a complicated repo so I'm a bit out of my depth so sorry in advance if this is all wrong. 

I couldn't figure out how to test this in this repo structure but I made a similar change in the tarfile.pyi in my own `.venv/lib/python-3.8/site-packages/mypy/typeshed/stdlib/2and3/tarfile.pyi` and it solved the issue in my own project. Though that `tarfile.pyi` file looked a bit different to the one in this repo, are there big changes going on? 

Question:
* Is 3.7 the correct version to apply this to? Pathlib has been in since 3.4 no?
* How would I go about writing a test for this?

Thanks!

### CODE REVIEW

**Comment by Akuli** [comment]
Seems like I created a pull request to fix that issue without noticing that you had done it first. Oops.

Your fix doesn't do the right thing on Python 3.5. The paths passed to `tarfile.add` go to `os.path.splitdrive` and `os.path.join`, but those work with pathlib.Path until Python 3.6.

Do you mind if I create a pull request to your `fix_tarfile_add_path` branch that essentially does what I did on my branch?

**Comment by frehoy** [comment]
> Do you mind if I create a pull request to your `fix_tarfile_add_path` branch that essentially does what I did on my branch?

Not at all, that would be great! Thanks for clearing up the 3.6 vs 3.7 stuff.

**Comment by Akuli** [comment]
there is pull request now

**Comment by Akuli** [comment]
that means that my commit in this pull request (7e023e5a) should be reverted by frehoy, e.g. like this:

```
git checkout fix_tarfile_add_path
git revert 7e023e5a
git push something something
```

**Comment by frehoy** [comment]
Ah well spotted @hauntsaninja and thanks for the gut tips @Akuli . Just pushed an update with StrPath for both sys.version_info => 3 and => 3.7. Very nifty redefining StrPath depending on version.

Now one of the stubtest runs seems to be failing though but it's only failing for ubuntu on 3.8 and I can't make any sense of the error output. Any ideas?

**Comment by Akuli** [comment]
other pull requests have the same failure, doesn't seem to have anything to do with your changes

**Comment by Akuli** [comment]
try rerunning the build by adding an empty commit, should no longer fail:

```
git commit --allow-empty -m "trigger github actions build"
git push something something
```

**Comment by frehoy** [comment]
> As Akuli mentions, remerging master should fix CI. Thanks for this PR and your patience!

Thanks! I merged this repos master into my fork now and CI looks good.

**Pull request merged**
