### PR TITLE
xml.dom.minidom: add missing definitions

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Will probably get complaints for old Pythons...

**Comment by hauntsaninja** [comment]
Still a ways to go, but it's a start

**Review by srittau — APPROVED** [review]
Just one minor issue below. Feel free to merge after fixing.

**Comment by hauntsaninja** [comment]
I think I already fixed that?

**Comment by srittau** [comment]
> I think I already fixed that?

True, weird that the diff view showed an old diff.

**Pull request merged**
