### PR TITLE
Accept more unicode in 2.7 tempfile stubs

### PR DESCRIPTION
**Pull request by JukkaL**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Oooh, are we now using basestring instead of Union[bytes, unicode] in PY2? I guess that's fine, but there seems to be no unity.

**Comment by matthiaskramm** [comment]
I thought the recommended pattern was
```
Union[Text, bytes]
```
for both Python 2 and 3.

**Comment by JukkaL** [comment]
I only used `basestring` because that was what the rest of the stub was using. I was planning to ask about this, as using it as a return type at least doesn't sound right.

**Comment by matthiaskramm** [comment]
Add a comment (or TODO) to the top of the stub that it shouldn't use `basestring`?

**Comment by JukkaL** [comment]
OK, will do.

**Comment by JukkaL** [comment]
Added a TODO comment: https://github.com/python/typeshed/commit/d09cc058a61b0338bc7961fd75ea82261b185876

**Pull request merged**
