### PR TITLE
fix: enable encode/decode from/to hex string

### PR DESCRIPTION
**Pull request by PabloLION**
Co-authored-by: srittau <srittau@rittau.biz>

This PR fixes https://github.com/python/typeshed/issues/300

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Thanks!

**Comment by hauntsaninja** [comment]
Hmm, I think this is incorrect:
```
Python 3.10.0 (default, Oct 28 2021, 00:42:42) [Clang 12.0.5 (clang-1205.0.22.11)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import codecs
>>> codecs.encode("some_str", encoding="hex")
Traceback (most recent call last):
  File "/Users/shantanu/.pyenv/versions/3.10.0/lib/python3.10/encodings/hex_codec.py", line 15, in hex_encode
    return (binascii.b2a_hex(input), len(input))
TypeError: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: encoding with 'hex' codec failed (TypeError: a bytes-like object is required, not 'str')
```

And this returns bytes:
```
>>> codecs.decode("a0a0", "hex")
b'\xa0\xa0'
```

When I fixed the original issue in https://github.com/python/typeshed/pull/3599  I used these tables: https://docs.python.org/3/library/codecs.html#binary-transforms

**Comment by hauntsaninja** [comment]
Thanks! typeshed in general prefers matching runtime behaviour over documentation, so I opened a PR in https://github.com/python/typeshed/pull/7118 which makes your stackoverflow snippet correctly type check.

**Comment by PabloLION** [comment]
I just made a #7119 with the same idea

**Pull request merged**
