### PR TITLE
Add `no_logs` parameter to `AssertLogsContext`

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by Akuli** [comment]
What problem does this PR solve? `_AssertLogsContext` is not meant to be a public. Currently you currently have to `# type: ignore` it anyway, because the runtime defines in `unittest/_log.py`, not in `unittest/case.py`.

**Comment by AlexWaygood** [comment]
> What problem does this PR solve? `_AssertLogsContext` is not meant to be public. Currently you currently have to `# type: ignore` it anyway, because the runtime defines in `unittest/_log.py`, not in `unittest/case.py`.

The `__init__` method *is* currently incorrect, though?

**Comment by Akuli** [comment]
It is, but it's also not meant to be used (and is very difficult to use) outside the `logging` library itself.

**Comment by Akuli** [comment]
Maybe a good solution would be a simple `no_logs: bool`. That way we don't have much extra code to maintain that nobody uses, but it's still correct.

**Comment by AlexWaygood** [comment]
> It is, but it's also not meant to be used (and is very difficult to use) outside the `logging` library itself.

Sure. It just saddens me to see an incorrect stub :) wouldn't be bothering with it if I hadn't edited the same class earlier today!

**Comment by AlexWaygood** [comment]
> Maybe a good solution would be a simple `no_logs: bool`. That way we don't have much extra code to maintain that nobody uses, but it's still correct.

I'll just take out `__new__` if keeping the code simple is your concern, it doesn't really need to be there!

**Review by Akuli — APPROVED** [review]

**Pull request merged**
