### PR TITLE
Change SocketType to be an alias of socket

### PR DESCRIPTION
**Pull request by sbrudenell**
I couldn't figure out why `SocketType` wasn't just `socket`.

This seems consistent with [the docs](https://docs.python.org/3/library/socket.html#socket.SocketType) that say
>It is the same as `type(socket(...))`.

I got tripped up by `socketserver.BaseServer.socket` being `Any`. Looking around typeshed, some things are declared as `SocketType` and others as `socket` but I couldn't figure out the difference.

I searched docs and prior issues about this; if I missed something please let me know

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
They're not actually the same at runtime: `socket.SocketType` is an alias for `_socket.socket`, which is a base class for `socket.socket`. Strictly speaking, we should mirror that structure exactly in typeshed, but this PR seems like an improvement.

**Comment by sbrudenell** [comment]
Interesting. The docs are wrong then I guess.

I'm struggling to think of the use case for `SocketType`. Should it be deprecated from the standard library? Was `socket()` a factory at some point, which made `SocketType` more meaningful?

If `SocketType` is strictly less useful than `socket` I'd like to update this PR to note that in a comment or something, and eliminate all other usage of `SocketType` in typeshed.

**Comment by srittau** [comment]
I haven't looked at this, but often stdlib implementations are artifacts from earlier, weirder times. As Jelle pointed out, we should mirror those weird structures, if possible. Comments pointing out this weirdness can be useful. Getting the stdlib itself improved is also a possibility.

**Comment by srittau** [comment]
Closing this per discussion, although we could certainly improve `SocketType`.

**Pull request closed without merging**
