### PR TITLE
stubtest: temporary pin to python 3.10.0

### PR DESCRIPTION
**Pull request by Akuli**
Together with #6600, should make the CI green.

We should fix the stubs instead of sticking to an older version of Python 3.10, but for now I just want the CI to work again.

### CODE REVIEW

**Review by srittau — APPROVED** [review]

**Comment by hauntsaninja** [comment]
Hmm, Github, why `/opt/hostedtoolcache/Python/3.10.1/x64/bin/python`?

**Comment by srittau** [comment]
I guess we can just fix the stubtest problems. I can take a stab.

**Comment by hauntsaninja** [comment]
Good catch Akuli! I should have seen that, I was messing with these files today to try out the mypy upgrade

**Comment by srittau** [comment]
#6604

**Pull request merged**
