### PR TITLE
Stub: asyncore.pyi

### PR DESCRIPTION
**Pull request by elazarg**
I can't really test this stub since I don't use this module. I believe it's not far from the real thing.

It's based on the [source code](https://hg.python.org/cpython/file/default/Lib/asyncore.py) and not on the [documentation](https://docs.python.org/3.6/library/asyncore.html).

### CODE REVIEW

**Comment by elazarg** [comment]
Problems:
* No library stub file for standard library module 'asynchat'
* Signature of `dispatcher.recv()` is incompatible with supertype `socket`, as explained in the code.

**Comment by elazarg** [comment]
Test fails for 2.7:
```
Error while parsing pyi:
  File "stdlib/2and3/asynchat.pyi", line 34
    if sys.version_info[0] >= 3:
                       ^
SyntaxError: Unexpected 'LBRACKET'
```
I have no idea why.

**Comment by elazarg** [comment]
Issue #356

**Comment by matthiaskramm** [comment]
Try changing that line to
```
sys.version_info >= (3, 0, 0):
```

**Comment by elazarg** [comment]
This is the syntax suggested by the README

**Comment by elazarg** [comment]
I reveresed the syntax. apparently a positive test and then `pass; else: ...` does not work for some reason.

**Comment by matthiaskramm** [comment]
Thanks for the PR! I'll update the README file.

**Pull request merged**
