### PR TITLE
make `list.__contains__` take `_T` for the other arg

### LINKED ISSUE #6232: `list.__contains__` should use generic for other argument
see https://github.com/python/mypy/issues/11425#issuecomment-960175925

### PR DESCRIPTION
**Pull request by DetachHead**
closes #6232 

This matches how TS handles this scenario https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEYD2A7AzgF3gMyUgXPAK4oDWKSA7igLABQoksCy6WEAlpoZjBygHMA2gF169DtngAKTpgB0-SEVBppuJAEpN8AN714h+PQC+QA

### CODE REVIEW

**Comment by sobolevn** [comment]
My wild guess is that `object` is here due to the fact a lot of projects have incorrect `List` typings. And changing this to `_T` will increase the number of false-positives even more (that's what `mypy_primer` tells us) 😞

**Comment by Akuli** [comment]
It doesn't make sense to require that the type matches exactly. For example, `string_or_none in list_of_strings` or `string in list_of_strings_or_nones` are both reasonable code that works, and there's no reason to ban that.

Ideally there would be a way to say "the argument type must have some overlap with `_T`", but I don't think that's possible in typeshed.

**Comment by DetachHead** [comment]
> Ideally there would be a way to say "the argument type must have some overlap with _T", but I don't think that's possible in typeshed.

That's how generic inference works in TypeScript, and how Kotlin's `OnlyInputTypes` works.

Here's an issue https://github.com/python/typing/issues/900 regarding implementing generic inference with this capability.

**Comment by srittau** [comment]
Please fix the build errors then we can have a closer look at the effect per the mypy_primer output. One quick suggestion is always allow a `None` argument as that is most likely a common case.

**Comment by srittau** [comment]
Now at least we have a clearer picture, but considering the number of failures spotted by mypy_primer, I don't think we should go ahead with this. A few false positives this causes:

```python
def foo(x: Literal["a", "b"]):
    if x in ["a", "b"]: ...  # as ["a", "b"] is inferred to be list[str]

# similar in "alerta"
class Scope(str): ...
def is_in_scope(scopes: list[Scope]):
    if "x" in scopes: ...

# similar in "bokeh"
def foo(x: str | int):
    if x in ["a", "b"]: ...
```

Thank you for your effort!

**Pull request closed without merging**
