### PR TITLE
Make sys.modules a Dict[str, Any]

### PR DESCRIPTION
**Pull request by matthiaskramm**
Modules can contain anything, so give them a generic `__getattr__(name) -> Any`.
This makes code like the following type-check, in pytype:
```
    sys.modules.get("random").randint
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Sounds reasonable, but this appears to break some of mypy's tests.

**Comment by matthiaskramm** [comment]
Yep. I'll undo the Python 3 change for now.

**Comment by gvanrossum** [comment]
Hold on, the test failure suggests that there's something fundamental wrong here. With this change mypy believes that *every* module has every attribute. E.g. `import sys; sys.randint` would pass (because the type of `sys` is `ModuleType`). That sure can't be right? I think it only failed with Python 3 because mypy's Python 2 tests are less comprehensive.

**Comment by gvanrossum** [comment]
Maybe declaring sys.modules to be of type `Dict[str, Any]` would be a more appropriate solution? After all there's a pattern (I think used for lazy imports) where the module in sys.modules is replaced with a sort of proxy object that lazily loads attribute access.

**Comment by matthiaskramm** [comment]
Fine with me. As a matter of fact, that's how it was already defined in `stdlib/3/sys.pyi`. So changing the Python 2 version, too.

**Comment by gvanrossum** [comment]
[Hey @JelleZijlstra, nexttime, in addition to editing the commit subject line, could you also trim the local commits from the final commit message? In this case they are particularly unhelpful, since they were all undone.]

**Comment by JelleZijlstra** [comment]
Makes sense, will remember that for next time.

**Pull request merged**
