### PR TITLE
`Any`-> `object` in simple `operator` funcs

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by Akuli** [comment]
Can you do the same for `not_` and `truth`? This could be done to several other functions too, but `not_`, `truth`, `is_` and `is_not` are perhaps the simplest ones, least likely to cause any problems.

**Comment by AlexWaygood** [comment]
> Can you do the same for `not_` and `truth`?

I was less sure about those than about these, because of the `numpy` weirdness around truth-testing. But I guess `builtins.bool.__new__` is annotated as accepting `object`, and we should be consistent! I'll make the change.

**Review by Akuli — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Any idea why mypy_primer has suddenly started taking much longer in the last few days, btw?

**Comment by hauntsaninja** [comment]
I finally got around to fixing project setups for the modular typeshed change, so now mypy_primer installs many more pip packages (and pip is really slow). I also added maybe 20 more projects.

**Comment by AlexWaygood** [comment]
> I finally got around to fixing project setups for the modular typeshed change, so now mypy_primer installs many more pip packages (and pip is really slow). I also added maybe 20 more projects.

Ahh, makes sense, thanks!

**Comment by hauntsaninja** [comment]
Recent changes visible like so: https://github.com/hauntsaninja/mypy_primer/compare/master..35e004c92

**Comment by AlexWaygood** [comment]
> ...if it's ever released

👀

**Comment by AlexWaygood** [comment]
> I'm hopeful mypy 0.920, if it's ever released, will make mypy-primer much faster

Definitely important to have a more comprehensive diff in the meantime, anyway! Thanks for all the work you do maintaining such an awesome tool 🙂

**Pull request merged**
