### PR TITLE
[WIP] Sqlalchemy 23

### PR DESCRIPTION
**Pull request by aleksanb**
Continuation of https://github.com/python/typeshed/pull/647

Still has some issues which need resolving.

### CODE REVIEW

**Comment by stianjensen** [comment]
What other issues remain?

**Comment by aleksanb** [comment]
The issues were mainly that when using this version of typeshed for our internal project, new errors unraveled themselves due to other parts of sqlalchemy stubs missing, which i couldn't resolve locally with #  type: ignore, so i put the PR on hold.
It might still be better than the current situation, though. But i'd like it if someone else tested this PR as well.

**Comment by gvanrossum** [comment]
@aleksanb Are you still interested in pursuing this? If so, please rebase and push another version. If we don't hear from you in a few weeks we'll just close this PR without action.

**Comment by gvanrossum** [comment]
Closed in favor of #857.

**Pull request closed without merging**
