### PR TITLE
Add stubs for flake8-plugin-utils

### PR DESCRIPTION
**Pull request by kasium**

### CODE REVIEW

**Comment by kasium** [comment]
So, the project has a ``FLAKE8_ERROR`` constant which is a type alias. Can't I use ``FLAKE8_ERROR = tuple[int, int, str, Type[Any]]``

**Comment by srittau** [comment]
This is a bug in mypy 0.910 with type aliases. You have to use `Tuple` (from `typing`).

**Comment by Akuli** [comment]
`flake8_plugin_utils` already has type annotations in the code. Instead of copying the type annotations to typeshed, it would be better to add a `py.typed` file to `flake8_plugin_utils`, so that mypy recognizes the types in `flake8_plugin_utils`.

**Comment by kasium** [comment]
> `flake8_plugin_utils` already has type annotations in the code. Instead of copying the type annotations to typeshed, it would be better to add a `py.typed` file to `flake8_plugin_utils`, so that mypy recognizes the types in `flake8_plugin_utils`.

Thanks for the hint. I asked it here: https://github.com/afonasev/flake8-plugin-utils/issues/77.

**Pull request merged**
