### PR TITLE
regex: accept buffers

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Similar to #7679

### CODE REVIEW

**Review by srittau — APPROVED** [review]

**Comment by AlexWaygood** [comment]
@rchen152, could you possibly take a look at the pytype crash when you have a moment? (Not urgent!) :)

**Comment by rchen152** [comment]
> @rchen152, could you possibly take a look at the pytype crash when you have a moment? (Not urgent!) :)

Looking now!

**Comment by rchen152** [comment]
I have a fix for the pytype issue out for review. Should be able to release it tomorrow or Wednesday.

**Comment by AlexWaygood** [comment]
> I have a fix for the pytype issue out for review. Should be able to release it tomorrow or Wednesday.

Brilliant, thank you!

**Comment by rchen152** [comment]
pytype-2022.5.10 contains the fix.

**Comment by JelleZijlstra** [comment]
Thanks @rchen152! 

CI is green now and Sebastian approved a while ago, so I'll merge.

**Pull request merged**
