### PR TITLE
Change functools.Wrapped call signature from wrapper to wrapped

### PR DESCRIPTION
**Pull request by hereisasound**

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hi, thanks for the PR! It looks like this would cause mypy to start emitting a bunch of new errors on several open-source projects -- mind explaining what problem you're trying to solve here? :)

**Comment by srittau** [comment]
Please note that there is quite a lengthy discussion around this behavior in #6670 when it was last changed.

**Comment by hereisasound** [comment]
Hello :) 
For example here

```
import functools
from typing import reveal_type


class Flamingo:
    def __init__(self, name: str, age: int):
        pass

class Flock:
    def __init__(self):
        self.flamingos = []

    @functools.wraps(Flamingo.__init__)
    def add_flamingo(self, *args, **kwargs):
        flamingo = Flamingo(*args, **kwargs)
        self.flamingos.append(flamingo)

flock = Flock()
reveal_type(flock.add_flamingo)
flock.add_flamingo('Fiona', 3)

print(help(flock.add_flamingo))
```

I have this problem
```
mypy fiona.py
fiona.py:19: note: Revealed type is "functools._Wrapped[[self: fiona.Flamingo, name: builtins.str, age: builtins.int], None, [self: fiona.Flock, *args: Any, **kwargs: Any], Any]"
fiona.py:20: error: Argument 1 to "__call__" of "_Wrapped" has incompatible type "str"; expected "Flock"  [arg-type]
fiona.py:22: error: "help" does not return a value (it only ever returns None)  [func-returns-value]
Found 2 errors in 1 file (checked 1 source file)
```

But yes, it seems really not very easy here with conflicts :(

**Comment by srittau** [comment]
The problem here is not the used type var, it's the fact that the whole signature is copied – including the first argument. Usually this makes sense, although not in the case of wrapping a method, as the example show. In this case, the first argument should be ignored.

So we would need an overload for cases where a method is passed to wraps, but I'm not sure the current type system can handle that.

**Comment by AlexWaygood** [comment]
Is this the same issue that has been reported in https://github.com/python/typeshed/issues/10653?

**Comment by srittau** [comment]
> Is this the same issue that has been reported in #10653?

Looks like it, although that issue is a bit convoluted.

**Comment by srittau** [comment]
See also python/typing#1410.

**Comment by hereisasound** [comment]
Hmm, maybe something like this:

```
def wraps(
        wrapped: Callable[Concatenate[Self, _PWrapped], _RWrapped],
        assigned: Sequence[str] = (
        "__module__", "__name__", "__qualname__", "__doc__", "__annotations__", "__type_params__"),
        updated: Sequence[str] = ("__dict__",),
) -> _MethodWrapper[_PWrapped, _RWrapped]: ...
```

**Comment by srittau** [comment]
I'm not sure that would work, but it's worth a try as an additional overload.

**Comment by srittau** [comment]
Unfortunately, I don't think this going to work like this. We need a solution like discussed [here](https://discuss.python.org/t/making-functions-subscriptable-at-runtime/26463/35) or in #10653 to be able to overload the  function, depending on whether a function or method is passed.

**Comment by srittau** [comment]
I've marked this inexpressible and I'm closing it per my previous comment. Thanks for the effort! I hope we'll have a working solution for this at some point.

**Pull request closed without merging**
