### PR TITLE
Widen MutableMapping.update type

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Part of #6056

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Primer shows that some third-party sub-classes need to be updated. That is ok.

**Comment by aaugustin** [comment]
Third-party maintainer (of websockets) ends ups here after half an hour spent tracking down what changed and is puzzled about how to fix this :-) What would you recommend?

Here's a trimmed down version of the code that is now raising a warning:

```python
from typing import Iterable, Mapping, MutableMapping, Tuple, Union

class Headers(MutableMapping[str, str]):
    def update(
        self,
        *args: Union[Headers, Mapping[str, str], Iterable[Tuple[str, str]]],
        **kwargs: str,
    ) -> None:
        ...
```

I'd like to avoid introducing a dependency on typeshed or `if typing.TYPE_CHECKING: ...` conditionals — I don't have any at this point.

**Comment by aaugustin** [comment]
(If there's no simple fix, this will get a `# type: ignore`, given the dubious effort / benefit ratio of doing anything else.)

**Comment by JelleZijlstra** [comment]
So the problem with your version is that `MutableMapping.update` accepts any object that provides the `keys` and `__getitem__` methods, but your override only accepts `Mapping` objects. You can see that in the default implementation of `update()`: https://github.com/python/cpython/blob/9d1c4d69dbc800ac344565119337fcf490cdc800/Lib/_collections_abc.py#L941

The most prominent example of an object that has `keys` and `__getitem__` but isn't a Mapping is the `pandas.Series` class.

Possible fixes:
- Use `_typeshed.SupportsKeysAndGetItem`, but you'll have to import it within an `if TYPE_CHECKING` block because it's stub-only.
- Define your own version of the protocol in your code. It's pretty simple: https://github.com/python/typeshed/blob/a11a6643a7599c352ae11ac1b08dc5f3d71b106c/stdlib/_typeshed/__init__.pyi#L77
- Don't override `update()` at all, and rely on the stdlib's `MutableMapping.update` implementation.

**Comment by aaugustin** [comment]
Thank you very much!

I will investigate option 2; I didn't notice the type was that simple. (And double check that the implementation indeed supports the wider type; I think it does.)

**Comment by aaugustin** [comment]
Fixed. Thanks again! :-)

**Pull request merged**
