### PR TITLE
Enable flake8-pyi's Y037

### LINKED ISSUE #4819: PEP 604 (Unions with pipe character) tracker
This issue is supposed to track when we can start to use the pipe character as union ([PEP 604](https://www.python.org/dev/peps/pep-0604/)) in typeshed. Support is needed in released versions of:

* [x] mypy (python/mypy#9610), mostly works, except (full list of related issues [here](https://github.com/python/mypy/labels/topic-pep-604)):
    * [x] Type aliases (python/mypy#10901)
    * [x] https://github.com/python/mypy/issues/12392
    * [x] https://github.com/python/mypy/issues/12393
    * [x] https://github.com/python/mypy/issues/11098
    * [x] https://github.com/python/mypy/issues/14158
* [x] pytype (google/pytype#924)
* [x] pyright (microsoft/pyright#659)
* [x] pyre
* [x] PyCharm ([PY-44974](https://youtrack.jetbrains.com/issue/PY-44974))

### PR DESCRIPTION
**Pull request by AlexWaygood**
Always use PEP 604 syntax instead of `Union` and `Optional`.

Closes #4819

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
beautiful

**Comment by Avasam** [comment]
I was looking forward to this one. There's still a mention to it in CONTRIBUTING.md though: https://github.com/python/typeshed/blob/main/CONTRIBUTING.md?plain=1#L438

**Comment by intgr** [comment]
types-requests version 2.28.11.11 somehow causes issues with lots of djangotestframework-stubs CI tests. (https://github.com/typeddjango/djangorestframework-stubs/actions/runs/4114959794/jobs/7103023727)

According to [changelog](https://github.com/typeshed-internal/stub_uploader/blob/main/data/changelogs/requests.md) this PR was the only change in that version.

Errors like this appear in every tests:

> requests-stubs/sessions.pyi:80: error: Type application has too many types (1 expected) (diff)
> requests-stubs/sessions.pyi:81: error: Type application has too many types (1 expected) (diff)
> requests-stubs/sessions.pyi:99: error: Type application has too many types (1 expected) (diff)
> requests-stubs/sessions.pyi:106: error: Type application has too many types (1 expected) (diff)
> urllib3-stubs/fields.pyi:6: error: Type application has too many types (1 expected) (diff)

**Comment by AlexWaygood** [comment]
@intgr do your tests run with mypy 1.0? If not, you may need to upgrade to mypy 1.0.

**Comment by AlexWaygood** [comment]
That error message comes from https://github.com/python/mypy/issues/11098, but that bug should have been fixed in mypy 1.0.

**Comment by intgr** [comment]
Created issue #9690. Sorry, should have done that in the first place.

**Pull request merged**
