### PR TITLE
Add setuptools stubs

### PR DESCRIPTION
**Pull request by srittau**
Still work in progress: There are mypy failures.

### CODE REVIEW

**Comment by srittau** [comment]
I'm unclear why pytype fails, maybe @rchen152 has some ideas.

**Comment by rchen152** [comment]
Huh, pytype thinks SetuptoolsDeprecationWarning is a module - maybe because of how it's imported? Looking into it.

**Comment by rchen152** [comment]
Still trying to figure out how to fix this, but in the meantime, I did find a workaround: if you replace all `from .. import <SomeClass>` statements with `from setuptools import <SomeClass>`, that appears to make pytype happy.

**Comment by srittau** [comment]
stubtest crashes. Maybe @hauntsaninja has an idea.

**Comment by hauntsaninja** [comment]
Looks like something in setuptools that looks like a function raises on inspect.signature. We could also just catch TypeError here: https://github.com/python/mypy/blob/6fd2dc2403889f7104648d8bfbb8df3f5e83b63f/mypy/stubtest.py#L670

**Comment by Akuli** [comment]
Apparently stubtest has an instance of `NonDataProperty`:

```
>>> from setuptools.command.test import NonDataProperty
>>> import inspect
>>> inspect.signature(NonDataProperty)
<Signature (fget)>
>>> inspect.signature(NonDataProperty(print))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/inspect.py", line 3083, in signature
    return Signature.from_callable(obj, follow_wrapped=follow_wrapped)
  File "/usr/lib/python3.7/inspect.py", line 2833, in from_callable
    follow_wrapper_chains=follow_wrapped)
  File "/usr/lib/python3.7/inspect.py", line 2208, in _signature_from_callable
    raise TypeError('{!r} is not a callable object'.format(obj))
TypeError: <setuptools.command.test.NonDataProperty object at 0x7f67b94a3ef0> is not a callable object
>>> 
```

**Comment by srittau** [comment]
Let's wait for the next mypy release: python/mypy#10884, also this requires updated distutils.

**Comment by hauntsaninja** [comment]
Here's a fix in stubtest: https://github.com/python/mypy/pull/10884
Might be easiest to just remove `test.test_args` from this PR to unblock (or avoid typing it as a method)

**Comment by hauntsaninja** [comment]
@srittau I pushed a workaround, so CI is now green if you want to merge.

**Comment by srittau** [comment]
Should we merge this, though? It will not work with current mypy as it requires newer stdlib stubs. I'm 50/50 on merging now vs after the next mypy release.

**Comment by hauntsaninja** [comment]
Well, I figured it's nice to have the option! :-)
I think I'd lean towards merging: other type checkers can benefit, a mypy release probably isn't imminent (if I had to guess, I'd say the next one would be around Python 3.10 release), setuptools.__init__ should work and that's 99% of setuptools usage.

**Comment by rchen152** [comment]
I know you've already worked around the pytype issue, but anyway, pytype release 2021.08.03 should fix it ^^

**Comment by srittau** [comment]
I marked it as ready to merge if someone has time to review it and thinks we should merge now.

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
