### PR TITLE
Sync `_stat.pyi` with `stat.pyi`

### PR DESCRIPTION
**Pull request by sobolevn**
Refs https://github.com/python/typeshed/pull/6705

### CODE REVIEW

**Comment by Akuli** [comment]
At runtime, `stat.py` does `from _stat import *`. We should probably do that too.

**Comment by sobolevn** [comment]
I think that we cannot do that until https://github.com/python/mypy/pull/11867 is merged. Am I correct, @hauntsaninja?

**Comment by AlexWaygood** [comment]
> I think that we cannot do that until [python/mypy#11867](https://github.com/python/mypy/pull/11867) is merged. Am I correct, @hauntsaninja?

I think that that mypy issue only applies to `.py` files, and that `from foo import *` is already considered by mypy to be an explicit re-export for `.pyi` files

**Review by Akuli — APPROVED** [review]
Diff was unreadable, but I created similar changes myself and rearranged code until it looked similar to this PR's branch.

**Pull request merged**
