### PR TITLE
Fix password hashes being non-optional for verify()

### PR DESCRIPTION
**Pull request by Ovsyanka83**
passlib allows hash argument to be None for convenience but the stubs do not indicate that. 

```python
if hash is None:
    # convenience feature -- let apps pass in hash=None when user
    # isn't found / has no hash; useful because it invokes dummy_verify()
    self.dummy_verify()
    return False
```

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Thanks!

**Review by hauntsaninja — COMMENTED** [review]
Is this definitely the case? It's documented as being only unicode or bytes here: https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/context.py#L2280 

And elsewhere in the file they seem to note where things can be None, e.g. https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/context.py#L2087

**Comment by Ovsyanka83** [comment]
Yes, it is definitely the case:
verify: https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/context.py#L2338
verify_and_update: https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/context.py#L2417

**Comment by srittau** [comment]
@hauntsaninja: https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/context.py#L2272 says:

```python
        :type hash: unicode or bytes
        :arg hash:
            hash string to compare to

            if ``None`` is passed in, this will be treated as "never verifying"
```

And there is an explicit `None` check.

(Same for `verify_and_update()`.)

**Comment by hauntsaninja** [comment]
I was definitely looking at the `secret` argument :-) Sorry for the noise, this is what I get for reviewing a PR before bedtime.

**Comment by Ovsyanka83** [comment]
@srittau @hauntsaninja that was the fastest review/merge of my pull request I've ever seen in an open source project. 

You guys rock!

**Pull request merged**
