### PR TITLE
Add _pydecimal and _decimal stubs

### PR DESCRIPTION
**Pull request by CraftSpider**
Consistent with decimal.py, one is python the other is native.

### CODE REVIEW

**Comment by CraftSpider** [comment]
@hauntsaninja Requesting your opinion, should the changes by whitelisted in stubtest, or should I remove the consistency check? I'm leaning towards the first

**Comment by hauntsaninja** [comment]
For some context on the inconsistencies themselves, see https://github.com/python/typeshed/pull/3633 and https://bugs.python.org/issue39722. Note the conclusion on the bugs.python.org report is that `context` isn't part of decimal's public API.

I think personally I would first do:
- Change decimal.pyi to `from _decimal import *`, since that's what's happening most of the time when using Python.

And then either:
a) Reduce duplication, and accept that we won't type `_pydecimal` exactly as per implementation. So change _pydecimal.pyi `from decimal import *`
b) Type _pydecimal.pyi exactly, potentially by using a copy of the file from before #3633 

Given that the difference would only be visible to users if they did `import _pydecimal` and that the differences would involve things considered to not be part of the public API, I'd prefer option a, since that reduces the amount of code typeshed would have to maintain.

**Comment by CraftSpider** [comment]
I went with option a, and as I have trouble testing stubtest locally (windows machine, maybe at some point I'll actually make it work right), I'll fix any issues as travis spits them out

**Comment by CraftSpider** [comment]
Okay, that method causes errors because _decimal doesn't exist in python 2. May do the reverse situation, where `_decimal` and `_pydecimal` export `decimal`

**Comment by hauntsaninja** [comment]
Oh, Python 2. Overall, this looks good to me. Thanks for fixing the existing errors in decimal!

**Pull request merged**
