### PR TITLE
stdlib: use `bool` for annotations where the default is `False`

### PR DESCRIPTION
**Pull request by AlexWaygood**
Found by grepping for `: int = False`

(I also grepped for `: int = True`, but there weren't any hits.)

### CODE REVIEW

**Comment by AlexWaygood** [comment]
It looks like a big fallout because of the verbose error messages, but in actual fact that's only 3 new hits being reported in user code.

I could also just revert the changes to `builtins.compile()`, however. Curious for other people's thoughts.

**Review by Akuli — APPROVED** [review]
I like the simple defaults in stubs :)

**Comment by Akuli** [comment]
I think it's fine to get a new mypy error for using an integer as the `compile()` argument. The documentation of `compile()` talks about zero and nonzero integers, but was written before Python had a `bool` type (Python 2.4 docs have the same text).

**Comment by AlexWaygood** [comment]
Then let's do it.

**Pull request merged**
