### PR TITLE
typing: minor changes

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Happy to split this PR up / not squash-merge it, if that makes sense for any reason.

**Comment by hauntsaninja** [comment]
Definitely a nervous PR!

**Comment by shannonzhu** [comment]
https://www.python.org/dev/peps/pep-0613/

Pep613 for explicit aliases actually relies on `TypeAlias` being defined in `typing`. I'm not sure if this PEP is supported in type checkers outside of Pyre at the moment, but this change ended up breaking the feature for us. Will see if I can revert this renaming and add some tests.

**Comment by hauntsaninja** [comment]
The TypeAlias removed in this PR is actually unrelated to PEP 613, and is instead meant to reflect typing internals in CPython that were removed (the `_TypeAlias`) class.

Given that PEP 613 is accepted, I'd certainly accept a PR on the lines of #4243 (or whatever closes matched the expected implementation of TypeAlias within CPython)

**Comment by shannonzhu** [comment]
@hauntsaninja Thanks for the quick response, adding this to typing extensions stubs seems reasonable to me. The #4243 PR ends up defining TypeAlias as an object rather than something that can itself be used as a type, so will propose a change there

**Pull request merged**
