### PR TITLE
Fix `re.split(...)` return type

### PR DESCRIPTION
**Pull request by tusharsadhwani**
Example:

```python
re.split(r' (?=(x)*.)', 'a b') # ['a', None, 'b']
```

### CODE REVIEW

**Comment by Akuli** [comment]
This change breaks a lot of code that assumes the list doesn't contain `None`s. In most cases, it can't contain `None`s, because the regex used doesn't contain optional groups.

We have some options:
- Change the return type to `List[Optional[str]]` as in this PR. This breaks a lot of code, and fixing it requires annoying `assert thing is not None` checks or similar.
- Change the return type to `List[Any]`. Might hide bugs that type checkers could otherwise find.
- Do nothing. This seems like the best option to me.

What do you think?

**Comment by JelleZijlstra** [comment]
This can also be implemented more precisely in a type checker plugin that could look at the regex to see if there are optional groups.

**Comment by tusharsadhwani** [comment]
I guess so.

I was just startled when mypy assured me that split returns `list[str]` but my code gave me `None`s. However annoying it might be in the former case, the latter case is misleading... so I don't know what's right and what's not.

**Comment by Akuli** [comment]
There's not a good way to express this in stubs. If you want, you can create a feature request to mypy.

**Review by srittau — APPROVED** [review]

**Pull request merged**
