### PR TITLE
Add missing methods to asyncio stubs

### PR DESCRIPTION
**Pull request by cole**
Addresses a number of missing methods described in https://github.com/python/typeshed/issues/2313.

### CODE REVIEW

**Comment by cole** [comment]
@srittau ah, of course. I've made that change, but it seems to break pytype. I feel like I'm missing something obvious..?

I've also added a few more items noted in #2313 — let me know if any of those changes need revisions.

**Comment by srittau** [comment]
@rchen152 Does pytype not support `async def` yet?

**Comment by rchen152** [comment]
Huh, I'm surprised this hasn't come up before. pytype only supports the `@coroutine` decorator in stubs, not `async def`. I'll go ahead and add support for `async def` and update here when it's released. (If it turns out to be easy, it'll probably be out tomorrow; otherwise, it'll be delayed to next week, since the rest of this week is a holiday for me.)

**Comment by rchen152** [comment]
This is turning out to be more troublesome than I anticipated =(
I've prepared a change making `async` a keyword in stubs, but its rollout is being held up by Google code that uses `async` as a variable name. It's hard to say how long it'll take to deal with - anywhere from a few days to a few weeks depending on how many occurrences I find and how responsive code owners are.

In the meantime, if you'd like to get this PR in without waiting on pytype, maybe `async def foo() -> X` could be rewritten to `def foo() -> Coroutine[Any, Any, X]`?

**Comment by srittau** [comment]
Let's just use `@coroutine` for now, like the PR did originally.

**Comment by cole** [comment]
Ready for re-review.

**Comment by rchen152** [comment]
FYI with https://github.com/python/typeshed/pull/3112, pytype should now support the `async def` syntax. I guess I shouldn't have been so pessimistic about how long it would take to get that change released ^^;

**Comment by cole** [comment]
Reverted to `async def` 😄

**Comment by cole** [comment]
@srittau are there any changes I should make to this PR?

**Comment by srittau** [comment]
Sorry, I missed this completely.

**Pull request merged**
