### PR TITLE
Fixes #1976: Change return type of concurrent.futures.wait

### LINKED ISSUE #1976: concurrent.futures.wait stub uses a tuple instead of DoneAndNotDoneFutures
The [definition of wait](https://github.com/python/typeshed/blob/2c6296034fc107689c489b973e82959fe7d06807/stdlib/3/concurrent/futures/_base.pyi#L43) indicates that it returns `Tuple[Set[Future[_T]], Set[Future[_T]]]`. The actual return type is [a DoneAndNotDoneFutures namedtuple](https://github.com/python/cpython/blob/master/Lib/concurrent/futures/_base.py#L307).

The problem with this is that the type inference is not able to determine that `done` and `not_done` are members of the tuple. If you use the namedtuple by indexing it then type checking works, however I find that compromises readability.

There is a definition for `DoneAndNotDoneFutures` in the same file which appears to be unused, so perhaps it was overlooked?

### PR DESCRIPTION
**Pull request by bw-matthew**
https://github.com/python/typeshed/issues/1976

The [definition of wait](https://github.com/python/typeshed/blob/2c6296034fc107689c489b973e82959fe7d06807/stdlib/3/concurrent/futures/_base.pyi#L43) indicates that it returns `Tuple[Set[Future[_T]], Set[Future[_T]]]`. The actual return type is [a DoneAndNotDoneFutures namedtuple](https://github.com/python/cpython/blob/master/Lib/concurrent/futures/_base.py#L307).

The problem with this is that the type inference is not able to determine that `done` and `not_done` are members of the tuple. If you use the namedtuple by indexing it then type checking works, however I find that compromises readability.

There is a definition for `DoneAndNotDoneFutures` in the same file which appears to be unused, so perhaps it was overlooked?

### CODE REVIEW

**Comment by bw-matthew** [comment]
I've been running the mypy_test.py locally against the changes I have been pushing for this PR. When trying to define an example to test the difference I wrote this:

```python
from collections import namedtuple
from typing import NamedTuple, Set

Foo = namedtuple('Foo', 'done not_done')
FooType = NamedTuple('Foo', [('done', Set[str]), ('not_done', Set[str])])

def mthd() -> FooType:
    return Foo(['one', 'two'], ['1', '2'])
```

However running `mypy --python-version 3.6 ...` results in

```
error: Incompatible return value type (got "Foo", expected "Foo@5")
```

I've just started learning the typing stuff today so I think I'm missing something in my test code.

My other concern is that the DoneAndNotDoneFuture named tuple loses the _T constraint over the Futures that are passed in. I'm looking into ways to restore that however I'm running into trouble coupling the two generic types.

**Comment by gvanrossum** [comment]
In your test code, the first arg to `NamedTuple` should match the variable to which you assign it, i.e. `FooType`, not `Foo`. And there's no reason to define a `namedtuple` *and* a `NamedTuple` -- the latter works at runtime as the former, so if you need types you only need the latter.

**Comment by bw-matthew** [comment]
Thanks for the tips! In this case I'm trying to match the external application of the type information. I've made some progress by splitting my code into a .py file with an associated .pyi

**Comment by bw-matthew** [comment]
If I use the original DoneAndNotDoneFutures type definition as the named tuple then it fails validation when I populate it with two sets.

**Comment by gvanrossum** [comment]
Correct, the original definition was wrong.

**Comment by bw-matthew** [comment]
Thanks for confirming that. It looks like I cannot resolve the generic constraint as mypy gives the error _Generic tuple types not supported_.

**Comment by gvanrossum** [comment]
Sorry, what test code gives that error on what line?

**Comment by bw-matthew** [comment]
Right sorry:

```python
from typing import Generic, NamedTuple, TypeVar, Set

T = TypeVar('T')

class Foo(Generic[T], NamedTuple):
    done: Set[T]
    not_done: Set[T]

def mthd(v: T) -> Foo[T]:
    return Foo({v}, {v})
```

When validated with `mypy --python-version 3.6 ...` gives

```
my_library.py:9: error: Generic tuple types not supported
my_library.py:10: error: Argument 1 to <set> has incompatible type "T"; expected "Tuple[Set[T], Set[T]]"
```

**Comment by gvanrossum** [comment]
That has nothing to do with this PR though, right?

**Comment by matthewfranglen** [comment]
Hi, this is my home account.

I think that this PR improves the situation. I was trying to be complete by working on preserving the generic type of the futures.

**Comment by matthewfranglen** [comment]
I've opened https://github.com/python/typeshed/pull/1978 to do so. Thanks for all the help with this PR.

**Pull request closed without merging**
