### PR TITLE
Experiment: decouple types.DynamicClassAttribute from property

### PR DESCRIPTION
**Pull request by tungol**
I'm curious to see what the tests look like.

### CODE REVIEW

**Comment by tungol** [comment]
Less breakage than I imagined. "Run mypy against the stubs" passes for 3.11+, which I suspect means that enum.property being named `property` is sufficient to get (some of) the special treatment, but the primer results show it's not all of it. One other thing I want to try.

**Comment by tungol** [comment]
Subclassing doesn't appear to make any difference.

**Comment by AlexWaygood** [comment]
> "Run mypy against the stubs" passes for 3.11+, which I suspect means that enum.property being named `property` is sufficient to get (some of) the special treatment,

It's actually because mypy hardcodes in some extra special casing to cope with typeshed's stubs here. See https://github.com/python/mypy/pull/14133

**Comment by tungol** [comment]
Thanks for the context, I appreciate it

**Pull request closed without merging**
