### PR TITLE
redis: Add stubs for lmove and blmove

### PR DESCRIPTION
**Pull request by richli**
For reference:

https://redis.io/commands/lmove
https://redis.io/commands/blmove

https://github.com/redis/redis-py/blob/v4.0.2/redis/commands/core.py#L1170-L1189

### CODE REVIEW

**Comment by Akuli** [comment]
This might need an overload in `class Pipeline`, defined in `client.pyi`. I'm not familiar enough with redis to know which methods need to be overrided there to return a `Pipeline`, and which methods don't return a `Pipeline` even when called on a `Pipeline` instance.

Nit: Don't force-push, as it makes it harder to see what changed since the previous review. We will use GitHub's "Squash and merge" button when merging the PR, so it will appear as a single commit in our commit history anyway.

**Review by JelleZijlstra — CHANGES_REQUESTED** [review]
Looks like these do return a Pipeline, as @Akuli noted. Could you make that change?

**Comment by richli** [comment]
Yes, I'll make the changes in a few days after I return from traveling. I don't use the Pipeline functionality much so I wasn't sure about that, but thanks for confirming it.

**Comment by richli** [comment]
The `stubtest` check failed and I'm afraid I'm clueless on how to address this error. Any ideas?

**Comment by Akuli** [comment]
stubtest wants the `# type: ignore[override]` comments to be on the first line of each method, lines 658 and 674, not the last line of each method. I don't understand why this happens though, because stubtest and the mypy checks both use the same mypy version, 0.930.

**Comment by richli** [comment]
@Akuli Thanks, that's pretty tricky! I'll make the change. Just a note, most other multi-line function signatures have that comment on the first line, but `xclaim` has it on the last line. Is that something I should change, too?

**Comment by Akuli** [comment]
The comment location is type checker specific. If it doesn't fail our CI, that's good enough :)

**Review by Akuli — APPROVED** [review]

**Comment by Akuli** [comment]
Thanks!

**Pull request merged**
