### PR TITLE
Add stubs for ujson

### PR DESCRIPTION
**Pull request by Michael0x2a**
This pull request adds stubs for [ujson](https://pypi.python.org/pypi/ujson). Note that the interface for ujson is a bit more restrictive then the interface for the json module in the standard library.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Have you checked with the developers of ujson whether they are okay with including these stubs in typeshed? Our policy for third_party packages requires checking this. You can probably just ask them in their tracker and once they respond, link back to their tracker issue here.

**Comment by gvanrossum** [comment]
PS. Would be nice if we had a bot that automatically asked that whenever someone submits stubs for a new package in third_party.

**Comment by Michael0x2a** [comment]
I asked them just now, and they were ok with it: https://github.com/esnme/ultrajson/issues/233

**Comment by timabbott** [comment]
@Michael0x2a how confident are you that the `ujson` methods take a `str` (as opposed to e.g. an `AnyStr`)?  I haven't looked too closely, but based on https://github.com/esnme/ultrajson/issues/11, it seems current `ujson` is intended to return a `unicode` if you pass it a `unicode`, I think?

**Comment by timabbott** [comment]
(For context, I'm getting errors trying to use this with the Zulip project, which has annotations assuming that e.g. `ujson.loads` can be passed a `Text` object)

**Comment by gvanrossum** [comment]
Can't you just try this in the REPL? Should take 1 minute if you have ujson
installed and will tell you the truth.

**Comment by Michael0x2a** [comment]
Hmm, you might be right -- in retrospect, I'm not sure if I tested my stubs very thoroughly on Python 2.

I did some quick testing, and it seems like the `loads` functions most likely can take in strings of type `Union[Text, bytes]`. The `dumps` functions seem a bit more complicated -- they seem to return `str` in both Python 2 and Python 3 (which means they're really returning `bytes` in Python 2 and `Text` in Python 3?).

But perhaps I'm wrong about this again.

**Comment by timabbott** [comment]
Yeah, I just tested as well and indeed `loads` at least can take Text and bytes.

**Comment by timabbott** [comment]
Opened https://github.com/python/typeshed/pull/540 to fix this issue.  Thanks @Michael0x2a for also investigating this :)

**Pull request merged**
