### PR TITLE
Add warnings.catch_warning type hints with Literal.

### LINKED ISSUE #3463: Output type of warnings.catch_warnings with record=True
Although [warnings.catch_warnings](https://docs.python.org/3/library/warnings.html#warnings.catch_warnings) with `record=True` returns
a list, mypy is not aware of that:

File `foo.py`:

```python
import warnings

with warnings.catch_warnings(record=True) as w:
    print(len(w))
```

Command `mypy foo.py` gives:

```
$ mypy foo.py
foo.py:4: error: Argument 1 to "len" has incompatible type "Optional[List[_Record]]"; expected "Sized"
Found 1 error in 1 file (checked 1 source file)
```

Using recent mypy from master (`0.750+dev.e97377c454a1d5c019e9c56871d5f229db6b47b2`).

---

I've attached PR fixing this #3464.

### PR DESCRIPTION
**Pull request by mslapek**
Fixes #3463

### CODE REVIEW

**Comment by bluetech** [comment]
This is a nice change, thanks.

However, I wonder if there is a better way to fix the issue This PR changes `catch_warning` from a class to a function which returns `typing.ContextManager`. This has two downsides:

1. It breaks the usual rule of "accept abstract, return concrete". Returning an abstract interface is strictly weaker than returning a concrete type which implements this interface. It does make sense if the implementation wants to keep its options open, but that's not the case here.

2. The [docs](https://docs.python.org/3.8/library/warnings.html#warnings.catch_warnings) document `catch_warnings` as a class. Changing it to a function means (I think) that the type checker will no longer allow to subclass it, or check `isinstance` of it, return it from wrapper functions, etc.

Maybe @srittau knows how to keep it a class? Maybe it's possible to `@overload` `__init__` and inject a generic param to self in some way? Dunno.

**Comment by srittau** [comment]
I agree that keeping it as a class would be preferable. From what I understand overloaded init method that allow to narrow the type of a typecast is something that is currently being worked on in mypy. So we can probably improve these hints soon.

**Comment by blueyed** [comment]
As pointed out already this fails now:
```python
import warnings


class WarningsRecorder(warnings.catch_warnings):
    pass
```

```
t.py:4: error: Function "warnings.catch_warnings" is not valid as a type
t.py:4: note: Perhaps you need "Callable[...]" or a callback protocol?
t.py:4: error: Invalid base class "warnings.catch_warnings"
Found 2 errors in 1 file (checked 1 source file)
```

Are there plans to fix / allow this still?

**Comment by JelleZijlstra** [comment]
It looks like we should revert to an implementation that uses a class and overloads `__new__`. Contributions would be welcome.

**Comment by mslapek** [comment]
I've performed modification in #3499 to "eat the cake and have it too".

@JelleZijlstra Thanks for tip with `__new__` overloading.

**Pull request merged**
