### PR TITLE
Use PEP 585 syntax in `@python2/_ast`, convert more `TypeVar`s to `_typeshed.Self`, & `# noqa` a `SQLAlchemy` line

### PR DESCRIPTION
**Pull request by AlexWaygood**
Part II of trying to get the CI green for https://github.com/PyCQA/flake8-pyi/pull/97

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by hauntsaninja** [comment]
Does this definitely work? I.e. why did we skip Python 2 when we did this codemod previously?

**Comment by hauntsaninja** [comment]
https://github.com/python/typeshed/pull/5872 just says "scripts did something weird", but looks like we switched Python 2 to use PEP 604 syntax in https://github.com/python/typeshed/pull/5915 and nothing went wrong :-)

**Comment by Akuli** [comment]
I wrote "e.g. because scripts did something weird", and this particular reason isn't why I skipped `@python2` stubs. I didn't touch `@python2` simply because I don't care about what happens to Python 2 stubs.

Also, AlexWaygood's scripts tend to be of much better quality than my quick and dirty scripts, so they're less likely to ruin stub files and require manual work :)

**Comment by Akuli** [comment]
Another note: flake8-pyi uses typeshed's `.flake8` file in its CI, so configuring flake8 to silence `@python2` errors there is also an option.

**Pull request merged**
