### PR TITLE
Add stubs for symbol

### PR DESCRIPTION
**Pull request by JelleZijlstra**

### CODE REVIEW

**Comment by ambv** [comment]
Why not use the 3.6 variable annotation syntax?

**Comment by JelleZijlstra** [comment]
Mypy still doesn't support that in typeshed I believe. Or was that fixed?

**Comment by ambv** [comment]
It's fine after https://github.com/python/mypy/pull/3000 got merged.

**Comment by JelleZijlstra** [comment]
Do we know for sure that pycharm is also OK? (Pytype is covered by Travis.)

**Comment by ambv** [comment]
@vlasovskikh, does PyCharm support variable annotations in stubs for all Python versions? Mypy and pytype do.

**Comment by ilevkivskyi** [comment]
``annassign = ...  # type: int`` looks quite ironically :-)

**Comment by vlasovskikh** [comment]
@ambv Recent versions of PyCharm use the Python 3.6 syntax for Python stubs.

**Pull request merged**
