### PR TITLE
argparse: Forbid invalid `type` and `choices` combinations

### PR DESCRIPTION
**Pull request by srittau**
----

Deferred: See this discussion: https://discuss.python.org/t/constraining-generic-argument-types/56809

### CODE REVIEW

**Comment by srittau** [comment]
I'm unsure why the pyright regression tests fail. I can't see how the two ignored tests can match any of the overloads.

**Comment by srittau** [comment]
Regarding the primer output: pylint is actually using `add_argument` in an unsafe manner. It defines "argument" classes that have choices, which are `list[str]` and a `type` that can be a callable returning arbitrary values. This doesn't work at runtime, unless the callable returns a `str`.

mkosi has the usual problem that mypy can't merge overload definitions:

```python
    parser.add_argument(
        "-C", "--directory",
        type=parse_chdir if chdir else str,
        default=Path.cwd(),
        help="Change to specified directory before doing anything",
        metavar="PATH",
    )
```

This seems like a special case to me and is easily worked around by mkosi by replacing a trinary operator with an `if/else` block. I'm fine with that.

**Comment by JelleZijlstra** [comment]
(But I don't think we need to wait for that mypy PR.)

**Comment by srittau** [comment]
@erictraut Could you have a look at https://github.com/python/typeshed/pull/12211/files? I'm not sure why pyright thinks the lines in question are okay. I don't think any potential should match, but maybe I'm overlooking something?

**Comment by erictraut** [comment]
I presume you're talking about the lines with `# type: ignore` comments next to them? For example: `parser.add_argument("--foo", type=int, choices=[""])`?

The second overload ('If `type` is a callable...') makes this OK. Here's a simplified version:

```python
from typing import Callable, Iterable

def add_argument[_T](
    *name_or_flags: str, type: Callable[[str], _T], choices: Iterable[_T]
) -> _T: ...

x = add_argument("--foo", type=int, choices=[""])
reveal_type(x) # int | str
```

**Comment by srittau** [comment]
That's interesting. mypy comes to a different conclusion (when using a slightly adapted example):

```
foo.py:10: error: Argument "type" to "add_argument" has incompatible type "type[int]"; expected "Callable[[str], str]"  [arg-type]
foo.py:11: note: Revealed type is "builtins.str"
```

mypy's interpretation (constraining `_T` based on each individual argument, instead of constraining it to the union of the arguments) is what I would have expected to happen. I guess this is a discrepancy that should be discussed separately. I've added the deferred status for now.

**Comment by srittau** [comment]
It seems that this is currently inexpressible in a way that's compatible with all type checkers.

**Pull request closed without merging**
