### PR TITLE
termios: improve comments, add more constants

### PR DESCRIPTION
**Pull request by JelleZijlstra**
I just got the list in termios.c of all constants that can potentially exist.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Is there any chance we can reduce the amount we allowlist this module? See also #9150.

**Comment by JelleZijlstra** [comment]
Other than your PR? I think it's hard because the set of constants that exists varies so much by exact OS version.

**Comment by AlexWaygood** [comment]
> Other than your PR? I think it's hard because the set of constants that exists varies so much by exact OS version.

Yeah, fair enough :)

**Review by AlexWaygood — APPROVED** [review]
Reviewed by reading the source code — looks good!

**Pull request merged**
