### PR TITLE
Upgrade black to 21.4b0 and reformat

### PR DESCRIPTION
**Pull request by srittau**
This introduces newlines before decorators.

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
I'd prefer we run with `--skip-magic-trailing-comma` that I added in this release, thoughts? Helps keep definitions compact when they fit on one line.

**Comment by srittau** [comment]
Unfortunately, there is a discrepancy between running black with `--check --diff` and running it without it when using `skip_magic_trailing_comma = true`, which makes it impossible to use this option for now.

**Comment by srittau** [comment]
I couldn't isolate the black problem so far, but the problem can be reproduced locally by running `black --check --diff stdlib` (showing diffs) and running `black --check stdlib` (saying all files unchanged).

**Comment by srittau** [comment]
Weirdly enough, if I copy my typeshed directory (just doing `cp -r`), black will be consistent in the new location. I have no time to investigate this further at the moment and suggest to start without `skip_magic_trailing_comma` for now.

**Comment by srittau** [comment]
Different computer:

```
srittau@blitz:~/Projekte$ diff -u --recursive typeshed typeshed2
srittau@blitz:~/Projekte$ 
```

```
(.venv-3.9) srittau@blitz:~/Projekte/typeshed$ black stubs/ stdlib/ --check
All done! ✨ 🍰 ✨
1334 files would be left unchanged.
(.venv-3.9) srittau@blitz:~/Projekte/typeshed$ 
```

```
(.venv-3.9) srittau@blitz:~/Projekte/typeshed2$ black stubs/ stdlib/ --check
would reformat stdlib/logging/config.pyi
would reformat stdlib/importlib/util.pyi
would reformat stdlib/distutils/filelist.pyi
would reformat stdlib/smtpd.pyi
would reformat stdlib/_typeshed/__init__.pyi
would reformat stubs/click/click/formatting.pyi
would reformat stubs/click-spinner/click_spinner/__init__.pyi
would reformat stubs/protobuf/google/protobuf/json_format.pyi
would reformat stdlib/ftplib.pyi
would reformat stubs/redis/redis/lock.pyi
would reformat stubs/waitress/waitress/compat.pyi
would reformat stubs/protobuf/google/protobuf/descriptor.pyi
would reformat stdlib/@python2/logging/__init__.pyi
would reformat stubs/JACK-Client/jack/__init__.pyi
would reformat stdlib/asyncio/base_events.pyi
would reformat stdlib/typing.pyi
would reformat stubs/redis/redis/client.pyi
Oh no! 💥 💔 💥
17 files would be reformatted, 1317 files would be left unchanged.
(.venv-3.9) srittau@blitz:~/Projekte/typeshed2$ 
```

I am stumped.

**Comment by srittau** [comment]
I merged the version without skip_magic_trailing_comma for now.

**Pull request merged**
