### PR TITLE
Add GenericMeta (so that classes can be Generic when they already hav…

### PR DESCRIPTION
**Pull request by cpennington**
…e a metaclass)

### CODE REVIEW

**Comment by cpennington** [comment]
I just tried this change locally, and it isn't working as advertised yet. Closing for now, until I can get it into a working state.

**Comment by gvanrossum** [comment]
There's also the issue that GenericMeta isn't part of the documented API of the typing module. It's not in `__all__` and it's not in the documentation (nor in PEP 484) and I'm pretty sure zero thought was given to how 3rd party code could or should subclass it.

**Comment by cpennington** [comment]
Even if the only thing that was public was that there was a class of that name, that would be enough to safely typecheck the inheritance from the metaclass, which would allow a class to be typed as Generic while still using its own metaclass as well.

**Comment by gvanrossum** [comment]
Can you supply an example? (It should at least have *some* functionality in
the other metaclass.)

**Comment by cpennington** [comment]
https://github.com/cpennington/XBlock/blob/static-typing/xblock/mixins.py#L333-L358 is the particular chunk of code that I was trying to make this work for. (This repo is also the one that was prompting me to make descriptor typing work correctly).

**Comment by gvanrossum** [comment]
OK, I think I see what you're after. I think we may have to document what you can/cannot do in a class derived from GenericMeta.

Does the code in this PR actually make this work for you, or do you need additional mypy changes as well?

**Comment by cpennington** [comment]
It's broken right at the moment. I'll update once I've gotten it to work (my plan is to include as minimal a set of things in the stubs as I need to get that code working).

**Comment by cpennington** [comment]
Ok, this is now sufficient for the code I referenced above.

**Comment by gvanrossum** [comment]
Can you fix the test failure?

https://travis-ci.org/python/typeshed/jobs/180747613

**Comment by cpennington** [comment]
Oops, should be fixed now.

**Comment by gvanrossum** [comment]
Thanks, this looks pretty harmless (and certainly minimal :-). I will merge it, even though I have lingering doubts about what should happen with the keyword args to `__new__`. I've got a feeling that your code that subclasses GenericMeta (https://github.com/cpennington/XBlock/blob/static-typing/xblock/mixins.py#L333-L358) would run into some kind of problem when `get_type_hints()` is called on something using one of those, since that ends up calling `_eval_type()`, which ends up calling `self.__class__` (where `self` is a generic class, i.e. an instance of GenericMeta, so `self.__class__` is GenericMeta or a subclass thereof) with all kinds of extra args. I guess you don't use that.

**Pull request merged**
