### PR TITLE
Remove workaround for _dict_values

### PR DESCRIPTION
**Pull request by JelleZijlstra**
The mypy issue was fixed

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Well that's not looking good.

**Comment by JelleZijlstra** [comment]
I guess it's because we run mypy-primer against the latest mypy release. Let's punt on this until the mypy release cycle catches up.

**Comment by hauntsaninja** [comment]
It's going to be a long, long time before the fix gets released (since it won't make the rumoured v0.920 release). Feel free to merge now, don't think it breaks anything if we do.

**Review by srittau — APPROVED** [review]
We can merge now, as mypy will only ship this version of the stubs with a mypy version that contains the fix.

**Pull request merged**
