### PR TITLE
os.path.{abspath, basename, join} should accept _PathType

### PR DESCRIPTION
**Pull request by sid-kap**

### CODE REVIEW

**Comment by eric-wieser** [comment]
I think this needs to become `_PathType = AnyStr` and `_PathType = Union[_PathLike, AnyStr]`

**Comment by sid-kap** [comment]
@eric-wieser What do you mean by that?
Also, how do I figure out which test is failing?

**Comment by JelleZijlstra** [comment]
You have to click through a few times. The error is:
```
FAILURE  #115 check stdlibsamples (3.2)
glob.py:44: error: Incompatible types in "yield" (actual type "str", expected type "bytes")
SUMMARY  1/132 tasks and 1/132 tests failed
```
in mypy's selftest, which among others runs mypy on some sample code.

I haven't looked in detail, but the types here are complicated because we both have to support Paths and we have to make it so that if the argument is bytes, we return bytes (that's what the previous AnyStrs were for). @eric-wieser's suggestion (changing the way `_PathType` is defined) may work, but may also cause more problems.

**Comment by eric-wieser** [comment]
I mean change
```diff
 if sys.version_info >= (3, 6):
     from builtins import _PathLike
-    _PathType = Union[bytes, Text, _PathLike]
+    _PathType = Union[AnyStr, _PathLike]
 else:
-    _PathType = Union[bytes, Text]
+    _PathType = AnyStr
``

**Comment by JelleZijlstra** [comment]
That's very risky since we import and reuse `os.path. _PathType` in several other stubs.

**Comment by eric-wieser** [comment]
I suspect this is the correct definition in all the other cases though, and if that causes failures there are probably mistakes in those stubs.

**Comment by JelleZijlstra** [comment]
It's not, since your definition includes a TypeVar. It is correct only in cases where there are multiple types that should match (e.g., an argument and a return type). It is wrong when _PathType is used only as an argument type.

**Comment by eric-wieser** [comment]
I don't understand the scoping rules of type vars yet.

Perhaps we want instead

```
 if sys.version_info >= (3, 6):
     from builtins import _PathLike
-    _PathType = Union[bytes, Text, _PathLike[AnyStr]]
+    class _PathType(Generic[AnyStr], Union[AnyStr, _PathLike[AnyStr]]): pass
 else:
-    _PathType = Union[bytes, Text]
+    class _PathType(Generic[AnyStr], AnyStr): pass
```

**Comment by eric-wieser** [comment]
Ah, perhaps

```
T = TypeVar('T', str, bytes)

```diff
 if sys.version_info >= (3, 6):
     from builtins import _PathLike
-    _PathType = Union[bytes, Text, _PathLike[AnyStr]]
+    T = TypeVar('T', str, bytes)
+    _PathType = Union[T, _PathLike[T]]  # use elsewhere as _PathType[AnyStr]
 else:
-    _PathType = Union[bytes, Text]
+    _PathType = ???
```

**Comment by sid-kap** [comment]
@eric-wieser @JelleZijlstra I'm pretty new to mypy/typeshed so I don't know enough to decide which one seems correct. If you come to a conclusion about how to do it correctly, feel free to open up a new PR.

**Comment by eric-wieser** [comment]
Opened python/typing#543 about how to write this

**Comment by JelleZijlstra** [comment]
I reimplemented this in a way I thought should work (https://github.com/JelleZijlstra/typeshed/tree/ospathlike), but that unfortunately triggers python/mypy#3644. Let me try to think of some other way to handle it.

**Comment by JelleZijlstra** [comment]
Oh actually, it works with overloads (https://github.com/JelleZijlstra/typeshed/commit/f4c10cbd449e3a3c4bfcf5b6962da6def818d0ee).

**Comment by FichteFoll** [comment]
See also https://github.com/python/typeshed/issues/1841 for a previous attempt.

**Comment by JelleZijlstra** [comment]
Superseded by #2053.

**Pull request closed without merging**
