### PR TITLE
Fix click.getchar return type

### PR DESCRIPTION
**Pull request by pkch**
The docs and actual behavior confirm `click.getchar` returns a `bytes` object.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Are you sure? http://click.pocoo.org/5/utils/#getting-characters-from-terminal says getchar returns a character as "a Unicode character". The implementation at https://github.com/pallets/click/blob/master/click/_termui_impl.py#L518 suggests it may return bytes in Python 3 on Windows, but in all other circumstances it decodes the character first.

**Comment by pkch** [comment]
Hmm I was on Windows and python 3 and saw a `bytes` object. Then I read the docs and, given that python doesn't have a type called "character", I conveniently interpreted this to mean a "bytes object that contains the unicode code point" :)

So yeah, you're right it's not correct. But... I don't think it's the greatest API to return a `str` in one case and `bytes` in another. I suppose I should change it to `Union[str, bytes]`?

**Comment by JelleZijlstra** [comment]
I think you can do this with version/platform checks (unless I'm misreading the code): the return type is bytes if you're on Windows and Python 3, and otherwise Text.

I have a hard time understanding why it's implemented this way though; maybe it's a bug in the library?

**Comment by pkch** [comment]
Ok, let me ask on `click` github first to clarify; then I can update this PR.

**Comment by JelleZijlstra** [comment]
Your click issue didn't get much response, but the one responder also seems to think that returning bytes on Windows in Python 3 is unexpected. For now, can we just change the return annotation to `Text`? That should fix an existing bug in Python 2. If you want, we can also use version and platform checks to reflect the fact that currently it returns bytes on Windows in py3.

**Comment by gvanrossum** [comment]
Ping? Is this still needed? It's been well over half a year since the last activity.

**Comment by JelleZijlstra** [comment]
I just implemented my suggestion above of using `Text` (which is mostly correct). I think we should merge that version.

**Comment by kip-13** [comment]
I think that the return type can be maybe `Union[Text, bytes]`, because if the `getchar` run in `Windows / Python 3` the value is a byte string.

The function [getchar](https://github.com/pallets/click/blob/master/click/_termui_impl.py#L519) use the function [getch](https://docs.python.org/2/library/msvcrt.html#msvcrt.getch) from module msvcrt.

Is just my suggestion.

**Pull request merged**
