### PR TITLE
fix email.mime

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by gvanrossum** [comment]
What's broken that you are "fixing" here?

**Comment by graingert** [comment]
@gvanrossum I get missing module email.mime.application when running the tests with mypy on this version of typeshed

**Comment by gvanrossum** [comment]
Which tests? How do you run them? You really need to provide more information.

**Comment by graingert** [comment]
@gvanrossum I upgraded the typeshed submodule and ran the tests in mypy as defined by .travis.yml

**Comment by gvanrossum** [comment]
I cannot repro that. Please provide more detailed steps to reproduce the problem you are fixing (preferably in a separate issue).

**Comment by graingert** [comment]
Hmm dang, ok will try and demo on Travis or something

**Comment by JelleZijlstra** [comment]
There is an `__init__.py` file instead of `__init__.pyi` in stdlib/3/email/mime right now. This PR adds the missing pyi file but doesn't remove the py. @graingert could you make that change?

The new stub for email.mime.application in Python 2 looks good.

**Pull request merged**
