### PR TITLE
Split struct_rusage into a separate file

### PR DESCRIPTION
**Pull request by srittau**
This is an attempt to work around the intermittent
mypy crashes while running the test cases.

### CODE REVIEW

**Comment by srittau** [comment]
Cf. #11220

**Comment by AlexWaygood** [comment]
LGTM. Since I managed to repro the crash locally, I can try to find time to stress-test this, to check if it does fix the crash. Or we can just merge this now and hope it fixes things -- we can always revert it later if the error still persists. I'm easy either way :)

**Comment by srittau** [comment]
A stress test would be good, I think. I'm not really convinced that this PR fixes things.

**Comment by AlexWaygood** [comment]
Regrettably.....

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\alexw\coding\typeshed\.venv\Lib\site-packages\mypy\__main__.py", line 37, in <module>
    console_entry()
  File "C:\Users\alexw\coding\typeshed\.venv\Lib\site-packages\mypy\__main__.py", line 15, in console_entry
    main()
  File "mypy\main.py", line 100, in main
  File "mypy\main.py", line 182, in run_build
  File "mypy\build.py", line 191, in build
  File "mypy\build.py", line 265, in _build
  File "mypy\build.py", line 2943, in dispatch
  File "mypy\build.py", line 3334, in process_graph
  File "mypy\build.py", line 3415, in process_fresh_modules
  File "mypy\build.py", line 2111, in fix_cross_refs
  File "mypy\fixup.py", line 52, in fixup_module
  File "mypy\fixup.py", line 127, in visit_symbol_table
  File "mypy\lookup.py", line 31, in lookup_fully_qualified
AssertionError: Cannot find module for _resource_rusage.struct_rusage
```

**Pull request closed without merging**
