### PR TITLE
Add missing constants to flask-cors stubs

### PR DESCRIPTION
**Pull request by ashm-dev**

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Thanks!

(At some point, the constants could be converted to `Final` strings that are assigned the actual value, but that can wait for another PR.)

**Comment by ashm-dev** [comment]
> Thanks!
> 
> (At some point, the constants could be converted to `Final` strings that are assigned the actual value, but that can wait for another PR.)


Thanks!
Do you mean for me to pack them in Final? I was just taking an example from other packages, so I did it the way it was)

**Comment by srittau** [comment]
The current gold standard for constants is to use `Final` and the actual constant value (if it is relevant) or use `Final` with the type if the constant value is not really relevant:

```python
ANSWER_QUESTION_OF_LIFE: Final = 42
SOME_RANDOM_CONSTANT: Final[int]
```

We'd certainly appreciate a PR changing the flask-cors constants accordingly.

**Comment by ashm-dev** [comment]
@srittau Thanks for the explanation, I'll try to update soon!)

**Pull request merged**
