### PR TITLE
Expand the sqlalchemy stubs related to the Column model.

### PR DESCRIPTION
**Pull request by timabbott**

### CODE REVIEW

**Comment by gvanrossum** [comment]
(Hope you didn't put too much faith in the Travis CI tests yet. They exclude sqlalchemy for now, because there's still a bug in how the test runner runs mypy. :-( )

**Comment by timabbott** [comment]
Well sqlalchemy would be failing tests anyway because of sqlalchemy.orm having a messily incomplete stub.  I only fixed sqlalchemy.sql yesterday.

**Comment by timabbott** [comment]
(It does pass tests for me locally)

**Comment by gvanrossum** [comment]
Looks good. Merging.

**Pull request merged**
