### PR TITLE
Add color back to CI output

### LINKED ISSUE #9204: CI output is no longer colorised
See e.g. https://github.com/python/typeshed/actions/runs/3472143680/jobs/5802584010. I haven't done any investigation yet as to what the cause might be.

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #9204

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Still don't know exactly what changed here, but this seems to fix it!

**Review by srittau — APPROVED** [review]

**Review by JelleZijlstra — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Not sure what's taking the third-party stubtest on MacOS so long -- it should only be running on four stubs packages:

```pycon
>>> import tomli
>>> from pathlib import Path
>>> for path in Path("stubs").iterdir():
...     metadata = path / "METADATA.toml"
...     if "darwin" in tomli.loads(metadata.read_text(encoding="utf-8")).get("tool", {}).get("stubtest", {}).get("platforms", ["linux"]):
...         print(path.parts[-1])
...
JACK-Client
psutil
pyaudio
pynput
```

**Comment by JelleZijlstra** [comment]
Yes, GitHub seems generally laggy at the moment. Maybe the runners ate too much Thanksgiving turkey. I'd recommend waiting a while longer and re-triggering CI if it doesn't eventually show up.

**Comment by AlexWaygood** [comment]
Yes, looks like the `brew install` step failed in the macOS stubtest run. But even if that's not just a laggy-GitHub fluke, I'm confident it won't have been caused by this PR.

**Pull request merged**
