### PR TITLE
Add empty stubs for 2.7 internet protocol modules

### PR DESCRIPTION
**Pull request by alvarocaceres**
Based on https://docs.python.org/2.7/library/internet.html , except for decimal.pyi which is unrelated

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Please also file a bug, referencing this PR, about the fact that these stubs are incomplete and somebody should fill them in.

**Comment by gvanrossum** [comment]
Please don't merge.

I don't like these kinds of dummy stubs. They give a false sense of security.

If you don't like to see the errors about these imports with mypy, use `-s` or just filter out these specific errors.

**Comment by JukkaL** [comment]
Mypy doesn't support module-level `__getattr__` yet :-(

Also, it's not clear why you are adding empty stubs for these modules. I think we should have a discussion about whether they are desirable first.

**Comment by alvarocaceres** [comment]
The motivation for the PR was to help pytype -- I think it has a different approach than mypy for missing modules, but will leave it to @matthiaskramm to explain. I'll see if I can use some stub generators to make these files instead

**Comment by matthiaskramm** [comment]
`-s` sounds like a big hammer, just for silencing a few (incorrect) errors about (correct) imports.

Here's our problem: We have a few thousand files all across our codebase that do something like, say, `import decimal`. Since they do nothing incorrect, we'd like to avoid having warnings generated for those files.

It feels like we need *some* way of maintaining, in machine readable form, a list of modules that exist in the standard library, but happen to not be in typeshed yet. Adding modules with `def __getattr__(...) -> Any` seemed the easiest way to accomplish that. Do you have an idea for an alternative solution?

**Comment by gvanrossum** [comment]
Doesn't pytype already have its own alternative source of stubs? You could
put them there. Or you could add a blacklist (or is that a whitelist?) to
pytype saying "if you don't find a stub for this module, it's not an error".

Such a list could even be committed to typeshed, but it seems the list is
fairly dependent on the user -- you don't want to have to maintain a list
of every module on PyPI. In fact I think it's probably only Google that's
in need of this list for now -- for the rest of us, we can (and do!) easily
put `# type: ignore` on the offending import.

**Comment by matthiaskramm** [comment]
We would only need such a list for all the modules in the standard library. (Maybe we can make it a directory? typeshed/missing/2.7? It sounds like over-engineering, but maybe there's some merit in it since it also doubles as a TODO list for modules that typeshed still needs)

However, yes, if we're the only ones who need such a list, we'll just put it into pytype.

**Comment by gvanrossum** [comment]
Let's just agree that whatever form it takes it should *not* be what's in this PR. Apart from that I don't mind much how you solve it -- a list or new directory in typeshed or something in pytype are both acceptable.

**Pull request closed without merging**
