### PR TITLE
changed format_exception to use BaseException as value

### PR DESCRIPTION
**Pull request by phouse512**
A fix for #224 - I ran `python3 runtests.py` and it passed fine, but let me know if there is more to the usual pull-request workflow here.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Did you also write some code that uses this API and verify that it works as
expected at runtime and also type checks?

--Guido (mobile)

**Comment by phouse512** [comment]
I did! How should I put that code in this pr- a gist or screenshot?

**Comment by gvanrossum** [comment]
A Gist would be great. Ideally when running it, it actually prints some
non-trivial traceback produced by sys.exc_info().

**Comment by phouse512** [comment]
Here is a [gist](https://gist.github.com/phouse512/9a05b7ba3ec9f78a826230df27257b6f).  I hope that's helpful! Let me know if there is anything else needed.

**Comment by gvanrossum** [comment]
Excellent! Merging now.

**Pull request merged**
