### PR TITLE
Fix `len(T)` so it doesn't upcast `Literal[:int]` from to `int` if returned from `T.__len__() `

### PR DESCRIPTION
**Pull request by jorenham**
Previously `len(T)` always returned and `int`, even if `T.__len__() -> Literal[42]`. I.e. `T.__len__()` and `len(T)` did not invariably match. 

This PR fixes this discrepancy, by making `len()` generic on the return type of `__len__`, i.e. as `len[N: int]: (SupportsLen[N]) -> N`.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This is incorrect, `len()` always returns an int in CPython.

**Comment by JelleZijlstra** [comment]
```
>>> class X:
...     def __len__(self): return "x"
... 
>>> len(X())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer
```

**Comment by JelleZijlstra** [comment]
And similarly if you return a subclass of `int`:

```
>>> class X:
...     def __len__(self): return True
... 
>>> len(X())
1
```

**Comment by jorenham** [comment]
Unfortunately, using a `N = TypeVar("N", int, LiteralInt)` isn't possible at the moment. But the current upcasting behaviour from `Literal[:int]` to `int` is also incorrect.

**Comment by JelleZijlstra** [comment]
As you can see, this leads to lots of new obscure errors. I don't think it's worth it.

**Comment by jorenham** [comment]
@JelleZijlstra Yea I tend to agree: It might be best to re-address this issue when something like a `LiteralInt` or `Literal[int]` type is introduced. 

And for now, there's the simple workaround of using `.__len__()` instead of `len()`.

**Pull request closed without merging**
