### PR TITLE
Improve `runpy` typings

### PR DESCRIPTION
**Pull request by sobolevn**
Changes:
- Removes protected members. They are not a part of public (or even usable / user-facing API)
- Add `__all__` (it only mentions two existing functions, but still)

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I'd prefer to keep the private classes since they're already there, and our general policy is to include private names if a user wants them.

**Comment by sobolevn** [comment]
> if a user wants them.

I don't think someone ever really wanted them.
They were generated automatically 6 years ago: https://github.com/python/typeshed/commit/e2dde66eb19a95dba17d9478c40fe00b7a671ef4#diff-12f2d6523ac3c2288fac6fd78ccba88fb0d370af82bd1bbf60ad27726949c319R7-R18

From their usage, I would say that they are very minor implementation details: 
- https://github.com/python/cpython/blob/9d4161a60ca8b470148ffd6c73e3110a0aa6d66f/Lib/runpy.py#L96
- https://github.com/python/cpython/blob/9d4161a60ca8b470148ffd6c73e3110a0aa6d66f/Lib/runpy.py#L285-L286

No tests, no docs.

**Comment by Akuli** [comment]
After the auto-generation, the types were improved in #2395, but that PR improves `runpy.pyi` in general, not just those classes.

**Comment by JelleZijlstra** [comment]
I'd still prefer to keep them. Typeshed changes have repercussions in lots of code we can't easily check, so I'd like to be conservative in making changes that don't fix a clear problem.

**Comment by JelleZijlstra** [comment]
But I would like to have the improved `__all__` :)

**Comment by sobolevn** [comment]
Done! Only `__all__` is changed.

**Review by JelleZijlstra — APPROVED** [review]
Thank you!

**Pull request merged**
