### PR TITLE
Fixed missing methods, wrong names and types

### PR DESCRIPTION
**Pull request by agronholm**
Changes:

* Added the missing methods `selected_alpn_protocol()` and `version()` to `SSLObject`
* Fixed the naming of the `shared_ciphers()` method in `SSLSocket` and `SSLObject` (was missing the last "s")
* Fixed return type of `cipher()` (it's documented to return `None` if no connection has been established)
* Fixed type of second item in the return value of `cipher()` and `shared_ciphers()` (it's a string like "TLSv1.2", not an integer)
* Added explicit overloads for `getpeercert()` based on the type of the `binary_form` argument

### CODE REVIEW

**Comment by agronholm** [comment]
Wow, that was fast!

**Comment by agronholm** [comment]
I'm also trying to use `Literal` to fix the return type of `getpeercert()` but I have not yet found the correct mypy incantation to do so.

**Comment by srittau** [comment]
Return types that depend on a boolean flag generally look something like this:

```python
@overload
def foo(x: Literal[True]) -> int: ...
@overload
def foo(x: Literal[False] = ...) -> str: ...
@overload
def foo(x: bool) -> Any: ...
```

The last overload is necessary if the valued of `x` can't be determined statically.

**Comment by agronholm** [comment]
I tried pasting that into a module and running mypy on it:
```
error: Overloaded function signatures 1 and 2 overlap with incompatible return types
error: Overloaded function signature 3 will never be matched: signature 1's parameter type(s) are the same or broader
error: Overloaded function signature 3 will never be matched: signature 2's parameter type(s) are the same or broader
```

**Comment by agronholm** [comment]
It seems like mypy is not dealing well with the conditional import:
```python3
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
```
error: Incompatible import of "Literal" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")

Once I deleted the `typing_extensions` import and ran the check on Python 3.8, it worked fine.

**Comment by agronholm** [comment]
Oh btw, the solution that worked:
```python3
@overload
def foo(x: Literal[True]) -> int: ...

@overload
def foo(x: Literal[False] = False) -> str: ...

def foo(x=False):
    pass
```

**Comment by agronholm** [comment]
I'm done with my changes.
@srittau are you in a position to merge this?

**Pull request merged**
