### PR TITLE
Ignore PyCharm project files in Git

### PR DESCRIPTION
**Pull request by vlasovskikh**

### CODE REVIEW

**Comment by vlasovskikh** [comment]
Pytype fails to install correctly for reasons unrelated to this PR.

**Comment by gvanrossum** [comment]
I've submitted https://github.com/google/pytype/pull/46 to the pytype project to fix this.

**Comment by matthiaskramm** [comment]
Triggering a CI rerun.

**Comment by vlasovskikh** [comment]
Thanks!

**Pull request merged**
