### PR TITLE
Fix return type annotation for `asyncio.Task.get_coro()`

### LINKED ISSUE #12440: `asyncio.Task.get_coro` can return `None` on 3.12+
This was discovered when looking at [#122332](https://github.com/python/cpython/issues/122332) on CPython.

With 3.12's new `asyncio.eager_task_factory`, `Task.get_coro()` is able to return `None` (see [here](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.get_coro)). This needs to be reflected in the stubs.

### PR DESCRIPTION
**Pull request by ZeroIntensity**
This closes #12440.

### CODE REVIEW

**Comment by ZeroIntensity** [comment]
This is bug in AnyIO (as in, it does not support `eager_task_factory`), as found when debugging [this issue report](https://github.com/python/cpython/issues/122332).

**Comment by JelleZijlstra** [comment]
Should this be made conditional on the version? The CPython docs imply that before 3.12 it could not return None.

**Comment by ZeroIntensity** [comment]
> Should this be made conditional on the version? The CPython docs imply that before 3.12 it could not return None.

Oh, that's right, I'll update it.

**Comment by ZeroIntensity** [comment]
Issue in AnyIO opened: https://github.com/agronholm/anyio/issues/764

**Comment by graingert** [comment]
I'm not sure why eager task factory can't return the coro it's passed, this seems like a cpython bug

**Comment by ZeroIntensity** [comment]
I think it's intentional, and apparently it helps performance: see [here](https://github.com/python/cpython/blob/45614ecb2bdc2b984f051c7eade39458a3f8709f/Modules/_asynciomodule.c#L3193).

**Comment by kumaraditya303** [comment]
It is done deliberately, it help performance as it clears cycle refs.

**Comment by graingert** [comment]
It seems obvious that `asyncio.eager_task_factory(loop, coro).get_coro()` can return the coro without being a breaking change.

I suspect that performance increase was added without realising it's a breaking change, that would need a deprecation warning and 3 releases

**Comment by JelleZijlstra** [comment]
I merged this as it reflects the documented behavior of CPython. If you want to change CPython's behavior, open an issue on the CPython repo.

**Pull request merged**
