### PR TITLE
Change empty string literals to ellipsis

### PR DESCRIPTION
**Pull request by alvarocaceres**
For pytype compatibility

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Should that be `arg: str = ...`?

**Comment by JukkaL** [comment]
It would be better to add `: str` annotations when it makes sense instead of just removing these.

**Comment by alvarocaceres** [comment]
for all I know, some of those functions accept non-str types, so I didn't want to introduce changes. But if you're both ok with a str annotation then will add them

**Comment by JukkaL** [comment]
A fair point -- it's actually not trivial to see whether `str` is the right type for many of these. Sometimes `unicode` might be the right thing. Just using `...` is reasonable unless the type seems obvious enough.

**Comment by alvarocaceres** [comment]
could mypy give different errors for these two stubs?

def f(a=''): ...
def f(a=...): ...


I believe for pytype they're equivalent, I think the only literals that we get type information from (in stubs) are None, ints and floats

**Comment by gvanrossum** [comment]
Looks like for mypy they're equivalent.

**Comment by JukkaL** [comment]
They are equivalent. The reason why stubs have non-empty default values is often due to the mypy stubgen utility. It generates function stubs with default argument values to make it easier to manually annotate stubs. Often the default value gives a hint about the type of the argument. For example, if it's `None`, the argument should almost always be given an `Optional[...]` type.

**Comment by matthiaskramm** [comment]
Would it be possible to tweak stubgen to generate a comment instead, or something along those lines?

**Comment by JukkaL** [comment]
Sure, it shouldn't be hard. As mypy is happy with the literals there hasn't been much of an incentive until now.

**Pull request merged**
