### PR TITLE
Change time.struct_time to use __new__ instead of __init__.

### PR DESCRIPTION
**Pull request by rchen152**

### CODE REVIEW

**Comment by gvanrossum** [comment]
What problem does this change solve? AFAICT it accepts exactly the same constructor calls.

Also, what is your git workflow? It seems every PR you ever submitted is included in the list of commits.

**Comment by rchen152** [comment]
The problem is that when __new__ isn't defined, pytype uses the __new__ method of the namedtuple instance for type-checking and complains that the constructor call is missing parameters tm_mon, tm_mday, etc.

Re: workflow:
I have a local clone of a fork of typeshed, and when I want to make a change I do something along the lines of
git fetch upstream
git merge upstream/master
<make a change>
git commit -am ...
git push
and then go into the browser to open a pull request. Is there something I should be doing differently to make the pull request not show all of my old commits?

**Comment by gvanrossum** [comment]
Hm, but have you tested it?

I have this test:
```py
import time
def foo():
    # type: () -> time.struct_time
    return time.struct_time((0, 0, 0, 12, 34, 0, 0, 0, 0))
```
This has no errors before your PR and gives these errors with your PR:
```
tt.py:4: error: Too few arguments for "struct_time"
tt.py:4: error: Argument 1 to "struct_time" has incompatible type "Tuple[int, int, int, int, int, int, int, int, int]"; expected "int"
```
So that's exactly backwards from your claim.

Re workflow: You are probably doing all your work in master. But since we squash-merge all PRs, your master has a different sequence of commits than upstream/master. You may be able to fix this using "git rebase upstream/master; git push -f". But a better workflow would be to create a new branch for each PR and just delete the branch after your PR has been merged. Then "git pull upstream/master; git push" will keep your master exactly in sync with upstream/master.

**Comment by gvanrossum** [comment]
Oh wait, this may be because mypy and pytype interpret this situation differently. In order to make both work right you may have to redundantly define both `__new__` and `__init__` (so just keep the existing `__init__` and add your `__new__`).

**Comment by gvanrossum** [comment]
Oh wait, this may be because mypy and pytype interpret this situation differently. In order to make both work right you may have to redundantly define both `__new__` and `__init__` (so just keep the existing `__init__` and add your `__new__`).

**Comment by rchen152** [comment]
Ok, I added the __init__ method back. I'll create a new branch for each PR going forward. Is the current one okay, or should I try to fix the commit history?

**Comment by gvanrossum** [comment]
NP, thanks!

**Pull request merged**
