### PR TITLE
Improve Python 2.7 inspect stub

### PR DESCRIPTION
**Pull request by jstasiak**
This patch consists of:

* Splitting and reordering the content into sections corresponding
  to the module's documentation sections
* Implementing some missing functions
* Adding TODOs for missing stuff (I may've missed something)

The signature of isgenerator() (was: Any argument, is: argument of type
object) is changed for consistency with other is* functions I added
here, after some considerations I couldn't decide whether it should be
object or Any - if object is not advised please let me know.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks! I think for arguments in a stub file there's no difference between object and Any.

Can you do the Python 3 stub for this file too?

**Comment by jstasiak** [comment]
I can and I want to, it'll just take a while. One obstacle is that there are many things changed/added in the module in 3.2-3.5, do I understand correctly that I'll need to provide different copies of the stub in ``stdlib/3.2``, ``stdlib/3.3``, ``stdlib/3.4`` and ``stdlib/3.5``?

**Comment by gvanrossum** [comment]
Technically that's the right thing to do. But if the differences are small
it's okay to take the 3.5 version and put it in the "3" directory. Maybe
with comments explaining which APIs don't exist in previous versions.

**Comment by gvanrossum** [comment]
OK, let's do that in a separate PR. I'll merge this now.

**Comment by jstasiak** [comment]
Thanks, I'm in the process of preparing a generic-ish Python 3 stub, should have something read soon.

**Pull request merged**
