### PR TITLE
fix socket.socket.sendmsg to support ReadableBuffer

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Review by srittau — APPROVED** [review]
LGTM, apart from the black/isort complaints.

**Comment by graingert** [comment]
This is only the method I ran into Probably the whole socket module needs updates for ReadableBuffer and WritableBuffer

**Comment by srittau** [comment]
> This is only the method I ran into Probably the whole socket module needs updates for ReadableBuffer and WritableBuffer

That's fine. But please reformat the file with black/isort.

**Comment by lancelote** [comment]
@graingert You need to move `from _typeshed import ReadableBuffer` to the second line right after `import sys` to have the correct import sorting. See https://github.com/python/typeshed/pull/5541/checks?check_run_id=2683488273#step:4:17

`sendmsg()` signature is too long with your changes. It needs to be multiline now. See https://github.com/python/typeshed/pull/5541/checks?check_run_id=2683489069#step:4:33

**Comment by JelleZijlstra** [comment]
This has a pretty bad merge conflict because of _socket/socket moves. I'm preparing a new PR.

**Comment by graingert** [comment]
@JelleZijlstra awesome, thanks for taking this over for me

**Pull request closed without merging**
