### PR TITLE
Added partial type stubs for stdlib xml

### PR DESCRIPTION
**Pull request by onionymous**
### Changes
* Added stubs for `xml.dom.minidom.parse` and `xml.dom.minidom.parseString`
* Added empty stubs for expatbuilder, minicompat and xmlbuilder submodules

### Testing
Ran all tests under `tests/`, and ensured they passed:
```
(.venv3) λ  typeshed git:(test) python3 tests/check_consistent.py
```

```
(.venv3) λ  typeshed git:(test) python3 tests/mypy_self_check.py
...
Success: no issues found in 240 source files
mypy self test succeeded
```

```
(.venv3) λ  typeshed git:(test) python3 tests/mypy_test.py
...
Success: no issues found in 916 source files
```

```
(.venv3) λ  typeshed git:(test) python3 tests/mypy_test_suite.py
...
=================================== 291 passed in 109.45s (0:01:49) ====================================
mypy tests succeeded
```

```
(.venv3) λ  typeshed git:(test) python3 tests/pytype_test.py
...
Ran pytype with 1916 pyis, got 0 errors.
```

```
(.venv3) λ  typeshed git:(test) python3 tests/stubtest_unused.py
```

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Thanks for the PR! From a quick scan, I think the type of parser is `Optional[XMLReader]`, but I'm not too familiar with these modules so could be wrong :-)

**Review by hauntsaninja — COMMENTED** [review]
Thanks, onion! XMLParser does sound like it makes sense :-) Unfortunately I'm having trouble tracing it in the code.

I got XMLReader from:
https://github.com/python/cpython/blob/e1dc0db8c7cb8c4d7343e051ba85146b375bb8e0/Lib/xml/dom/minidom.py#L2001 calls 
https://github.com/python/cpython/blob/e1dc0db8c7cb8c4d7343e051ba85146b375bb8e0/Lib/xml/dom/pulldom.py#L342 calls
https://github.com/python/cpython/blob/e1dc0db8c7cb8c4d7343e051ba85146b375bb8e0/Lib/xml/sax/__init__.py#L70 which is currently annotated as returning XMLReader
https://github.com/python/typeshed/blob/d4bd95fd8699893392dc76de05478b54928d30af/stdlib/2and3/xml/sax/__init__.pyi#L26
which matches up with what I get at runtime:
```
>>> type(xml.sax.make_parser()).__mro__
(<class 'xml.sax.expatreader.ExpatParser'>, <class 'xml.sax.xmlreader.IncrementalParser'>, <class 'xml.sax.xmlreader.XMLReader'>, <class 'xml.sax.xmlreader.Locator'>, <class 'object'>)
```

Does that seem correct to you? (It's also possible there's some duck typing going on)

**Comment by onionymous** [comment]
Yep, that makes sense to me too. Thanks for tracing the flow!

**Comment by hauntsaninja** [comment]
Thanks again!

**Pull request merged**
