### PR TITLE
Add `@final` to `slice`/`memoryview`/`range`

### PR DESCRIPTION
**Pull request by AlexWaygood**
None of these classes can be subclassed at runtime.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Looks like you found a mypy bug: ast.pyi defines its own class called slice, but somehow it's checking `@final` on `builtins.slice`?

**Comment by AlexWaygood** [comment]
> Looks like you found a mypy bug: ast.pyi defines its own class called slice, but somehow it's checking `@final` on `builtins.slice`?

😣

**Comment by hauntsaninja** [comment]
Hmm, the other weird thing is that the mypy tests pass, it's only when running the mypy build in the stubtest invocation does it fail...

**Comment by hauntsaninja** [comment]
hmm hmm hmm, locally:
```
stubtest --custom-typeshed-dir ~/dev/typeshed ast. # passes
stubtest --custom-typeshed-dir ~/dev/typeshed ast _ast  # passes
stubtest --custom-typeshed-dir ~/dev/typeshed _ast ast  # fails
```

**Comment by hauntsaninja** [comment]
Spent some more time digging through mypy code, it's pretty thorny.

Here's a one character fix:
```
diff --git a/stdlib/builtins.pyi b/stdlib/builtins.pyi
index b4890072..53575f8f 100644
--- a/stdlib/builtins.pyi
+++ b/stdlib/builtins.pyi
@@ -19,7 +19,7 @@ from _typeshed import (
     SupportsRDivMod,
     SupportsWrite,
 )
-from ast import AST, mod
+from _ast import AST, mod
 from io import BufferedRandom, BufferedReader, BufferedWriter, FileIO, TextIOWrapper
 from types import CodeType, MappingProxyType, TracebackType
 from typing import (
```

There's really a lot going on here: 1) collision with a name in builtins, 2) builtins depending on ast, 3) ast doing `from _ast import *`

**Comment by AlexWaygood** [comment]
> Spent some more time digging through mypy code, it's pretty thorny.
> 
> Here's a one character fix:
> [...]

Amazing, thanks for looking into it! I'll see if I can edit my patch tomorrow.

**Comment by JelleZijlstra** [comment]
Thanks for investigating @hauntsaninja!

Not sure if it will make a difference, but it looks like we can also remove `mod` from that import. It's only used in a union with AST in an argument type, and `_ast.mod` is a subclass of `_ast.AST`.

**Comment by AlexWaygood** [comment]
Huzzah!

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
