### PR TITLE
Enable aliases in pytest_mock and put on pytest exclude list

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Pytype still fails in Travis, unfortunately. I guess the exclude list just filters out errors from those files, but pytype still runs on them, so if it hangs it still hangs.

**Comment by srittau** [comment]
Oh well.

**Comment by srittau** [comment]
The pytest check passes now. 🎉

**Comment by Akuli** [comment]
#4363 does the same pytype version requirement change (possible merge conflict to be fixed by whoever's PR is merged last)

**Comment by Akuli** [comment]
Nevermind, there seems to be no merge conflict

**Pull request merged**
