### PR TITLE
Increase pyright strictness when checking `__all__`

### PR DESCRIPTION
**Pull request by AlexWaygood**
And also fix a typo in `pyrightconfig.stricter.json` that was already fixed in `pyrightconfig.json` in https://github.com/python/typeshed/pull/7355

### CODE REVIEW

**Comment by AlexWaygood** [comment]
@srittau, could you possibly take a look at the Redis hit picked up [here](https://github.com/python/typeshed/runs/5297403027?check_suite_focus=true)? (I can have a go, if not — but you know much more about Redis than I do 🙂)

**Comment by srittau** [comment]
@AlexWaygood Looking at the source code, `RedisCluster` needs to be re-exported from `.cluster` in the stubs.

**Comment by AlexWaygood** [comment]
> I can create a separate PR if you wish.

Yes please 🙂

**Comment by srittau** [comment]
#7371

**Comment by AlexWaygood** [comment]
I'm going to mark this as "ready for review", as it's nearly mergeable. There are two remaining blockers:

- #7370
- `Popen` is listed in `asyncio.windows_utils.__all__`, but is not currently defined in the stub. I'd submit a patch to add it to the stub, but I've looked at the source code 5 times now and have no idea how the class is meant to work or how it should be typed. Any help on that one would be appreciated!

**Review by srittau — APPROVED** [review]
LGTM, once CI clears.

**Comment by AlexWaygood** [comment]
(#7412 is a new blocker now that #7343 has been merged...)

**Comment by AlexWaygood** [comment]
Aaand CI is finally green! 🥳🥳🥳

**Review by hauntsaninja — APPROVED** [review]
Hooray!

**Pull request merged**
