### PR TITLE
Fix return types in urllib.request

### PR DESCRIPTION
**Pull request by srittau**
* Add missing methods to `http.client.HTTPResponse`
* Tighten return types of URL handlers
* `urlopen()` et al. return a modified `HTTPResponse`
* Add missing arguments (not annotated) to `HTTPErrorProcessor` methods

### CODE REVIEW

**Comment by srittau** [comment]
pytype fails for a reason I do not understand, although it also reports errors in unchanged files.

**Comment by JelleZijlstra** [comment]
Hm, pytype is still not happy. :( @rchen152 could you take a look?

**Comment by rchen152** [comment]
Sorry, I missed this notification - happened to see this just now while browsing the PRs. Pytype is probably complaining about the `# type: ignore` - should be a simple enough thing to fix on the pytype end. I'll update once we've done so.

**Comment by rchen152** [comment]
Released pytype-2018.9.18 and reran the failing test - everything looks good now.

**Comment by JelleZijlstra** [comment]
Thanks for fixing this!

**Pull request merged**
