### PR TITLE
Fix annotation shadowed by forward reference of preoprty in `datetime` constructor

### PR DESCRIPTION
**Pull request by dkgi**
Pyre thinks the `tzinfo` here refers to the property defined later in the class.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Shouldn't the occurrence of `Optional[tzinfo]` on line 84 also be updated (just to be sure)?

**Comment by dkgi** [comment]
Good catch. Will update.

**Comment by dkgi** [comment]
Anybody want to take another look at this?

**Comment by JelleZijlstra** [comment]
Looks good now (I had skipped this PR because it looked like you hadn't sent an update yet).

**Comment by dkgi** [comment]
> Looks good now (I had skipped this PR because it looked like you hadn't sent an update yet).

Yeah, I'm still bad at GitHub 🙈Thanks for taking a look.

**Comment by JelleZijlstra** [comment]
No problem! We generally prefer that people don't amend and force-push commits, so it's clearer when feedback is addressed.

**Pull request merged**
