### PR TITLE
Fix the type signature of ConfigParser.get()

### PR DESCRIPTION
**Pull request by KellerFuchs**
The documentation [explicitely specifies](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.get) that `None` is a legitimate `fallback` value.

### CODE REVIEW

**Comment by KellerFuchs** [comment]
Ideally, we should express that the return value is `Optional[str]` only if `fallback` is, but I'm unsure how to express that in `typeshed`.  Perhaps with polymorphism?

**Comment by JelleZijlstra** [comment]
You could probably do that with overloads: one that takes `fallback: str = ...` and returns `str`, and one that takes `fallback: None` and returns `Optional[str]`.

**Comment by KellerFuchs** [comment]
@JelleZijlstra Thanks for the suggestion.

**Comment by JelleZijlstra** [comment]
You need to use `@overload` to express overloads. (I'm kind of surprised this code passed tests; I think a change that @ilevkivskyi made to mypy master recently would make it fail now.)

**Comment by KellerFuchs** [comment]
@JelleZijlstra Thanks for the info.  Now that I've added `@overload`, `mypy` complains that the [Signature of "get" [is] incompatible with supertype "Mapping"](https://travis-ci.org/python/typeshed/jobs/426232885#L483) despite the `type: ignore` annotation.

**Comment by srittau** [comment]
@KellerFuchs The problem is that both overloads have a default value for `fallback`. This means that the type checker does not know which overload to use when `fallback` is missing.

**Comment by JelleZijlstra** [comment]
I think @wimi's comment is right. In addition, exactly one of the overloads should have the `= ...`.

**Comment by KellerFuchs** [comment]
Thank you all for the helpful feedback, and sorry for not getting back to this PR sooner  :)

**Comment by KellerFuchs** [comment]
@srittau I removed the `fallback` parameter in the second overload, and the same issue is still present.

**Pull request merged**
