### PR TITLE
Fix base64 stub

### PR DESCRIPTION
**Pull request by k-saka**
base64 module has accepted bytes-like object and added new encode,decode functions from python3.4.

### CODE REVIEW

**Comment by ambv** [comment]
Instead of providing totally different stubs, would you consider merging your changes with the existing `stdlib/3/base64.pyi`?

Look for `if sys.version_info` checks to see how to implement parts of the stub that only apply to a newer version (look for example in `3/unittest/__init__.pyi`.

**Comment by k-saka** [comment]
Merged 3.4 stub to stdlib/3/base64.pyi. And fixup it for version 3.3.

**Comment by k-saka** [comment]
Merged 3.4 stub to stdlib/3/base64.pyi. And fixup it for version 3.3.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
