### PR TITLE
Type fixes in socketserver

### PR DESCRIPTION
**Pull request by michael-lazar**
Greetings!

I've been working with ``socketserver``  recently and I found a few significant errors in the type stubs.

For some reason that I don't understand, I can't get mypy to complain about these even though the they are clearly wrong. Pycharm's type checker does catch them though (using this same typeshed file) and will highlight the errors.

Here's a minimal example

```python
import socketserver

class MyServer(socketserver.BaseServer):
    def handle_error(self, request, client_address):
        print(request.getsockname())
```

This is valid according to the implementation in ``socketserver.py``, but is flagged as incorrect by the type checker.

> Unresolved attribute reference 'getsockname' for class 'bytes' 

The correct types are actually

- ``request: Union[SocketType, Tuple[bytes, SocketType]]``
- ``client_address: Union[Tuple[str, int], str]``

But I went with ``Any`` instead, following the guidance in the BaseRequestHandler

```
    # Those are technically of types, respectively:
    # * Union[SocketType, Tuple[bytes, SocketType]]
    # * Union[Tuple[str, int], str]
    # But there are some concerns that having unions here would cause
    # too much inconvenience to people using it (see
    # https://github.com/python/typeshed/pull/384#issuecomment-234649696)
```

### CODE REVIEW

**Comment by srittau** [comment]
I am sorry for the late review. Before doing a full review, there is one thing that stands out:

> The correct types are actually
> 
> * `request: Union[SocketType, Tuple[bytes, SocketType]]`
> * `client_address: Union[Tuple[str, int], str]`
> 
> But I went with `Any` instead, following the guidance in the BaseRequestHandler
> 
> ```
>     # Those are technically of types, respectively:
>     # * Union[SocketType, Tuple[bytes, SocketType]]
>     # * Union[Tuple[str, int], str]
>     # But there are some concerns that having unions here would cause
>     # too much inconvenience to people using it (see
>     # https://github.com/python/typeshed/pull/384#issuecomment-234649696)
> ```

Please note that this comment is specifically targeted at these fields and it should not apply to argument types. Generally, using unions in fields and return types can be really inconvenient, but is usually not a problem in argument types.

**Comment by JelleZijlstra** [comment]
Any updates here? @srittau is right that we shouldn't need the `Any` types in argument positions.

**Review by lastthyme — APPROVED** [review]

**Comment by michael-lazar** [comment]
Apologies for the long delay! I've pushed an update for the method arguments.

**Review by srittau — APPROVED** [review]
My understanding of this module is limited, but I trust that these are correct. The primer warning for werkzeug seems ok, werkzeug just needs to adapt its stub to conform to this improved annotation.

**Pull request merged**
