### PR TITLE
Improves `Process` class in `psutil`

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/giampaolo/psutil/blob/master/psutil/__init__.py

### CODE REVIEW

**Comment by sobolevn** [comment]
@JelleZijlstra friendly ping 🙂

**Review by srittau — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks! 👍

**Comment by OneMoreSecond** [comment]
`psutil.Process.status()` returns `str` instead of `int`
https://psutil.readthedocs.io/en/latest/#psutil.Process.status

**Comment by srittau** [comment]
@OneMoreSecond Thanks, #6245.

**Pull request merged**
