### PR TITLE
SMTPChannel.push() accepts str

### PR DESCRIPTION
**Pull request by mkurnikov**
https://github.com/python/cpython/blob/master/Lib/smtpd.py#L313

### CODE REVIEW

**Comment by mkurnikov** [comment]
Should it be `Union[str, bytes]` or just `type: ignore` on the line? PR motivated by https://github.com/django/django/blob/master/tests/mail/tests.py#L1283 in Django tests and implementation seems to only accept `str`.

**Comment by JelleZijlstra** [comment]
For reference mypy currently produces the error `stdlib/2and3/smtpd.pyi:43: error: Argument 1 of "push" is incompatible with supertype "async_chat"; supertype defines the argument type as "bytes"`.

You should `# type: ignore` this because it really does accept only `str` in Python 3. The argument type should be written as `Text` though, because it would accept both `str` and `unicode` in Python 2.

**Comment by mkurnikov** [comment]
@JelleZijlstra Updated it.

**Comment by JelleZijlstra** [comment]
Thanks!

**Pull request merged**
