### PR TITLE
Add `Final` for stdlib constants

### PR DESCRIPTION
**Pull request by max-muoto**
Use the following script: https://gist.github.com/max-muoto/3bdfd495d4ee48dba99c16513e855983 to add `Final` to all module-level standard library constants. (Used [libcst](https://github.com/Instagram/LibCST) as opposed to the native ast module, since it was the easiest way to preserve comments/formatting details across all modules)

Technically this script makes `MY_CONSTANT: Literal[1]` into `MY_CONSTANT: Final[Literal[1]]`, but I ran the Ruff rule [`redundant-final-literal`](https://docs.astral.sh/ruff/rules/redundant-final-literal/) to fix cases of this.

Otherwise:

```python
MY_CONSTANT = 1
MY_CONSTANT_2: int = 1

# Becomes:
MY_CONSTANT: Final = 1
MY_CONSTANT_2: Final[int] = 1
```

With `TypeVar`, `ParamSpec`, `TypeVarTuple`, and `NewType` excluded.

Additionally, ths this excludes the `wintypes.pyi` module (see commit [here](https://github.com/python/typeshed/pull/12318/commits/d1886343945d7165fb901de572611ab94a1d3c6a)), adding final leads Pyright to raise a `Variable not allowed in type expression` warning. I'll dig a bit deeper post this going out, and possibly put up an issue on Pyright's end, since this initially seems like a bug to me.

The other commits on this PR are mostly fixing things like `_TypeVar` that my script didn't account, and removing an extra import of `Final` in `typing.pyi` and `typing_extensions.pyi`.

### CODE REVIEW

**Comment by max-muoto** [comment]
I think this uncovered a PyType bug, it choked on this (I think believing it was associated with the `RegexFlag` enum). Reverted the change for this one line: https://github.com/python/typeshed/pull/12318/commits/76720eca1f4b3c46779432c3cf7d535063886481

**Comment by JelleZijlstra** [comment]
We probably can't merge this with all the mysterious new `error: _T? not callable`. I'm not sure what's causing that, maybe the new imports messed up mypy's handling of the builtin import cycle.

**Comment by max-muoto** [comment]
> We probably can't merge this with all the mysterious new `error: _T? not callable`. I'm not sure what's causing that, maybe the new imports messed up mypy's handling of the builtin import cycle.

That's from an older run, it's not occcuring anymore if you look at the latest mypy primer.

**Comment by max-muoto** [comment]
Okay, consolidated the commits fixing PyType related stuff: https://github.com/python/typeshed/pull/12318/commits/abb0a27d50632ffd4e7bde52bd45a99a91f52257

I there's two issues here (the enum one mentioned above) and another with callables, I'll report both, and once they're fixed this commit can be unwinded in the future.

**Review by max-muoto — COMMENTED** [review]
For whatever reason one of the `Literal[X]` -> `CONSTANT: Final = X` fixed this issue: https://github.com/python/typeshed/pull/12318/commits/c2be29c0649eb6c033809cbe97f6f8de50b6c6d9

**Comment by AlexWaygood** [comment]
It might be good to split this into two PRs: a first PR that makes changes like this, which are arguably no-brainers; we can merge this first PR quickly and easily:

```diff
- FOO: Literal[42]
+ FOO: Final = 42
```

And a second PR that makes changes like this, which will probably require more careful review from us:

```diff
- BAR = 42
+ BAR: Final = 42
- BAZ: int
+ BAZ: Final[int]
```

**Comment by max-muoto** [comment]
> It might be good to split this into two PRs: a first PR that makes changes like this, which are arguably no-brainers; we can merge this first PR quickly and easily:
> 
> ```diff
> - FOO: Literal[42]
> + FOO: Final = 42
> ```
> 
> And a second PR that makes changes like this, which will probably require more careful review from us:
> 
> ```diff
> - BAR = 42
> + BAR: Final = 42
> - BAZ: int
> + BAZ: Final[int]
> ```

Sounds good - let me split out that first change.

**Pull request closed without merging**
