### PR TITLE
Make PathLike generic in AnyStr

### PR DESCRIPTION
**Pull request by gvanrossum**
See https://github.com/python/typing/issues/402#issuecomment-288200802.

Calling out @JelleZijlstra and @sproshev.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Hm, `os.PathLike` as it exists in CPython isn't actually generic, so this would work in stubs but not at runtime. I think that's why @ilevkivskyi wants to add a separate generic `typing.PathLike`. It would be cleaner to change os.py to make PathLike actually generic, but that might break BC and as I understand it we're not currently supposed to use typing in the stdlib.

**Comment by ilevkivskyi** [comment]
@JelleZijlstra 
> this would work in stubs but not at runtime

Yes, but maybe it is OK to do it like this for now, and revisit this later when protocols are settled.

**Comment by gvanrossum** [comment]
Good points, but I think this PR doesn't make things worse, it still makes things better (the existing code is just wrong since it always makes `__fspath__()` return `str`).

I'm not sure how this could be solved using PEP 544 (Protocols) though?

**Comment by ilevkivskyi** [comment]
> I'm not sure how this could be solved using PEP 544 (Protocols) though?

This would be an additional (probably independent) improvement. I think ``PathLike`` is one of those examples where structural check is much better than nominal one. In general, this probably applies to all "compact" classes, with one-two methods with simple signatures.

So that in future we could both make ``PathLike`` a "real" generic and a protocol, by just inheriting from ``Protocol[AnyStr]``.

**Comment by gvanrossum** [comment]
Thanks for the review and the quick merge. So anyways, how should PathLike be used? I guess there are two cases.

1. Someone writes a new object that has a `__fspath__()` method. They could inherit from `PathLike[str]` if they want to express that their `__fspath__()` always returns `str`. It's also possible that they are already generic over `AnyStr` (like `os.DirEntry` ought to be). But because at runtime the class is not generic, they should actually inherit from plain `PathLike` (i.e. `PathLike[Any]`), but in their stub they could be more precise (as long as their implementation matches that).

2. Someone writes a function that takes a `PathLike`. This should never use `PathLike[str]` or `PathLike[bytes]`, they should always use `PathLike`, `PathLike[Any]` (these two mean the same thing), or `PathLike[AnyStr]`. So outside stubs their only choice would be `PathLike` which also seems fine, at least in the short term.

All this makes me think there isn't a lot of use for having this in typing.py.

**Comment by JelleZijlstra** [comment]
Regarding your point 2, `pathlib.Path` actually doesn't take bytes paths, so it accepts only `Union[str, PathLike[str]]`. Therefore, APIs that use pathlib internally may also need to specify `PathLike[str]`.

**Comment by gvanrossum** [comment]
Oh, eeuw. That's nasty. Maybe I can add that to the branch I'm currently working on.

**Pull request merged**
