### PR TITLE
Add missing attributes to `contextlib._(Async)GeneratorContextManager`

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hmm, well mypy's support of `ParamSpec` is still far from perfect, judging by that diff.

**Comment by AlexWaygood** [comment]
I have no idea what those pytype errors mean.

**Comment by rchen152** [comment]
I don't see any obvious issues in how _P is being used here, so the test failure is likely due to a bug in pytype - sorry about that! I'll take a look, but it'll be at least a week before a fix is released, since we're currently in a holiday freeze.

**Comment by AlexWaygood** [comment]
> I don't see any obvious issues in how _P is being used here, so the test failure is likely due to a bug in pytype - sorry about that! I'll take a look, but it'll be at least a week before a fix is released, since we're currently in a holiday freeze.

Of course, no worries!!

**Comment by AlexWaygood** [comment]
I've taken out the use of `_P` for now, so that this is mergeable — the more precise types can always be added later if the pytype/mypy errors are fixed 🙂

**Review by srittau — APPROVED** [review]

**Comment by rchen152** [comment]
I figured out why pytype was erroring here! The ParamSpec attribute for keyword args is called `kwargs`, but this PR was using `kwds`. The next pytype release will change pytype's error message from that weird "Can't find pyi for '_P'" to "Unrecognized ParamSpec attribute: kwds", which I think should be much clearer.

**Comment by AlexWaygood** [comment]
@rchen152 oh wow, I feel like such an idiot 🤦 thanks so much for looking into it !!

**Pull request merged**
