### PR TITLE
Use AsyncResult from multiprocessing.pool

### PR DESCRIPTION
**Pull request by Sterbic**
The `multiprocessing.__init__` is using AsyncResult from the wrong module, `multiprocessing` instead  of `multiprocessing.pool`. This leads to the following problem:

```
import time
from multiprocessing import Pool
from multiprocessing.pool import AsyncResult
from typing import List

def pool_func():
    time.sleep(5)

def check_results(results: List[AsyncResult]):
    for r in results:
        if r.ready():
            print("ready")

N_PROCESSES = 2
pool = Pool(N_PROCESSES)

results = [pool.apply_async(pool_func) for i in range(N_PROCESSES)]
check_results(results)
```

Mypy error: `test.py:21: error: Argument 1 to "check_results" has incompatible type List[AsyncResult]; expected List[AsyncResult]`

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Looks good, I'll merge once tests pass.

**Comment by matthiaskramm** [comment]
It looks like Travis is a bit behind with its queue. This PR has been opened over an hour ago, but testing hasn't even started yet.

**Comment by JelleZijlstra** [comment]
I suppose I'm sending too many PRs.

**Comment by Sterbic** [comment]
The one I send earlier today took even longer: #1314

**Pull request merged**
