### PR TITLE
run stubtest on python 3.10 (attempt 2)

### PR DESCRIPTION
**Pull request by Akuli**
Previous attempt #5305 was reverted, will have to fix its problems before merge:
- [x] github api rate error: #5308 (#5322 should help)
- [x] running with an older alpha, so was getting in the way of changes
- [x] Use fixed Python 3.10 version to ensure that "the level of breakage isn't too high"
- [x] problems with unused: will things need to be removed from py3_common?
    - [x] should this move out of py3_common.txt? `collections.Callable  # Some typecheckers need this as specialform`
- [x] delete unused entries

We should also change positional-only test to use Python 3.10, but I think we should do that in a separate PR once this PR is merged.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
The Github API rate limit should be a mypy_primer comment thing, not a stubtest thing

**Comment by hauntsaninja** [comment]
re: Python 3.9, I just meant python3.9-dev proved to be somewhat unstable for a while, even post-beta, so it kept breaking our CI on master.

**Comment by Akuli** [comment]
I guess we could use a specific version?

**Comment by Akuli** [comment]
>The Github API rate limit should be a mypy_primer comment thing

Both Python 3.10 stubtests failed on master with an API rate error, presumably because they make more requests when installing a not-cached version of Python. All other stubtests worked.

**Comment by Akuli** [comment]
Waiting for Python 3.10 beta1, should be released today

**Comment by Akuli** [comment]
Using a fixed beta version (instead of something that changes frequently) should be fine:
- Because it is a fixed version, tests shouldn't fail on master if they pass in a pull request
- Because it is a beta version, no new features will be added

**Comment by Akuli** [comment]
I think I addressed all problems pointed out when the previous attempt was reverted

**Review by srittau — APPROVED** [review]
LGTM, but I'll defer to @hauntsaninja's opinion about this.

**Review by hauntsaninja — APPROVED** [review]
Thanks, looks good!

**Comment by hauntsaninja** [comment]
I just triggered a remove unused entries workflow, so any issues lurking or caused by merge race to master should surface

**Pull request merged**
