### PR TITLE
In TextIO, 'errors' is Optional

### PR DESCRIPTION
**Pull request by TrueBrain**
In io.pyi `errors` is defined as `Optional[str]`, but in typing.pyi it is defined as `str`.

### CODE REVIEW

**Comment by TrueBrain** [comment]
It reads to me typing.pyi has a close relation to the typing repository. I am unsure if you would like a PR in the typing repository too related to this issue.

If you rather have all 'errors' to be `str`, I can fix it that way too of course :)

**Comment by gvanrossum** [comment]
Hm, we need to fix this in typing.py too. Can you submit a PR there? (https://github.com/python/typing) And can you please double-check if any of the other methods should have optional results or args?

**Comment by TrueBrain** [comment]
Done (https://github.com/python/typing/pull/317).
I checked but didn't find any other issues with Optional, not around TextIO nor with class variables inheritance.

**Comment by gvanrossum** [comment]
OK, however, this still needs to be done for Python 2 too. (Somehow, the Python 2 backport of typing.py in the typing repo has no return type for errors; but the typeshed stub for Python 2 does.)

**Comment by TrueBrain** [comment]
I cannot find where there is an `errors` variable in Python 2 typeshed files? Only in an ``__init__`, but that seems unrelated? (I can fully misunderstand the situation in these stubs)

**Comment by gvanrossum** [comment]
Is this not it? https://github.com/python/typeshed/blob/5a2a46d3bd43f5fffb9a6216fe6dedf59ce2f7a1/stdlib/2/typing.pyi#L278

**Comment by TrueBrain** [comment]
I hereby resign my grep rights. Tnx, and fixed :)

**Comment by gvanrossum** [comment]
No problem.

If you want the mypy PR to pass, you'll have to add a "sync typeshed" commit to it.

**Pull request merged**
