### PR TITLE
Bump pyright to 1.1.315

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by AlexWaygood** [comment]
With the latest update, pyright is failing on a bunch of our test cases for openpyxl descriptors. @Avasam, could there be a bug in our openpyxl stubs/tests, or do you think this may be a pyright regression? :)

**Comment by Avasam** [comment]
If it ain't too much of a hurry I'll take a deeper look at it tomorrow. There's two specific descriptors failing, and only for setters tests.
If this was a regression I'd expect more than that.

Maybe I didn't override the `__set__` correctly.

**Comment by AlexWaygood** [comment]
> If it ain't too much of a hurry I'll take a deeper look at it tomorrow.

No hurry at all, take your time!!

**Comment by Avasam** [comment]
There you go: #10356

**Pull request closed without merging**
