### PR TITLE
Use Literal for statistics.quantiles()

### LINKED ISSUE #7462: Use Literal for statistics.quantiles()
Replace `method: str` with `method: Literal["inclusive", "exclusive"]`.

See:  https://github.com/python/typeshed/blob/6c967d4202bb3bca716ded414f3c4ebd56f4cd21/stdlib/statistics.pyi#L105

### PR DESCRIPTION
**Pull request by Akuli**
Fixes #7462

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]
Looks good. I don't think #7258 needs to block this.

**Comment by hauntsaninja** [comment]
"Prefer false negatives over false positives" would imply we shouldn't do this without a fallback overload right? Esp given that there are false positives in practice^

**Review by AlexWaygood — APPROVED** [review]
I think this is a good change to make. The one false positive is very easily fixed. https://github.com/python/typeshed/issues/7258 is a temporary moratorium on literal constants, not on literal argument types.

**Comment by AlexWaygood** [comment]
Shoot, I screwed up the commit description a bit there. Apologies :)

**Comment by Akuli** [comment]
It happens :) It's not super critical with stdlib stubs anyway. With third-party stubs, this matters more because commit messages turn into an auto-generated changelog.

**Pull request merged**
