### PR TITLE
Coroutine functions should return Generator type

### PR DESCRIPTION
**Pull request by telendt**
Any function decorated with `@coroutine` should return `Generator` type. I checked most of them, and indeed, they use `yield from`.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thank you, thank you, thank you!

**Comment by telendt** [comment]
You're welcome!

**Comment by JelleZijlstra** [comment]
This broke some of my code after today's mypy release came out that incorporates this change. Here is a simple reproducer:

```
$ cat mypytest.py 
import asyncio


ev = asyncio.Event()

async def f() -> None:
    reveal_type(ev.wait())
    await asyncio.wait_for(ev.wait(), timeout=1)
$ python3 -m mypy mypytest.py 
mypytest.py:7: error: Revealed type is 'typing.AwaitableGenerator[Any, void, builtins.bool, typing.Generator[Any, void, builtins.bool]]'
mypytest.py:8: error: Argument 1 to "wait_for" has incompatible type AwaitableGenerator[Any, None, bool, Generator[Any, None, bool]]; expected "Union[Generator[Any, None, None], Awaitable[None]]"
```
This code is correct, and reverting `asyncio.Event.wait()` to return `bool` fixes the mypy error. Maybe the type of `@coroutine` needs to change, or we may need to special case it (further?) inside mypy.

**Comment by gvanrossum** [comment]
Can you file this regression as a separate bug? I'm thinking the problem is mypy's treatment of `AwaitableGenerator` (search for it in checker.py and checkexpr.py).

**Comment by JelleZijlstra** [comment]
Thanks, I'll do that. I'll also set up something to check my code against mypy and typeshed master so I can catch this sort of thing faster in the future.

**Pull request merged**
