### PR TITLE
Make FunctionType and MethodType Callable.

### PR DESCRIPTION
**Pull request by carljm**
Currently instances of `FunctionType` and `MethodType` do not satisfy `Callable`.

### CODE REVIEW

**Comment by ambv** [comment]
This would be useful to ensure that arguments/variables typed with FunctionType or MethodType are considered callable. However, this innocent change triggers a flurry of mypy failures since it considers "Callable" in that .pyi an invalid type. @JukkaL, why is this happening?

**Comment by gvanrossum** [comment]
Callable is not a real class and you can't inherit from it.

**Comment by carljm** [comment]
I guess this will wait for protocols, then.

**Comment by ambv** [comment]
Was the error you were seeing the same when using collections.abc.Callable instead?

**Comment by carljm** [comment]
Reopened so you can see the errors I see when using collections.abc.Callable. Not sure what's going on, haven't put much time into investigating, and I don't plan to; it's a problem that's easy to work around for now with a `cast()`, and protocols is a better and more thorough long-term fix anyway.

**Comment by JelleZijlstra** [comment]
Sounds like this is a problem with the initial import cycle; types, builtins, and typing are all interdependent and changing the way they depend on each other is prone to confusing mypy.

**Comment by gvanrossum** [comment]
No, you really can't inherit from Callable. E.g.
```
from typing import Callable
class C(Callable):
    def __call__(self, *a, **k): pass
```
gives the error
```
__tmp__.py:2: error: Invalid base class
```

**Pull request closed without merging**
