### PR TITLE
Bump pyright to 1.1.126, enable 3.10 testing

### PR DESCRIPTION
**Pull request by jakebailey**
Pyright hasn't been updated in a while; update it.

Enable testing 3.10 with pyright; there have been some changes in typeshed recently for 3.10 that should be getting checked. We don't actually need 3.10 to be out to check these.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks for this!

Stubtest is failing in CI because of changes to its own source; I might have some time later today to update the whitelists accordingly (cc @hauntsaninja).

**Comment by jakebailey** [comment]
Ah, I was wondering why it'd break but HEAD is okay. No worries.

**Comment by hauntsaninja** [comment]
Oh right, sorry. Forgot that we unpinned mypy because of modular typeshed. (Can pick up tonight/tomorrow if you don't get to it first)

**Comment by hauntsaninja** [comment]
https://github.com/python/typeshed/pull/5155 for fixing CI

**Comment by jakebailey** [comment]
I think things are working now; I'm unfortunately not an org member so can't click the button myself. 🙂

**Review by JelleZijlstra — APPROVED** [review]
I'll merge once CI is all green

**Pull request merged**
