### PR TITLE
Fix type for reduce

### PR DESCRIPTION
**Pull request by sid-kap**
So this still isn't technically correct, since when the initial value is given, the type should be
```
(t -> s -> t) -> [s] -> t -> t
```
but when the initial value isn't given, it should be
```
(t -> t -> t) -> [t] -> t
```
since in this case we assume the first value in the list is the initial value, and thus `s` must equal `t` in this case. 

In any case, the number of arguments in the `Callable` was definitely wrong earlier, since it must take two arguments.

Is there a way to specify different type signatures for different versions of the function that take different numbers of arguments?

### CODE REVIEW

**Comment by sid-kap** [comment]
Okay, it seems like an `@overload` annotation is the correct way to do this. I added this, so this should be good to go.

**Comment by gvanrossum** [comment]
Looks good, but can you also update the reduce() signature for Python 2 (in stdlib/2/builtins.pyi)?

PS. Please never use Haskell types again here. It gave me a headache. ;-)

**Comment by sid-kap** [comment]
There's one last thing about this that I want to ask about. The python2 version takes an `Iterable`, while the python3 version takes an `Iterator`. Is this correct, or should one of these be changed?

**Comment by gvanrossum** [comment]
Oh, it should be Iterable. It would be silly if reduce() forced you to
create an iterator if you wanted to use it on a list.

**Comment by sid-kap** [comment]
Fixed!

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
