### PR TITLE
Set return type of Match.__getitem__ to Optional[AnyStr]

### LINKED ISSUE #5546: Incorrect annotation for Match.__getitem__
[The annotation for `typing.Match.__getitem__`](https://github.com/python/typeshed/blob/9795bae6f7bca95efcc96a7b470c92d0ad2b9e4e/stdlib/typing.pyi#L578) states that it returns an `AnyStr`.  However, it can also return `None` when the specified group was not captured.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #5546.

### CODE REVIEW

**Comment by srittau** [comment]
This probably has the same problems as outlined in #3902, although the primer run will be interesting.

**Comment by JelleZijlstra** [comment]
Interesting, the primer output is less bad than I'd expect.

**Comment by Akuli** [comment]
#5528 is similar. I think we should make all the grouping methods (at least `group`, `groups`, `__getitem__`) consistent with each other, instead of fixing them one by one in one-line pull requests.

**Comment by hauntsaninja** [comment]
+1 to Akuli's point. To the extent that we trust mypy primer, it'll also let us see the damage in a single PR. I also do seem to recall us having made changes along these lines and having to revert them based on Dropbox's experience.

**Comment by srittau** [comment]
Superseded by #5557. Thank you for the PR, this was quite useful for figuring out the best way forward.

**Pull request closed without merging**
