### PR TITLE
Make Enum Iterable (etc.) only structurally

### PR DESCRIPTION
**Pull request by elazarg**
Should fix python/mypy#3210 and python/mypy#3349

Remove `Iterable`, `Reversible` and `Container` from being (nominal) baseclasses of `Enum`.

### CODE REVIEW

**Comment by elazarg** [comment]
How should I add a test for this?

**Comment by ilevkivskyi** [comment]
There is one small warning, pytype and PyCharm may be not ready for this. (_In principle_ it should be possible to fix this in mypy by modifying nominal constrain inference to make it more like structural, but I am not really proposing this since I don't have time to implement this in nearest future.)

**Comment by JelleZijlstra** [comment]
@elazarg typeshed doesn't currently have tests for specific stubs. There is an issue for adding it. In the meantime, could you share files you tested with mypy and their output?

@matthiaskramm @vlasovskikh are you OK with this change (which depends on protocols) for mypy and pycharm?

**Comment by elazarg** [comment]
```python
from enum import Enum
from typing import Container, Iterable, Reversible, TypeVar
T = TypeVar('T')

class E(Enum):
    one = 1

reveal_type(list(E))  # E: Revealed type is 'builtins.list[E*]'
reveal_type(iter(E))  # E: Revealed type is 'typing.Iterator[E*]'
reveal_type(reversed(E))  # E: Revealed type is 'typing.Iterator[E*]'
reveal_type(x for x in E)  # E: Revealed type is 'typing.Iterator[E*]'
for a in E: reveal_type(a)  # E: Revealed type is 'E*'

x: Container[E] = E
y: Iterable[E] = E
z: Reversible[E] = E

def c(x: Container[T]) -> T: raise Exception
def it(x: Iterable[T]) -> T: raise Exception
def re(x: Reversible[T]) -> T: raise Exception
reveal_type(c(E))  # E: Revealed type is 'Any'  # Bad; see below
reveal_type(it(E))  # E: Revealed type is 'E'
reveal_type(re(E))  # E: Revealed type is 'E'
```
`Container` does not seem to be suitable for inference as a protocol, since the signature of `__contains__` accepts `Any`. Maybe I should keep it as an explicit base class.

(And maybe `Container` should not be generic in the first place?)

**Comment by ilevkivskyi** [comment]
Situation with ``Container`` is a topic of a separate issue: mypy infers ``UninhabitedType`` if there are no constraints, see https://github.com/python/mypy/issues/3032

**Comment by elazarg** [comment]
@JelleZijlstra given the bad tests in the updated results, this PR should not be merged yet. I'd like to keep this open as a WIP though. I wonder why the assignments does not fail.

**Comment by elazarg** [comment]
@ilevkivskyi do you have any hint as to why `x: Iterable[A] = MyEnum` will not fail?

**Comment by ilevkivskyi** [comment]
This may be a problem in ``bind_self``. I also realized that there is only one small test in mypy for protocols that use self-types of the form ``Type[T]``. It makes sense to open an issue for this on mypy tracker.

**Comment by ilevkivskyi** [comment]
@elazarg Yes, it looks like the fix is very simple, ``bind_self`` assumes that ``Type[T]`` can appear only in class methods, replacing ``is_classmethod`` with ``is_classmethod or isinstance(original_type, Instance) and original_type.type.is_metaclass()`` fixes the problem, I get:
```
Incompatible types in assignment (expression has type "Type[E]", variable has type "Iterable[str]")
```

**Comment by ilevkivskyi** [comment]
Hm, but then I get other spurious errors, so the actual fix will be a bit more complex, but I think this is the right direction.

**Comment by elazarg** [comment]
Thanks. I think I will open an issue about this.

**Comment by vlasovskikh** [comment]
@JelleZijlstra PyCharm doesn't support protocols yet, but we will support them eventually, so this change is OK.

**Pull request merged**
