### PR TITLE
Replace overloads in `os.path` stubs with Unions of TypeVars

### PR DESCRIPTION
**Pull request by FichteFoll**
Support for this has been added in a recently merged mypy PR (https://github.com/python/mypy/pull/14396) and this commit makes full use of it, getting rid of all overloads in the `os.path` stubs.

Continues the efforts of https://github.com/python/typeshed/pull/2053 (and the previous attempts referenced there).

Introduces a new TypeAlias `GenericOrLiteralPath` and replaces  functions of the following styles:

```py
@overload
def a(path: PathLike[AnyStr]) -> AnyStr: ...
@overload
def a(path: AnyStr) -> AnyStr: ...

@overload
def b(path: PathLike[AnyStr]) -> AnyStr: ...
@overload
def b(path: AnyOrLiteralStr) -> AnyOrLiteralStr: ...
```

with:

```py
def a(path: GenericPath[AnyStr]) -> AnyStr: ...
def b(path: GenericPath[AnyOrLiteralStr]) -> AnyOrLiteralStr: ...
```

Note that quite unexpectedly running `mypy_test.py` does not result in a failure on the latest stable locally and I don't know why (at least not at this time of day), so running against CI to find out more.

Related: https://github.com/python/mypy/issues/12554

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Note that mypy doesn't support LiteralString (it currently mostly just treats it like str), so PRs like this will need careful testing with pyright

**Comment by FichteFoll** [comment]
Fails in pyright. I'll take a look tomorrow on how to setup a pyright environment for me to test locally.
https://github.com/python/typeshed/actions/runs/3864921546/jobs/6588076084#step:7:30

**Comment by FichteFoll** [comment]
Problems have been addressed. 

What remains to be tested is how/whether a `LiteralString` is properly transferred into the return type because the `AnyStr` (or `AnyStr_co`) type var(s) used in `GenericPath` are restricted to `str` and `bytes` respectively, but from shallow thinking a `LiteralString` should satisfy this.

**Comment by FichteFoll** [comment]
None of the things noted by mypy_primer seem to be relevant to the changes in this PR.

**Comment by JelleZijlstra** [comment]
The streamlit and pytorch changes are definitely not unrelated: they're the direct result of changes made by this PR. What seems to be going on is that mypy now infers Any for cases where it previously inferred a non-Any type, which means that this PR would cause a regression.

**Comment by FichteFoll** [comment]
Right, it appears to be the same issue as with werkzeug where the typevar is infered to `Any`.

Unfortunately I have no idea to time to figure out how to proceed with this, for the moment at least.

**Comment by AlexWaygood** [comment]
This has a lot of merge conflicts now, and it doesn't look like maintainers have been given permission to push to the PR branch, so I can't resolve them. As such, I'm closing this as stale for now -- but feel free to open a new PR if you'd like to fix the conflicts and see what `mypy_primer` looks like now that mypy 1.1.1 is out.

**Pull request closed without merging**
