### PR TITLE
Remove invalid Python 3 syntax

### LINKED ISSUE #83: invalid syntax in builtins
The [PEP 484 section on stub files](https://www.python.org/dev/peps/pep-0484/#stub-files) says that stub files have the same syntax as Python files.  Typeshed conforms to this spec except in [one place](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L608) in `builtins.pyi`:
```python
True = ...  # type: bool
False = ...  # type: bool
__debug__ = False
```
This is a "can't assign to keyword" syntax error.

I propose we remove these three lines from typeshed to make it PEP 484 compliant.  This means that type checkers will have to hard code their knowledge that `True`, `False`, and `__debug__` are `bool`s, which seems reasonable.

### PR DESCRIPTION
**Pull request by ddfisher**
Fix #83.

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Could you put a prominent comment into stdlib/2/builtins.pyi that True and False have been deliberately left out?

**Comment by ddfisher** [comment]
That seems like a good idea -- added.

**Comment by matthiaskramm** [comment]
Thanks! Let me know if you want me to merge the PR. I take it mypy needs to be adjusted, too.

**Comment by ddfisher** [comment]
Yeah, mypy will need to be adjusted.  I have a PR out for that [here](https://github.com/python/mypy/pull/1218), that should be pretty much ready to merge after this change.

I guess the CI build will just have to fail in the meanwhile?

**Comment by ddfisher** [comment]
If that seems reasonable, please merge. :)

**Comment by matthiaskramm** [comment]
Merging.

**Pull request merged**
