### PR TITLE
Add __class_getitem__ to builtins generified in PEP 585

### PR DESCRIPTION
**Pull request by east825**

### CODE REVIEW

**Comment by east825** [comment]
I'm not sure about the exact types, though. It's not possible to express the type of an arbitrary PEP 484 compliant type hint expression that `__class_getitem__` can accept, so I favor `Any` for it. However, technically, the implementation allows any value to be passed, e.g. `list[42]`, so probably it should have been `object` instead according to CONTRIBUTING.md. The return type for such an intrinsic method is also not that obvious.

I'm all ears on how to declare those properly!

**Comment by JelleZijlstra** [comment]
Thanks! I'm not sure the types on this method matter a lot in practice because type checkers will surely special-case this method anyway.

The actual return type of this methods is `types.GenericAlias`, so probably it'd be better to mark that as the return type in the stub too. I'm fine with `Any` for the argument type.

**Comment by east825** [comment]
Ok, makes sense! Returning `GenericAlias` will make special handling mandatory., i.e. it won't be possible to understand that the result of `list.__class_getitem__(int)` is at least something that has the interface of the normal `list` class. On the other hand, it will be easier to tell when `__class_getitem__` is used to emulate extending from `typing.Generic`. Hopefully, there won't be many other use cases for it, though.

However, `types.GenericAlias` is not present in `typeshed` too at the moment and seems even trickier to annotate properly. `stubgen` helpfully deduces `GenericAlias: Any`. Considering [its implementation](https://github.com/python/cpython/blob/master/Objects/genericaliasobject.c), I can put something like: 

```
if sys.version_info >= (3, 9):
    class GenericAlias:
        __origin__: Any
        __args__: Tuple[Any, ...]
        __parameters__: Tuple[Any, ...]
        def __init__(self, origin: type, args: Any): ...
        def __getattr__(self, name: str) -> Any: ...  # incomplete
```
in types.pyi. What do you think of it? Is it beneficial to go further in describing its interface?

**Comment by east825** [comment]
For instance, should `__origin__` be `Any` (closer to the implementation) or `type` (closer to the intended use)?

**Comment by east825** [comment]
@JelleZijlstra Ping :) Pushed as described in my comment above. Ready for further steering)

**Pull request merged**
