### PR TITLE
Use `TypeIs` is for `iscoroutinefunction`

### PR DESCRIPTION
**Pull request by max-muoto**
Use `TypeIs` for `iscoroutinefunction` to provide more accurate types in the negative case.

https://github.com/python/typeshed/issues/8009#issue-1256762216 talks about former issues with the negative cases before `TypeIs`.

### CODE REVIEW

**Comment by max-muoto** [comment]
@JelleZijlstra It seems in this case:

```python
if iscoroutinefunction(z):
    assert_type(z, Callable[[str, int], Coroutine[Any, Any, Any]])
```

The intersection type `"(str, int) -> (str | Awaitable[bytes])"` we now get is less accurate, since we know it's not awaitable. Curious if you have any thoughts or potential workarounds, since it would be a little bit of a regression.

**Comment by JelleZijlstra** [comment]
This is incorrect because `iscoroutinefunction()` does not (and cannot) return True for all callables that return a `Coroutine`.

**Comment by max-muoto** [comment]
> This is incorrect because `iscoroutinefunction()` does not (and cannot) return True for all callables that return a `Coroutine`.

I see, closing this out then!

**Comment by jmehnle** [comment]
Eeeek, does this mean that despite `TypeIs` we _still_ don't have a solution for totally narrowing types in `if inspect.iscoroutinefunction(f): ...` / `else: ...` constructs?

**Pull request closed without merging**
