### PR TITLE
Add default values for third-party stubs beginning with 'P'

### PR DESCRIPTION
**Pull request by AlexWaygood**
We have a lot of stubs beginning with 'P'!

I skipped `pycurl` (couldn't install it locally) and `python-xlib` (@Avasam did it just the other day in #9642).

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hmm, looks like there might be a pyright bug here. For now, I'll just revert the defaults that pyright is complaining about, and I'll file an issue over at pyright later.

**Comment by Avasam** [comment]
I can check pycurl if you want. I still have my mid-2009 macbook pro I patched and upgraded for this exact reason.
The installation is a bit complex, but documented in METADATA.toml

For linux, it's a lot simpler.

Windows you need to build from source. But you wan use WSL. If you use VSCode there's https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl you can use to even straight up have all your tools in VSCode think you're on Linux (including os-specific intellisense and whatnot)

**Comment by AlexWaygood** [comment]
> I can check pycurl if you want. I still have my mid-2009 macbook pro I patched and upgraded for this exact reason.
> The installation is a bit complex, but documented in METADATA.toml

Ah, that would be great if you could, thank you!

**Review by srittau — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> > python-xlib (@Avasam did it just the other day in #9642).
> 
> I think that was before more defaults were allowed. stubdefaulter adds a couple more tuple and dict defaults now

'Kay, I'll do it in a followup PR (or you can if you like!)

**Comment by AlexWaygood** [comment]
> Hmm, looks like there might be a pyright bug here. For now, I'll just revert the defaults that pyright is complaining about, and I'll file an issue over at pyright later.

- https://github.com/microsoft/pyright/issues/4856

**Pull request merged**
