### PR TITLE
Correct return type of `asynccontextmanager` in 3.10

### LINKED ISSUE #6625: AsyncContextManager is not callable error when used as decorator
**Bug Report**

It apprears that mypy is not aware that starting with Python 3.10 async context managers created using `contextlib.asynccontextmanager` can be used as decorators.

**To Reproduce**

The following is example code from the Python docs for [`contextlib.asynccontextmanager`](https://docs.python.org/3/library/contextlib.html#contextlib.asynccontextmanager). Running mypy against it results in the error included below the code.

```python
import time
from contextlib import asynccontextmanager


@asynccontextmanager
async def timeit():
    now = time.monotonic()
    try:
        yield
    finally:
        print(f"it took {time.monotonic() - now}s to run")


@timeit()
async def main():
    pass
```

```
$ mypy example.py
example.py:14: error: "AsyncContextManager[Any]" not callable
Found 1 error in 1 file (checked 1 source file)
```

**Expected Behavior**

The example code should type check without problems on Python 3.10+

**Actual Behavior**

Mypy complains that the context manager is not callable.

**Your Environment**

- Mypy version used: 0.920
- Mypy command-line flags: None
- Mypy configuration options from `mypy.ini` (and other config files): None
- Python version used: 3.10.1
- Operating system and version: macOS 10.15.7

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #6625 (I think)

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Review by srittau — APPROVED** [review]
There's also a `_GeneratorContextManagerBase` base class for both `_GeneratorContextManager` and `_AsyncGeneratorContextManager` (on Python 3.9), which is worth considering for a future PR.

**Comment by AlexWaygood** [comment]
> There's also a `_GeneratorContextManagerBase` base class for both `_GeneratorContextManager` and `_AsyncGeneratorContextManager` (on Python 3.9), which is worth considering for a future PR.

Well, I had a go. You can see the results in [a branch over here](https://github.com/AlexWaygood/typeshed/commit/fd74044f72b1c98a4c493f8990a5d1c922d9e368) -- but I'm not really sure it's worth worrying about, since it seems like it breaks mypy :/ 

Even after adding 5 `# type: ignore`s I get

> stdlib\contextlib.pyi:50: error: INTERNAL ERROR -- Please try using mypy master on Github

when I try to run mypy on it.

**Comment by hauntsaninja** [comment]
Do you have a full stack trace on hand?

**Comment by JelleZijlstra** [comment]
For what it's worth, I don't think it's too important to add the `_GeneratorContextManagerBase` base class since it's private and provides no public methods.

**Comment by AlexWaygood** [comment]
> Do you have a full stack trace on hand?

Here's a full traceback:

```
(.venv3) C:\Users\Alex\Desktop\Code dump\typeshed>mypy test.py --custom-typeshed-dir . --tb
stdlib\contextlib.pyi:49: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.920
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "mypy\semanal.py", line 4990, in accept
  File "mypy\nodes.py", line 959, in accept
  File "mypy\semanal.py", line 1078, in visit_class_def
  File "mypy\semanal.py", line 1100, in analyze_class
  File "mypy\semanal.py", line 1330, in clean_up_bases_and_infer_type_variables
AssertionError: mypy does not currently support ParamSpec use in generic classes
stdlib\contextlib.pyi:49: : note: use --pdb to drop into pdb
```

- Python version: 10.1
- mypy version: 0.920
- Command run: `mypy test.py --custom-typeshed-dir . --tb` (`test.py` being an empty file in the root folder of my typeshed clone).

**Comment by hauntsaninja** [comment]
Okay, so should be fixed come 0.930

**Comment by ljodal** [comment]
> Fixes #6625 (I think)

I can confirm that it fixes the issue in my codebase. Thanks for the fix! 🙌

**Pull request merged**
