### PR TITLE
binhex: improve bytes handling

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/python/cpython/blob/85f88f63d96b07208c98a725391af7cb710fe06b/Lib/binhex.py#L216-L234

Both `write` and `write_rsrc` calls `io.open(..., 'wb').write(data)`

### CODE REVIEW

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
Looks like it calls `len`. I'd say we should add a `_BufferWithLen: TypeAlias = ReadableBuffer` to `_typeshed` (or at least add a comment). This would have been useful in at least one other place

**Review by hauntsaninja — APPROVED** [review]
Thanks!

**Comment by AlexWaygood** [comment]
> Looks like it calls `len`. I'd say we should add a `_BufferWithLen: TypeAlias = ReadableBuffer` to `_typeshed` (or at least add a comment). This would have been useful in at least one other place

I agree with adding this, but why the leading underscore, out of interest?

**Comment by hauntsaninja** [comment]
Oh, I don't remember exactly what rules we have for `_typeshed`, but I wanted to mark as "private / experimental / do not use"... The type doesn't really correspond to its name, it's currently incorrectly typed (e.g. since `ReadableBuffer` includes `pickle.PickleBuffer`), we don't know the fate of PEP 688, etc.

**Comment by sobolevn** [comment]
> but I wanted to mark as "private / experimental / do not use"...

+1

**Comment by AlexWaygood** [comment]
Cool, that makes sense!

**Pull request merged**
