### PR TITLE
Convert typing.ContextManager.exit to use dunder parameter names

### PR DESCRIPTION
**Pull request by mrkmndz**
This means that the stubs as written for `unittest.mock._patch.__exit__`, `unittest.mock._patch_dict.__exit__` and the third party variants of these no longer successfully conform to `typing.ContextManager` because they are written only to accept positional arguments, and `typing.ContextManager` accepts arguments by name.  

There are three alternatives to fix this:
1. [SELECTED] Convert `typing.ContextManager.exit` to 
```
def __exit__(self, __exc_type: Optional[Type[BaseException]],
                 __exc_value: Optional[BaseException],
                 __traceback: Optional[TracebackType]) -> Optional[bool]: ...
```
This seems problematic given that one could imagine a caller wanting to refer to these by name to avoid confusion.  However, this would solve the problem more generally, as a survey of typeshed shows many `__exit__` methods with the wrong names. 
2. Convert  `unittest.mock._patch.__exit__` etc. to be `*args: Any, **kwargs: Any`.  This seems to have been the original intention, but I think we can be more precise.
3. Convert  `unittest.mock._patch.__exit__` etc.  to match `typing.ContextManager` exactly.  This kicks the can down the road for the other classes that also don't match.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Would it also solve your problem if we marked the arguments to `__exit__` in the protocol positional-only? I'd prefer that because the runtime implementation of these mock functions actually takes `*exc_info`, and I can easily imagine people calling `patcher.__exit__()` directly.

**Comment by mrkmndz** [comment]
I was considering it, but was just concerned about people calling this function by name.
Are you saying it should be
```
def __exit__(self, __exc_type: Optional[Type[BaseException]] = None,
                 __exc_value: Optional[BaseException] = None,
                 __traceback: Optional[TracebackType] = None) -> Optional[bool]: ...
```
?

**Comment by JelleZijlstra** [comment]
My suggestion is to leave mock unchanged and instead change `typing.pyi` to make the `ContextManager.__exit__` take three required, positional-only arguments. That way, a class with `__exit__(self, *exc_info)` would still be a subtype of `ContextManager`.

**Comment by mrkmndz** [comment]
Cool, if that's good with you, that definitely good with me.

**Comment by mrkmndz** [comment]
What is the timeline for getting this merged?

**Pull request merged**
