### PR TITLE
Annotate known magic method return types

### PR DESCRIPTION
**Pull request by sobolevn**
I was pretty careful to include only 100% ones.

### CODE REVIEW

**Review by srittau — APPROVED** [review]
There might be some cases, where the dunder method does something strange in the implementation, but as long as primer passes, I think this situation is better than the alternative and potential problems can be fixed when they come up.

**Review by AlexWaygood — APPROVED** [review]
This is great, thank you!

**Comment by sobolevn** [comment]
Looks like I need to fix metaclasses of many projects.

@srittau can you please trigger `daily` task? I don't have permissions in this repo to do that.

**Comment by AlexWaygood** [comment]
@sobolevn it already failed last night: #9127

**Pull request merged**
