### PR TITLE
[XML] iterparse fix

### PR DESCRIPTION
**Pull request by gaborbernat**
[XML] iterparse is None for end-ns, Tuple[str, str] for start-ns, Element otherwise

### CODE REVIEW

**Comment by gaborbernat** [comment]
any ETA/feedback for this? :+1:

**Comment by JelleZijlstra** [comment]
Sorry I didn't write anything here earlier. One piece of feedback here is that your initial message is rather cryptic, which makes it harder for me to confirm that the change is right. Ideally, PRs should include links to the relevant code and documentation, although we should probably add that to CONTRIBUTING.md.

I'm also uneasy about this change because we generally avoid Unions in return types. The reason for that is that using a Union forces users who use the return value of iterparse to do an `isinstance` check every time they do something with the return value, which is frequently annoying because the user will know what type to expect. Perhaps it's the right thing to do here though.

In this case, from https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.iterparse it seems like the type of the second tuple member is different depending on the string value of the first member, so users will probably idiomatically check the value of this string and then assume the type of the second element. Therefore, I think it makes more sense to make the type of the second element `Any` here, so people don't have to do unnecessary `isinstance` checks.

**Comment by gaborbernat** [comment]
@JelleZijlstra agreed and changed to ``Any``

**Comment by gaborbernat** [comment]
@JelleZijlstra ping on this :+1:

**Comment by JelleZijlstra** [comment]
Sorry for the delay!

**Pull request merged**
