### PR TITLE
Remove Any from asyncio.create_task()

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Provide more accurate type for yield type.

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Test failures look unrelated...

**Comment by srittau** [comment]
I find Python async terribly complex and hard to wrap my head around. (As opposed to async in other languages.) But does the generator really yield futures?

**Comment by Dreamsorcerer** [comment]
I think in the normal case, it doesn't (hence the `Optional`), but there is code in there that suggests it's possible.

This ultimately passes the coro into `Task`, which ends up reaching this code:
https://github.com/python/cpython/blob/3.9/Lib/asyncio/tasks.py#L276-L321

`result` has come from the coro yield. Most of the cases there are just showing useful error messages.
The 2 cases that appear to be allowed are `None` (line 307), and a Future with `_asyncio_future_blocking` set to True (line 291).

Although maybe it would be more accurate to use a Protocol for duck typing, as per:
https://github.com/python/cpython/blob/42d873c63aa9d160c132be4a34599531574db12c/Lib/asyncio/base_futures.py#L21

I'm not really sure under what case this occurs, but it does seem possible.

**Comment by Dreamsorcerer** [comment]
Added the annotation to `Task` as well.

**Review by srittau — APPROVED** [review]

**Pull request merged**
