### PR TITLE
protobuf: Add some return types

### PR DESCRIPTION
**Pull request by Dreamsorcerer**

### CODE REVIEW

**Review by sobolevn — COMMENTED** [review]
protobuf stubs are special: 
- https://github.com/python/typeshed/blob/main/stubs/protobuf/METADATA.toml#L2
- https://github.com/python/typeshed/blob/a7cf6144deeb3f99570f8b97fb5f5ecf16f20c01/scripts/generate_proto_stubs.sh

**Comment by AlexWaygood** [comment]
@sobolevn, you're incorrect -- only the files ending with `_pb2.pyi` are autogenerated.

**Comment by sobolevn** [comment]
Oh, I see. Sorry.

They even have `@generated by mypy-protobuf.  Do not edit manually!` headers.

**Comment by AlexWaygood** [comment]
@nipunn1313, could you possibly give this a look, if you have the time? :)

**Comment by Dreamsorcerer** [comment]
Implementation:
https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/well_known_types.py#L75-L90
https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/symbol_database.py#L195-L197

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> Implementation: https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/internal/well_known_types.py#L75-L90 https://github.com/protocolbuffers/protobuf/blob/main/python/google/protobuf/symbol_database.py#L195-L197

Heh, those are pretty easy to review

**Comment by AlexWaygood** [comment]
Thanks!

**Comment by nipunn1313** [comment]
looks good - thanks!

**Pull request merged**
