### PR TITLE
zip.__iter__ and reversed.__iter__ return self

### PR DESCRIPTION
**Pull request by JelleZijlstra**
(On 3.9)
```
>>> class X(reversed): pass
... 
>>> x = X("abc")
>>> type(x)
<class '__main__.X'>
>>> type(iter(x))
<class '__main__.X'>
>>> class Y(zip):
...     pass
... 
>>> y = Y("abc", "def")
>>> type(y)
<class '__main__.Y'>
>>> type(iter(y))
<class '__main__.Y'>
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Hold on, this isn't true if you're reversing a list (thanks @AlexWaygood):

```
% ./python3.10 -c '''class X(reversed): pass           
print(type(iter(X([1, 2, 3]))))'''
<class 'list_reverseiterator'>
```

**Comment by AlexWaygood** [comment]
I think we should make the change to `zip` but leave `reversed` as it is and add a `# noqa: Y034` comment. It will be the only Y034 `noqa` in typeshed.

**Comment by JelleZijlstra** [comment]
I looked into the C code and realized this PR is right after all. The problem isn't that `iter(reversed([]))` doesn't return a `reversed` object, it's that `reversed([])` doesn't return a `reversed` object in the first place, but a `list_reverseiterator`, because `list` implements the `__reversed__` special method. We could model that in typeshed by overloading `__new__`, but I'd like to defer that until we actually need it.

**Comment by AlexWaygood** [comment]
> I looked into the C code and realized this PR is right after all. The problem isn't that `iter(reversed([]))` doesn't return a `reversed` object, it's that `reversed([])` doesn't return a `reversed` object in the first place, but a `list_reverseiterator`, because `list` implements the `__reversed__` special method. We could model that in typeshed by overloading `__new__`, but I'd like to defer that until we actually need it.

Huh. Bizarre :)

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
