### PR TITLE
Adds `TypeGuard` to `filter`

### PR DESCRIPTION
**Pull request by sobolevn**
Couple of questsions:
1. How can I test that it works?

I was testing it with local code:

```python
from typing import Iterator, Iterable, Callable, TypeVar, Generic, TypeGuard, Any, List, Optional, overload

_T = TypeVar('_T')
R = TypeVar('R')


class filter(Iterator[_T], Generic[_T]):
    @overload
    def __init__(self, __function: None, __iterable: Iterable[_T | None]) -> None: ...
    @overload
    def __init__(self, __function: Callable[[R], TypeGuard[_T]], __iterable: Iterable[R]) -> None: ...
    @overload
    def __init__(self, __function: Callable[[_T], Any], __iterable: Iterable[_T]) -> None: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __next__(self) -> _T: ...

a: List[Optional[int]]
def is_int_typeguard(a: object) -> TypeGuard[int]: pass
cc = filter(is_int_typeguard, a)
reveal_type(cc)  # N: Revealed type is "ex.filter[Union[builtins.int, None]]"
```

2. This is the first `TypeGuard` in `builtins.pyi`, are there any extra steps?

Closes https://github.com/python/typeshed/issues/5661

### CODE REVIEW

**Comment by hauntsaninja** [comment]
IIRC at least at some point mypy treated TypeGuard exactly the same as bool, instead of as a subtype. Could be a pretty easy fix.

(Also worth noting that in typeshed's CI, we use latest mypy release instead of mypy master)

**Comment by sobolevn** [comment]
> Also worth noting that in typeshed's CI, we use latest mypy release instead of mypy master

The same happens with `master`, I've just checked.
I will open a new issue in `mypy`. I hopefully will be able to fix it. 👍

**Comment by sobolevn** [comment]
Done: https://github.com/python/mypy/issues/11307

**Comment by sobolevn** [comment]
@hauntsaninja @JelleZijlstra  any chance to get this PR merged, please? https://github.com/python/mypy/pull/11314 🙂

**Review by JelleZijlstra — APPROVED** [review]
The mypy PR got merged, thanks!

This looks good but I'm going to retrigger CI just in case.

**Comment by JelleZijlstra** [comment]
I'm a bit worried about the mypy-primer results here, I'll have to look at it more.

**Comment by JelleZijlstra** [comment]
Looking at the freqtrade ones:
- the first one does `len(list(filter(lambda x: x["name"] == searchname, columns))) == 1` where `columns: List` (they got to turn on `--disallow-any-generics`). It produces `Argument 1 to "list" has incompatible type "filter[_T]"; expected "Iterable[_T]"`. That error makes little sense to me.
- The others are around a line `roi_list = list(filter(lambda x: x <= trade_dur, self.minimal_roi.keys()))`, where `self.minimal_roi: Dict`.
- So maybe there's a bug in mypy around using `Dict`/`List` without generic arguments.

**Comment by JelleZijlstra** [comment]
Let's see if mypy got any better.

**Comment by JelleZijlstra** [comment]
Still no good. I'm guessing this is also affected by python/mypy#11428. We can reopen this once mypy's TypeGuard support improves.

**Pull request closed without merging**
