### PR TITLE
dest argument to add_argument is Optional

### PR DESCRIPTION
**Pull request by JelleZijlstra**
argparse.py checks for None in _get_optional_kwargs.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
See https://github.com/python/cpython/blob/master/Lib/argparse.py#L1476. This fixes a CI failure introduced by #1937.

**Comment by gvanrossum** [comment]
Hm, what a pain. If I sync typeshed to this (after it's been merged) and cherry-pick the sync into the release-0.590 branch, I get a whole slew of extra typeshed PRs into the bargain.

To play it safe I would have to create a typeshed release branch and cp this into that, then sync that branch into mypy. It's doable, but a bit convoluted.

OTOH perhaps I'm being overly cautious. Let me see if just syncing to typeshed HEAD (after this) breaks anything in the Dropbox codebase.

**Comment by JelleZijlstra** [comment]
For what it's worth, the PR that introduced the PR that introduced this issue (#1937) was only merged tonight too, so it's not in your release branch. So you could make a branch with just the enum fix from #2039.

**Comment by JelleZijlstra** [comment]
The Travis failure here is just because the branch I used doesn't have #2039. This PR should be safe to merge.

**Comment by gvanrossum** [comment]
Yeah, I'm going to have to cp just the fix for #2039 -- the argparse
changes do break our internal codebase, and I don't want to have to sort
that out under time pressure.

**Pull request merged**
