### PR TITLE
Use stricter `Random.seed` type

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/python/cpython/blob/09087b8519316608b85131ee7455b664c00c38d2/Lib/random.py#L128-L164

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I don't think the overloads actually help, because e.g. `seed(bytearray, 2)` will just match the fallback overload. This is one of the things that `@evaluated` could fix.

**Comment by JelleZijlstra** [comment]
Oh actually, the overloads aren't even necessary because all of these types are accepted regardless of the version. The types you specified in the overloads are just handled specially.

**Comment by sobolevn** [comment]
@JelleZijlstra if you specify `.seed(bytearray(), version=1)` - this is probably now what you want.

So, technically all `.seed()` calls with allowed types will work. But, practically, this is a mistake. `.seed(bytearray(), version=2)` is the right thing to write in this case.

**Review by hauntsaninja — COMMENTED** [review]
Thanks!

I'm not sure I understand the overloads either... `.seed(bytearray(), version=1)` will still work since `bytearray` is treated as a subtype of `bytes`.

(Recently debugged an issue where seeding was non-deterministic across Python runs because a `np.random.SeedSequence` got passed to `random.seed` and just got `hash`-ed — was quite painful. Honestly, wouldn't mind using the stricter types with `sys.version_info >= (3, 9)`, when this was deprecated)

**Comment by sobolevn** [comment]
> .seed(bytearray(), version=1) will still work since bytearray is treated as a subtype of bytes.

Oh right, because of the mypy special casing!
What about other type-checkers? Do they behave the same way? 

> Honestly, wouldn't mind using the stricter types with sys.version_info >= (3, 9), when this was deprecated

Ok 👍

**Comment by sobolevn** [comment]
After further testing, I confirm that overloads here are not required.

**Comment by hauntsaninja** [comment]
I believe all type checkers perform similar special casing, or at least, typeshed assumes that they do. It's not particularly well documented though.

**Comment by hauntsaninja** [comment]
https://docs.python.org/3/library/typing.html#typing.ByteString is probably the best reference for it

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
