### PR TITLE
literal return type for platform.system()

### PR DESCRIPTION
**Pull request by Akuli**
Fixes https://github.com/python/mypy/issues/8166 so that https://github.com/python/mypy/pull/8461 is no longer needed.

### CODE REVIEW

**Comment by Akuli** [comment]
Now that I see the mypy_primer output, I'm no longer sure about whether this is a good idea, because it now warns about `Literal["Linux"] == Literal["Windows"]`.

**Comment by JelleZijlstra** [comment]
Yes, that's unfortunate. Maybe that mypy option can be taught to not error when comparing two literals that aren't part of a union.

**Comment by srittau** [comment]
This is an interesting case. Looked at from one side, this change is correct. Looked at from another side it isn't. I would suggest for now not to use conditionals and just return `Literal['Linux', 'Windows', 'Darwin'] | str` until mypy is changed. After that, I think this PR is worth a try.

**Comment by JelleZijlstra** [comment]
Going to close this as stale for now to keep the list of open PRs manageable. If you're still interested in seeing this through, feel free to reopen or open a new PR.

**Pull request closed without merging**
