### PR TITLE
Remove `object` as the only ancestor for classes in Python 3 stubs.

### PR DESCRIPTION
**Pull request by sproshev**
```
Python 3.6.0 (default, Dec 26 2016, 16:04:47) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> object in type.__bases__
True
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Does this solve a concrete problem for you? In Python 3 all classes implicitly inherit from `object`.

**Comment by sproshev** [comment]
I did it just for consistency. See `super` definition below.
Is it better to drop `object` in both cases?

**Comment by ambv** [comment]
Yes, I think removing the spurious `(object)` would be the way to go for 3 if you care about consistency. Fortunately, there's not too many cases.

stdlib:
```
3/_markupbase.pyi:3:class ParserBase(object):
3/builtins.pyi:83:class super(object):
3/calendar.pyi:22:class Calendar(object):
3/difflib.pyi:50:class HtmlDiff(object):
3/json.pyi:53:class JSONEncoder(object):
3/json.pyi:72:class JSONDecoder(object):
3/string.pyi:28:class Formatter(object):
```

third_party:
```
3/dateutil/parser.pyi:7:class parserinfo(object):
3/dateutil/parser.pyi:30:class parser(object):
3/dateutil/parser.pyi:48:class _tzparser(object):
3/dateutil/relativedelta.pyi:7:class weekday(object):
3/dateutil/relativedelta.pyi:28:class relativedelta(object):
3.6/click/utils.pyi:60:class KeepOpenFile(object):
```

**Comment by sproshev** [comment]
I'll update `Formatter` later.

**Pull request merged**
