### PR TITLE
Make urllib2's OpenerDirector.open not optional

### PR DESCRIPTION
**Pull request by msullivan**
This is a follow-up to #2821, though maybe more controversial.  It
seems like it is more plausible that a directly instantiated opener
could actually fail to handle a request, though I'm not familiar
enough with use patterns to be sure.

This fixes a small handful of errors in a dropbox code base.
I could definitely see saying no on this one. Thoughts?

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I'm not really familiar with how this library is normally used. I would guess that using a custom handler is a feature that is theoretically available, but that in practice almost nobody uses, in which case your change would be fine. But maybe actually lots of people use a custom handler?

**Comment by srittau** [comment]
I'm also not very familiar with urllib, except for the basic usage. On the one hand, I don't know why you would want to install your own director and return `None`, on the other hand this is documented behavior. Let's maybe apply this change and revert if any bugs are reported?

**Comment by msullivan** [comment]
I'm leaning towards not merging.

**Comment by JelleZijlstra** [comment]
Closing since @msullivan doesn't seem too feel strongly in favor of merging. We can reopen this if it turns out to be a big pain.

**Pull request closed without merging**
