### PR TITLE
Rework redis/asyncio/{connection,sentinel}.pyi

### PR DESCRIPTION
**Pull request by srittau**
Closes: #10362

### CODE REVIEW

**Comment by srittau** [comment]
I have no time to look into the pytype error at the moment. @rchen152: Could have a look? Otherwise I'll try to narrow the problem down tomorrow.

**Comment by srittau** [comment]
The pytype fix was fairly straightforward: Remove the quotes around bound types from the TypeVar, which is cleaner anyway:

https://github.com/python/typeshed/pull/10370/commits/45482b5cecfc71cae0766de9b5382bcf9b46e091

**Comment by srittau** [comment]
(Test failure is a GitHub hickup, I will restart the failed test.)

**Comment by JelleZijlstra** [comment]
@srittau ping on this one.

**Pull request merged**
