### PR TITLE
Check for PEP 604 usage in CI

### PR DESCRIPTION
**Pull request by hauntsaninja**
Since this is a common review issue and our stubs have all been
converted

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I'd rather put this in flake8-pyi, I'm happy to do the merging and releasing on a PR on that repo.

**Comment by srittau** [comment]
Also, `|` doesn't work in type aliases yet, so we can't check for it, at the moment.

**Comment by srittau** [comment]
ambv/flake8-pyi#45

**Comment by hauntsaninja** [comment]
@srittau This script doesn't check type aliases (just annotated assignments, function args, function returns), so should be fine to merge if we wanted to.
@JelleZijlstra that's a good point, I'll take a look. flake8-pyi won't be able to use ast.unparse for friendly errors, but should otherwise be workable.

**Comment by JelleZijlstra** [comment]
Sounds good!

Relatedly would either of you be interested in becoming a maintainer on flake8-pyi? I don't have the power to add more maintainers but I'm sure Lukasz would be OK with that.

**Comment by hauntsaninja** [comment]
Sure!

**Comment by srittau** [comment]
I'd be glad to help out.

**Comment by ambv** [comment]
@JelleZijlstra, done! Welcome, @srittau and @hauntsaninja.

**Comment by Akuli** [comment]
@hoefling Before I saw this PR, I pinged you on another merged PR asking you to do this, but now I can't find that PR. Sorry about that.

**Pull request merged**
