### PR TITLE
Fix boto stubs.

### PR DESCRIPTION
**Pull request by gvanrossum**
Replace two `FIXME` comments with `type: ignore`.
See https://github.com/python/mypy/issues/1237.

### CODE REVIEW

**Comment by gvanrossum** [comment]
@ambv: One of the tentative conclusions of python/mypy#1237 is that adding a `# type: ignore` is actually the right thing to do for an intentional Liskov violation. The type checker will then believe the indicated type and won't complain about the mismatch in the override. (It also won't catch errors due to calling the method on an object whose run time type is the subclass but in a context where its type as known to the type checker is the base class. That's unavoidable.

**Comment by ambv** [comment]
Alright, this makes sense to me!

**Comment by gvanrossum** [comment]
Thanks! Enjoy the holidays. It's a nice day!!

**Comment by ambv** [comment]
Likewise!

**Pull request merged**
