### PR TITLE
Make `allow_redirects` optional in `requests`

### PR DESCRIPTION
**Pull request by dorianj**

### CODE REVIEW

**Comment by Akuli** [comment]
There's still a bunch of `allow_redirects` arguments annotated with just `bool`:

```
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/api.pyi:    allow_redirects: bool = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        allow_redirects: bool | None = ...,
stubs/requests/requests/sessions.pyi:        self, request: PreparedRequest, *, stream=..., verify=..., cert=..., proxies=..., allow_redirects: bool = ..., **kwargs
```

Apart from `allow_redirects`, I don't think it makes sense to change `bool` to `bool | None` everywhere where `None` is technically accepted. I assume you have some practical use case for `allow_redirects=None`.

**Comment by dorianj** [comment]
@Akuli I just want this param to be options, as the rest of the args are.

Should I extend this to all those other definition sites?

**Comment by Akuli** [comment]
Do you have a concrete use case for this, or is this only for consistency? Other params allow `None`, because the definition in requests/sessions.py is:

```python
    def request(self, method, url,
            params=None, data=None, headers=None, cookies=None, files=None,
            auth=None, timeout=None, allow_redirects=True, proxies=None,
            hooks=None, stream=None, verify=None, cert=None, json=None):
```

**Comment by dorianj** [comment]
I'm trying to call like this: `response = requests.post(url=normalized_url, data=payload, **params)`, and without this change, that callsite gets a `Argument 3 to "post" has incompatible type "**Dict[str, Dict[str, Optional[str]]]"; expected "bool"`

**Comment by dorianj** [comment]
An alternative choice here might be to default `allow_redirects` to True in the typesig? That seems less-than-preferable since that's two layers of defaults

**Comment by Akuli** [comment]
Can you show how you have defined the `params` dict?

**Comment by Akuli** [comment]
Because your `params` dict has type `Dict[str, Dict[str, Optional[str]]]`, doing `**params` in a function call will pass `Dict[str, Optional[str]]` for each argument. The type checker won't accept this any better if we allow `None`, because it thinks you're trying to pass a dict.

If you provide more context to how the `params` dict is defined, I can help you how to communicate your intent to the type checker cleanly.

**Pull request closed without merging**
