### PR TITLE
requests: Fix Response.content return type

### PR DESCRIPTION
**Pull request by holmanb**
With the following code mypy reports an unreachable statement. The Response.content property can return a type of None, so update the stub.

```python
class UrlResponse:
    def __init__(self, response: requests.Response):
        self._response = response

    @property
    def contents(self) -> bytes:
        if self._response.content is None:
            return b""
        return self._response.content
```

### CODE REVIEW

**Comment by holmanb** [comment]
> Diff from [mypy_primer](https://github.com/hauntsaninja/mypy_primer), showing the effect of this PR on open source code:
> 
> ```diff
> cloud-init (https://github.com/canonical/cloud-init)
> + cloudinit/sources/DataSourceLXD.py:287: error: Item "None" of "bytes | None" has no attribute "decode"  [union-attr]
> + cloudinit/sources/DataSourceLXD.py:296: error: Item "None" of "bytes | None" has no attribute "decode"  [union-attr]
> + cloudinit/sources/DataSourceLXD.py:324: error: Item "None" of "bytes | None" has no attribute "decode"  [union-attr]
> + cloudinit/sources/DataSourceLXD.py:367: error: Item "None" of "bytes | None" has no attribute "decode"  [union-attr]
> + cloudinit/sources/DataSourceLXD.py:406: error: Item "None" of "bytes | None" has no attribute "decode"  [union-attr]
>  ```

I had forgotten that [mypy_primer uses cloud-init](https://github.com/hauntsaninja/mypy_primer/pull/39), so I was a bit surprised to see cloud-init test results at the top of the test results. 

I came across this issue while debugging a [spurious mypy warning in cloud-init](https://github.com/canonical/cloud-init/pull/5350/commits/ee8f0363b4b72e8a40755bdc0ba841e05ca7c94b#r1645011657).

**Comment by srittau** [comment]
Under which conditions can `content` be `None`? [The documentation](https://requests.readthedocs.io/en/latest/api/#requests.Response.content) only says: "Content of the response, in bytes." Looking at the [source code](https://github.com/psf/requests/blob/0e322af87745eff34caffe4df68456ebc20d9068/src/requests/models.py#L890), it's obvious that `content` can be `None` if either `status_code` is `0` or `Response.raw` is `None`, but I'm not clear under which circumstances that can be the case. At the moment, I would assume that `content` being `None` is not something ordinary users should have to deal with, so using `bytes | MaybeNone` could be a better alternative.

**Comment by TheRealFalcon** [comment]
> but I'm not clear under which circumstances that can be the case

Here is an example:
```python
>>> from requests.models import Response
>>> type(Response().content)
<class 'NoneType'>
```

I realize that this isn't a normal usage pattern, but it shows how we can get `None` in the code.

**Comment by srittau** [comment]
In that, I think `bytes | MaybeNone` (`MaybeNone` needs to be imported from `_typeshed`) is the best return type to use. This doesn't disrupt the normal usage by having to introduce spurious `isinstance` checks, but also communicates that this can return `None` and allows to handle `None` values.

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
