### PR TITLE
Add FrozenSet to the typing stub files

### PR DESCRIPTION
**Pull request by Vgr255**
Followup from python/typing#261

Now, mypy sees that FrozenSet is in the module, but it complains that it's an invalid type. I'm probably overlooking something simple, I guess.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Oh, `TypeAlias()` only works for types that have hard-coded support in mypy. But I think you can make it derive from `AbstractSet` and you probably won't have to add anything else.

**Comment by Vgr255** [comment]
Aah, fair enough. I still have a bit to learn about mypy.

**Comment by Vgr255** [comment]
Force-pushed new commit; mypy effectively detects it. Cheers!

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
