### PR TITLE
`property`: `fget`, `fset`, `fdel` are read-only

### PR DESCRIPTION
**Pull request by AlexWaygood**
It feels a bit weird to have `@property` in the stub for `property` itself, but mypy seems cool with it... it's turtles all the way down, I guess!

### CODE REVIEW

**Comment by AlexWaygood** [comment]
I don't understand why stubtest is succeeding for Python 3.10, but failing for all other Pythons. The typeshed stub for `types.DynamicClassAttribute` is the same for all Pythons, and the CPython source code didn't change between Python 3.9 and Python 3.10.

**Comment by hauntsaninja** [comment]
https://github.com/python/typeshed/blob/d00b3b2d1256ce5cd8de15553b910c1d03fe7737/tests/stubtest_allowlists/py310.txt#L129
So you should move the allowlists to py3_common.txt (if we merge this)

I'm surprised this isn't causing issues for type checkers, since it is not valid Python code, but there is a tonne of special casing for property (mypy doesn't acknowledge the possibility of `fget` on `Class.property_def.fget`). It looks like the same trick does not work on other classes. Other than assuming `from __future__ import annotations` I don't think there's precedent to stubs resolving symbols differently than Python. I could also see this causing problems if people ever try to reduce the amount of special casing that property has, e.g. with some of the generic property proposals.

**Comment by AlexWaygood** [comment]
> https://github.com/python/typeshed/blob/d00b3b2d1256ce5cd8de15553b910c1d03fe7737/tests/stubtest_allowlists/py310.txt#L129
> 
> 
> So you should move the allowlists to py3_common.txt (if we merge this)
> I'm surprised this isn't causing issues for type checkers, since it is not valid Python code, but there is a tonne of special casing for property (mypy doesn't acknowledge the possibility of `fget` on `Class.property_def.fget`). It looks like the same trick does not work on other classes. Other than assuming `from __future__ import annotations` I don't think there's precedent to stubs resolving symbols differently than Python. I could also see this causing problems if people ever try to reduce the amount of special casing that property has, e.g. with some of the generic property proposals.

There's more important things to worry about, I'll just close the PR — everything you say makes a lot of sense 🙂

**Comment by AlexWaygood** [comment]
> I don't think there's precedent to stubs resolving symbols differently than Python.

Well, the first line in the stub for `sys` is `import sys` ;)

**Comment by Akuli** [comment]
> Well, the first line in the stub for sys is import sys ;)

This works at runtime too: if you `import foo`, the module object is put to `sys.modules` before the module is executed, and so during the execution `import foo` will work, and give you the not-yet-loaded module object.

**Comment by AlexWaygood** [comment]
> > Well, the first line in the stub for sys is import sys ;)
> 
> This works at runtime too: if you `import foo`, the module object is put to `sys.modules` before the module is executed, and so during the execution `import foo` will work, and give you the not-yet-loaded module object.

Huh. Well TIL :)

**Comment by hauntsaninja** [comment]
Well you still have a point in that `sys` differs from Python, since `sys.platform` is not defined when it is first used in sys, so one would get an AttributeError. mypy and pyright don't think about such things though.

**Pull request closed without merging**
