### PR TITLE
_csv.Reader and _csv.Writer

### PR DESCRIPTION
**Pull request by tungol**

### CODE REVIEW

**Review by srittau — COMMENTED** [review]
I think a better approach would be to omit the aliases for 3.10+, and use a conditional import in `csv` instead:

```python
if sys.version >= (3, 10):
    from _csv import Reader, Writer
else:
    from _csv import _reader as Reader, _writer as Writer
```

Also the old classes should be marked with `@type_check_only`.

**Comment by tungol** [comment]
That is better, yeah

**Comment by tungol** [comment]
Actually we still need the aliases for the return types of `_csv.reader` and `_csv.writer`. But the imports are better this way.

**Comment by srittau** [comment]
You can just change the return types to `Reader` and `Writer`.

**Comment by tungol** [comment]
I could, but then I need to create aliases in the other branch, `Reader = _reader`, and that's an alias without the underscore prefix.

**Comment by tungol** [comment]
It's that or duplicate the functions in the two version_info branches, which seems like overkill just for the return type

**Review by srittau — APPROVED** [review]

**Pull request merged**
