### PR TITLE
add `__init__` to `SimpleNamespace`

### PR DESCRIPTION
**Pull request by JelleZijlstra**
```
In [11]: SimpleNamespace(x=3)
Out[11]: namespace(x=3)
```

### CODE REVIEW

**Comment by gvanrossum** [comment]
Ideally those would also make mypy understand that those names are predefined and maybe give them a type derived from the argument value?

**Comment by JelleZijlstra** [comment]
That sounds like a job for a plugin rather than for typeshed.

**Comment by gvanrossum** [comment]
Agreed, I'll leave it to the OP to create an issue. (Maybe they don't need it and the `Any` they currently get is good enough or maybe even it's what they want.)

**Comment by gvanrossum** [comment]
(Sorry, I didn't realize the OP is you, Jelle. :-)

**Pull request merged**
