### PR TITLE
Various fixes in `gdb`

### PR DESCRIPTION
**Pull request by pmderodat**
See post-merge comments in #8013

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]
Great, thank you!

**Comment by syheliel** [comment]
Thanks for your contribution! I have put `types-gdb` as pip requirement in [pwngdb](https://github.com/pwndbg/pwndbg). 
When using `mypy pwndbg`, I found that `gdb.events` are not recorded. You can see [pwndbg/events.py:63](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/events.py)
Here is the full mypy log
```
pwndbg/stdio.py:10: error: Need type annotation for "queue" (hint: "queue: List[<type>] = ...")
pwndbg/color/lexer.py:1: error: Skipping analyzing "pygments.lexer": module is installed, but missing library stubs or py.typed marker
pwndbg/color/lexer.py:3: error: Skipping analyzing "pygments.token": module is installed, but missing library stubs or py.typed marker
pwndbg/funcparser.py:3: error: Skipping analyzing "pycparser": module is installed, but missing library stubs or py.typed marker
pwndbg/config.py:37: error: Invalid index type "Type[int]" for "OrderedDict[Type[bool], int]"; expected type "Type[bool]"
pwndbg/config.py:43: error: Invalid index type "Type[str]" for "OrderedDict[Type[bool], int]"; expected type "Type[bool]"
pwndbg/events.py:63: error: Module has no attribute "events"
pwndbg/events.py:100: error: Module has no attribute "events"
pwndbg/events.py:105: error: Need type annotation for "registered"
pwndbg/events.py:106: error: Module has no attribute "events"
pwndbg/events.py:107: error: Module has no attribute "events"
pwndbg/events.py:108: error: Module has no attribute "events"
pwndbg/events.py:109: error: Module has no attribute "events"
pwndbg/events.py:110: error: Module has no attribute "events"
pwndbg/events.py:111: error: Module has no attribute "events"
pwndbg/events.py:116: error: Module has no attribute "events"
pwndbg/events.py:117: error: Module has no attribute "events"
pwndbg/events.py:136: error: Need type annotation for "objfile_cache" (hint: "objfile_cache: Dict[<type>, <type>] = ...")
pwndbg/events.py:196: error: Module has no attribute "events"
pwndbg/events.py:223: error: Module has no attribute "events"
pwndbg/memoize.py:19: error: Module "collections" has no attribute "Hashable"
pwndbg/memoize.py:19: error: Name "Hashable" already defined (possibly by an import)
pwndbg/memoize.py:80: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:89: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:104: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:117: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:130: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:143: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:156: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/memoize.py:169: error: Need type annotation for "caches" (hint: "caches: List[<type>] = ...")
pwndbg/qemu.py:8: error: Skipping analyzing "psutil": module is installed, but missing library stubs or py.typed marker
pwndbg/prompt.py:14: error: Cannot determine type of "functions"
pwndbg/prompt.py:19: error: Cannot determine type of "commands"
pwndbg/exception.py:14: error: Cannot find implementation or library stub for module named "ipdb"
pwndbg/exception.py:14: error: Name "pdb" already defined (by an import)
pwndbg/exception.py:95: error: Incompatible types in assignment (expression has type "Callable[[], Any]", variable has type "Callable[[DefaultNamedArg(Optional[str], 'header')], None]")
pwndbg/color/syntax_highlight.py:10: error: Skipping analyzing "pygments": module is installed, but missing library stubs or py.typed marker
pwndbg/color/syntax_highlight.py:11: error: Skipping analyzing "pygments.formatters": module is installed, but missing library stubs or py.typed marker
pwndbg/color/syntax_highlight.py:12: error: Skipping analyzing "pygments.lexers": module is installed, but missing library stubs or py.typed marker
pwndbg/color/syntax_highlight.py:27: error: Need type annotation for "lexer_cache" (hint: "lexer_cache: Dict[<type>, <type>] = ...")
pwndbg/regs.py:489: error: Module has no attribute "OnlyWhenRunning"
pwndbg/regs.py:494: error: Module has no attribute "OnlyWhenRunning"
pwndbg/regs.py:513: error: Need type annotation for "last" (hint: "last: Dict[<type>, <type>] = ...")
pwndbg/regs.py:638: error: Decorated property not supported
pwndbg/regs.py:643: error: Decorated property not supported
pwndbg/arch.py:5: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/arch.py:15: error: Module has no attribute "ptrsize"
pwndbg/abi.py:16: error: Need type annotation for "register_arguments" (hint: "register_arguments: List[<type>] = ...")
pwndbg/elftypes.py:258: error: Name "pwndbg.ctypes.Structure" is not defined
pwndbg/elftypes.py:277: error: Name "pwndbg.ctypes.Structure" is not defined
pwndbg/elftypes.py:296: error: Name "pwndbg.ctypes.Structure" is not defined
pwndbg/elftypes.py:309: error: Name "pwndbg.ctypes.Structure" is not defined
pwndbg/disasm/x86.py:1: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/x86.py:2: error: Skipping analyzing "capstone.x86": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/x86.py:14: error: Name "X86_REG_RSP" is not defined
pwndbg/stack.py:19: error: Need type annotation for "stacks" (hint: "stacks: Dict[<type>, <type>] = ...")
pwndbg/elf.py:15: error: Skipping analyzing "elftools.elf.constants": module is installed, but missing library stubs or py.typed marker
pwndbg/elf.py:16: error: Skipping analyzing "elftools.elf.elffile": module is installed, but missing library stubs or py.typed marker
pwndbg/elf.py:174: error: Module has no attribute "OnlyWhenRunning"
pwndbg/elf.py:186: error: Module has no attribute "OnlyWhenRunning"
pwndbg/disasm/jump.py:1: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/radare2.py:27: error: Cannot find implementation or library stub for module named "r2pipe"
pwndbg/ida.py:273: error: Need type annotation for "_breakpoints" (hint: "_breakpoints: List[<type>] = ...")
pwndbg/vmmap.py:29: error: Need type annotation for "explored_pages" (hint: "explored_pages: List[<type>] = ...")
pwndbg/vmmap.py:32: error: Need type annotation for "custom_pages" (hint: "custom_pages: List[<type>] = ...")
pwndbg/vmmap.py:356: error: Cannot find implementation or library stub for module named "pt"
pwndbg/symbol.py:13: error: Skipping analyzing "elftools.common.exceptions": module is installed, but missing library stubs or py.typed marker
pwndbg/symbol.py:13: error: Skipping analyzing "elftools": module is installed, but missing library stubs or py.typed marker
pwndbg/symbol.py:13: error: Skipping analyzing "elftools.common": module is installed, but missing library stubs or py.typed marker
pwndbg/symbol.py:14: error: Skipping analyzing "elftools.elf.constants": module is installed, but missing library stubs or py.typed marker
pwndbg/symbol.py:14: error: Skipping analyzing "elftools.elf": module is installed, but missing library stubs or py.typed marker
pwndbg/symbol.py:15: error: Skipping analyzing "elftools.elf.elffile": module is installed, but missing library stubs or py.typed marker
pwndbg/symbol.py:16: error: Skipping analyzing "elftools.elf.segments": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/arch.py:2: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/arch.py:20: error: Need type annotation for "assistants" (hint: "assistants: Dict[<type>, <type>] = ...")
pwndbg/glibc.py:23: error: Module has no attribute "OnlyWhenRunning"
pwndbg/disasm/arm.py:1: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/arm.py:2: error: Skipping analyzing "capstone.arm": module is installed, but missing library stubs or py.typed marker
pwndbg/emu/emulator.py:8: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/emu/emulator.py:10: error: Skipping analyzing "unicorn": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/__init__.py:8: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/disasm/__init__.py:22: error: Incompatible types in assignment (expression has type "None", variable has type Module)
pwndbg/disasm/__init__.py:25: error: Name "CS_ARCH_ARM" is not defined
pwndbg/disasm/__init__.py:26: error: Name "CS_ARCH_ARM" is not defined
pwndbg/disasm/__init__.py:27: error: Name "CS_ARCH_ARM64" is not defined
pwndbg/disasm/__init__.py:28: error: Name "CS_ARCH_X86" is not defined
pwndbg/disasm/__init__.py:29: error: Name "CS_ARCH_X86" is not defined
pwndbg/disasm/__init__.py:30: error: Name "CS_ARCH_X86" is not defined
pwndbg/disasm/__init__.py:31: error: Name "CS_ARCH_PPC" is not defined
pwndbg/disasm/__init__.py:32: error: Name "CS_ARCH_MIPS" is not defined
pwndbg/disasm/__init__.py:33: error: Name "CS_ARCH_SPARC" is not defined
pwndbg/disasm/__init__.py:37: error: Name "CS_MODE_LITTLE_ENDIAN" is not defined
pwndbg/disasm/__init__.py:38: error: Name "CS_MODE_BIG_ENDIAN" is not defined
pwndbg/disasm/__init__.py:41: error: Name "CS_MODE_32" is not defined
pwndbg/disasm/__init__.py:41: error: Name "CS_MODE_64" is not defined
pwndbg/disasm/__init__.py:43: error: Name "CS_OPT_SYNTAX_INTEL" is not defined
pwndbg/disasm/__init__.py:43: error: Name "CS_OPT_SYNTAX_ATT" is not defined
pwndbg/disasm/__init__.py:57: error: Need type annotation for "backward_cache"
pwndbg/next.py:8: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/heap/ptmalloc.py:83: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:153: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:158: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:163: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:168: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:173: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:178: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:183: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:188: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:200: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:206: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:212: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:218: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:224: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:294: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:594: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:599: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:604: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:609: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:614: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:619: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:624: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1444: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1450: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1456: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1462: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1468: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1474: error: Decorated property not supported
pwndbg/heap/ptmalloc.py:1480: error: Decorated property not supported
pwndbg/arguments.py:6: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/__init__.py:52: error: Need type annotation for "history" (hint: "history: Dict[<type>, <type>] = ...")
pwndbg/color/disasm.py:1: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/vmmap.py:7: error: Skipping analyzing "elftools.elf.constants": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/vmmap.py:8: error: Skipping analyzing "elftools.elf.elffile": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/shell.py:65: error: Incompatible types in assignment (expression has type "filter[str]", variable has type "List[str]")
pwndbg/commands/shell.py:66: error: Incompatible types in assignment (expression has type "filter[str]", variable has type "List[str]")
pwndbg/commands/search.py:16: error: Need type annotation for "saved" (hint: "saved: Set[<type>] = ...")
pwndbg/commands/procinfo.py:13: error: Skipping analyzing "psutil": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/procinfo.py:85: error: Decorated property not supported
pwndbg/commands/procinfo.py:92: error: Decorated property not supported
pwndbg/commands/procinfo.py:148: error: Decorated property not supported
pwndbg/commands/procinfo.py:161: error: Decorated property not supported
pwndbg/commands/p2p.py:83: error: Bracketed expression "[...]" is not valid as a type
pwndbg/commands/p2p.py:83: note: Did you mean "List[...]"?
pwndbg/commands/p2p.py:115: error: Bracketed expression "[...]" is not valid as a type
pwndbg/commands/p2p.py:115: note: Did you mean "List[...]"?
pwndbg/commands/hexdump.py:54: error: Module has no attribute "hexdump_bytes"
pwndbg/commands/elf.py:1: error: Skipping analyzing "elftools.elf.elffile": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/comments.py:12: error: Need type annotation for "file_lists" (hint: "file_lists: Dict[<type>, <type>] = ...")
pwndbg/commands/nearpc.py:4: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/heap.py:914: error: Assignment to variable "e" outside except: block
pwndbg/commands/heap.py:915: error: Assignment to variable "e" outside except: block
pwndbg/commands/heap.py:916: error: Assignment to variable "e" outside except: block
pwndbg/commands/context.py:54: error: Need type annotation for "outputs" (hint: "outputs: Dict[<type>, <type>] = ...")
pwndbg/commands/context.py:807: error: Module has no attribute "events"
pwndbg/commands/context.py:808: error: Module has no attribute "events"
pwndbg/commands/context.py:809: error: Module has no attribute "events"
pwndbg/commands/version.py:33: error: Skipping analyzing "capstone": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/version.py:42: error: Skipping analyzing "unicorn": module is installed, but missing library stubs or py.typed marker
pwndbg/commands/reload.py:11: error: Cannot find implementation or library stub for module named "__builtins__"
pwndbg/commands/misc.py:11: error: Unsupported target for indexed assignment ("Mapping[int, str]")
pwndbg/commands/misc.py:61: error: Name "pwndbg" already defined (by an import)
pwndbg/__init__.py:89: error: Skipping analyzing "unicorn": module is installed, but missing library stubs or py.typed marker
pwndbg/__init__.py:89: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
pwndbg/heap/structs.py:44: error: Cannot assign multiple types to name "PTR" without an explicit "Type[...]" annotation
pwndbg/heap/structs.py:44: error: Incompatible types in assignment (expression has type "Type[c_uint64]", variable has type "Type[c_uint32]")
pwndbg/heap/structs.py:45: error: Cannot assign multiple types to name "SIZE_T" without an explicit "Type[...]" annotation
pwndbg/heap/structs.py:45: note: (Skipping most remaining errors due to unresolved imports or missing stubs; fix these first)
Found 163 errors in 48 files (checked 147 source files)
```

**Comment by pmderodat** [comment]
Hello! Sorry about the delay for my answer. If I understand correctly your log, the issue isn’t that `gdb.events` is not available (we do have stubs for it: https://github.com/python/typeshed/blob/master/stubs/gdb/gdb/events.pyi), but rather that, according to the current stubs, you need to explicitly have `import gdb.events` in your code whereas this is not necessary in practice (`gdb.events` is automatically loaded and available).

I’ve attempted a fix for this: see https://github.com/python/typeshed/pull/8788, please let me know if this does not fix your issue. Thanks!

**Comment by syheliel** [comment]
That fix works as expect🆒. We are currently adding type support to [pwndbg](https://github.com/pwndbg/pwndbg) and It would be nice to know how the type-stub is generated. I have a quick look at gdb's python extension, it's written in C and I have no idea now to extract types through it... Are there any tools or tutorials to generate type-stub from C-written python package(like gdb)?
Also CC @disconnect3d @gsingh93

**Comment by pmderodat** [comment]
Excellent! Thank you for the confirmation.

I’m not sure what you mean wrt `pwndbg`: it seems to be a pure Python project, so presumably it does not need type stubs: you can add type annotations directly to the Python code. As to type stubs for the `gdb` module hierarchy, well… my work here is supposed to cover all its API surface, so except for new features that will get added to next GDB releases, we should be good.

I’m not aware of any tutorial to do this, by the way: I just read [mypy’s documentation](https://mypy.readthedocs.io/en/latest/index.html), [GDB’s](https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html) and a bit of GDB’s C source code to infer the expected types.

**Comment by syheliel** [comment]
> I’m not aware of any tutorial to do this, by the way: I just read [mypy’s documentation](https://mypy.readthedocs.io/en/latest/index.html), [GDB’s](https://sourceware.org/gdb/current/onlinedocs/gdb/Python.html) and a bit of GDB’s C source code to infer the expected types.

Oh, What I'm concerned is the update of gdb's type-stub. So basiclly you write the type-stubs by hand? I originally think that there maybe a tool to generate them 😂

**Comment by pmderodat** [comment]
No, that was manual: I don’t think there are tools to automatically generate stubs for modules implemented on top of CPython’s extension API… Now I don’t expect very big updates in the future: GDB’s Python API seems like a slow moving target to me. :-)

**Pull request merged**
