### PR TITLE
Return `bool` from `operator` comparison functions

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Returning a non-bool from these methods isn't all that uncommon; numpy arrays do it. Perhaps we could do something fancy here with generic Protocols.

(Also, unrelatedly, thanks for all the enthusiasm in improving things! I really appreciate your work here.)

**Comment by AlexWaygood** [comment]
> (Also, unrelatedly, thanks for all the enthusiasm in improving things! I really appreciate your work here.)

Thanks 🙂 also, do let me know if I'm being a pain at any point!

**Comment by AlexWaygood** [comment]
> Perhaps we could do something fancy here with generic Protocols.

Hmmmm

**Comment by AlexWaygood** [comment]
> But in fact we have to look at both operands, so we need something more complicated.

Yeah. I tried doing something more ✨fancy✨ in #6448, but a lot of the false-positives seemed to arise from giving e.g. `__lt__` and `__gt__` different signatures. So that's quite a big constraining factor here 😕

**Comment by Akuli** [comment]
I think we should also distinguish between `x < y` and `x.__lt__(y)`. An operator like `<` will call `y.__gt__(x)`, if `y.__gt__` exists but `x.__lt__` doesn't. This was previously discussed when improving the type hint for `max()`.

**Comment by AlexWaygood** [comment]
> I think we should also distinguish between `x < y` and `x.__lt__(y)`. An operator like `<` will call `y.__gt__(x)`, if `y.__gt__` exists but `x.__lt__` doesn't. This was previously discussed when improving the type hint for `max()`.

Just WAIT till you see my next PR

**Pull request closed without merging**
