### PR TITLE
py39: return once again to CI

### PR DESCRIPTION
**Pull request by hauntsaninja**
Github Actions now supports prerelease builds
https://github.com/actions/setup-python/issues/20

### CODE REVIEW

**Comment by hauntsaninja** [comment]
A number of unwhitelisted errors have cropped up in the interim, will fix or whitelist.

**Comment by gvanrossum** [comment]
BTW, after this is done, do you want to look at starting support for 3.10?

**Comment by hauntsaninja** [comment]
Yup, I will. stubtest makes it really easy to do the 80-20 work of a new version, e.g. this was my todo list (as of May) for 3.9 https://gist.github.com/hauntsaninja/6870c77b502c0d19e33c831adac976ac

**Comment by hauntsaninja** [comment]
This is now ready for review / merge

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
