### PR TITLE
Remove ModuleType.__getattr__

### PR DESCRIPTION
**Pull request by JukkaL**
This caused false negatives for mypy -- mypy would consider that any
module would have any attribute. The method also does not exist at
runtime.

I've also updated `builtins.__import__`, `importlib.__import__`, and
`importlib.import_module` to return `Any`. I don't have a strong
opinion on this change, but this arguably minimizes the impact of the
removal, and maintains the return types of these functions consistent.

Also, it could be argued that since arbitrary objects can be stuffed
into `sys.modules` (and I've heard people actually suggest taking
advantage of this), the `Any` type best reflects this.

There may be other reasonable ways to deal with module objects, but I
think that adding `ModuleType.__getattr__` regresses things too much.

### CODE REVIEW

**Review by ilevkivskyi — APPROVED** [review]

**Comment by AlexWaygood** [comment]
(As the person who introduced this change), I don't have a strong opinion on what the return type of  `builtins.__import__`, `importlib.__import__`, and
`importlib.import_module` should be, as long as they remain consistent 🙂

**Comment by JelleZijlstra** [comment]
Could mypy instead be changed so that if an object is a specific, known module, it ignores the `__getattr__`? I feel like that would still give a better overall system than returning Any from all the `import_module`-like functions.

**Comment by AlexWaygood** [comment]
A slightly more "out there" suggestion, but —something else I was wondering about a few weeks ago, when we discussed this last, was whether type-checkers could be special-cased to recognise that the return type of `__import__("collections")` (for example) will be, well, the literal `collections` module. There doesn't seem to be _that_ much difference between the following two snippets in terms of the information available to mypy, but the inferred type is obviously quite different, and it doesn't seem to me like something that's solveable in the stubs:

(1)

```python
import collections as c
reveal_type(c.deque())  # Revealed type is "collections.deque[<nothing>]"
```

(2)

```python
c = __import__("collections")
reveal_type(c.deque())  # Revealed type is "Any"
```

But I appreciate that this probably isn't the right place to discuss the feasibility of that idea.

**Comment by JelleZijlstra** [comment]
I imagine most cases where people call these functions the argument is going to be dynamic.

**Comment by AlexWaygood** [comment]
> I imagine most cases where people call these functions the argument is going to be dynamic.

No, you're right. I thought I remembered there being more instances in the diff [here](https://github.com/python/typeshed/pull/6302#issuecomment-968944783) where people were just `__import__` as a one-liner way to import a module and immediately access an object from the module. But it seems I misremembered — so, that idea of mine shouldn't be a priority.

**Comment by JukkaL** [comment]
> Could mypy instead be changed so that if an object is a specific, known module, it ignores the `__getattr__`?

I'll have a look. If this is straightforward to implement, I'll abandon this PR.

**Comment by JukkaL** [comment]
The issue was actually very simple to work around in mypy, so this PR is no longer needed (python/mypy#11597).

**Pull request closed without merging**
