### PR TITLE
Akuli and srittau: Remove Python 2 branches from Python 3 stubs

### PR DESCRIPTION
**Pull request by Akuli**
Combination of #5460 and #5458

### CODE REVIEW

**Comment by Akuli** [comment]
@srittau This is the combined PR. When going through the conflicts, I noticed that you generally did this better than my script, although the script handled one version check that you had missed.

**Comment by srittau** [comment]
Give me a sec, I'm still going through my PR a second time to see if there are any errors.

**Comment by Akuli** [comment]
Clicking the merge commit above shows how this PR differs from yours. The version check you missed is in stdlib/warnings.pyi. The `unix_dialect` you already fixed is in stdlib/csv.pyi.

Given that this is a combination of something done with a script and something done by a human, this quite likely catches missing things (script) and handles comments and funny corner cases properly (human).

**Review by srittau — APPROVED** [review]
Thank you for the merge! LGTM.

**Comment by srittau** [comment]
@Akuli Just to avoid double work again (sorry about that!): I would start working on those now-obsolete aliases like `_Text` etc.

**Comment by Akuli** [comment]
Sure, you can do that. I think this double work wasn't a bad thing, since my PR and your PR both had some problems that the combined PR didn't have.

In the past, I have done a similar thing at work, although slightly more complicated: I and a coworker both did some changes, then we both finished merging them at about the same time (many conflicts), then we together merged our already once merged versions together.

**Pull request merged**
