### PR TITLE
Add stubs for `contextvars` backport (3.5 and 3.6)

### PR DESCRIPTION
**Pull request by stevenjackson121**
Permission from repo maintainer: https://github.com/MagicStack/contextvars/issues/10

`python tests/mypy_selftest.py` fails when I try running it locally with the same summary (`4 failed, 6349 passed, 164 skipped`) both before and after this change.

`python tests/mypy_test.py` passes and I believe `python tests/pytype_test.py` is only applicable for python2.

### CODE REVIEW

**Comment by stevenjackson121** [comment]
This failure looks to me like a failure with Travis-CI config and not a problem with the PR: https://travis-ci.org/python/typeshed/jobs/414689751 (Copied below for convenience)

```
3.6-dev is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.6-dev.tar.bz2
$ curl -sSf -o python-3.6-dev.tar.bz2 ${archive_url}
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
Unable to download 3.6-dev archive. The archive may not exist. Please consider a different version.
```

If this is not the case please let me know how I could go about troubleshooting the cause.

**Comment by JelleZijlstra** [comment]
I restarted the flake8 build.

It is not true that the pytype test is only applicable to Python 2; it runs pytype, which runs under Python 2, but it also checks the Python 3 stubs.

Could you add this file to `tests/check_consistent.py` to make sure we keep the stdlib and third-party versions in sync?

**Comment by stevenjackson121** [comment]
Thanks for the restart and the information @JelleZijlstra ! 

I added `contextvars` to `tests/check_consistent.py` as requested. Let me know if there's anything else I should do!

**Comment by stevenjackson121** [comment]
Ping :)

**Pull request merged**
