### PR TITLE
Re-export code from _ast into ast

### PR DESCRIPTION
**Pull request by ilinum**
After mypy [started hiding](https://github.com/python/mypy/pull/3706) imported names in stubs unless `from ... import ...` is used, we found an error with stubs of ast module. 

It looks like ast module should re-export everything in `_ast` and according to PEP 484, it can do that by doing `from _ast import *`, so this is what this PR does.

### CODE REVIEW

**Comment by gvanrossum** [comment]
The flake8 linter doesn't like * imports. I wonder if we should just disable that rule in the config file.

**Comment by ilinum** [comment]
Hmm, I think we should disable the rule.

 But if other people think otherwise, I am happy to fix the import.

**Comment by gvanrossum** [comment]
Let's disable the rule.

**Comment by ilinum** [comment]
Submitted #1519 to allow star imports.

**Comment by gvanrossum** [comment]
Please re-merge and re-push this to show the tests are now green.

**Comment by ilinum** [comment]
Merged and pushed!

**Pull request merged**
