### PR TITLE
Allow passing None to Mapping.get

### PR DESCRIPTION
**Pull request by aecay**
See the discussion at https://github.com/python/mypy/issues/9430 for the rationale.  The test file from there now typechecks without problems using this branch of typeshed.

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
I'm not sure how I feel about this.
In some ways I'd feel more comfortable if we just loosened `key` all the way up to `object` for `get`: it's more predictable and people mostly use the more strongly typed `__getitem__`. But maybe that's not the right decision on the pragmatism spectrum.
It might also be better to add this to dict, instead of Mapping. As evidenced by CI, changing Mapping will probably break LSP for some users.

**Comment by aecay** [comment]
Hmm.  The unit tests failed, which showed that the shelve library was defined with key and value types set to `Any`, whereas I think it should be a generic `MutableMapping[str, V]`.  I've made the change, which I hope is correct (as well as a corresponding change adding overloads for `None` in a werkzeug class that extends the dict interface).

**Comment by hauntsaninja** [comment]
Unfortunately, it's imprecise to simplify get to a single call, since if you specify a non-None default (and your value type is not None), you will not get None back. (You can simplify to two overloads, instead of the original four. I didn't mention it earlier, since it read as clearer to the intention)

**Comment by aecay** [comment]
Then I ran into errors like

```
error: shelve.Shelf.get is inconsistent, runtime argument "default" has a default value of type None, which is incompatible with stub argument type Union[_VT_co`2, _T`-1]
Stub: at line 428
def [_T] (self: typing.Mapping[_KT`1, _VT_co`2], key: Union[_KT`1, None], default: Union[_VT_co`2, _T`-1] =) -> Union[_VT_co`2, _T`-1]
Runtime: at line 104 in file /usr/lib/python3.8/shelve.py
def (self, key, default=None)
```

I don't understand why mypy doesn't unify `_T`-1` with `None` and allow this to pass -- but this is at the very edge of my understanding of type theory.  As part of trying to puzzle this out, I reduced the definition of get from four overloads to two:
```
    @overload
    def get(self, key: Optional[_KT], default: None = ...) -> Union[_VT_co, None]: ...
    @overload
    def get(self, key: Optional[_KT], default: Union[_VT_co, _T] = ...) -> Union[_VT_co, _T]: ...
```
The first in case `default` is `None` and the second generic case.

(@hauntsaninja thanks for your comments.  For some reason they were not showing up in the github UI -- I have a bad habit of leaving tabs open without refreshing them -- and now as I've been puzzling this out I see that they have showed up.  I hope that I've eventually converged on the two overloads you had in mind all along...)

**Comment by aecay** [comment]
Aha, I think I've cracked it...there's only one definition needed:
```
def get(self, key: Optional[_KT], default: _T = ...) -> Union[_VT_co, _T]: ...
```

Specifying the type of the default arg as a union was confusing me (and maybe mypy) -- the default is something whose type we will concretely know at runtime.  The union only needs to be specified on the return type.  At least, I hope that's true.  I will defer to the wisdom of others, and to the test suite (which I've only *sort of* managed to get running locally, but insofar as it runs, passes for this new idea of mine...)

**Comment by JelleZijlstra** [comment]
I agree with @hauntsaninja that this doesn't feel very principled. Technically `.get()` will accept any hashable type and just give you None back, so we could type the key argument as `object`, but that feels like we're throwing out a lot of useful type safety. It doesn't seem so bad in this case to have users check for `None` before using `.get()`.

**Comment by gvanrossum** [comment]
Maybe I was too quick in suggesting to make a PR here. Perhaps we should circle back to the issue (#9430) first?

**Comment by aecay** [comment]
> Technically .get() will accept any hashable type and just give you None back, so we could type the key argument as object, but that feels like we're throwing out a lot of useful type safety.

I agree that loosening the key type to `object` would discard useful type info, which is why I didn't propose it....the loosening to `Optional` is driven by a specific usage pattern which I described in the original issue that @gvanrossum linked to.

**Comment by srittau** [comment]
I am closing this due to our upcoming typeshed restructuring.

**Pull request closed without merging**
