### PR TITLE
Add stub for typing_extensions.get_args

### LINKED ISSUE #4371: Missing get_args in typing_extensions
Method `get_args` is missing in `typing_extensions` package. Can you please add it?

https://github.com/microsoft/pyright/issues/302#issuecomment-664459334

### PR DESCRIPTION
**Pull request by HarrySky**
Fixes #4371 . Ready for review.

### CODE REVIEW

**Comment by Akuli** [comment]
`get_args(Literal['foo', 'bar'])` returns a tuple of strings, not a tuple of types, maybe add overloads for Literal and other similar things?

**Comment by Akuli** [comment]
ci failure doesn't seem to have anything to do with your changes

**Comment by HarrySky** [comment]
Maybe I can use something else instead of `tp: type` to detect `Literal` type? :thinking:

(no expert, don't know if it is even possible)

**Comment by HarrySky** [comment]
In `typing.pyi` we can see this, by the way:

https://github.com/python/typeshed/blob/c96b1ae1bfa0fb1703b695b039d9ed697c05d233/stdlib/3/typing.pyi#L606

**Comment by HarrySky** [comment]
I annotated it just like in `typing` module. If there is a way to detect if type is `Literal` or `Callable`, they will return `Tuple[Any, ...]`, so I thought that it can be used for all overloads.

**Comment by HarrySky** [comment]
@hauntsaninja is there anything else I need to change to merge this?

**Pull request merged**
