### PR TITLE
Remove redundant inheritances from Iterator in itertools

### PR DESCRIPTION
**Pull request by tungol**

### CODE REVIEW

**Comment by tungol** [comment]
Both mypy primer hits look like instances of https://github.com/python/mypy/issues/4373 to me.

python-chess simplifies to:
```python
import itertools

foo: list[int] = []
condition = True

iter(itertools.pairwise(foo) if condition else [])
```

xarray simplifies to
```python
import itertools

cond = True
foo: list[int] = []
set().difference(range(1) if cond else itertools.accumulate(foo))
```

The unused ignore from jax is something involving an overloaded function that I don't fully understand yet. I played around with it a bunch, and ended up with this simplified form:

```python
import itertools
from typing import overload


@overload
def foo(arg1: str) -> str: ...


@overload
def foo(arg1: str, arg2: int) -> int: ...


def foo(arg1: str, arg2: int | None = None) -> int | str:
    return 1


def bar() -> int | str:
    arrs: list[int] = []
    result = foo(*itertools.chain(arrs))
    reveal_type(result)
    return result
```

Without this change, this produces:

```
temp.py:19: error: No overload variant of "foo" matches argument type "chain[int]"  [call-overload]
temp.py:19: note: Possible overload variants:
temp.py:19: note:     def foo(arg1: str) -> str
temp.py:19: note:     def foo(arg1: str, arg2: int) -> int
temp.py:20: note: Revealed type is "Any"
Found 1 error in 1 file (checked 1 source file)
```

With this MR in place, mypy gives:

```
temp.py:20: note: Revealed type is "builtins.str"
Success: no issues found in 1 source file
```

This might also be a mypy bug? It seems like when itertools.chain is explicitly `Iterator[_T]`, mypy knows that `*chain()` works out to `_T`. When chain is not explicitly `Iterator`, mypy is failing to pick up the type from `chain.__next__() -> T` and inserting `Any`

**Review by srittau — APPROVED** [review]

**Comment by AlexWaygood** [comment]
I'm a bit concerned by the primer output here. Even if the root cause of these false positives is a mypy bug, we should try not to make changes to the stubs if they end up hurting users of type checkers more than they end up helping users of type checkers. All else being equal, I agree it's best to have a class's MRO in the stubs be as accurate as it can possibly be, but that shouldn't come at any cost.

**Comment by tungol** [comment]
Would you like me to put up an MR reversing the change?

**Comment by AlexWaygood** [comment]
I would prefer that, yes :-)

**Pull request merged**
