### PR TITLE
os.path: isabs takes AnyStr, not just unicode

### PR DESCRIPTION
**Pull request by durin42**
Noticed this while running pytype on Mercurial.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Don't they all?

**Comment by gvanrossum** [comment]
Also, when something is declared as taking unicode (in the PY2 stubs) then it actually also takes str/bytes. Can you show an example that failed with unicode but passed with AnyStr? I can't think of any.

**Comment by matthiaskramm** [comment]
@durin42 encountered this problem running pytype, not mypy. The example is simple:

```
os.path.isabs('foo.txt')
```

> Also, when something is declared as taking unicode (in the PY2 stubs) then it actually also takes str/bytes. 

We should document all these special rules.
(This one sounds like a mypy peculiarity that leaked into typeshed. Bound to happen, but let's start a list.)

**Comment by gvanrossum** [comment]
OK, let's close this (too specific) PR and continue the discussion at #270 (to document the rules) and also https://github.com/python/typing/issues/208. See also https://github.com/python/mypy/issues/1141.

**Comment by durin42** [comment]
Works for me. Thanks!

**Pull request closed without merging**
