### PR TITLE
Port decimal stub to Python 2

### PR DESCRIPTION
**Pull request by youtux**
Python 2/3 specific code has been commented and TODOs were added, according to https://github.com/python/typeshed/pull/94#issuecomment-189408778.

### CODE REVIEW

**Comment by gvanrossum** [comment]
I apologize for the advice I gave earlier. I think it's better to have separate decimal.pyi files for 2.7 and 3 after all. The number of sections with version-specific comments in this version scares me.

**Comment by youtux** [comment]
Yeah, the single-file strategy would make sense if mypy supported version-specific comments, but until that moment it's better to split.

**Comment by gvanrossum** [comment]
I'm really sorry, I had to roll this back because there were some deficiencies. For example:
- `__div__` and `__rdiv__` were missing
- comparison to float should be possible

**Comment by youtux** [comment]
I'll try to fix it as soon as I can. Thank you for pointing that out.

**Pull request merged**
