### PR TITLE
Improve type for setdefault()

### PR DESCRIPTION
**Pull request by JelleZijlstra**
- With one argument, it may return None
- With two arguments, it returns the default's type or the dict's value type.
- Also remove incorrect `= ...` from `pop()`. The one-argument case has its own overload.

Context: https://github.com/python/typing/discussions/1033#discussioncomment-1986359

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Actually, this is not correct: one-argument setdefault() should only be allowed if the dict's value type is compatible with `None`. But I don't know if there's a way to express that in the current type system.

**Comment by AlexWaygood** [comment]
> Actually, this is not correct: one-argument setdefault() should only be allowed if the dict's value type is compatible with `None`. But I don't know if there's a way to express that in the current type system.

It's not correct, but I think it's better than the current situation, in which mypy is falling back to the other overload and confidently proclaiming that a variable has a completely incorrect type.

**Comment by JelleZijlstra** [comment]
Yes, I think this change is still an improvement. I added a comment to make it explicit.

**Review by AlexWaygood — APPROVED** [review]

**Review by hauntsaninja — COMMENTED** [review]
Could do it with evaluated types :-)

Would `(self: MutableMapping[_KT, _T | None], __key: KT) -> _T | None` work?

**Comment by JelleZijlstra** [comment]
That works! Test case with mypy:
```
from typing import Any


d: dict[int, str] = {}
d2: dict[int, str | None] = {}
d3: dict[int, Any] = {}

reveal_type(d.setdefault(1))
reveal_type(d.setdefault(1, "x"))
reveal_type(d2.setdefault(1))
reveal_type(d2.setdefault(1, "x"))
reveal_type(d3.setdefault(1))
reveal_type(d3.setdefault(1, "x"))

# stdlib/setdefault.py:8: error: Too few arguments for "setdefault" of "MutableMapping"
# stdlib/setdefault.py:8: note: Revealed type is "builtins.str*"
# stdlib/setdefault.py:9: note: Revealed type is "builtins.str*"
# stdlib/setdefault.py:10: note: Revealed type is "Union[builtins.str, None]"
# stdlib/setdefault.py:11: note: Revealed type is "Union[builtins.str, None]"
# stdlib/setdefault.py:12: note: Revealed type is "Union[Any, None]"
# stdlib/setdefault.py:13: note: Revealed type is "Any"
```

**Pull request merged**
