### PR TITLE
Add stubs for some of the most heavily used parts of six.moves 

### PR DESCRIPTION
**Pull request by timabbott**
This is a cleaned up version of the part of https://github.com/python/typeshed/pull/21 that actually has existing stubs.  It passes mypy tests on my machine.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Please ignore the Travis CI failure (I followed the instructions for setting it up and then got distracted).

Did you run mypy's tests with this or should I try that?

**Comment by timabbott** [comment]
I ran mypy's `python3.5 runtests.py` and it passed; not sure if that is complete

**Comment by gvanrossum** [comment]
Tim, I've got passing tests now (though they don't test everything yet). Can you merge and repush the PR?

**Comment by timabbott** [comment]
OK rebased (and CI tests passed)

**Pull request merged**
