### PR TITLE
Fixed the signature of six.raise_from()

### PR DESCRIPTION
**Pull request by agronholm**
The type definition of raise_from() should cover the use case for "raise ... from None".

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Can you also change this in the Python 3 stubs for six?

**Comment by JelleZijlstra** [comment]
Otherwise looks good.

**Comment by agronholm** [comment]
I didn't realize Python 3 had separate stubs for six.

**Comment by agronholm** [comment]
Also the return type should be `NoReturn`, yes?

**Comment by JelleZijlstra** [comment]
Good call no `NoReturn`. Yes, we should probably merge the six stubs at some point.

**Pull request merged**
