### PR TITLE
google.protobuf for python 3

### PR DESCRIPTION
**Pull request by smessmer**
This allows usage of the google.protobuf type stubs from python 3 code.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks for the PR! What have you done to test that these stubs work right in Python 3?

**Comment by smessmer** [comment]
We're using these in one of our projects, where they work fine. However, coverage is very likely incomplete.

**Comment by JelleZijlstra** [comment]
Thanks. I noticed there are a ton of functions like `protobuf/wrappers_pb2.pyi:    def FromString(cls, s: str) -> FloatValue: ...`. Do those really take `str`, not `bytes` in Python 3? I don't have an easy way to check.

**Comment by smessmer** [comment]
They probably take `bytes`, but I don't have an easy way to check either. I did change a few call sites from `str` to `bytes` where we used them and I know they're actually meant to be `bytes`.

**Comment by JelleZijlstra** [comment]
Is it reasonable to assume that all `FromString` methods take the same type?

**Comment by smessmer** [comment]
I'm unsure. `MergeFromString` and `ParseFromString` in `Message` take type `Any`.

**Comment by gvanrossum** [comment]
PS. See also #2157.

**Comment by nipunn1313** [comment]
All `FromString` methods do in fact take bytes. They take in a serialized input.
FromString is a bit of a misnomer in python3, but the naming was designed for python2.
 
I believe that google.protobuf uses the same code for both python2 and python3, so as long as we use `bytes` and `Text`, we shouldn't have (in theory) any typing issues.

That being said, unexpected things do occur. I'm not sure there's a worthwhile way for us to derisk all of these up front.

In #2174 - I made a similar diff which replaced all instances of str -> bytes.

**Comment by JelleZijlstra** [comment]
I merged #2174 instead.

**Pull request closed without merging**
