### PR TITLE
py313: mark Linux-only decimal allowlist entries as unfixable for now

### PR DESCRIPTION
**Pull request by aminalaee**
Just to test with the pipeline

### CODE REVIEW

**Comment by AlexWaygood** [comment]
I suggest that instead of trying to "fix" the Linux-only allowlist entries here, we move them to a separate section of the allowlist with a comment explaining why we shouldn't try to fix them at this point in time.

**Comment by aminalaee** [comment]
Yeah I think that makes sense, I initially started this PR to double-check what I'm seeing is right. I didn't want to start another discussion in the CPython repo (yet) 😅

**Comment by AlexWaygood** [comment]
It definitely seems like the `setup-python` build doesn't install the `_decimal` extension for CPython 3.13.0b1. I'm not sure whether that's also going to be the case for 3.13.0b2 without changes at `setup-python`, or whether CPython has since made changes that mean that 3.13.0b2 will be okay.

@erlend-aasland, would you be able to clarify that at all? https://github.com/python/cpython/issues/115119 is a long issue thread, and I'm not quite sure what the status is right now, as a non-expert in CPython's build system 😄

**Comment by erlend-aasland** [comment]
3.13.0b2 build system will fall back to the CPython vendored (but deprecated) libmpdecimal library, so unlike 3.13.0b1, 3.13.0b2 should have the `_decimal` C extension.

See also:

- python/cpython#119217

**Comment by AlexWaygood** [comment]
Thanks so much @erlend-aasland! @aminalaee, for the Linux-only stubtest allowlist entries, let's just do what I suggested in https://github.com/python/typeshed/pull/12061#issuecomment-2139332045 for now, in that case :-)

**Review by AlexWaygood — APPROVED** [review]
Thanks!

**Pull request merged**
