### PR TITLE
socket: rework to match docs more closely, improve accuracy on linux

### PR DESCRIPTION
**Pull request by hauntsaninja**
Match the documentation more closely

Fixes some of #8101 , in particular I no longer see any missing constants on the Linux machines I have access to

### CODE REVIEW

**Comment by hauntsaninja** [comment]
(This PR might be a little tricky to review, but I'm fairly confident. We check socket with stubtest quite tightly on macOS and Windows, and I've manually confirmed we fix stuff without regressions on Linux. Primer is also good)

**Review by srittau — APPROVED** [review]
LGTM, when skimming over it and going by your comment and the primer output. Please merge in a day or two, unless someone else wants to do a deep review.

**Review by AlexWaygood — APPROVED** [review]
Haven't done a proper review here (and I can't without access to a Linux machine :), but this all looks highly plausible, and I trust your judgement + stubtest!

How many stubtest errors would there be in CI if we removed the blanket allowlist entries for linux now, do you know? Is it low enough that we could remove the [blanket entries](https://github.com/python/typeshed/issues/8101#issuecomment-1789438742) and just enumerate all the errors? (Doesn't need to be done in this PR, I'm just curious!)

**Comment by hauntsaninja** [comment]
Yes, just enumerating all the errors would be great. There's still quite a few errors... this PR only eliminates ones that are certainly errors, where we're missing things in the stubs.

The cases where we're missing things at runtime are trickier, because I don't know whether that's just the Linux machines I have access to or if it's real. So I might try to whittle down what I can, and when I give up I'll just allowlist how many ever are left.

**Pull request merged**
