### PR TITLE
AsyncIterator.__anext__ can be any Awaitable object

### PR DESCRIPTION
**Pull request by graingert**
https://peps.python.org/pep-0525/#support-for-asynchronous-iteration-protocol

### CODE REVIEW

**Comment by graingert** [comment]
I think this also applies to AsyncGenerator

**Comment by graingert** [comment]
Yep they're all specified as returning Awaitable:

https://peps.python.org/pep-0525/#asynchronous-generator-object

I think this PR needs reverting https://github.com/python/typeshed/pull/7105

**Comment by AlexWaygood** [comment]
> I think this PR needs reverting #7105

Yes, I think that's probably right. stubtest is complaining because these are all `async def` functions at runtime (but wouldn't be in the stub with this PR merged), but the return type for abstract interfaces should be broader. I've filed https://github.com/python/mypy/pull/12343 to relax that stubtest check.

**Comment by graingert** [comment]
It would be nice if "real" `async def agenfn(...): ... yield` had a stricter type which did have Coroutine `asend/aclose`

**Comment by AlexWaygood** [comment]
> It would be nice if "real" `async def agenfn(...): ... yield` had a stricter type which did have Coroutine `asend/aclose`

Not sure I understand, sorry

**Comment by graingert** [comment]
> > It would be nice if "real" `async def agenfn(...): ... yield` had a stricter type which did have Coroutine `asend/aclose`
> 
> Not sure I understand, sorry

Oh this already exists as `types.AsyncGeneratorType`

**Pull request closed without merging**
