### PR TITLE
Update `turtle` to 3.12

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/python/cpython/blob/3.12/Lib/turtle.py

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Oh, stubtest is failing for the one in the global scope. Can't immediately see why, though.

**Comment by sobolevn** [comment]
Because `turtle` uses some magic in `_make_global_funcs`, I am trying to figure out if this is correct.

**Comment by sobolevn** [comment]
I find missing default and kw-only translated into positional-or-keyword as problems. I will report a bug to `cpython`.

**Comment by AlexWaygood** [comment]
Why don't you revert the global-namespace `teleport` changes for now, until the CPython change is fixed? Then we can merge this now, and deal with the last remaining change later

**Comment by sobolevn** [comment]
Sure!

**Comment by AlexWaygood** [comment]
Thanks!

**Pull request merged**
