### PR TITLE
Improve flask-cors stubs

### PR DESCRIPTION
**Pull request by kasium**

### CODE REVIEW

**Comment by kasium** [comment]
Mhm, I thought it's now possible to include 3rd party packages

**Comment by AlexWaygood** [comment]
> Mhm, I thought it's now possible to include 3rd party packages

We implemented the necessary changes in the stub-uploader repo, but there are some further changes required to typeshed's CI before this will be possible (as you can see).

**Comment by kasium** [comment]
Thanks for the update. Let me close the PR for now

**Comment by AlexWaygood** [comment]
#5768 is the issue to track this :)

**Pull request closed without merging**
