### PR TITLE
Added SupportsAnnotations protocol for `get_type_hints`

### LINKED ISSUE #4678: get_type_hints `obj` argument type seems too restrictive
The current type hints is:
```python
def get_type_hints(
    obj: Callable[..., Any], globalns: Optional[Dict[str, Any]] = ..., localns: Optional[Dict[str, Any]] = ...
) -> Dict[str, Any]: ...
```

The `Callable[..., Any]` seems really restrictive. The function works for example on an entire module, if you have a module such as:

```
# foo.py
VAR: str
```

The following code works fine and as expected:
```
import typing
from . import foo

typing.get_type_hints(foo)
# {'VAR': <class 'str'>}
```

However, there's a warning raised:
```
Argument 1 to "get_type_hints" has incompatible type Module; expected "Callable[..., Any]"
```

The fix seems easy, but I'm also wondering if there are other cases not covered by `Callable`. The function body seems to just call `getattr(obj, '__annotations__')` so I'm wondering if setting a type other than `Any` is even doable?

### PR DESCRIPTION
**Pull request by rohitkg98**
Fixes #4678 

Implemented a `SupportsAnnotations` protocol to use in `get_type_hints` argument.
The implementation does mention specific allowed types but `SupportsAnnotations` seems more apt.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
You'll need to make SupportsAnnotation private (or move it to _typeshed). Also could you confirm whether this works? I don't know that mypy understands what does and does not have __annotations__ attributes.

**Comment by hauntsaninja** [comment]
Although looking at typeshed it looks like we just define `__annotations__` on object (even though that's not necessarily true). Maybe we should just loosen this to object and not use a protocol?

**Comment by rohitkg98** [comment]
Oh, so it works for all types! The implementation does throw an error if the argument has no attribute `__annotations__`. Instead of loosening, how about using a Union of these types, mentioned in the implementation:

```python
_allowed_types = (types.FunctionType, types.BuiltinFunctionType,
                  types.MethodType, types.ModuleType,
                  WrapperDescriptorType, MethodWrapperType, MethodDescriptorType)
```

**Comment by rohitkg98** [comment]
closing this PR and creating a new one with above mentioned changes

**Pull request closed without merging**
