### PR TITLE
`tensorflow` fix `tensorflow.VariableSynchronization`

### PR DESCRIPTION
**Pull request by hoel-bagard**
See documentation [here](https://www.tensorflow.org/api_docs/python/tf/VariableAggregation)

@hmc-cs-mdrissi

### CODE REVIEW

**Review by hmc-cs-mdrissi — APPROVED** [review]
Good catch.

**Comment by hmc-cs-mdrissi** [comment]
General typeshed maintainer on tf prs I've marked approved. Those are ones I think look good for final review and being landed.

I'll review other tf prs after a few get merged.

**Comment by JelleZijlstra** [comment]
Is it worth investigating why stubtest didn't catch this?

**Comment by JelleZijlstra** [comment]
> Is it worth investigating why stubtest didn't catch this?

Possibly just because tensorflow defines this enum in some weird dynamic way. I looked at it though and can confirm these values are right.

**Pull request merged**
