### PR TITLE
Complete requests.packages.urllib3.exceptions stubs

### LINKED ISSUE #6054: requests.packages.urllib3.exceptions stubs are incomplete (e.g. SNIMissingWarning is missing)
`from requests.packages.urllib3.exceptions import SNIMissingWarning` is valid import.
It's part of  module public API: https://github.com/urllib3/urllib3/blob/d8eabf304190c62766e05c79ef44be7ff94cfbcb/src/urllib3/exceptions.py#L260

Yet mypy complains: `error: Module "requests.packages.urllib3.exceptions" has no attribute "SNIMissingWarning"  [attr-defined]`

### PR DESCRIPTION
**Pull request by jpy-git**
Closes #6054.

Complete implementation of: https://github.com/urllib3/urllib3/blob/d8eabf304190c62766e05c79ef44be7ff94cfbcb/src/urllib3/exceptions.py#L260

### CODE REVIEW

**Comment by jpy-git** [comment]
Closing as decided in #6859 to not type `requests/packages/urllib3` files (since it's just duplicating work from urllib3 stubs)

**Comment by Akuli** [comment]
The corresponding changes in `stubs/urllib3/` would be appreciated :)

**Comment by jpy-git** [comment]
> The corresponding changes in `stubs/urllib3/` would be appreciated :)

Good shout! Those look like they don't have these updates yet so will update those instead 😄

**Comment by srittau** [comment]
The urllib3 stubs are just of a copy of the `requests.packages.urllib3` stubs at the moment, so any improvements are welcome!

**Comment by jpy-git** [comment]
Thanks I've made a separate PR #6865 to update the stubs in `urllib3.exceptions` instead 😄

**Pull request closed without merging**
