### PR TITLE
Remove most consistency checks and split builtins.pyi into py2/3 files

### PR DESCRIPTION
**Pull request by srittau**
Drop unnecessary version info branches from builtins. Replace Text with str in Python 3 branch.

Partly addresses #4674

### CODE REVIEW

**Comment by srittau** [comment]
I am not sure why pytype is failing. Cc @rchen152

**Comment by rchen152** [comment]
@srittau I think you just need to add 2/builtins.pyi and 3/builtins.pyi to pytype_exclude_list: https://github.com/python/typeshed/blob/master/tests/pytype_exclude_list.txt. pytype doesn't need to be able to parse the builtins pyis, since we maintain our own.

**Comment by srittau** [comment]
> @srittau I think you just need to add 2/builtins.pyi and 3/builtins.pyi to pytype_exclude_list: https://github.com/python/typeshed/blob/master/tests/pytype_exclude_list.txt. pytype doesn't need to be able to parse the builtins pyis, since we maintain our own.

Thank, I completely missed the exclude list.

**Review by hauntsaninja — COMMENTED** [review]
Thanks for doing this! Maybe we should keep the consistency checks for the Python 3 backports? (mock, dataclasses, contextvars)

**Comment by srittau** [comment]
I considered leaving them in, but decided against it, for several reasons:

* I don't know how actively the backports are maintained. This means that we need to check changes in the standard lib against the third party implementation as well.
* Keeping python 2 branches in the python 3 stubs makes them harder to maintain. Especially with unicode support.
* I don't expect many changes to the python 2 part of the stubs. I also don't expect python 2 users to use many newer features of those libraries.

**Comment by srittau** [comment]
Addendum: I eventually plan to clean up the stubs to remove python 2 branches and `Text` types. This wouldn't work with consistency checks still enabled.

**Review by hauntsaninja — APPROVED** [review]
Sorry, I meant the Python 3 to Python 3 backports (so actually just dataclasses and contextvars). Totally on board with dropping Python 2.

**Pull request merged**
