### PR TITLE
Add execution_options to Session.get()

### PR DESCRIPTION
**Pull request by srittau**
Also use builtin.type instead of typing.Type

### CODE REVIEW

**Comment by srittau** [comment]
Example for #4820. Leaving open for now for experiments.

**Comment by srittau** [comment]
This looks much better. We need to fix the stubtest warnings, but should do that outside this PR.

**Comment by srittau** [comment]
1.4.29 was released a few hours ago, so I assume the new stubtest errors are due to that. Will have a look later.

**Review by Akuli — APPROVED** [review]
`execution_options` seems to be a dict, but it isn't clear to me what mapping protocol would make sense the most for this, and `Any` is much better than a missing argument.

**Pull request merged**
