### PR TITLE
pathlib2: most of the methods support the "unicode" type.

### PR DESCRIPTION
**Pull request by ppentchev**
With only two exceptions - see my much-too-late-but-still pathlib2 fix at
https://github.com/ppentchev/pathlib2/commit/a75493d48d971ad5f0858abb25c7e6598deb560f -
all the pathlib.Path and pathlib.PurePath methods will automatically
reencode Unicode strings (the "unicode" Python 2.x type) when passed as
arguments.

This may be tested with the following tool:

  https://devel.ringlet.net/devel/pathlib2/pathlibtest.py

Closes: #5726

### CODE REVIEW

**Review by srittau — CHANGES_REQUESTED** [review]
Nit: Use `Text` rather than `Union[str, unicode]`. Also, could you update the version in `METADATA.toml` while you're updating these stubs?

**Comment by hauntsaninja** [comment]
(I'm forgetting my Python 2, but) `Text` isn't equivalent to `Union[str, unicode]`, are you suggesting to use `Union[str, Text]` instead of `Union[str, unicode]`?

**Comment by ppentchev** [comment]
Ah, good point about using Text! I guess it shows that I made some of these changes in the middle of the night :)

Okay, so there are one or two functions where I changed a straight-up `str` argument to `Union[str, unicode]` - I guess it's best to change those to `Text`. However, @srittau, what would you like me to do about most of the places where this is already a `Union[str, PurePath]` - should I change them to `Union[Text, PurePath]` for simplicity, or explicitly list them as `Union[str, unicode, PurePath]` as they are in my current version?

Thanks for looking at this!

**Comment by srittau** [comment]
Please use `Union[Text, ...]`. `Text` has slightly different semantics that `Union[str, unicode]` (although not really in argument types).

**Comment by ppentchev** [comment]
Thanks again, @srittau; pushed.

**Comment by ppentchev** [comment]
Let me know if you'd like me to squash all of these into a single commit and force-push, or leave them as they are.

**Comment by srittau** [comment]
Just leave them as is as that makes it easier to review. We squash on merging to master.

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
