### PR TITLE
Add typing.ClassVar (fixes #888)

### LINKED ISSUE #888: ClassVar is missing
`typing.ClassVar` was added in Python 3.5.3, but it's missing in typeshed. Since mypy 0.470 supports PEP 526, it'd be really nice to have a possibility to use it, even without declared semantics (I believe this is something mypy devs should implement anyway).

### PR DESCRIPTION
**Pull request by miedzinski**
As title says. Resolves #888.

### CODE REVIEW

**Comment by gvanrossum** [comment]
To resolve #888, this should also be added to stdlib/2/typing.pyi.

**Comment by miedzinski** [comment]
Looks like adding `import sys` to stdlib/2/typing.pyi causes

```stdlib/2/types.pyi:16: error: Cannot determine type of 'long'```

Should I ignore it or remove version check from stdlib/2? Is it actually needed there? Python docs mention it was added in 3.5.3. I think it could be clarified in [CONTRIBUTING](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#stub-versioning) file.

**Comment by gvanrossum** [comment]
Oh, actually this should not be conditional at all.

--Guido (mobile)

**Comment by miedzinski** [comment]
That makes more sense. :) There are comments in that stub that convinced me that `ClassVar` shouldn't be defined on Python <3.5.

```
# TODO: Several types should only be defined if sys.python_version >= (3, 5):
# Awaitable, AsyncIterator, AsyncIterable, Coroutine, Collection, ContextManager.
# See https: //github.com/python/typeshed/issues/655 for why this is not easy.
```

```
# TODO: ContextManager (only if contextlib.AbstractContextManager exists)
```

https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#stub-versioning doesn't help either.

**Comment by gvanrossum** [comment]
That comment refers to types that are defined in the language or in other parts of the stdlib, and only appear in newer Python versions. But ClassVar is unconditionally defined in typing.py, so it will work whenever a new enough typing.py is present. (True, it won't exist in the stdlib version for Python 3.5.0--3.5.2, but that's where that section in CONTRIBUTING.md applies -- it does exist in the stdlib for 3.5.3.)

Anyway, this still requires changes to mypy as well -- we're tracking that in https://github.com/python/mypy/issues/2771.

**Pull request merged**
