### PR TITLE
[stubsabot] Bump Markdown to 3.4.*

### PR DESCRIPTION
**Pull request by hauntsaninja**
Release: https://pypi.org/project/Markdown/3.4.1/
Homepage: https://Python-Markdown.github.io/

If stubtest fails for this PR:
- Leave this PR open (as a reminder, and to prevent stubsabot from opening another PR)
- Fix stubtest failures in another PR, then close this PR

### CODE REVIEW

**Comment by hauntsaninja** [comment]
https://github.com/Python-Markdown/markdown/blob/master/docs/change_log/release-3.4.md

**Comment by AlexWaygood** [comment]
@leven-cn, would you be interested in helping review this? Are there any changes new in 3.4 that are missing from this PR? :)

**Review by leven-cn — APPROVED** [review]
It seems that all changes new in *3.4* are included in this PR.

**Comment by AlexWaygood** [comment]
Thanks for helping out @leven-cn!

**Pull request merged**
