### PR TITLE
Don't trigger mypy_primer from commits created by pre-commit.ci

### PR DESCRIPTION
**Pull request by Akuli**
Description copied from #6382 :

> If pre-commit makes a change immediately after a PR has been made, it's important that the stubtest/mypy/pytype/pyright checks are run again, as line numbers might have changed. However, there's no reason to start a new run of mypy_primer, since pre-commit will make no substantative changes to a PR, only cosmetic changes, and that shouldn't affect the diff from mypy_primer.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Thanks!

I think you'll need to make a more substantive change to properly demonstrate that it works — as it is, pre-commit is undoing all your changes to the standard library, meaning that under the _current_ rules, mypy_primer won't be run on the push by pre-commit, since it is only run on PRs that alter files in the standard library.

Try adding a pointless `TypeVar` in a black-incompatible way, or something 🙂

**Comment by Akuli** [comment]
>mypy_primer won't be run on the push by pre-commit, since primer is only run on PRs that alter files in the standard library.

It ran anyway, so to me it looks like it runs when a commit changes the stdlib, even if the pull request as a whole doesn't. I have added a useless TypeVar too.

**Comment by AlexWaygood** [comment]
> It ran anyway, so to me it looks like it runs when a commit changes the stdlib, even if the pull request as a whole doesn't. I have added a useless TypeVar too.

No, it _finished_ running on your push that had black-incompatible syntax, and the bot commented the diff accordingly, but it did _not_ start a second primer run after pre-commit pushed _its_ commit, which changed the PR so that it no longer affected the stdlib

**Comment by AlexWaygood** [comment]
Anyway, LGTM — thanks!

**Pull request merged**
