### PR TITLE
Add `TODO` to support `Concatenate` in `curses`

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/python/cpython/blob/main/Lib/curses/__init__.py#L94

### CODE REVIEW

**Comment by sobolevn** [comment]
No idea what is going on: `stdlib/email/message.pyi:13: error: Cannot determine type of "Any"  [has-type]`

**Comment by AlexWaygood** [comment]
I've just filed #7019

**Review by Akuli — APPROVED** [review]
I have used `Concatenate` once before, and it was in a situation very similar to this.

**Comment by sobolevn** [comment]
@Akuli but I've only added a comment 🤔 
Looks like something else is broken.

**Comment by Akuli** [comment]
Yes, the CI failure is unrelated.

**Pull request merged**
