### PR TITLE
Move asyncio from 3.4 to 3

### PR DESCRIPTION
**Pull request by srittau**
Split from #2303, because this move makes pytest tests fail.

### CODE REVIEW

**Comment by srittau** [comment]
I still have no idea why this simple move from `stdlib/3.4` to `stdlib/3` fails the pytype tests. I had a quick glance at the pytype source, but did not spot anything obvious. @rchen152, could you have a look?

**Comment by gvanrossum** [comment]
Perhaps pytype doesn't look in the 3.4 directory so this is the first time it's encountered asyncio. The error message printed definitely looks like a bug in pytype, so I'm calling in @rchen152 -- perhaps there's a way to crank up the verbosity of the tests to make it easier to debug?

**Comment by srittau** [comment]
Found it. I forgot to update `tests/pytype_blacklist.txt`, which blacklists `asyncio/tasks.pyi`.

**Comment by gvanrossum** [comment]
Cool! So it was a pre-existing issue after all. :-)

**Pull request merged**
