### PR TITLE
colorama: Preserve input type for `wrap_stream`

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Implementation looks like this:

```python
def wrap_stream(stream, convert, strip, autoreset, wrap):
    if wrap:
        wrapper = AnsiToWin32(stream,
            convert=convert, strip=strip, autoreset=autoreset)
        if wrapper.should_wrap():
            stream = wrapper.stream
    return stream
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
My motivation here is to make that error in Black go away :)

**Review by AlexWaygood — APPROVED** [review]
If I understand correctly, in some circumstances this actually returns a `colorama.ansitowin32.StreamWrapper` instance rather than the object that was passed in. But `colorama.ansitowin32.StreamWrapper` objects just [delegate nearly all attribute access to the underlying stream anyway](https://github.com/tartley/colorama/blob/21c4b94fe21ce29c85c896ace828da24b7527641/colorama/ansitowin32.py#L18-L20). So it basically comes to the same thing, and it's probably not worth worrying about.

**Comment by JelleZijlstra** [comment]
@AlexWaygood the stub reflects that, the function returns a union. Thanks for taking a look!

**Comment by AlexWaygood** [comment]
> @AlexWaygood the stub reflects that, the function returns a union. Thanks for taking a look!

Hah, so it does :)

**Pull request merged**
