### PR TITLE
Expose curses.BUTTON5_* in Python 3.10

### PR DESCRIPTION
**Pull request by lancelote**
New in Python 3.10

- [bpo-39273][1]: ncurses does not include BUTTON5_* constants
- [`curses.getmouse()` documentation][2]
- PR python/cpython#17996: Expose BUTTON5_* constants in the curses module if available

**Note:** I wasn't sure whether `version_info` check should be surrounded by the empty lines or not here. `black` is fine in either case so I followed an example from the same file where version check is used between the constants without extra empty lines

https://github.com/python/typeshed/blob/2255a6fdc807934a6fa1857fe3963db92f526651/stdlib/_curses.pyi#L60

[1]: https://bugs.python.org/issue39273
[2]: https://docs.python.org/3.10/library/curses.html#curses.getmouse

### CODE REVIEW

**Comment by Akuli** [comment]
Seems like MacOS doesn't have `curses.BUTTON5_PRESSED` and similar constants. Portability section in linux `getmouse(3)` seems to explain this: "These  calls  were designed for ncurses(3NCURSES), and are not found in       SVr4 curses, 4.4BSD curses, or any other previous version of curses."

We generally prefer false negatives (type check passes but running code errors) over false positives (code runs but type check errors), so I'd suggest adding the new constants to `tests/stubtest_whitelists/darwin-py310.txt`.

**Comment by Akuli** [comment]
Now that I think about it, we might as well use something like `if sys.version_info >= (3, 10) and sys.platform != "darwin"`, along with an appropriate comment.

**Comment by lancelote** [comment]
Thank you for taking a look at it @Akuli 🙏

I have my doubts about the best wording for the comment, please ping me if you don't like the current version and I'll change it.

**Review by Akuli — APPROVED** [review]

**Comment by srittau** [comment]
> I have my doubts about the best wording for the comment, please ping me if you don't like the current version and I'll change it.

No need to change it, but for future reference: I don't think the comment would be needed at all, the code is quite clear. Platform checks like this are quite common in typeshed.

**Pull request merged**
