### PR TITLE
Support for response hooks

### PR DESCRIPTION
**Pull request by ikonst**
Adds support for response hooks, i.e.
```py
import requests

def _response_hook(response: requests.Response) -> Any:
   pass

session = requests.session()
session.hooks['response'] = _response_hook
```

### CODE REVIEW

**Comment by ikonst** [comment]
Actually, this is wrong too, since the callable actually gets:
- 1 positional argument typed `requests.Response`
- named arguments:
  - `stream: Bool`
  - `timeout: Optional[int]`
  - `verify: Bool`
  - `cert: Optional[???]`
  - `proxies: OrderedDict`

**Comment by rowillia** [comment]
@JelleZijlstra Mind taking a look at this?

**Comment by JelleZijlstra** [comment]
I just got back from vacation; I'll take a look after I take care of some other backlogs.

**Comment by JelleZijlstra** [comment]
Is there documentation for this feature? http://docs.python-requests.org/en/master/user/advanced/?highlight=hook#event-hooks suggests only response hooks exist.

Also, can you fix the merge conflict? It's with your other PR that I just merged in.

**Comment by ikonst** [comment]
@JelleZijlstra You're absolutely right. `'response'` is all there is. I fixed the typeshed accordingly. Also, fixed to indicate that `Session.hooks` is not optional, since:
```
>>> import requests
>>> s = requests.session()
>>> s.hooks is not None
True
```

**Comment by JelleZijlstra** [comment]
Thanks! Could you fix the build failures?

**Pull request merged**
