### PR TITLE
move _operator classes to operator

### PR DESCRIPTION
**Pull request by tungol**
This matches what they call themselves at runtime.

### CODE REVIEW

**Comment by tungol** [comment]
After some experimentation, the pytype failure seems to be related to the circular dependency. I'm not yet sure why this one is a problem when other circular dependencies have passed without issue.

**Comment by tungol** [comment]
I created a minimal reproduction of the pytype error in https://github.com/tungol/pytype-error-reproduction and opened an issue with pytype here: https://github.com/google/pytype/issues/1797

Interestingly, it only occurs if the file with ParamSpec is processed before the other one in the circular dependency loop.

**Review by srittau — APPROVED** [review]

**Comment by srittau** [comment]
Seems fine to me, but I've marked it as deferred for now, until the pytype problem is addressed.

**Comment by frigus02** [comment]
https://github.com/python/typeshed/pull/12778 should unblock this.

**Pull request merged**
