### PR TITLE
Update adapters.pyi

### PR DESCRIPTION
**Pull request by KalleDK**
The cert can be
* A string / bytes which is a path to a certfile
* A tuple with two string / bytes, where the first is the certfile and the second is a keyfile
* None (optional)

The tuple could be anything indexable, but there are strict requirement to actualle have two items, don't know if there is something more generic

See https://github.com/psf/requests/blob/main/requests/adapters.py#L242-L248

### CODE REVIEW

**Comment by KalleDK** [comment]
I can rebase to a single commit, if it's wanted

**Comment by AlexWaygood** [comment]
> I can rebase to a single commit, if it's wanted

No need — we'll use github's "squash and merge" feature to merge it, which will combine all commits into a single commit on master :)

**Comment by KalleDK** [comment]
One thing I noticed was the use of Text | bytes and not AnyStr? Any reason or simply typing from before AnyStr was introduced?

**Comment by AlexWaygood** [comment]
> One thing I noticed was the use of Text | bytes and not AnyStr? Any reason or simply typing from before AnyStr was introduced?

`AnyStr` is a `TypeVar`, which is different to `Text | bytes` (a union expression).

Having said that, `Text` shouldn't really be used in the `requests` stubs at all (it should be `str | bytes` rather than `Text | bytes`). The `requests` stubs used to support Python 2, but no longer do, but we haven't got round to changing `Text` to `str` in the `requests` stubs yet.

**Comment by KalleDK** [comment]
Ah okay - then I wont change anymore :D Just got annoyed when I had to make a subclass of the HTTPAdapter and the send args didnøt make sense :)

**Pull request merged**
