### PR TITLE
fix type of selenium.webdriver.chrome.webdriver

### PR DESCRIPTION
**Pull request by PabloLION**
Add the `service` init param for the latest selenium `selenium.webdriver.chrome.webdriver.

https://github.com/SeleniumHQ/selenium/blob/3f75c6bc10caf67c606a2f74855320907927973e/py/selenium/webdriver/chrome/webdriver.py#L39

### CODE REVIEW

**Comment by PabloLION** [comment]
Also added the typing for `option` param

**Comment by PabloLION** [comment]
## Observation
- the import sort is legit.
- the other `Check third party stubs with stubtest` action is failed incorrectly.

**Comment by JelleZijlstra** [comment]
I haven't looked but if these are new arguments, you may need to update the version in the METADATA.toml file for this package.

**Comment by Akuli** [comment]
Note that the stubs are for selenium 3. It wouldn't make sense to create stubs for selenium 4, because it comes with its own type annotations.

**Comment by PabloLION** [comment]
@Akuli I didn't know that. Sorry. I think the code I referred to is from selenium 5. So this PR is useless.
By the way, could you help me with disabling it from VScode. It's giving an error when I create a `driver = webdriver.Chrome(service=service)` that Pylint reports an error "No parameter named "service".
Thanks

**Comment by JelleZijlstra** [comment]
Are you sure it's Pylint and not Pylance or Pyright? It's possible that they have a bug where they use the typeshed stubs for Selenium 3 when they should use the package's native annotations instead.

**Comment by Akuli** [comment]
Actually, I'm no longer sure if we should have selenium 4 stubs: https://github.com/SeleniumHQ/selenium/issues/9480

On the one hand, they don't have a `py.typed` file, which would tell type checkers to just look at the source code instead of stubs. On the other hand, they might add one soon.

**Comment by PabloLION** [comment]
@JelleZijlstra , thanks. It's Pylance. Maybe I should create an issue if it is what you said.

**Comment by PabloLION** [comment]
@akuli Do you want to create an issue in their repo? for the `py.typed` Or should I do it?

**Comment by PabloLION** [comment]
I'm not very clear if we can close this PR. Maybe some of you can confirm and do it.

**Comment by srittau** [comment]
I guess we should wait for the discussion in SeleniumHQ/selenium#9480 to know how to proceed.

**Pull request closed without merging**
