### PR TITLE
Run pyright on matrix of platforms and python versions

### PR DESCRIPTION
**Pull request by jakebailey**
Pyright 1.1.115 has flags to specify the platform and python version. This modifies the wrapper script to pass argv through and adds the matrix to the workflow.

I'm not sure how "good" it is to run a big matrix like this, but they only take a few seconds each.

### CODE REVIEW

**Comment by jakebailey** [comment]
I added 3.10 as pyright supports some of the upcoming features, but it seems like typeshed is missing a few things (which are probably stub conditional bugs). I'll remove that.

**Comment by jakebailey** [comment]
#5070 includes a fix for the lone failure in 3.6.

**Review by JelleZijlstra — APPROVED** [review]
Thanks, looks good! We can merge after the fixes from the other PR land.

**Comment by jakebailey** [comment]
:shipit:

**Pull request merged**
