### PR TITLE
Improve operator.mod

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by Akuli** [comment]
What does mypy_primer say if you do this to other similar functions too, e.g. `add`, `sub`, `mul`, `matmul`? I imagine mypy_primer might give a false sense of correctness, because `operator.mod` is not used very often, and seeing the output for more similar functions would show whether this is a good idea in general.

**Comment by AlexWaygood** [comment]
> What does mypy_primer say if you do this to other similar functions too, e.g. `add`, `sub`, `mul`, `matmul`?

The output from primer in #6448 shows that we get large numbers of false positives if we make e.g. `__sub__` have a different signature to `__add__` (see e.g. the `rotki` errors in the diff), because people often use functions in the operator module in highly dynamic ways, such that mypy can't be sure which function is going to be called. I don't think `__mod__` has the same problem,  though, as there's no "opposite" function similar to `__sub__` with respect to `__add__`.

However, I need to account for `__rmod__` for this to be merged...

**Comment by Akuli** [comment]
I still find it weird that `mod` is very different from `add` and `sub`. I will let other maintainers decide what to do with this.

**Comment by AlexWaygood** [comment]
> I still find it weird that `mod` is very different from `add` and `sub`. I will let other maintainers decide what to do with this.

My thinking is that __sub__ and __add__ would probably benefit from similar treatment to the one the binary-operator comparison functions have received. I can add that to this PR, if you like?

**Pull request closed without merging**
