### PR TITLE
Add back six.moves.range (Python 2)

### PR DESCRIPTION
**Pull request by JukkaL**
This was accidentally removed in #4287.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Maybe worth reporting the bug to isort?

**Comment by JelleZijlstra** [comment]
Sorry, what is the isort bug?

**Comment by hauntsaninja** [comment]
Not confirmed, but it seems like these regressions would have been caused by isort... Guessing it's something like it doesn't handle `from x import A as A, A as B` well.

**Comment by srittau** [comment]
Well, considering that this PR passed the isort test, I believe that it is fixed by the version we are currently using. There have been a lot of  isort updates, since the original reformat PR was applied.

**Pull request merged**
