### PR TITLE
Add unicode support to py2 string.Template.

### PR DESCRIPTION
**Pull request by rchen152**
I played around with this in a 2.7 interpreter, and as far as I
can tell, the template and mapping keys can be str or
unicode, the return type is str if all of the mapping values are
str, and the return type is unicode if at least one mapping value
is unicode.

### CODE REVIEW

**Comment by rchen152** [comment]
Fixed!

**Comment by msullivan** [comment]
This seems to break substitutions using just a `Dict[str, str]`, since mapping is not covariant in its key type.
```
template.py:5: error: Argument 1 to "substitute" of "Template" has incompatible type "Dict[str, str]"; expected "Mapping[unicode, str]"
```

**Comment by JelleZijlstra** [comment]
Makes sense. We should probably use `Union[Mapping[str, ...], Mapping[Text, ...]]`

**Comment by rchen152** [comment]
Sorry about that! I sent https://github.com/python/typeshed/pull/2888 to fix the type of `mapping`.

**Pull request merged**
