### PR TITLE
Add --threads argument to pyright cli

### PR DESCRIPTION
**Pull request by Avasam**
Available since https://github.com/microsoft/pyright/releases/tag/1.1.371 , crash fixed in https://github.com/microsoft/pyright/releases/tag/1.1.377 (https://github.com/microsoft/pyright/issues/8775)

### CODE REVIEW

**Review by srittau — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Does this actually speed things up much?
- Looking at runs of our pyright CI prior to this change, it seems like most jobs on the matrix took around 1m: https://github.com/python/typeshed/actions/runs/10999144438.
- But on this PR, it looks like most jobs on the pyright matrix took between 1m20s and 1m30s: https://github.com/python/typeshed/actions/runs/10997579100

So for our purposes, this argument might slow things down?

**Comment by Avasam** [comment]
> Does this actually speed things up much?

About a second locally (17.45s vs 18.81s average) running `python .\tests\pyright_test.py` on a Ryzen 7 5800X. Wanted to see if it could help the CI too, but it looks like it might not be the case.

Even if within the same GitHub action, there's 1-2s variance between jobs, `Run pyright with basic settings on all the stubs` is consistently over 10s longer on the second action.

I think we can revert, including the non-CI part (I'm not gonna fight for a ~1s improvement on a 16 logical core CPU when it might make others' run slower ^^" ).
Dunno if Eric would be interested in seeing these numbers or if that's just expected for GitHub actions.

**Comment by AlexWaygood** [comment]
> Dunno if Eric would be interested in seeing these numbers or if that's just expected for GitHub actions.

Without having looked into it at all: it might well be the kind of thing where a huge codebase with very large packages in it would get a speedup from `--threads`, but a repo of our size does not

**Comment by JelleZijlstra** [comment]
We already get a ton of parallelism from running so many different GH Actions; I think it makes sense that we don't get much gain from further parallelizing within each action. It might help more when run locally but the speedup @Avasam posted doesn't seem that compelling.

**Comment by AlexWaygood** [comment]
I opened #12690 to revert

**Pull request merged**
