### PR TITLE
stdlib: use PEP 604 in most places

### PR DESCRIPTION
**Pull request by hauntsaninja**
This uses PEP 604 in place of Optional and Union in most cases.

Script used to produce this (stuck with regexes and not lib2to3 or libcst or astor or whatever for fear of https://xkcd.com/1319):
```
import subprocess

commands = r"""
# some of these regexes are subsumed by later regexes, but doing things this way isolates the more
# complicated replacements to their own commits, where they can be inspected more thoroughly

# simple unions
fastmod -d stdlib --accept-all '\bUnion\[([\w\.]+), ([\w\.]+)\]' '$1 | $2'
fastmod -d stdlib --accept-all '\bUnion\[([\w\.]+), ([\w\.]+), ([\w\.]+)\]' '$1 | $2 | $3'
fastmod -d stdlib --accept-all '\bUnion\[([\w\.]+), ([\w\.]+), ([\w\.]+), ([\w\.]+)\]' '$1 | $2 | $3 | $4'

# unions with single level generics
fastmod -d stdlib --accept-all '\bUnion\[([\w\.]+)(\[[^\[\]]+\])?, ([\w\.]+)(\[[^\[\]]+\])?\]' '$1$2 | $3$4'
fastmod -d stdlib --accept-all '\bUnion\[([\w\.]+)(\[[^\[\]]+\])?, ([\w\.]+)(\[[^\[\]]+\])?, ([\w\.]+)(\[[^\[\]]+\])?\]' '$1$2 | $3$4 | $5$6'

# simple optionals
fastmod -d stdlib --accept-all '\bOptional\[([\w\.\| ]+)\]' '$1 | None'
# optionals with single level generics
fastmod -d stdlib --accept-all '\bOptional\[([^\[\]]+)\[([^\[\]]+)\]\]' '$1[$2] | None'

# unused imports
for x in $(rg '\bOptional\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '\s*from typing import Optional$' ''; done
for x in $(rg '\bOptional\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '^\s+Optional,$' ''; done
for x in $(rg '\bOptional\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '(from typing import )Optional, (.*)' '$1$2'; done
for x in $(rg '\bOptional\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '(from typing import.*), Optional' '$1'; done
for x in $(rg '\bUnion\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '\s*from typing import Union$' ''; done
for x in $(rg '\bUnion\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '^\s+Union,$' ''; done
for x in $(rg '\bUnion\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '(from typing import )Union, (.*)' '$1$2'; done
for x in $(rg '\bUnion\b' -c | grep stdlib | pyp 'x.split(":")[0] if x.endswith(":1") else None'); do fastmod -g $x --accept-all '(from typing import.*), Union' '$1'; done
"""

subprocess.check_call("git reset --hard origin/master", shell=True)
for cmd in commands.splitlines():
    print(cmd)
    subprocess.check_call(cmd, shell=True)
    try:
        subprocess.check_call("git diff --exit-code > /dev/null", shell=True)
    except:
        subprocess.check_call(["git", "commit", "--all", "-m", cmd])
subprocess.check_call("black stdlib; isort stdlib", shell=True)
subprocess.check_call(["git", "commit", "--all", "-m", "black and isort"])
```

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Hmm, looks like mypy and pyright both don't accept PEP 604 syntax in type aliases (at least, not without PEP 613). I guess I knew this about mypy https://github.com/python/mypy/issues/9880#issuecomment-765672469

**Comment by hoefling** [comment]
@hauntsaninja I can share a script I've used to update our internal stubs. Requires `libcst` though:
```py
import functools
import logging
import libcst as cst
from pathlib import Path

rootdir = Path(__file__).parent / "stdlib"
none_node = cst.Name(value="None")


def main(where: Path = rootdir) -> None:
    try:
        from rich.logging import RichHandler

        fmt = "{message} ({funcName}, {filename}:{lineno})"
        handlers = [RichHandler()]
    except ImportError:
        fmt = "{asctime} [{levelname:5}] {message} ({funcName}, {filename}:{lineno})"
        handlers = None
    logging.basicConfig(
        level=logging.DEBUG,
        format=fmt,
        style="{",
        handlers=handlers,
    )
    logging.logThreads = 0
    logging.logProcesses = 0

    rewriter = PEP604Rewrite()
    for stub in rootdir.rglob("*.pyi"):
        logging.info("current file: %s", stub)
        stub_tree = cst.parse_module(stub.read_text())
        modified_stub_tree = stub_tree.visit(rewriter)
        stub.write_text(modified_stub_tree.code)


def bit_or(left: cst.BaseExpression, right: cst.BaseExpression) -> cst.BinaryOperation:
    return cst.BinaryOperation(
        operator=cst.BitOr(),
        left=left,
        right=right,
    )


def bit_or_none(node: cst.BaseExpression) -> cst.BinaryOperation:
    return cst.BinaryOperation(
        operator=cst.BitOr(),
        left=node,
        right=none_node,
    )


class PEP604Rewrite(cst.CSTTransformer):
    def transform(self, node: cst.Subscript) -> cst.CSTNode:
        if node.value.value == "Union":
            names = [element.slice.value for element in node.slice]
            new_node = functools.reduce(bit_or, names)
            logging.debug(
                "transformed Union: %r", cst.parse_module("").code_for_node(new_node)
            )
            return new_node

        if node.value.value == "Optional":
            new_node = bit_or_none(node.slice[0].slice.value)
            logging.debug(
                "transformed Optional: %r", cst.parse_module("").code_for_node(new_node)
            )
            return new_node
        return node

    def leave_ImportFrom(
        self, original_node: cst.ImportFrom, updated_node: cst.ImportFrom
    ) -> cst.CSTNode:
        if updated_node.module is not None and updated_node.module.value == "typing":
            # drop Optional & Union imports if present
            names = [
                alias
                for alias in updated_node.names
                if alias.name.value not in ("Union", "Optional")
            ]
            if names:
                # case `from typing import ..., Union`
                names[-1] = names[-1].with_changes(comma=cst.MaybeSentinel.DEFAULT)
                return updated_node.with_changes(names=names)
            else:
                # case `from typing import Union` etc
                return cst.RemoveFromParent()
        return updated_node

    def leave_Subscript(
        self, original_node: cst.Subscript, updated_node: cst.Subscript
    ) -> cst.CSTNode:
        logging.debug("%r", cst.parse_module("").code_for_node(updated_node))
        return self.transform(updated_node)


if __name__ == "__main__":
    import sys

    sys.exit(main())
```

**Comment by srittau** [comment]
I think @Akuli has now converted most of typeshed.

**Comment by hoefling** [comment]
@srittau then I'm too late with the script; pity! Just disregard the above comment then.

**Comment by Akuli** [comment]
I converted most stubs in #5872. If you want, you can run both scripts and compare the results. My script did weird things to some files, and I just did some files manually after running the script.

**Comment by hoefling** [comment]
@Akuli I executed the script over the current master and the only files touched are those from `@python2`, so I think there's nothing left to do. Good job!

**Comment by srittau** [comment]
I think we could convert the Python 2 files as well, couldn't we?

**Comment by hoefling** [comment]
@srittau this I can do :-)

**Comment by Akuli** [comment]
@hoefling Would you like to modify your script to instead check whether the stubs use the new syntax, and add it to CI? If you want, I can do that too.

**Comment by hoefling** [comment]
@Akuli no worries about pinging me! The script I pasted here is an overkill for the task anyway, since it uses `libcst` to actually modify the stubs. What @hauntsaninja proposes in #5903 is a much simpler solution.

**Pull request closed without merging**
