### PR TITLE
typing module private base classes

### PR DESCRIPTION
**Pull request by tungol**
I think there's general agreement here for including private base classes for the sake of MRO accuracy, and this is the last chunk of them that aren't represented in typeshed right now, so that's why this is an MR. That said, it's the last chunk for two reasons: 

a) it's the typing module
b) the level of churn in these version to version is high, and that means that the conditionally inheriting from object trick is being pushed pretty far.

Probably worth mentioning: TypeVar, TypeVarTuple, ParamSpecArgs, ParamSpecKwargs, and ParamSpec drop all their bases for 3.12+ because they were moved to a C implementation.

### CODE REVIEW

**Comment by tungol** [comment]
Not sure if this is salvageable, but I'll give it a shot.

**Comment by tungol** [comment]
The pydantic diffs looks plausible; they're deep in the weeds of the typing module.

Something about this is making pytype very sad still, however.

**Comment by tungol** [comment]
The pytype error is because of typing_extensions importing `_Final` from typing. That class isn't present in pytype's stub file for typing, and it throws an error about it.

**Comment by tungol** [comment]
https://github.com/google/pytype/pull/1839 to unblock

**Comment by tungol** [comment]
Also to note: pyright doesn't allow silencing it's unnecessary ignore warning on a per-line basis. I worked around this by ensuring that the relevant classes would always have redundant inheritance from object, but it's a pretty unfortunate hack.

**Comment by JelleZijlstra** [comment]
I feel this isn't worth doing. These base classes are private and highly unstable.

**Comment by tungol** [comment]
That's probably the only reasonable view of this. I'm glad I worked out what it would look like, but... yeah.

**Pull request closed without merging**
