### PR TITLE
Add cache_clear to lru_cache

### PR DESCRIPTION
**Pull request by ethanhs**
This will end up being used in mypy once we move some module search caching to lru_cache.

### CODE REVIEW

**Comment by eric-wieser** [comment]
Want to add `cache_info` too?

**Comment by ethanhs** [comment]
>Want to add cache_info too?

It is on the line above.

**Comment by eric-wieser** [comment]
Yep, I now see that!

**Comment by eric-wieser** [comment]
Regarding using it in mypy core - it's unfortunate that `@lru_cache` throws away the types of the arguments of the function it wraps.

**Comment by gvanrossum** [comment]
Maybe you meant a different issue?

**Comment by ethanhs** [comment]
@eric-wieser what about `typed=[True|False]`? Or are you thinking of something else?

**Comment by eric-wieser** [comment]
Good catch: wrong project, right number

**Pull request merged**
