### PR TITLE
Use sys.platform instead of comments

### PR DESCRIPTION
**Pull request by ymyzk**
Use of `sys.platform` is now recommended for platform-dependent APIs #2275. So, I update stubs which contains `# Windows only` or `# Unix only` to use `if sys.platform ...`.

### CODE REVIEW

**Comment by ymyzk** [comment]
To fix failing tests https://travis-ci.org/python/typeshed/jobs/397420897, should we update tests in mypy, or should we avoid using `sys.platform` for some APIs to fix failing tests?

**Comment by gvanrossum** [comment]
Hm, I see the problem. Many of the `O_*` flags are present on some platforms and not others, with a finer granularity than `sys.platform` can indicate. So there's a convention to check for presence of a specific flag, which you see in the failing example code. I think for the `O_` flags in particular it would be better to restore the original code (maybe add a clarifying comment as to why it's going against the recommendation).

**Comment by ymyzk** [comment]
I see the problem. I reverted stubs for `O_*` flags and add comments why we decided not to use `sys.platform` for now.

**Comment by JelleZijlstra** [comment]
I wonder if the same problem will happen with other flags changed in this PR. @gvanrossum perhaps you could check this PR against Dropbox's codebase to see if it introduces new mypy errors? (Our typed codebase doesn't tend to use low-level os features.)

**Comment by gvanrossum** [comment]
OK checking now...

**Comment by JelleZijlstra** [comment]
Thanks for checking!

**Comment by gvanrossum** [comment]
PS. In the future don't amend your commits during code review -- just push new commits, it's easier for the reviewers. They'll be squashed when we merge.

**Comment by ymyzk** [comment]
Sorry about that. I'll take care next time!

**Pull request merged**
