### PR TITLE
Fix type annotation of ast.NodeTransformer.generic_visit()

### PR DESCRIPTION
**Pull request by MapleCCC**
This pull request is aimed at address the issue #4482.

### CODE REVIEW

**Review by srittau — APPROVED** [review]
LGTM, although I'd like to have another opinion. Cc @JelleZijlstra @hauntsaninja

**Comment by JelleZijlstra** [comment]
The `Optional` is actually correct. See https://github.com/python/cpython/blob/master/Lib/ast.py#L484: it skips the AST node if the visit method returned None. This is also mentioned in the documentation: https://docs.python.org/3.8/library/ast.html#ast.NodeTransformer.

The default implementation of `generic_visit()` does indeed never return None, but the class is designed for subclassing, and it's acceptable for a subclass to return None from `generic_visit()`.

**Comment by MapleCCC** [comment]
I think @JelleZijlstra is right about subclassing and the information from documentation. I am not super familiar with type annotation system, the question is "Is the parent class method **required** to have a looser type annotation than the correspondiong subclass overriding method?". If the answer is yes, then we should probably close the PR.

**Comment by srittau** [comment]
@JelleZijlstra I think that is true for `NodeVisitor` (`NodeTransformer`'s base class), but not for the latter. Actually, `NodeTransformer` only overwrites `generic_visit()`, so overriding it again doesn't seem to make much sense to me. I think the statement in the docs refers to the `visit_XXX()` methods, not `generic_visit()`. That said, I don't have too much experience with the `ast` module, so I might misunderstand things.

**Comment by gvanrossum** [comment]
I reasoned like @srittau. While it's hard to be absolutely sure of the intention, I am willing to bet that this PR is a net improvement.

**Comment by JelleZijlstra** [comment]
OK, let's do it.

**Pull request merged**
