### PR TITLE
Improve locale

### PR DESCRIPTION
**Pull request by tharvik**
https://docs.python.org/3/library/locale.html

Also remove old stubs about it.

Commenting `locale.str` because of [mypy#2009](https://github.com/python/mypy/pull/2009).

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can you test the workaround I suggested in https://github.com/python/mypy/pull/2009?

**Comment by tharvik** [comment]
Tested in 0a3b7f8, but doesn't seems to help.

**Comment by gvanrossum** [comment]
Oh, the workaround is more complicated. You have to change *all* references to str with builtins.str or `_str`, using `import builtins; _str = builtins.str`.

**Comment by tharvik** [comment]
Ho, okay, a bit ugly but seems to work.

**Pull request merged**
