### PR TITLE
Use TypeIs for various stdlib functions

### PR DESCRIPTION
**Pull request by JelleZijlstra**
See #11453. This should start working when mypy 1.10 is released, which should be very soon.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Primer analysis:

- Lots of removed type ignores! That's a very positive sign.
- [pytest](https://github.com/pytest-dev/pytest/blob/fafab1dbfd2414c2282b558f0c7af9a7ad0318ab/testing/test_monkeypatch.py#L417): this is a false positive but a pretty understandable one. It monkeypatches `functools.partial` to not be a class, and then checks `inspect.isclass(functools.partial)`.
- [antidote](https://github.com/Finistere/antidote/blob/7d64ff76b7e283e5d9593ca09ea7a52b9b054957/src/antidote/lib/lazy_ext/_lazy.py#L164): I think something is going wrong with the `inspect.isfunction` call here that causes mypy to narrow `_kind` down too much. Need to investigate more.

**Comment by srittau** [comment]
Looks good to me. The mypy bug (if it turns out to be one) seems obscure enough that the improvements this brings are worth it.

**Comment by JelleZijlstra** [comment]
I tracked it down to a preexisting mypy bug: python/mypy#8869. Given that it's a bug that is not directly related to TypeIs, I agree this is worth merging.

**Comment by hauntsaninja** [comment]
Hooray!

**Pull request merged**
