### PR TITLE
ignore type for mock.pyi inheritance from Any

### PR DESCRIPTION
**Pull request by toejough**
**Problem**:
Any time I run `mypy --strict --ignore-missing-imports`, I get an error like `<site-packages>/lib/mypy/typeshed/stdlib/3/unittest/mock.pyi:34: error: Class cannot subclass 'Any' (has type 'Any')`

**Analysis**:
https://github.com/python/typeshed/issues/1446 complains about the inheritance from `Any`, among other things, but what's relevant to this PR is where the use of `# type: ignore` is followed everywhere else this inheritance happens.

I'm not sure if it's the "right" solution, but adding `# type: ignore` to `mock.pyi`'s use of `Any` resolves the error message I keep seeing.  It also passes all of the [tests requested](https://github.com/python/typeshed/blob/master/README.md#running-the-tests).

**Resolution**:
I added the same `# type: ignore` comment to the inheritance from `Any` in `mock.pyi` that is used in other places that that inheritance is done.

**Documentation**:
No docs modified/added for this change.

**Testing**:
Ran the [tests](https://github.com/python/typeshed/blob/master/README.md#running-the-tests) locally on osx 10.11.6, and they all passed.

**Impact**:
Patch - ignoring an illegal type inheritance that appears to work but is flagged by mypy (and is ignored in other areas of typeshed code).

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
See also #1446 (cc @ethanhs).

**Comment by gvanrossum** [comment]
The OP, in his comprehensive post, does not mention what flags he passes to mypy, but I suspect he uses `--strict`. This implies `--disallow-subclassing-any` which explains the error. I am not aware of any workarounds other than a `# type: ignore` comment. If you're worried that such a comment's significance will be lost in the future, add a `# TODO` comment on the line before, e.g.
```
# TODO: Get rid of the # type: ignore below.
# It is currently required to shut up mypy when run with `--strict`
# or `--disallow-subclassing-any`. The `Any` base class is currently
# the only way to allow passing an instance of `Mock` to functions
# expecting other classes (as is Mock's purpose)
```

**Comment by toejough** [comment]
Ooh, sorry, yes, I'm running `mypy --strict --ignore-missing-imports`.

I realize this "fix" is a little quick-and-dirty, but until a more correct solution is agreed upon, is there any downside to including it?  

With respect to people looking to typeshed for examples, the use of `Any` is present with or without the PR.  Could this be merged and a new issue opened to discuss/track the correct resolution?

I would like to be able to run `mypy --strict` on my own code without encountering failures due to typeshed code.

Ooh.  Is there somewhere I could look for guidance on the right way to write a test for ensuring `mypy --strict` doesn't error on typeshed code?  Is that kind of test something you guys would want?

**Comment by ethanhs** [comment]
@toejough considering a better solution is not evident right now this fix is fine, but please add a TODO comment please. Also the issue I opened tracks all subclassing from Any. As for making typeshed mypy --strict safe, we are still working on that, and will likely need to ignore some errors.

**Comment by toejough** [comment]
cool.  added.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
