### PR TITLE
Make args positional-only for applicable methods in ``list`` and ``tuple``

### PR DESCRIPTION
**Pull request by AlexWaygood**

### CODE REVIEW

**Comment by Akuli** [comment]
This is unnecessary. All arguments to `__dunder__` methods are implicitly positional-only.

**Comment by JelleZijlstra** [comment]
I believe that is true only for mypy.

**Comment by AlexWaygood** [comment]
> All arguments to `__dunder__` methods are implicitly positional-only.

That's surely not true for *all* dunder-method arguments. It's certainly not true for `__init__`, `__new__` and `__init_subclass__`. Those three are perhaps special cases to an extent, since they're all invoked during construction. But it's also not true for certain other dunder methods written in pure Python, [such as](https://github.com/python/typeshed/pull/6242#pullrequestreview-798299635) `numbers.Real.__round__` and `fractions.Fraction.__round__`.

Anyway, if it _is_ true that most arguments to dunder methods are implicitly positional-only, I'd argue that could be valuably added to typeshed's `CONTRIBUTING.md` file 🙂

**Comment by Akuli** [comment]
Sure, feel free to make a pull request that adds it to CONTRIBUTING.md.

I don't think this is mypy specific, because if a type checker doesn't make most dunder methods (obviously not `__init__` or `__new__`) implicitly positional-only, that would lead to a lot of LSP violations, even within typeshed.

**Comment by srittau** [comment]
I don't think we should add this to CONTRIBUTING. I also think it makes sense to mark these implicitly positional-only arguments as such: It improves documentation and it means that not every consumer of typeshed needs to implement that logic.

**Comment by AlexWaygood** [comment]
@Akuli, in this snippet, how does Mypy know to raise an error for `int.__add__`, but not for `Fraction.__round__`? Both are currently marked as positional-or-keyword in typeshed. Is the "implicitly positional-only" behaviour specific to dunder methods relevant to operator overloading, perhaps?

```
from fractions import Fraction
(2).__add__(x=3)
Fraction(1, 3).__round__(ndigits=3)
```

Mypy playground gist [here](https://mypy-play.net/?mypy=latest&python=3.10&gist=8ae09041b2a7c993f3171bbccd080906).

**Comment by Akuli** [comment]
With "implicitly positional only", I meant that this doesn't cause an LSP error:

```python
class Foo:
    def __round__(self, ndigits: int) -> float:
        return 12.34

class Bar(Foo):
    def __round__(self, lolwat: int) -> float:
        return 12.34
```

But it isn't like I thought, because it doesn't become an error if I use non-dunder methods instead, e.g. replace `__round__` with `asd`.

**Comment by JelleZijlstra** [comment]
Yes, mypy just doesn't check pos-or-keyword params for LSP.

**Comment by AlexWaygood** [comment]
> I also think it makes sense to mark these implicitly positional-only arguments as such: It improves documentation and it means that not every consumer of typeshed needs to implement that logic.

I agree with @srittau here. Typeshed isn't just used for MyPy, nor even just for type-checkers. It's also a useful resource for people who want to understand the standard library better, since the source code for cpython doesn't include any type hints at all (and since `help()` is often very uninformative about function signatures if the function is written in C). Inconsistencies, such as not having positional-only parameters marked as such, reduce the usefulness of typeshed's stubs in that regard.

I only intended to manually work through `builtins.pyi`, anyway, as I don't have the capacity to manually check the whole stdlib(!). I'm nearly finished on that front — are there any strong objections if I continue?

**Comment by JelleZijlstra** [comment]
> I'm nearly finished on that front — are there any strong objections if I continue?

Go for it!

It should be possible to find these things automatically in a lot of cases using stubtest, the mypy tool that we use to check stubs against their implementation. I think it's a bit permissive about positional-only args because historically we've not done a good job of reflecting pos-only args in typeshed. Also, for C functions that don't use argument clinic it's hard to know if the argument is positional-only.

**Pull request merged**
