### PR TITLE
add typing.ContextManager for 3.6+ only

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This fixes the easier part of #655.

Would it make sense to add a generic typing.ContextManager that exists in any Python version?

### CODE REVIEW

**Comment by gvanrossum** [comment]
> Would it make sense to add a generic typing.ContextManager that exists in any Python version?

I don't think so, since it doesn't exist at runtime.

**Comment by gvanrossum** [comment]
[Ahem, let me try that again.]

> Would it make sense to add a generic typing.ContextManager that exists in any Python version?

Maybe, but it'll take a long time until everyone has it (esp. Python 3.5 users). I do think there's some room for improvement, esp. since the stdlib name is apparently AbstractContextManager. But let's merge this PR without waiting for that.

**Comment by gvanrossum** [comment]
Don't merge yet, there may be a problem with this and our internal codebase.

**Comment by gvanrossum** [comment]
Ironically the issues I am seeing are due to Python 2 code importing ContextLib (inside `if MYPY`). Let me see what I can do about it.

**Comment by gvanrossum** [comment]
Sorry, I'm still waiting for a resolution on our end. This affects a fair amount of code.

**Comment by JelleZijlstra** [comment]
If it's easier to move things forward, I'd be happy to keep `contextlib.ContextManager` in typeshed for now, although we should eventually remove it.

I imagine it's going to be helpful for use cases like yours if `typing.ContextManager` existed for Python < 3.6, so it could be used as an ABC. I'll propose that on the typing tracker.

**Comment by gvanrossum** [comment]
OK, let's close this and keep typing.ContextManager in all versions, per https://github.com/python/typing/pull/422.

**Comment by JelleZijlstra** [comment]
We'll still need some changes here since currently there is no ContextManager in typing.pyi. I'll reopen this and make the appropriate changes once the typing PR is resolved.

**Comment by gvanrossum** [comment]
Oh wait, you're right. This PR removes it from contextlib. We may still want that but first we want to add it to typing, so I can switch our usages to the latter.

FWIW the usages seem to be of the form
```
if MYPY:
    from contextlib import ContextManager
.
.
.
def foo(a):
    # type: (...) -> ContextManager[...]
    ...
```

**Pull request closed without merging**
