### PR TITLE
Changed Iterables to Sequences

### LINKED ISSUE #4508: Incorrect type for first argument of concurrent.futures.wait
First argument of `concurrent.futures.wait` is declared here as `fs: Iterable[Future[_T]]`.
However, CPython calls `len(fs)` (to check if all futures are already done), which fails at runtime for iterables that doesn't have `__len__`, such as generators.

The [documentation](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.wait) doesn't say anything about this argument type:

> Wait for the `Future` instances (possibly created by different `Executor` instances) given by *fs* to complete.

But, based on CPython implementation, `Iterable` is too broad for this argument.

### PR DESCRIPTION
**Pull request by rohitkg98**
- Narrowed the type according to the use case

Fixes #4508

### CODE REVIEW

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
This isn't correct for as_completed, at least for master:
https://github.com/python/cpython/blob/d4b9edd5052a2d9ae3d2be69975cc933afb37737/Lib/concurrent/futures/_base.py#L222

**Comment by rohitkg98** [comment]
can you please elaborate? I don't see how using Sequence could be a problem here unless we want to allow Iterables as an argument, and we can because it gets converted into a set anyways, but I would prefer to uniform API hence Sequence at both places.

**Comment by hauntsaninja** [comment]
We want to allow Iterables as an argument. When in doubt, typeshed tries to type as per the actual implementation, rather than making editorial / aesthetic judgements. [Hyrum's Law](https://www.hyrumslaw.com) definitely ends up applying to CPython users.

**Comment by rohitkg98** [comment]
Yea, that makes a lot of sense. Hyrum's Law looks very cool too. Thanks for the help!

**Comment by rohitkg98** [comment]
Let me know if any more changes are required.
Should this thing also move to implementation instead of types?
As in, should we convert the Iterable argument to set inside the code? Instead of using Sequence here?

**Review by hauntsaninja — APPROVED** [review]
Thanks, this looks good. I'll merge once CI completes.

It seems reasonable that concurrent.futures.wait could be modified to accept an Iterable. It looks like it already creates a set in the code, it just doesn't stick it in a variable / use it when making the `len(fs)` check. I don't know if that's intentional, to me it looks like it would actually be a little bit better if it used the equivalent of `len(set(fs))`. But anyway, that's outside typeshed's scope; to change the CPython implementation you'd have to open an issue on bugs.python.org and make your case.

**Pull request merged**
