### PR TITLE
Add ret_type keyword argument for croniter

### PR DESCRIPTION
**Pull request by ruuda**
The croniter `__init__` method does have a `ret_type` keyword argument. See also https://github.com/kiorky/croniter/blob/062fdc0/src/croniter/croniter.py#L66.

I am not the author of the croniter package. I did not obtain consent from the authors, as the version on Pypi points to kiorky/croniter which has issues disabled, and taichino/croniter from which it was forked seems abandoned. Though we can ask the author here: @kiorky, are you okay with this?

### CODE REVIEW

**Comment by kiorky** [comment]
@taichino/croniter isnt abandoned.

**Comment by gvanrossum** [comment]
OK, waiting for permission from @taichino then.

**Comment by ruuda** [comment]
Apologies @taichino. For some reason GitHub shows that ba29379 from 2012 is the most recent commit when I visit the project page, which lead me to believe it was abandoned. I filed a bug report.

**Comment by kiorky** [comment]
hehe, my fault, i tend to fake commit dates to avoid tracing.

**Comment by kiorky** [comment]
Which permissions do you want ? No pr is open yet ?

**Comment by kiorky** [comment]
( @ruuda @gvanrossum the active croniter maintainer is me.)

**Comment by ruuda** [comment]
It is about this PR, which modifies a stub that contains type annotations for croniter. The readme of this repository says:

> NOTE: When you're contributing a new stub for a package that you did not develop, please obtain consent of the package owner (this is specified in PEP 484). The best way to obtain consent is to file an issue in the third party package's tracker and include the link to a positive response in your PR for typeshed.

**Comment by kiorky** [comment]
Well no open issue on croniter is done but, just go ahead with that PR, you have my go.

**Comment by gvanrossum** [comment]
Thanks!

**Pull request merged**
