### PR TITLE
typing: type decorators so they don't count as untyped lines

### PR DESCRIPTION
**Pull request by terencehonles**
This change allows Mypy to report lines decorated with `@overload` as typed. I'm not sure how the other type analysers handle `@overload` or the other decorators, or how they report type coverage, but rather than special case Mypy it made sense to just type typeshed.

I also noticed type variables `_F` and `_C` were basically the same so I uniqued the code to use `_F`.

### CODE REVIEW

**Review by hauntsaninja — APPROVED** [review]
Looks good to me, hopefully CI agrees!

**Comment by hauntsaninja** [comment]
CI does not agree. `black` is easy to mollify, and `stubtest` just wants you to change some argument names. `pyright` is a little more concerning here...

**Comment by terencehonles** [comment]
> CI does not agree. `black` is easy to mollify, and `stubtest` just wants you to change some argument names. `pyright` is a little more concerning here...

Thanks for approving the run, I'll adjust them and see what I can do about the last

**Comment by terencehonles** [comment]
I pushed the changes for everything except pyright, I'll have to look at that later, but "hopefully" that's an issue unrelated to this PR.

**Comment by terencehonles** [comment]
I'm able to repro locally and looking at the error it probably is related to this PR :confused:. I'll see what I can dig up, but I'll have to leave this to run some errands.

**Comment by hauntsaninja** [comment]
cc @erictraut (this might sort of be the opposite of the issue we ran into with OrderedDict earlier today :-) )

**Comment by erictraut** [comment]
Pyright (and presumably other type checkers) need to special-case the handling of "overload". This PR changes the definition of "overload" from an object to a function, and pyright no longer recognizes it and executes its special-case logic. I've updated pyright to accommodate this change in [this commit](https://github.com/microsoft/pyright/commit/35a86355150f354ee70e97b4adaf24fa67a7bfda).

Short of completely disabling the pyright tests, this will require a new build of pyright to fix. If you are in a hurry to get this PR merged, I can publish a new release of pyright right away. (I normally publish every 3 or 4 days, and the last version was published less than a day ago.)

**Comment by hauntsaninja** [comment]
Thanks as always for the quick fix! I'm not in any special hurry, three days is a totally reasonable amount of time to wait (and in the case of #5345 we'll need to wait a day or so for pytype anyway)

**Comment by terencehonles** [comment]
Thanks @erictraut! Definitely no rush for me, I just bumped against it when playing around with some things and figured it would be a pretty simple fix.

**Comment by erictraut** [comment]
I just published a new version of pyright (1.1.138) that fixes this issue. You'll need to update the version number from "1.1.136" to "1.1.138" in "pyright_test.py" and in "tests.yml".

**Comment by hauntsaninja** [comment]
Thanks,  https://github.com/hauntsaninja/typeshed/pull/new/pyr

**Pull request merged**
