### PR TITLE
nodes.pyi: Set fields as a Tuple

### PR DESCRIPTION
**Pull request by utkarsh2102**
This is just a part of #3197.  
After this is merged, I'll fix for other classes as well.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This is not syntactically valid.

**Comment by utkarsh2102** [comment]
> This is not syntactically valid.

Though I'm aware of the problem at hand, but I'm kinda unsure how to go about it?

**Comment by utkarsh2102** [comment]
Hi, @srittau, @JelleZijlstra,
How can I go about this?

**Comment by utkarsh2102** [comment]
Hi @srittau,  
Could you help in here a bit?

**Comment by srittau** [comment]
@utkarsh2102 The literal syntax does not contain field names, just the types. In this case you could go with either `Tuple[str, str, str]` or `Tuple[Literal["node"], Literal[...`.

**Comment by srittau** [comment]
Closing for now, please reopen if you find time to work in this.

**Pull request closed without merging**
