### PR TITLE
See #1977: Delete DoneAndNotDoneFutures definition

### PR DESCRIPTION
**Pull request by matthewfranglen**
The generic type of the futures provided to the wait method cannot
currently be preserved through this definition. For now deleting the
unused NamedTuple is the best approach.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
`DoneAndNotDoneFutures` does actually exist in the file at runtime, so I don't see why we should delete it, even if we can't use it in the return type of `wait`.

**Comment by gvanrossum** [comment]
Because it's essentially a type definition? It's undocumented, and I suspect it's an implementation detail.

**Comment by gvanrossum** [comment]
Also the definition as given here is wrong -- it's a tuple of two *sets* of futures...

**Comment by JelleZijlstra** [comment]
OK, that makes sense.

**Comment by bw-matthew** [comment]
Thank you for merging this PR.

Since the `DoneAndNotDoneFutures` named tuple has been described as an implementation detail, is it appropriate to name the two fields that it exposes in [the documentation](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.wait)?

Personally this documentation would be consistent with the types that are defined in `_base.pyi` if it did not name the two fields of the tuple and there was a tiny bit of example code showing decomposition.

**Comment by gvanrossum** [comment]
Let's just reconsider once we can have generic NamedTuple.

**Pull request merged**
