### PR TITLE
Allow passing complex to complex constructor

### PR DESCRIPTION
**Pull request by ethanhs**

### CODE REVIEW

**Review by Akuli — APPROVED** [review]
I find it weird that `complex` isn't a valid `SupportsComplex`, but this matches runtime behavour.

**Comment by JelleZijlstra** [comment]
Interesting:
```
In [79]: complex(real=1j)
Out[79]: 1j
```

Even this works:
```
In [80]: complex(real=1j, imag=1)
Out[80]: 2j
```

**Comment by ethanhs** [comment]
@Akuli yeah, perhaps I should file a b.p.o for complex to have a `__complex__`.

**Comment by ethanhs** [comment]
@JelleZijlstra oh interesting I didn't think of the second one! You can even do

```
>>> complex(real=7, imag=3j)
(4+0j)
```

**Comment by ethanhs** [comment]
https://bugs.python.org/issue24234

We are not the first to run into this :)

**Comment by hauntsaninja** [comment]
Also related: veky's comment on https://bugs.python.org/issue38629 and my comment on https://github.com/python/mypy/issues/3186#issuecomment-762121456

**Comment by ethanhs** [comment]
Also based on the docs: https://docs.python.org/3/library/functions.html#complex

It looks like the __new__ should probably be rewritten.

**Comment by JelleZijlstra** [comment]
Yes, that would be more strictly correct. Though I'm not sure I'd want to enable people to write code like your `complex(real=7, imag=3j)` :) – that confused me for a while before I realized it's 7 + 3j * j.

**Comment by ethanhs** [comment]
Well, we could always leave the second one as just `float`, which is probably the sensible thing to do.

**Pull request merged**
