### PR TITLE
Add stubs for markupsafe

### PR DESCRIPTION
**Pull request by rowillia**
This is needed for Flask.

Permission was given here:
https://github.com/pallets/itsdangerous/issues/69#issuecomment-246516942

### CODE REVIEW

**Comment by ambv** [comment]
Thanks!

You can ignore stubs for tests. Since this is a very small library, could you go through the source to add actual types to the stubs? Currently they're all "Any" which limits their usefulness.

**Comment by JukkaL** [comment]
Just adding types to some of the more commonly used features can be quite useful.

**Comment by rowillia** [comment]
@JukkaL @ambv Added types.

**Comment by ambv** [comment]
Alright, this looks good. I didn't cross-check it with sources, if there's issues, we'll learn in practice and improve forward. Thanks!

**Pull request merged**
