### PR TITLE
os.popen: add encoding argument for 3.11

### PR DESCRIPTION
**Pull request by JelleZijlstra**
python/cpython#92374

### CODE REVIEW

**Review by hauntsaninja — COMMENTED** [review]
Might need to be changed if https://github.com/python/cpython/pull/92415 is merged

**Review by hauntsaninja — COMMENTED** [review]
Also am I missing something obvious or does the original PR not do anything?

**Comment by Akuli** [comment]
We shouldn't merge this until the argument actually works in cpython. If they ship a broken argument to the next release, it's better to leave it out from the stubs.

**Comment by JelleZijlstra** [comment]
The argument was removed again: python/cpython#92836.

**Pull request closed without merging**
