### PR TITLE
Correct annotation of headers parameter of HTTP event handlers

### PR DESCRIPTION
**Pull request by mthuurne**
The standard library implementation (I checked Python 3.8.10) passes `http.client.HTTPMessage` for the headers parameter, which does not implement `Mapping[str, str]`: the value type is `Any` instead of `str` and `__iter__()` is missing. Also `HTTPMessage` has a lot of methods that are not present in `Mapping`.

Please read the individual commit comments for more details.

### CODE REVIEW

**Review by srittau — APPROVED** [review]

**Comment by asottile** [comment]
fwiw, this makes it a little annoying to mock an `HTTPError` since you have to feed through the right mapping type instead of using a plain dict

**Comment by srittau** [comment]
> fwiw, this makes it a little annoying to mock an `HTTPError` since you have to feed through the right mapping type instead of using a plain dict

I actually had the same issue.  [The documentation](https://docs.python.org/3/library/urllib.error.html) just states:

> **headers**
> The HTTP response headers for the HTTP request that caused the HTTPError.

The stdlib always initializes `HTTPError` with a `Message`, so having additional guarantees is a nice bonus. On the other hand I can see the use case for initializing your own `HTTPError`s with a plain dict. I wouldn't mind (partly) reverting this, but have no strong feelings.

**Comment by mthuurne** [comment]
Maybe custom `Protocol` would be a solution? Reverting everything would just move problems to a different place, namely when you want to create `HTTPError`s in request handlers.

**Comment by asottile** [comment]
it wasn't too difficult to update for me, though `email.message.Message` doesn't have a terribly convenient way to construct from a dictionary that I could find so I ended up with:
```python
def _msg(dct: Mapping[str, str]) -> email.message.Message:
    msg = email.message.Message()
    for k, v in dct.items():
        msg[k] = v
    return msg
```

**Pull request merged**
