### PR TITLE
macpath, os/path, posixpath and ntpath should basically be the same files

### PR DESCRIPTION
**Pull request by davidhalter**
Only the implementations differ.

e.g. in `3/posixpath.pyi`, `sep: str` was missing.

### CODE REVIEW

**Comment by srittau** [comment]
I haven't had time to look at this and think about it in detail, but the correct way to ensure that files stay consistent is to add them to `tests/check_consistent.py`. This is also the reason that CI fails, since ` stdlib/2/ntpath.pyi` and `stdlib/2/os2emxpath.pyi` do now differ.

**Comment by davidhalter** [comment]
Ok. So I fixed the issues you were pointing out. I agree that there were still flaws in my first try.

Now I think it's a bit better. All the Python 2 files are matching and as well as the Python 3 files. This is also part of the consistency file. IMO it's probably better in the future to use symlinks or something to not duplicate everything, but that's a different issue.

The previous state was that `2/os/path.pyi` and `3/os/path.pyi` were forced to match, because of the consistency test. This makes no sense at all. We could just move everything to `2and3/os/path.pyi` in that case.

IMO now it's better. There are separate files for Python 2 and 3. This makes more sense, since e.g. `walk` has been removed in Python 3.

If you want to investigate why I feel like this change was necessary, have a look at the original `os.py` file. There you will find two imports: `import posixpath as path` and `import ntpath as path`. macpath seems to be ignored there. No idea why. A bit later you will see a `sys.modules['os.path'] = path`, which makes importing those files possible.

**Comment by JelleZijlstra** [comment]
Also fyi, the reason we use check_consistent.py instead of symlinks is that we were unable to find a way to make symlinks work properly in Windows.

**Comment by davidhalter** [comment]
Ok. I copied *path.pyi to 2and3/ and left the previously existing 2/os/path.pyi and 3/os/path.pyi files as they were.

**Pull request merged**
