### PR TITLE
Added missing attributes of typing.Generator and typing.AsyncGenerator

### PR DESCRIPTION
**Pull request by vlasovskikh**

### CODE REVIEW

**Comment by vlasovskikh** [comment]
The problem reported by Mypy looks like a bug in it:
```
stdlib/2/types.pyi:16: error: Cannot determine type of 'long'
```

**Comment by gvanrossum** [comment]
So the mypy test for Python 2.7 fails with "stdlib/2/types.pyi:16: error: Cannot determine type of 'long'" .

I think this points to a disturbance of the initial import cycle. Before this PR, that import cycle (for Python 2) is `mypy_extensions abc typing _weakrefset builtins`. With this PR, it becomes `types mypy_extensions abc typing _weakrefset builtins` (i.e. `types` was added). I guess this means that `types` is being processed *before* `builtins` is processed, but since `types` references `long` (which is defined in `builtins` as an alias to `int`). I'm not sure of a fix yet.

**Comment by vlasovskikh** [comment]
Should I keep my pull requests to typeshed that don't pass the tests due to Mypy bugs open?

**Comment by gvanrossum** [comment]
> Should I keep my pull requests to typeshed that don't pass the tests due to Mypy bugs open?

Yes, but we should fix mypy or find work-arounds in typeshed for them.

**Comment by JelleZijlstra** [comment]
To move this forward, could we just change the offending types to `Any` for now?

**Comment by gvanrossum** [comment]
If it's just a matter of types.pyi referencing long, maybe it could be changed to int? There really is very little difference between the two even in Python 2.7.

**Comment by gvanrossum** [comment]
I will submit a PR that removes the `long` reference from stdlib/2/typing.pyi and then I will merge this.

**Comment by JelleZijlstra** [comment]
I'm doing some local testing to make sure this change doesn't break mypy in any way now.

**Comment by gvanrossum** [comment]
Me too (against internal code here).

**Comment by JelleZijlstra** [comment]
mypy_selftest passes.

**Comment by gvanrossum** [comment]
It's fine for us too. I'll do the honors.

**Comment by vlasovskikh** [comment]
@gvanrossum Thanks!

**Pull request merged**
