### PR TITLE
Use __new__ instead of __init__ for some builtin classes

### LINKED ISSUE #4514: Perhaps declare a `__new__` instead of an `__init__` for `str` and other similar types
At https://github.com/python/typeshed/blob/23300837329ec7f14578344f40f72d866b342dd8/stdlib/2and3/builtins.pyi#L446 , an `__init__` is declared for `str`

As I understand it, `str` has no proper `__init__`, it only has a proper `__new__`.

I came to this, thinking again about this issue in another repository: https://github.com/python/mypy/issues/9405

### PR DESCRIPTION
**Pull request by srittau**
Closes #4514 #2630 #2686

I tested this against our internal codebases and against the example in #1464 and it seems to works fine.

### CODE REVIEW

**Comment by srittau** [comment]
@hauntsaninja There is something strange going on with the mro here, see the comment in the stubtest whitelist. In my opinion, this special case (quirk in Python?) should be handled by stubtest (or mypy?), instead of putting the enums on the whitelist. What do you think?

An alternative is to override `__new__` explicitly in `IntEnum`, `IntFlag`, and another enum I forgot in the stubs. That doesn't feel right to me, though, as the implementation doesn't do that either.

**Comment by gvanrossum** [comment]
I'm guessing that the Enum metaclass plunks a reference to `Enum.__new__` in the `__dict__` of all new `Enum` subclasses. I think here: https://github.com/python/cpython/blob/a33f2c2bae759fc9d06e1c032fd2026135f2df45/Lib/enum.py#L273

**Review by hauntsaninja — APPROVED** [review]
Oh interesting. I'd probably agree that this should be handled by stubtest / mypy.

**Comment by srittau** [comment]
@gvanrossum @hauntsaninja 

1. Good catch!
2. Yikes!
3. In that case I am not sure that stubtest needs fixing. Since every enum sub-class basically gets `Enum.__new__` assigned to it, manually overriding it in sub-classes that derive from both `int`/`str` and `Enum` might be the correct solution.

**Comment by hauntsaninja** [comment]
I was a little worried about this PR, so I ran mypy_primer:
```
(mypy_primer) ~/dev/mypy_primer master λ python -m primer --new v0.782 --old v0.782 --custom-typeshed-repo ~/dev/typeshed --new-typeshed dundernew --old-typeshed 98667b18 -o concise     
+ isort/output.py:561: error: "_LineWithComments" has no attribute "comments"

- src/aiortc/mediastreams.py:22: note:     def __init__(self, x: Union[str, bytes, SupportsInt, _SupportsIndex] = ...) -> int
+ src/aiortc/mediastreams.py:22: note:     def __new__(cls, x: Union[str, SupportsInt, _SupportsIndex] = ...) -> int

+ sphinx/builders/html/__init__.py:94: error: unused 'type: ignore' comment
+ sphinx/builders/html/__init__.py:117: error: unused 'type: ignore' comment
```

Seems fine!

**Pull request merged**
