### PR TITLE
Fix groupby with key=None

### PR DESCRIPTION
**Pull request by srittau**
Cf #2790

### CODE REVIEW

**Comment by srittau** [comment]
CI failures seem unrelated to this patch and related to mypy changes.

**Comment by ilevkivskyi** [comment]
Yes, this looks like a mypy bug. I am not sure however why it doesn't show in the internal tests (maybe our version of typeshed is a bit behind). I will try to fix it today or tomorrow.

**Comment by srittau** [comment]
This could be a combination of c8c6271365195b08e0c5eb6ed0b7fa792bbef986 (from #2762), which hasn't been synched with mypy yet and a subsequent change in mypy (python/mypy#6358?).

**Comment by JelleZijlstra** [comment]
Thanks for the quick fix!

**Pull request merged**
