### PR TITLE
Split and restore correct Python 2 version of cgi.pyi

### PR DESCRIPTION
**Pull request by srittau**
#5063 incorrectly applied the security fix to Python 2 versions of `cgi.pyi` as well. Split the stubs into Python 2 and 3 versions, restore the Python 2 version and clean up.

This PR is probably easiest reviewed commit by commit.

### CODE REVIEW

**Comment by srittau** [comment]
Once again a bit weird failure. While the Python 2 test succeeded when the stubs were not split, now it fails? And it's only complaining about the non-subscriptable `list`, but it's fine with `tuple`? I can investigate further, but maybe someone else has an idea why this happens.

**Comment by Akuli** [comment]
Minimal repro:

```
$ cat a.pyi
class Foo(list[int]):
    pass
$ mypy --python-version 3.10 a.pyi
Success: no issues found in 1 source file
$ mypy --python-version 3.9 a.pyi
Success: no issues found in 1 source file
$ mypy --python-version 3.8 a.pyi
a.pyi:1: error: "list" is not subscriptable
Found 1 error in 1 file (checked 1 source file)
$ mypy --python-version 2.7 a.pyi
a.pyi:1: error: "list" is not subscriptable
Found 1 error in 1 file (checked 1 source file)
```

**Comment by srittau** [comment]
Hmm, mypy probably doesn't recognize there as stubs when called directly on them. But the why do the checks succeed for 3.8, but not for 2.7? Possibly something we need to change in `tests/mypy_test.py`.

**Comment by Akuli** [comment]
The 3.8 test uses Python 3 stubs (not from `@python2` directory), and those don't have a class that inherits from something with `list[str]`.

**Comment by Akuli** [comment]
I guess the right thing to do would be to use `List[str]` instead and report yet another mypy bug.

**Comment by srittau** [comment]
But it did not fail before, when there was no separate Python 2 stub, which concerns me.

**Comment by Akuli** [comment]
That code was under `if sys.version_info < (3, 0):`.

**Pull request merged**
