### PR TITLE
third_part peewee

### PR DESCRIPTION
**Pull request by Trim21**
- [x] EXCLUDED
- [x] SQL
- [x] JOIN
- [x] DJANGO_MAP
- [x] OP
- [x] DQ
- [x] chunked
- [x] ImproperlyConfigured
- [x] Field
- [x] UUIDField
- [x] BinaryUUIDField
- [x] IPField
- [x] BlobField
- [x] DoubleField
- [x] TimeField
- [x] DateTimeField
- [x] BareField
- [x] DateField
- [x] DecimalField
- [x] BooleanField
- [x] AutoField
- [x] BigAutoField
- [x] TimestampField
- [x] CharField
- [x] FixedCharField
- [x] IntegerField
- [x] BigIntegerField
- [x] SmallIntegerField
- [x] FloatField
- [x] BitField
- [ ] BigBitField
- [x] TextField
- [x] ForeignKeyField
- [x] PrimaryKeyField
- [ ] ManyToManyField
- [x] IdentityField
- [x] Table
- [x] Tuple
- [x] Case
- [ ] Database
- [ ] MySQLDatabase
- [ ] SqliteDatabase
- [ ] PostgresqlDatabase
- [x] Value
- [ ] prefetch
- [x] Check
- [ ] Model
- [ ] DeferredThroughModel
- [ ] fn
- [x] Column
- [ ] SchemaManager
- [x] DataError
- [x] NotSupportedError
- [x] InterfaceError
- [x] DatabaseError
- [x] ProgrammingError
- [x] OperationalError
- [x] InternalError
- [x] IntegrityError
- [x] AsIs
- [ ] QualifiedNames
- [ ] Select
- [x] Cast
- [ ] ValuesList
- [ ] DoesNotExist
- [ ] Context
- [ ] Window
- [ ] Index
- [ ] ModelIndex
- [ ] CompositeKey
- [ ] DeferredForeignKey
- [ ] Proxy
- [ ] DatabaseProxy

### CODE REVIEW

**Comment by Trim21** [comment]
Thanks for your suggestions

**Comment by Trim21** [comment]
Most of code are generated by mypy stubgen, I'm still working on it.

**Comment by vmotso** [comment]
Hi there

My company is very interested in this PR.
@Trim21 can you tell us approximately when this PR is planned to be completed?
We will be very grateful.

Thanks

**Comment by Trim21** [comment]
I’m not sure. Feel free to start a new pr based on my existing work.





------------------ Original ------------------

**Comment by gvanrossum** [comment]
May I suggest that it’s probably better to publish this as a separate package following PEP 561.

**Comment by srittau** [comment]
Just a heads up: Next week we will reshuffle the layout of typeshed. This means that the files in this PR will also need to be moved. This shouldn't be much of a problem, though, as there should be no conflicts.

**Pull request closed without merging**
