### PR TITLE
subprocess: Make stdin, stdout & stderr Optional for py3 to match py2

### PR DESCRIPTION
**Pull request by JasonGilholme**
This addresses this issue:

https://github.com/python/typeshed/issues/3646

Jase

### CODE REVIEW

**Comment by JasonGilholme** [comment]
As a discussion point, I got kinda close to defining the runtime behavior a bit better with the following code:

```python

from typing import *


T = TypeVar('T')
U = TypeVar('U')
V = TypeVar('V')


class Popen(Generic[T, U, V]):

    stdin = T
    stdout = U
    stderr = V

    def __init__(self, stdin=None, stdout=None, stderr=None):
        # type: (T, U, V) -> None
        self.stdin = stdin
        self.stdout = stdout
        self.stderr = stder
```

When using that class, what ever types you pass into the constructor are used as the types for stdin, stdout and stderr which is pretty similar to what's going on with subprocess.Popen. The key difference being that the type passed to the init isn't exactly what ends up as stdin.  What it really needs to do is say that if it's not None, then make self.stdin not Optional but I couldn't figure out how to do that without trying to write a mypy plugin.

Are there any typing guru's in the wings that know any clever tricks?

**Comment by JelleZijlstra** [comment]
You can probably do this by overloading the `__init__` method and making Popen generic over some more typevars, but I'm not sure that's worth it.

**Comment by msullivan** [comment]
Hm. It was intentional that we did not do this, I think. I expect it to break a lot of our code.

**Comment by JasonGilholme** [comment]
Any idea what the reason behind the intention was?  I would expect the stubs to accurately reflect the runtime possibilities as close as possible.

**Comment by srittau** [comment]
@msullivan With Popen? I remember the discussion only about `sys.stdout` et al.

**Comment by msullivan** [comment]
Hm, maybe I don't actually care with Popen. I do care about it for subprocess.CompleteProcess, see: https://github.com/python/typeshed/blob/6394c7c335507b16b04b693cbcb10baa6670f511/stdlib/3/subprocess.pyi#L46-L49

**Comment by JasonGilholme** [comment]
I know what you mean about being tedious, but I think in the case of CompletedProcess we can be type safe and convenient as the args to init are just passed directly to the stdin and stdout instance vars.  The following snippet passes mypy, will type check your code based on the provided args to stdint / stdout and also ensure only appropriate types are passed to the constructor:

```pythonstub

from typing import *

OptionalStdOutT = TypeVar('OptionalStdOutT', bound=Optional[_FILE])
OptionalStdErrT = TypeVar('OptionalStdErrT', bound=Optional[_FILE])


class CompletedProcess(Generic[OptionalStdOutT, OptionalStdErrT]):

    stdout: OptionalStdOutT
    stderr: OptionalStdErrT

    def __init__(self, stdout: OptionalStdOutT = ..., stderr: OptionalStdErrT = ...) -> None: ...
```

Usage example:

```python
stdout = open('/tmp/out')

proc = CompletedProcess(stdout=stdout, stderr=None)

reveal_type(proc.stdout)
reveal_type(proc.stderr)

proc.stdout.readlines() . # Passes mypy
proc.stderr.readlines() . # Caught by mypy - attr-defined error cause None type doesn't have readlines
```

Unfortunately the same can't be applied to `Popen` as there's runtime logic which determines whether the resulting stdin/out/err vars are Optional or not.

Shall I make another PR for the above update to `CompletedProcess`?  It shouldn't change @msullivan's usages unless they actually have type errors - which is why we're using type checking in the first place.

**Comment by JelleZijlstra** [comment]
Nobody (well, almost nobody) is going to be constructing `CompletedProcess` objects directly though. It's important that we write the signature of `subprocess.run` (which is already a horrific series of overloads) in such a way that the type params to CompletedProcess are inferred directly.

**Comment by JasonGilholme** [comment]
I see.

If I understand correctly though, even if we nail the typing of the args to `subprocess.run`, the construction of the `CompletedProcess` object won't reflect that work because a) stderr & stdout share the same type var, yet they can be different individual types and b) we're not respecting the Optional component indicating that, even if the user provides None to subprocess.run for stderr/stdout, it will somehow be promoted to a type.

**Comment by BoboTiG** [comment]
Just to be sure, with this patch merged, my old code now fails on Mypy 0.770:
```python
with subprocess.Popen(["xclip", "-selection", "c"], stdin=subprocess.PIPE) as p:
    p.stdin.write(text.encode("utf-8"))
    p.stdin.close()
    p.wait()
```
The error:
```bash
error: Item "None" of "Optional[IO[bytes]]" has no attribute "write"
error: Item "None" of "Optional[IO[bytes]]" has no attribute "close"
```

My code is bad or the stub should be adapted?

**Comment by srittau** [comment]
I see the same problem in our own code and I worked around it using `assert p.stdin`. Maybe we should use @JelleZijlstra's suggestion and make `Popen` generic.

**Pull request merged**
