### PR TITLE
Add stubs for python-datemath

### PR DESCRIPTION
**Pull request by kasium**

### CODE REVIEW

**Comment by kasium** [comment]
Maybe somebody can support here:

```
stubs/python-datemath/datemath/__init__.pyi (3.9): pytype.load_pytd.BadDependencyError: Can't find pyi for 'arrow', referenced from 'datemath'
stubs/python-datemath/datemath/helpers.pyi (3.9): pytype.load_pytd.BadDependencyError: Can't find pyi for 'arrow', referenced from 'datemath.helpers'
```

python-datemath has a dependency on arrow which has type hints natively.

**Comment by srittau** [comment]
I suspect (but haven't verified) that this is a shortcoming in our pytype tests that don't install the dependencies when testing third-party stubs.

**Comment by hauntsaninja** [comment]
@kasium these are the CI errors I'd look at for now: https://github.com/python/typeshed/pull/5765/checks?check_run_id=3047893267

typeshed currently assumes that all stub dependencies are typeshed stub packages, and that's the reason for all the remaining CI failures. We talked about relaxing this in at least https://github.com/python/typeshed/issues/5618 and it's something we definitely should do — but we haven't yet and you might have to bear with us for a little bit while we figure it out :-)

**Comment by kasium** [comment]
@hauntsaninja thanks a lot for the help. I'll wait till you solve it on your side and then continue with this PR :-)

**Comment by srittau** [comment]
What's the current status of this? I think we should try whether the errors were resolved.

**Comment by kasium** [comment]
@srittau this is still blocked, since AFAIK no 3rd party dependencies can be used, right?

**Comment by srittau** [comment]
I see. I added the "deferred" label so we track this.

**Comment by Avasam** [comment]
> I suspect (but haven't verified) that this is a shortcoming in our pytype tests that don't install the dependencies when testing third-party stubs.

You are correct https://github.com/python/typeshed/pull/9459#issuecomment-1371551013

There's possible workarounds (silence the error or ignore the file in pytype), but I think we're currently waiting to see if pytype can provide a non-hacky solution with an update?

**Review by AlexWaygood — APPROVED** [review]
Thanks @kasium! Sorry this took so long!

**Pull request merged**
