### PR TITLE
Fix `writeframes` type in `wave`

### PR DESCRIPTION
**Pull request by sobolevn**
Here's the source code for it:

```python
    def writeframesraw(self, data):
        if not isinstance(data, (bytes, bytearray)):
            data = memoryview(data).cast('B')
```

https://github.com/python/cpython/blob/ce7d66771ec64488134a1dd114015aa056eef696/Lib/wave.py#L423-L425

So, basically it accepts `bytes`, `bytearray`, and any type `memoryview` accepts.
Which is `ReadableBuffer`: https://github.com/python/typeshed/blob/de5ec6a0d14351797a54b12b3910534b67df609e/stdlib/builtins.pyi#L672

### CODE REVIEW

**Comment by sobolevn** [comment]
In the next PR I will fix `wave.open` type: https://github.com/python/cpython/blob/ce7d66771ec64488134a1dd114015aa056eef696/Lib/wave.py#L502-L513

**Comment by AlexWaygood** [comment]
> Which is `ReadableBuffer`

As some of us know all too well ☹

**Comment by sobolevn** [comment]
> As some of us know all too well

Sorry, I didn't get this one 🙂

**Comment by AlexWaygood** [comment]
> > As some of us know all too well
> 
> Sorry, I didn't get this one 🙂

Sorry — bad attempt at a joke based on https://github.com/python/mypy/issues/11887

**Comment by sobolevn** [comment]
My english-language jokes are the worst!
That's why I don't even try 😆

**Pull request merged**
