### PR TITLE
mailbox: Couple small fixes

### PR DESCRIPTION
**Pull request by suutari**
Fix type of the message argument in couple methods and make the stub-only helpers private by prefixing them with underscore.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
cc @CraftSpider who contributed the stubs.

**Comment by CraftSpider** [comment]
Double checked the source/docs, and looks good to me. `_MessageType` is bound to be a more specific sub-type of `email.message.Message`, I over-constrained the possible inputs (internally, add and __setitem__ call a non-stubbed private method that accepts  `_MessageData`)

**Comment by JelleZijlstra** [comment]
Thanks for the PR and review!

**Comment by suutari** [comment]
Thanks for reviewing and merging this so quickly!

It occurred to me while reading the review that there's still one more place that should be fixed accordingly, the `update` method. See PR #3493.

**Pull request merged**
