### PR TITLE
Fix int(Union[str, int])

### PR DESCRIPTION
**Pull request by Sterbic**
Calling `int()` over a union of `str` and `int` is currently broken. Fixed the types for `int.__init__` to solve this and remove `__int__` and `__float__` from the `str` class since it doesn't have those methods.

Solves the following case:

```
from typing import Union

user_id: Union[str, int] = "123"
user_id_str = "123"
user_id_int = 123

print(int(user_id))
print(int(user_id_str))
print(int(user_id_int))
```

Mypy error: `test.py:7: error: Argument 1 to "int" has incompatible type "Union[str, int]"; expected "SupportsInt"`

### CODE REVIEW

**Comment by ambv** [comment]
Removal of `__float__` and `__int__` methods looks good. The other change works around what is apparently a bug in mypy: there's already an overload there with the types you're adding.

```py3
class int(SupportsInt, SupportsFloat, SupportsAbs[int]):
    @overload
    def __init__(self, x: SupportsInt = ...) -> None: ...
    @overload
    def __init__(self, x: Union[str, bytes], base: int = ...) -> None: ...
```

Since the `base` attribute has a default value, it seems to me `int('10')` should have always worked. @JukkaL should we go forward with this workaround or file and fix an issue in mypy instead?

**Comment by Sterbic** [comment]
Ping

**Comment by JukkaL** [comment]
The mypy issue may take a while to get fixed, so going forward with a workaround seems reasonable. We can make the workaround cleaner by tweaking the signature a bit:

```py
class int(SupportsInt, SupportsFloat, SupportsAbs[int]):
    @overload
    def __init__(self, x: Union[str, bytes, SupportsInt] = ...) -> None: ...
    @overload
    def __init__(self, x: Union[str, bytes], base: int) -> None: ...
```

Note that there is no default for `base`, so the overload items aren't overlapping.

**Comment by gvanrossum** [comment]
There's something funky with the diff. It seems you have a lot of commits in your diff that are not yours and are from other PRs. Maybe you can merge or rebase your local repo (from upstream) and then `git push -f`, to simplify the review process?

**Comment by Sterbic** [comment]
Certainly, have already tried to clean this up.

**Pull request merged**
