### PR TITLE
Add openpyxl stubs

### PR DESCRIPTION
**Pull request by srittau**
stubgen + import cleanup + mypy fixes + black + isort

### CODE REVIEW

**Comment by srittau** [comment]
I'm out of ideas.

**Comment by JelleZijlstra** [comment]
We'll probably need to change stubtest to try-except more exception types in this case. Unfortunately that may mean we have to wait for the next mypy release.

**Comment by srittau** [comment]
I'm marking this as deferred for now.

**Comment by hauntsaninja** [comment]
There's an allowlist of distributions to skip running stubtest on; you could add to that to unblock this PR.

**Comment by srittau** [comment]
The toml flag was removed in the meantime as well as we fixed all remaining problems. We could reintroduce it, but we can also just wait for the next mypy release.

**Comment by srittau** [comment]
#7351 will allow us to merge despite stubtest.

**Pull request merged**
