### PR TITLE
Fix unnecessary 'pyright: ignore' warning in CI

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Hmm, what problem is this fixing? I see lots of stdlib stubtest failures on recent pushes `main`, but I don't see pyright failing at all

**Comment by srittau** [comment]
See here, for example: https://github.com/python/typeshed/actions/runs/12013896148/job/33488465170?pr=11709

Cf. #11709

**Comment by AlexWaygood** [comment]
Huh, that's very odd... Has it been happening on any other PRs that you know of?

**Comment by srittau** [comment]
I've merged the latest changes for the unnecessary allowlist entries into a few PRs. Let's see what happens.

**Comment by AlexWaygood** [comment]
Okay, it's not really a flake. It's because that PR adds stubs that depend on `django-stubs`, and `django-stubs` [depends on `tomli`](https://github.com/typeddjango/django-stubs/blob/c7df645ea58f387cfe05721a983d9ad3bd34e52c/setup.py#L23-L31), which pulls `tomli` into the environment and means that pyright can resolve the import in the `setuptools` stubs. So this is a side effect of the fact that we have no isolation between stubs packages when we test them with pyright in CI -- all non-types dependencies get installed into one big "venv soup".

**Comment by AlexWaygood** [comment]
Alternatively... we could maybe just delete this module from the stubs? It seems like an implementation detail at runtime to me; I'm not sure it's meant to be for public consumption. It's probably not worth the bother to maintain stuff like this? @Avasam, what do you think?

**Pull request closed without merging**
