### PR TITLE
Use `Literal` and `__all__` in `binhex`

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by sobolevn** [comment]
```
 Stub: at line 10
Literal[b'\\x90']
Runtime:
b'\x90'
```

@hauntsaninja is it valid? Or is it a bug?

**Comment by hauntsaninja** [comment]
Seems like a bug

**Comment by sobolevn** [comment]
@hauntsaninja should this be closed? I guess it can wait for 0.931 release

**Comment by sobolevn** [comment]
Rebased, now `Literal[bytes]` should work!

**Comment by sobolevn** [comment]
Awesome!

**Review by srittau — APPROVED** [review]

**Pull request merged**
