### PR TITLE
Fix incorrect type definition for `validator`

### PR DESCRIPTION
**Pull request by romanofski**
This function was mistakenly typed as `Callable[[Property], object] |
None`, however the actual function accepts two parameters of type
`Property, value`. The value can be of any type. Strictly speaking, the
type corresponds to the type of the property which is defined at runtime.

Relates to #7103

### CODE REVIEW

**Review by JelleZijlstra — CHANGES_REQUESTED** [review]
The `bool` return type seems to be wrong. I see this in the code:
```
        if self._validator is not None:
            new_value = self._validator(self, value)
            if new_value is not None:
                value = new_value
```
So it looks like it's meant to return a replacement value, which means it should return `object`.

Also, the second argument should probably be `Any`. Arguments to callables are contravariant, so if we say `object`, the type checker will only accept validators that really accept *all* objects. But here a specific validator probably just accepts the type of the specific property it's dealing with.

Maybe we could come up with a precise type with generics, but until we do that I recommend `Callable[[Property, Any], object]`.

**Comment by romanofski** [comment]
@JelleZijlstra You're right. I blindly followed the type annotation in the python-ndb repo, but after double checking it is the way you outlined. I've checked the documentation which mentions it too (https://cloud.google.com/appengine/docs/standard/python/ndb/entity-property-reference):

> Optional function to validate and possibly coerce the value.
> Will be called with arguments (prop, value) and should either return the (possibly coerced) value or raise an exception. Calling the function again on a coerced value should not modify the value further. (For example, returning value.strip() or value.lower() is fine, but not value + '$'.) May also return None, which means "no change". See also [Writing Property Subclasses](https://cloud.google.com/appengine/docs/standard/python/ndb/subclassprop)

Since you mentioned generics, I wonder if the type would simply become:

```Python
_V = TypeVar('_V')
validator: Callable[[Property, _V], _V] | None
```
I don't want to overdo it. I'd be happy to adjust as suggested for now.. just wondering.

**Comment by JelleZijlstra** [comment]
It might be fine to use a generic like you suggest, but I think we'll run into problems if any validator changes the type of its argument. I don't know if that's common.

**Comment by romanofski** [comment]
> It might be fine to use a generic like you suggest, but I think we'll run into problems if any validator changes the type of its argument. I don't know if that's common.

I kept the signature as you suggested: `Callable[[Property, Any], object]`, with one exception that is the `KeyProperty`, I used the upstream type annotation and made: `Callable[[Property, key_module.Key], key_module.Key]`. I think that was kind of appropriate to go with the specific type here.

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
