### PR TITLE
Added a lot of type annotations

### PR DESCRIPTION
**Pull request by Dakkaron**

### CODE REVIEW

**Comment by gvanrossum** [comment]
Please resolve conflicts.

**Comment by gvanrossum** [comment]
Please rebase. ConfigParser.pyi looks like a new file in your PR but in fact it already exists. Please search StackOverflow if you need help finding the right git commands (I don't know them any more).

**Comment by Herst** [comment]
OK, now you merged instead of rebasing but apart from that: great! :+1:

**Comment by gvanrossum** [comment]
This still looks like it contains a lot of changes that are already in master, and manually trying to merge it ran into some conflict. I don't know what you're doing wrong, but until you make it so that reviewing the "File changes" here shows just what you've done, I can't even begin to review this. Please get help somewhere.

**Pull request closed without merging**
