### PR TITLE
expose asyncio.open_unix_connection if it exists

### PR DESCRIPTION
**Pull request by JelleZijlstra**
I got an incorrect error from mypy when using `asyncio.open_unix_connection`.

### CODE REVIEW

**Comment by vlasovskikh** [comment]
You cannot use dynamic checks like this in stubs besides a small set of checks that static type checkers understand. See https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking

**Comment by JelleZijlstra** [comment]
Should we also change https://github.com/python/typeshed/blob/master/stdlib/3.4/asyncio/streams.pyi#L41 then?

**Comment by vlasovskikh** [comment]
I believe so, but let's wait for a core developer's opinion.

**Comment by gvanrossum** [comment]
I recommend testing for `sys.platform != 'win32'` instead (in both places). That's supported in mypy (and specified by PEP 484) and it's a very close approximation anyways. (Maybe cygwin will lose out, oh well.)

**Comment by gvanrossum** [comment]
@JelleZijlstra Can you make the suggested updates?

**Comment by JelleZijlstra** [comment]
Just pushed the change.

**Comment by gvanrossum** [comment]
Thanks Jelle!

**Pull request merged**
