### PR TITLE
Update explanation for importing builtins.str

### PR DESCRIPTION
**Pull request by srittau**

### CODE REVIEW

**Comment by srittau** [comment]
I opened this PR mainly for the attention of the pyright developers, and we can close it if there's no quick fix coming. The current version is not the nicest, but works fine.

**Comment by srittau** [comment]
Eric explained why pyright's behavior makes sense. I updated the comment instead.

**Comment by Akuli** [comment]
Needs black and isort.

**Review by Akuli — APPROVED** [review]
I think the import is quite self-explanatory, but adding a comment doesn't make it worse.

**Comment by Akuli** [comment]
GitHub actions is down: https://www.githubstatus.com/

**Comment by srittau** [comment]
> I think the import is quite self-explanatory, but adding a comment doesn't make it worse.

Well, I tried to remove it, and filed a bug report with pyright when that didn't work, so it wasn't self-explanatory to me. :)

**Comment by srittau** [comment]
I merged it after running isort, black, flake8 locally. Should not affect anything else.

**Pull request merged**
