### PR TITLE
Redis: add Lock in __init__

### PR DESCRIPTION
**Pull request by golgor**
I know it seems to be a bit of a discussion regarding redis-py, but I ran into the issue today of figuring out the types to pass a Lock-type. This fix worked out if I made the same changes in the types-redis locally.

### CODE REVIEW

**Comment by srittau** [comment]
As the stubtest error points out, `Lock` is not re-exported from `redis.lock`. What's wrong with using `redis.lock.Lock`?

**Comment by golgor** [comment]
> As the stubtest error points out, `Lock` is not re-exported from `redis.lock`. What's wrong with using `redis.lock.Lock`?

Sorry, this is my first time looking into this. Not sure if I follow what you mean. It doesn't work with Pylance in my own code-base when I have types-redis installed. I basically are trying to make a function that returns a lock with pre-defined settings:

```python
def get_lock(conn: redis.StrictRedis, mqtt_message: MqttMessage, timeout: int = 60) -> redis.lock.Lock:
"""Return a lock."""
return conn.lock(
    name=f"connector_lock_{mqtt_message.ep}:{mqtt_message.ts}:{mqtt_message.part}:{mqtt_message.parts}",
    timeout=60,
)
```
The return type redis.lock.Lock is just "Any" in this.

It does work fine when I use an instance:
```python
conn = redis.StrictRedis(host=settings.REDIS_HOST, db=settings.REDIS_DB)
redis_lock = conn.lock(
        name=<NAME>,
        timeout=<TIMEOUT>,
    )
```
Not sure where the problem lies, but with the changes in this PR it works fine in both cases. Not sure though if this is a good or bad way to do it.

Any feedback or help is very much appreciated!

**Comment by srittau** [comment]
Make sure you `import redis.lock`, not just `import redis`. pylance seems to have a problem with `redis` not explicitly importing `lock`.

**Comment by golgor** [comment]
> Make sure you `import redis.lock`, not just `import redis`. pylance seems to have a problem with `redis` not explicitly importing `lock`.

That seemed to do it. Is this a general problem with typeshed-packages? I.e. import more specifically what you need rather than relying on __init__. I will at least try to do this more often, thanks for tip!

**Pull request closed without merging**
