### PR TITLE
Add attribute types to `code.InteractiveInterpreter` and `code.InteractiveConsole`

### PR DESCRIPTION
**Pull request by hoefling**
Signed-off-by: oleg.hoefling <oleg.hoefling@gmail.com>

### CODE REVIEW

**Comment by Akuli** [comment]
All new attributes should be marked with `# undocumented`. The docs talk about "the buffer", for example, but they don't mention it's directly accessible with an attribute.

**Comment by hoefling** [comment]
@Akuli thanks, I forgot that. Mind if I also add the undocumented comment to `linecache.cache` dict I added in #5805 here as well?

**Review by srittau — COMMENTED** [review]
Also, please use `list` and `dict`, instead of `List` and `Dict`.

**Comment by hoefling** [comment]
@srittau 
> Also, please use `list` and `dict`, instead of `List` and `Dict`.

Done, also replaced `Optional[...]` usages with PEP 604-style hints.

**Review by srittau — APPROVED** [review]
Thanks!

**Comment by srittau** [comment]
Werkzeug is monkey-patching `compile`, so problems are expected.

**Pull request merged**
