### PR TITLE
Introduce explicit `__str__` and `__repr__` for Exceptions

### PR DESCRIPTION
**Pull request by sinancepel**
The objective here is to more accurately model the runtime, and be able to accurately detect when `Exception.__str__` is called (as opposed to `object.__str__`) for static analysis purposes.

In the runtime, the `__str__` and `__repr__` functions for Exceptions do not default to `object.__str__` and `object.__repr__`, instead defaulting to the BaseException implementations (Python 3) or those in `exceptions.Exception` (Python 2). Since there are no references to the Python 2 `exceptions` module in `builtins.pyi`, I chose to lie in the stubs a bit and pretend that both flow through BaseException. I'm happy to change the stub so that we only add these stubs for Python 3 code if folks have strong opinions :)

Hopefully this change isn't controversial, as we already seem to be documenting custom implementations of `__str__` and `__repr__` for classes such as `int`, `float` and `unicode`.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Could you elaborate more on how this change helps you? In the past we've usually told people to not include method overrides where the override is the same as the base class, although it doesn't seem like that rule is mentioned anywhere.

**Comment by sinancepel** [comment]
We have a taint analysis tool, in which we're hoping to flag calls to str(exception). For the static analysis, we simulate the runtime calls, relying on typeshed for builtins. It's important to understand which function is getting called in the runtime as we don't want to flag calls to obj.__str__ as serializing exceptions, as the method in which we annotate functions is by annotating the actual method getting called. You can find an example of what this looks like here: https://github.com/facebook/pyre-check/commit/04edacb1b734e0c5960c3a7d6de8d42f56f005fe

**Comment by srittau** [comment]
Makes some sense to me. But this is something that should be done consistently for overridden methods in the future, not just for exceptions. And it would need to be documented if we decide to go this route. My major fear is that this would make writing and reviewing stubs more cumbersome, because this is now something that we would need to check.

**Comment by sinancepel** [comment]
Seems like we already break this rule for a few builtins such as the `int`, `str` and `float` classes (https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L198), so exceptions to the convention already seem to exist :) In general, I don't have an expectation that typeshed does this consistently for all stubs, and I wouldn't want to add more red tape to introducing stubs. I don't imagine there being a need to add these overrides too often (this is the only case I've run into so far where typeshed wasn't sufficient), so would prefer to introduce an exception instead of making life hard for other stub authors :)

**Comment by sinancepel** [comment]
Thanks @srittau!

**Pull request merged**
