### PR TITLE
Change last asyncio.gather() overload ret. to List

### PR DESCRIPTION
**Pull request by bsolomon1124**
Stems from PR #1550/ Issue #3243.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Unfortunately this causes an error in mypy's own test suite. Could you submit a PR to mypy to address it? Then I can merge the two PRs to get things working on both the mypy and the typeshed side.

**Comment by bsolomon1124** [comment]
Yes, you're referring to `testAsyncioGatherPreciseType` from [this snippet](https://github.com/python/mypy/blob/475148f2b08dbe0126fc3e22c277132b65e47007/test-data/unit/pythoneval.test#L1126) @JelleZijlstra ?

**Comment by JelleZijlstra** [comment]
Yes

**Comment by bsolomon1124** [comment]
See https://github.com/python/mypy/pull/7550 @JelleZijlstra

**Pull request merged**
