### PR TITLE
add AsyncGenerator to typing.pyi

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This parallels https://github.com/python/typing/pull/346

### CODE REVIEW

**Comment by ambv** [comment]
I'm going to wait on python/typing#346 being merged with this one.

**Comment by lamenezes** [comment]
It would be nice to also add the `AsyncGenerator` to `collections.abc` [1] [2]

[1] https://github.com/python/typeshed/blob/master/stdlib/3/collections/__init__.pyi
[2] https://github.com/python/typeshed/blob/master/stdlib/3/collections/abc.pyi

**Comment by gvanrossum** [comment]
Now that python/typing#346 has been merged this can go in, but I agree that it should also be added to collections/abc.pyi. @JelleZijlstra Can you add that?

**Comment by JelleZijlstra** [comment]
Done, also rebased the branch.

**Comment by gvanrossum** [comment]
Can you fix the missing import?

**Comment by JelleZijlstra** [comment]
Looks like my push beat your comment by a second :) Sorry for not running the tests locally first.

**Pull request merged**
