### PR TITLE
Add mmap.MAP_POPULATE from 3.10

### PR DESCRIPTION
**Pull request by versusvoid**

### CODE REVIEW

**Comment by srittau** [comment]
Thanks. This also needs a platform check, I guess `if sys.platform != "darwin":`. Also, the corresponding entry needs to be removed from `tests/stubtest_allowlists/linux-py310.txt`.

**Comment by Akuli** [comment]
This flag appears to be linux specific, so `sys.platform == "linux"` would be a better fit. Or I could be misunderstanding linux's `mmap(2)` manual page. In the past, I have found it difficult to tell which flags in it are linux-specific and which conform to a POSIX standard.

**Comment by versusvoid** [comment]
It is linux-specific, so I've moved it under `platform == "linux"` check

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
