### PR TITLE
builtins: Specify return type of int.__pow__

### PR DESCRIPTION
**Pull request by cschramm**

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
The Any return type is intentional here because Union return types are generally annoying to deal with. This is mentioned in https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions.

**Comment by cschramm** [comment]
I don't really agree with that as the user always has the option to cast or just ignore Union return types and having specific types is the purpose of stub files but sorry for the fuss if it's common convention.

Then again, that convention is not followed consistently. There are e.g. signatures for `next` and `sum` in the same file that do have Union return types...

**Comment by gvanrossum** [comment]
The union return types for `next()` and `sum()` are only overloads for special cases, and in most cases the union will disappear because the iterator item type and the default/start value type are the same.

**Comment by cschramm** [comment]
There's absolutely no requirement for `isinstance`. Other options the user has include:

* `cast(int, n**2)` when we know that the result will be `int`
* `cast(Any, n**e)` or `n**e  # type: ignore` when we don't want to deal with the type (why use types at all then?)
* `float(n**e)` when both types are possible and we do not want to distinguish

**Comment by gvanrossum** [comment]
All of those have the same problem as `isinstance` -- if you have working correct code, mypy gives you a false positive forcing you to make it uglier. While *sometimes* that's the right thing to do (e.g. `a = []`), *usually* we prefer false negatives over false positives, since false positives very quickly annoy users. Remember that mypy users are Python users first and foremost, not type system zealots. :-)

**Comment by JukkaL** [comment]
By the way, mypy already special cases type checking of `n**m` for integers when `m` is a literal, and it can infer `int` / `float` as the type instead of `Any`.

**Pull request closed without merging**
