### PR TITLE
Remove pytest_mock

### PR DESCRIPTION
**Pull request by srittau**
pytest-mock is now type annotated, which makes typeshed's annotations
obsolete. See pytest-dev/pytest-mock#152.

### CODE REVIEW

**Comment by srittau** [comment]
CI is doing something weird, but it seems to have passed.

**Comment by Akuli** [comment]
This CI weirdness happens to me sometimes too. It usually gets better if you push an empty commit.

**Comment by JelleZijlstra** [comment]
Maybe we should move fully to GitHub Actions instead of Travis, it seems more stable.

**Comment by srittau** [comment]
Fine by me. I can look into it when I find some time. (Not sure when that is, though.)

**Comment by srittau** [comment]
Gentle ping.

**Comment by hauntsaninja** [comment]
Travis does seem to have run the tests, and unsurprisingly they passed, so merging.

**Pull request merged**
