### PR TITLE
Use native SupportsIndex in builtins

### PR DESCRIPTION
**Pull request by hatal175**
As requested by @Akuli in #5228.

### CODE REVIEW

**Comment by hatal175** [comment]
Not entirely sure where most of these come from (first diff excluded). Can anyone help?

**Comment by JelleZijlstra** [comment]
Seems like mypy picks the wrong `list.__getitem__` overload when you do `list[:]`, but I can't reproduce that writing similar code locally, or even running mypy master directly on Sphinx with your code.

**Comment by hauntsaninja** [comment]
So this is because mypy_primer isn't really updated for the modular typeshed changes. For some projects, we point mypy at a Python executable in a project venv (using `--python-executable`), so it can look at the project's dependencies. Unfortunately, as of modularised typeshed, when this happens there's no longer a types-typing-extensions to look at (that's only present in mypy's venv, since types-typing-extensions is now a mypy dependency)

I think there's a pretty strong case to be made that we should just pretend typing_extensions is part of the stdlib (mentioned previously in https://github.com/python/typeshed/pull/5109#issuecomment-803446432). At least from a mypy user's perspective, it's super unintuitive that passing `--python-executable` can cause complete mayhem for normal usage of stdlib, even if your project doesn't use typing_extensions at all.
Thoughts? cc @JukkaL @srittau 

Here's how you can repro mypy_primer locally:
```
mypy_primer --new 2ac722ac7 --old 2ac722ac7 --custom-typeshed-repo ~/dev/typeshed --new-typeshed 479fa0e3 --old-typeshed f44f38fd --debug --output concise -k sphinx
```
Here's a minimal repro (where `~/dev/typeshed` is checked out to this PR):
```
~/tmp/repro λ python3 -m venv mypyenv
~/tmp/repro λ mypyenv/bin/pip install git+https://github.com/python/mypy.
...
~/tmp/repro λ python3 -m venv projectenv
~/tmp/repro λ vim x.py
~/tmp/repro λ cat x.py
from typing import List
x: List[str]
x = x[:]
~/tmp/repro λ mypyenv/bin/mypy --python-executable projectenv/bin/python x.py
Success: no issues found in 1 source file
~/tmp/repro λ mypyenv/bin/mypy --python-executable projectenv/bin/python --custom-typeshed-dir ~/dev/typeshed x.py
x.py:4: error: Incompatible types in assignment (expression has type "str", variable has type "List[str]")
Found 1 error in 1 file (checked 1 source file)
```
Here's a quick and dirty patch for mypy_primer, if people feel badly about giving typing_extensions honourary stdlib status:
```
diff --git a/mypy_primer.py b/mypy_primer.py
index 6b3d5ca..819377d 100644
--- a/mypy_primer.py
+++ b/mypy_primer.py
@@ -345,6 +345,7 @@ class Project:
         if self.pip_cmd:
             assert "{pip}" in self.pip_cmd
             venv.create(self.venv_dir, with_pip=True, clear=True)
+            await run("{pip} install 'types-typing-extensions>=3.7.0'".format(pip=str(self.venv_dir / "bin" / "pip")), shell=True, cwd=repo_dir)
             await run(
                 self.pip_cmd.format(pip=str(self.venv_dir / "bin" / "pip")),
                 shell=True,
```

**Review by hauntsaninja — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
@hauntsaninja thanks for figuring it out! I agree that putting typing-extensions in the stdlib makes sense. It would be very confusing if users ran into this issue whenever we use typing-extensions in stdlib stubs.

**Pull request merged**
