### PR TITLE
fix list concatenation

### LINKED ISSUE #2383: Adding lists of subtypes together
Using `mypy==0.620` and Python 3.6.6, the following code:

```python
from typing import List, Optional

x: List[Optional[int]] = [1, 2, 3]
[None] + x
```

fails with:

```
a.py:4: error: Unsupported operand types for + ("List[None]" and "List[Optional[int]]")
```

This is presumably because lists are invariant w.r.t their generic parameter, and the declration requires a `List` of the same type

https://github.com/python/typeshed/blob/4e40b035c8337cddcf4f94fcd83a2f0d454488b6/stdlib/3/builtins.pyi#L619.

I don't know what the right solution here is -- can we just replace the `x: List[_T]` with `x: List[_T_co]` and make it covariant? Or doe we need another typevar `_U = TypeVar("U", bound=_T)` or something?

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Fixes #2383, python/mypy#5492.

I was a little surprised this works, but it does. I tried the test cases from both of the linked issues, and mypy allows them without any errors when this typeshed patch is applied.

Unfortunately, with this change `__iadd__` becomes incompatible with `__add__` according to mypy. I tried changing it to `def __iadd__(self: List[_T_co], x: Iterable[_T_co]) -> List[_T_co]: ...`, which passes mypy, but that breaks this test case:
```python
from typing import List
x: List[object]
y: List[int]
x += y
```
Therefore, I chose to `# type: ignore` it instead.

### CODE REVIEW

**Comment by ilevkivskyi** [comment]
I am not sure if this is the right solution. Maybe we can try something closer to `set.__or__`/`set.__ior__`? Will this fix the issues?

I guess a perfect solution for this kind of questions would require https://github.com/python/mypy/issues/2354 solved first.

**Comment by ilevkivskyi** [comment]
> I don't think that generic self types would help, since subclasses will default to generating `list` instances

Yes, indeed, it returns just a list. I remember people wanted generic self types when they want the return to be a subtype, but it is not the case here.

> The return type needs to use a union, similar to the set operations.

This actually might not solve the original issue, where a join is preferred:
```python
class B: ...
class C1(B): ...
class C2(B): ...

lst: List[B] = [C1()] + [C2()]
```
This is however an eternal question of union vs join, so I think there is no ideal solution here.

**Comment by ilevkivskyi** [comment]
Just to clarify I do think returning a `List[Union[T, S]]` is a better compromise.

**Comment by JelleZijlstra** [comment]
I am going to be out for another week and won't have time to update the code in this PR. If it's urgent, feel free to take over the PR and change the code as you see fit; otherwise I'll implement your suggestion in a few weeks.

**Comment by JelleZijlstra** [comment]
I implemented the Union return type suggestion now.

**Pull request merged**
