### PR TITLE
Update `pyright` version to 1.1.350

### PR DESCRIPTION
**Pull request by sobolevn**
There are multiple releases after the current one: https://github.com/microsoft/pyright/releases/

### CODE REVIEW

**Comment by sobolevn** [comment]
Looks like it reports quite a lot of new problems, for example:    
```
/home/runner/work/typeshed/typeshed/stdlib/builtins.pyi:450:29 - error: Position-only parameter not allowed after parameter that is not position-only (reportGeneralTypeIssues)
```

**Comment by Avasam** [comment]
1.1.351 added checks for positional-only params after pos-or-kw params
Some version before that made a few `reportGeneralTypeIssues` more specific (so the report name changed)

**Comment by sobolevn** [comment]
I will first update it to 350, then to newer versions 👍

**Comment by sobolevn** [comment]
Working on test cases now 👍

**Comment by Avasam** [comment]
No longer at my computer right now, but those openpyxl test failures look scary 😶
Could be that either pyright had a regression, or it stopped supporting something I was doing to make openpyxl descriptors work.

**Review by AlexWaygood — APPROVED** [review]

**Comment by AlexWaygood** [comment]
Thanks!

**Pull request merged**
