### PR TITLE
add six and pyyaml to requirements

### PR DESCRIPTION
**Pull request by martindemello**
pytype recently added a dependency on six and pyyaml.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks for looking into this!

Would it be better to specify these inside pytype itself (i.e., in setup.py)? That way we don't have to worry inside typeshed about the version of these dependencies.

**Comment by martindemello** [comment]
i did add `requires=['pyyaml (>=3.11)', 'six'],` to pytype's setup.py but it doesn't appear to do anything. (i'll admit i'm not familiar with distutils at all but read over the docs and it seemed like the correct way to do it)

**Comment by JelleZijlstra** [comment]
I think the error actually isn't due to dependencies, it's this:
```
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    In file included from pyi/parser.tab.hh:66:0,
                     from pytype/pyi/lexer.h:7,
                     from pytype/pyi/parser_ext.cc:3:
    pyi/stack.hh:92:12: error: expected ‘,’ or ‘...’ before ‘&&’ token
    pyi/stack.hh: In member function ‘void pytype::stack<T, S>::push(T)’:
    pyi/stack.hh:94:25: error: ‘move’ is not a member of ‘std’
    pyi/stack.hh:94:35: error: ‘t’ was not declared in this scope
    error: command 'gcc' failed with exit status 1
```
(You can get this in Travis output by clicking on the line where it pip installs mypy; it will expand the output. six and pyyaml are installed correctly.)

**Comment by martindemello** [comment]
pushed a fix for that (hopefully - is there a way to check out a travis environment locally and test?) and added `install_requirements` to setup.py since it looks like travis is explicitly invoking setuptools rather than distutils. (six and pyyaml are installing in this PR because i added them to requirements.txt rather than because setup.py installs them)

**Comment by martindemello** [comment]
took six and pyyaml out of `requirements.txt` and `install_requirements` does indeed install them. also the c++ extension issue is fixed.

**Comment by JelleZijlstra** [comment]
Great! The only remaining change is to move towards using requirements-tests-py2.txt in the Travis config, which seems like a good change (fewer places to configure the same thing), so I'll merge this PR.

**Comment by JelleZijlstra** [comment]
I believe pytype needs a 3.6 binary to check the Python 3 stubs.

**Comment by martindemello** [comment]
I agree that downloading and extracting to / is not ideal, but I tried a lot of other things to get a 3.6 interpreter installed in a 2.7 venv and this was the only one that worked :( now that we are moving towards running pytype itself under 3.6 we should be able to get rid of this hack pretty soon.

**Pull request merged**
