### PR TITLE
Fix mypy test

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Because we didn't set mypy's clean_exit parameter, it was
exiting immediately after checking the stdlib.

This exposed two issues:
- types-requests has a version-limited dependency on types-urllib3, which we crashed on
- mypy crashes checking the SQLAlchemy stubs. Not sure if that's a known issue.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
SQLAlchemy stack trace:

<details>
Traceback (most recent call last):
  File "/Users/jelle/py/typeshed/tests/mypy_test.py", line 346, in <module>
    main()
  File "/Users/jelle/py/typeshed/tests/mypy_test.py", line 330, in main
    this_code, checked = test_third_party_distribution(distribution, major, minor, args)
  File "/Users/jelle/py/typeshed/tests/mypy_test.py", line 277, in test_third_party_distribution
    code = run_mypy(args, configurations, major, minor, files)
  File "/Users/jelle/py/typeshed/tests/mypy_test.py", line 194, in run_mypy
    mypy_main("", sys.stdout, sys.stderr, clean_exit=True)
  File "/Users/jelle/py/mypy/mypy/main.py", line 96, in main
    res, messages, blockers = run_build(sources, options, fscache, t0, stdout, stderr)
  File "/Users/jelle/py/mypy/mypy/main.py", line 173, in run_build
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/jelle/py/mypy/mypy/build.py", line 180, in build
    result = _build(
  File "/Users/jelle/py/mypy/mypy/build.py", line 256, in _build
    graph = dispatch(sources, manager, stdout)
  File "/Users/jelle/py/mypy/mypy/build.py", line 2727, in dispatch
    process_graph(graph, manager)
  File "/Users/jelle/py/mypy/mypy/build.py", line 3071, in process_graph
    process_stale_scc(graph, scc, manager)
  File "/Users/jelle/py/mypy/mypy/build.py", line 3189, in process_stale_scc
    graph[id].write_cache()
  File "/Users/jelle/py/mypy/mypy/build.py", line 2311, in write_cache
    new_interface_hash, self.meta = write_cache(
  File "/Users/jelle/py/mypy/mypy/build.py", line 1488, in write_cache
    data = tree.serialize()
  File "/Users/jelle/py/mypy/mypy/nodes.py", line 344, in serialize
    'names': self.names.serialize(self._fullname),
  File "/Users/jelle/py/mypy/mypy/nodes.py", line 3364, in serialize
    data[key] = value.serialize(fullname, key)
  File "/Users/jelle/py/mypy/mypy/nodes.py", line 3301, in serialize
    data['node'] = self.node.serialize()
  File "/Users/jelle/py/mypy/mypy/nodes.py", line 953, in serialize
    "type": None if self.type is None else self.type.serialize(),
  File "/Users/jelle/py/mypy/mypy/types.py", line 1482, in serialize
    'variables': [v.serialize() for v in self.variables],
  File "/Users/jelle/py/mypy/mypy/types.py", line 1482, in <listcomp>
    'variables': [v.serialize() for v in self.variables],
  File "/Users/jelle/py/mypy/mypy/types.py", line 611, in serialize
    'upper_bound': self.upper_bound.serialize(),
  File "/Users/jelle/py/mypy/mypy/types.py", line 1079, in serialize
    type_ref = self.type.fullname
  File "/Users/jelle/py/mypy/mypy/nodes.py", line 2914, in __getattribute__
    raise AssertionError(object.__getattribute__(self, 'msg'))
AssertionError: De-serialization failure: TypeInfo not fixed
</details>

**Comment by AlexWaygood** [comment]
https://github.com/python/typeshed/pull/7482 for the `parsimonious` error.

**Comment by AlexWaygood** [comment]
The `urllib` errors come from checking `requests` on Python 2; `requests` is marked as being Python 2-compatible, but imports `urllib3`, which isn't Python 2-compatible. The easiest fix is probably just to mark `requests` as no longer being Python 2-compatible.

**Comment by AlexWaygood** [comment]
> The `urllib` errors come from checking `requests` on Python 2; `requests` is marked as being Python 2-compatible, but imports `urllib3`, which isn't Python 2-compatible. The easiest fix is probably just to mark `requests` as no longer being Python 2-compatible.

https://github.com/python/typeshed/pull/7483 to do that.

**Review by srittau — APPROVED** [review]
LGTM, once the problems are resolved.

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
