### PR TITLE
Mark `python-crontab` as completed

### PR DESCRIPTION
**Pull request by sobolevn**
It was just added in https://github.com/python/typeshed/pull/8917

### CODE REVIEW

**Comment by sobolevn** [comment]
I will try to check for possible stubtest changes to fix constants re-export.

**Review by AlexWaygood — APPROVED** [review]
Nice

**Comment by AlexWaygood** [comment]
> I will try to check for possible stubtest changes to fix constants re-export.

You could potentially try to get the source code with `inspect.getsource()`, and then do AST analysis to examine which symbols are exported from other modules.

**Comment by AlexWaygood** [comment]
Give me a ping if you want a hand/second look on anything :D

**Pull request merged**
