### PR TITLE
[redis] Add initial stubs for `redis.asyncio.cluster`

### PR DESCRIPTION
**Pull request by sobolevn**
There are a lot of things to add:
- Attributes
- Slots
- Maybe overloads
- Type arguments and generics

Maybe some types need to be adjusted. I've just copied them from the source code: https://github.com/redis/redis-py/blob/master/redis/asyncio/cluster.py

But, this is good enough for now.

### CODE REVIEW

**Comment by sobolevn** [comment]
Now everything passes, except `stubtest`. Looks like changes from https://github.com/redis/redis-py/blob/master/redis/asyncio/cluster.py are not yet released.

**Comment by AlexWaygood** [comment]
> Now everything passes, except `stubtest`. Looks like changes from https://github.com/redis/redis-py/blob/master/redis/asyncio/cluster.py are not yet released.

Do you want to revise this PR so that it only includes the things currently included in redis 4.3.4, or would you prefer to just defer this PR until redis 4.4.0 is released?

**Comment by sobolevn** [comment]
> or would you prefer to just defer this PR until redis 4.4.0 is released?

:)

**Comment by AlexWaygood** [comment]
> > or would you prefer to just defer this PR until redis 4.4.0 is released?
> 
> :)

(That means that, when 4.4.0 is released, you'll have to bump the version number in `METADATA.toml` for stubtest to pass. That might introduce some _new_ stubtest failures, FYI!)

**Comment by AlexWaygood** [comment]
We should now be able to merge this after the pinned `redis` version has been bumped to 4.4.0 (#9329).

**Comment by juanamari94** [comment]
@AlexWaygood Hey Alex! Even though we merged the main branch it seems to be failing on a large number of stub tests, do you need any help?

**Comment by AlexWaygood** [comment]
> @AlexWaygood Hey Alex! Even though we merged the main branch it seems to be failing on a large number of stub tests, do you need any help?

Yeah, looks like the runtime source code changed in between @sobolevn filing the PR and version 4.4.0 being released :(

Maybe @sobolevn is available to update the PR to fix the CI failures? But if we haven't heard from him in a few days, you can probably go ahead and finish it (make sure to credit him if you do, of course!).

**Comment by juanamari94** [comment]
@AlexWaygood I'll give it a look! As for co-authoring, is it enough to give credit in the commit description or build from the branch itself? Or is there an additional step?

**Comment by sobolevn** [comment]
Feel free to take this over :)
We have 5 days of holidays left! 😆

**Comment by juanamari94** [comment]
Hey @sobolevn ! Thanks for the understanding 🙏 I'm still stuck at trying to get past this error:

```error: redis.asyncio.cluster.ClusterPipeline is inconsistent, metaclass differs
Stub: at line 115 in file /home/runner/work/typeshed/typeshed/stubs/redis/redis/asyncio/cluster.pyi
N/A
Runtime: at line 1308 in file /tmp/tmpb89zcsbw/lib/python3.10/site-packages/redis/asyncio/cluster.py
<class 'typing._ProtocolMeta'>

error: redis.asyncio.cluster.RedisCluster is inconsistent, metaclass differs
Stub: at line 20 in file /home/runner/work/typeshed/typeshed/stubs/redis/redis/asyncio/cluster.pyi
N/A
Runtime: at line 85 in file /tmp/tmpb89zcsbw/lib/python3.10/site-packages/redis/asyncio/cluster.py
<class 'typing._ProtocolMeta'>```

I'm hoping I'll be able to get through it next week, just wanted to let you know on the status!

**Comment by AlexWaygood** [comment]
Closing in favour of #9468, which has you as a co-author :)

Thanks for the work done here @sobolevn, and thanks @juanamari94 for finishing the PR!

**Pull request closed without merging**
