### PR TITLE
Stubs for setuptools' pkg_resources package

### PR DESCRIPTION
**Pull request by mkurnikov**

### CODE REVIEW

**Comment by mkurnikov** [comment]
Just found out that it's not that easy. I don't have any consent from maintainers yet. Please don't merge.

**Comment by jaraco** [comment]
I've no objection to stubs being created for pkg_resources or setuptools, just as long as there's an understanding that the existence of these should not create a burden for the setuptools project itself by impeding change.

**Comment by gvanrossum** [comment]
Are you giving up so easily? Maybe you can manually write a very small stub that only defines the objects you really need right now? We can then iterate over time. See what I've done for pdb, for example: https://github.com/python/typeshed/blob/master/stdlib/2.7/pdb.pyi

**Comment by mkurnikov** [comment]
Tests were breaking at the `traceback.pyi`, completely unrelated to my code. Anyway, from the pull request there was a lot of new commits, I will merge them in a couple of days. 
Stub is about 90% complete right now (as far as I see). Remaining stubs aren't necessary for me now and I wasn't going to finish it. I'd figure out what's wrong with the tests and then it all could be merged.  
Thank you for cheering me up.

**Comment by gvanrossum** [comment]
If you want to I can merge it as-is. Tests are passing now (I did some
serious work on runtests.py). I don't know much about pkg_resources so
I can't compare it to the implementation or docs but in general my
policy is that we'll iterate more quickly if we can get people to
submit bugs sooner...

**Comment by mkurnikov** [comment]
It would be really nice.

**Comment by gvanrossum** [comment]
Done. Until I sync the typeshed subrepo of the mypy repo, you can test by doing a pull in the subrepo and passing -f to mypy. Thanks for your effort!

**Pull request merged**
