### PR TITLE
lru_cache preserves signature of wrapped function

### PR DESCRIPTION
**Pull request by Tomaz-Vieira**
This PR uses `ParamSpec` to make `lru_cache` preserve the signature of the wrapped function.

Unfortunately this removes the constraint that `*args` and `**kwargs` must be `Hashable` at least until the meaning of the `bound` parameter in `ParamSpec` is decided, but I feel that preserving the function signature is a worthy trade-off.

### CODE REVIEW

**Comment by Tomaz-Vieira** [comment]
So it seems `mypy` doesn't support `ParamSpec` yet. Could anyone point me to the correct course of action here? Should I just wait until it does?

**Comment by srittau** [comment]
You can `# type: ignore` the affected lines for now.

**Review by srittau — APPROVED** [review]
Thanks!

For future reference: Please don't force push, we squash on merge, but force pushing makes reviewing harder.

**Comment by srittau** [comment]
The new primer warnings are probably due to the missing `ParamSpec` support in mypy and can be ignored.

**Comment by srittau** [comment]
@Tomaz-Vieira You could try merging master, where we just updated the pytype version used. Maybe that will help.

**Comment by rchen152** [comment]
Oh, I think pytype only recognizes paramspecs in Callables right now. So the `Generic[_P]` is probably what's tripping it up. Let me see if I can fix that.

**Comment by rchen152** [comment]
I just released a pytype version (2021.11.2) that should fix the pytype_test failure.

**Comment by srittau** [comment]
@Tomaz-Vieira could you update the pytype version in the requirements file?

**Pull request merged**
