### PR TITLE
add __init_subclass__ to 3.6

### PR DESCRIPTION
**Pull request by JelleZijlstra**
This will require a bit of additional work in mypy because `__init_subclass__` is an implicit classmethod, like `__new__`. It might be good to provide a way to express this in the stubs.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Can you file a separate issue with the mypy project about special-casing `__new__` and `__init_subclass__`? I think there are few enough of these that we should be able to just have a list of these exceptions in the mypy source code, no need to invent a new notation to put in the stubs.

**Comment by gvanrossum** [comment]
(Sorry, closed by mistake.)

**Comment by JelleZijlstra** [comment]
Yes, I'm working on a separate pull request to mypy; agree that special-casing there is probably sufficient. I think that doesn't need to block this change though.

Thanks for fixing the whitespace issue.

**Comment by gvanrossum** [comment]
Can you just link to the mypy PR then?

**Comment by JelleZijlstra** [comment]
Mypy changes are at https://github.com/python/mypy/pull/2654. I think this can be merged independently of that change though.

**Comment by gvanrossum** [comment]
Thanks! This will go out in the next mypy release (0.4.7) later this week.

**Pull request merged**
