### PR TITLE
Fix pkg_resource functions

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
These functions are actually bound methods from working_set.

Any differences in the signatures (e.g. `Sequence[str]` in `require()` are bugs.

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Hmm, seems pytype doesn't recognise the working_set declaration on the line before. But, it works fine with Mypy.

Any ideas how to define this in a way compatible with pytype?

Similarly, flake8 is probably ignoring the declaration as there is no assignment operator. I think that's just because the tool was written to lint implementation code, rather than stubs.

**Comment by hauntsaninja** [comment]
Unfortunately, I don't think pytype supports bound methods. This came up in https://github.com/python/typeshed/pull/4282#issuecomment-650477906 as well.
You could probably placate flake8 by using `x: y = ...`, though.

**Comment by Dreamsorcerer** [comment]
Yep, does that mean I need to revert back and just copy/paste the fixed annotations?

**Comment by hauntsaninja** [comment]
Yes, although I filed https://github.com/google/pytype/issues/761. @rchen152 is super responsive, so maybe not too long from now it'll work :-)

**Comment by Dreamsorcerer** [comment]
Will close this in the meantime.

**Pull request closed without merging**
