### PR TITLE
Add stubs for stdlib-list

### PR DESCRIPTION
**Pull request by kasium**

### CODE REVIEW

**Comment by kasium** [comment]
Not sure how to fix the pytype issue. Seems like an issue with pytype_test

**Comment by JelleZijlstra** [comment]
The pytype output is 

```
Ran pytype with 2538 pyis, got 2 errors.
stdlib-list/stdlib_list/__init__.pyi (3.9): AssertionError
stdlib-list/stdlib_list/base.pyi (3.9): AssertionError
```

I don't know what that means either. @rchen152 could you take a look?

**Comment by rchen152** [comment]
The full output for each AssertionError is:
```
Traceback (most recent call last):
  File "/usr/local/google/home/rechen/typeshed/tests/pytype_test.py", line 73, in run_pytype
    ast = loader.load_file(_get_module_name(filename), filename)
  File "/usr/local/google/home/rechen/typeshed/tests/pytype_test.py", line 102, in _get_module_name
    assert parts[0] == "stubs"
AssertionError
```
It's some sort of issue in pytype_test with determining the module name - maybe the 'stdlib' part of the package name is throwing it off? Investigating.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
Thanks for the contribution!

**Comment by kasium** [comment]
Thanks for the fast fix

**Pull request merged**
