### PR TITLE
redis > 4.0.0 stubs generated with stubgen

### PR DESCRIPTION
**Pull request by chayim**

### CODE REVIEW

**Comment by Akuli** [comment]
Redis stubs contain quite a lot of manually improved types. It might be easier to port them to redis 4.0.0 than to start over from scratch.

**Comment by chayim** [comment]
@Akuli As a module maintainer I'm looking for an **automated** way I can provide stubs. I'm open to including them in the package. What I want to avoid is manual work for something like this. I see it being a barrier to it getting done. Why not start with the automation, and while we may move to type hints in the future.. it's better than it is, in that at least there are a valid function list and the like?

**Comment by Akuli** [comment]
Finding the correct types involves manual work, which is why typeshed exists in the first place :)

It would be best to include types with redis-py itself and have mypy (or some type checker) in redis-py's CI, ensuring that the types stay up to date. That way there's nothing to automate, and you as a developer of redis-py can be more confident that the code is correct.

For redis 3.5.x, a lot has already been done. I have a few ideas for getting the correct types in redis 4.0.x, without doing all the manual work again:
- Apply types from typeshed `.pyi` files to redis 3.5.x `.py` files (there are tools that do this automatically), and then try to combine that with redis 4.0.x. Not great, because this would likely become one huge merge conflict.
- Try to apply the types from typeshed `.pyi` files directly to redis 4.0.x `.py` files. How well this works will likely depend on the tool being used to do this, but if the unchanged parts of API work, that would be nice. Then only new features would need manual work.
- Keep the manually edited stubs in typeshed, and do the manual work to bring them compatible with 4.0.x. We can use stubgenned stubs for entirely new code. Even though we have stubtest, which is a tool that compares `.py` and `.pyi` files, this might still be more difficult because the `.py` and `.pyi` files are separated.

**Comment by srittau** [comment]
In addition to what @Akuli said, from the release notes it seems that while there were quite a few additions, the number of backwards-incompatible changes were quite small, so reshuffling and extending the existing stubs seems to be the best course of action. stubtest will probably point out which functions we are missing.

**Comment by srittau** [comment]
I'm closing this per the discussion in this issue. Thank you for opening the PR!

**Pull request closed without merging**
