### PR TITLE
Remove incomplete thrift stubs that cause false positives.

### PR DESCRIPTION
**Pull request by carljm**
Per the precedent set in #1659 and #1664, I am removing the thrift stubs. As noted in https://github.com/python/typeshed/commit/84d0cbf7765e1be6862ec31136302091abb68b20, "These stubs are pure stubgen and might not be much good." In fact, they are not much good, and we saw false positives from them when upgrading mypy (because of their recent move from `2` to `2and3`, which made them visible to us for the first time). The false positives we saw are due to classes which are missing entirely from the stubs; comparing the stubs to the actual source of Apache thrift, they are woefully incomplete.

IMO these should be in their own project, used via PEP 561.

### CODE REVIEW

**Comment by carljm** [comment]
Side note: it seems that incomplete typeshed stubs are rather hard to work around, other than by sprinkling `type: ignore` all over the place. I tried stuff like this in our `mypy.ini` to no avail:

```
[mypy-thrift.*]
ignore_errors=True
follow_imports=skip
```

Not sure why these config options seem to be ineffective for typeshed stubs.

**Comment by gvanrossum** [comment]
Can you create a separate project to host the stubs you are deleting, and accepting improvements? That's what's been done consistently with other stubs we deleted. Since Thrift (IIUC) comes out of Facebook this could well be a Facebook GitHub project.

IIRC the other problem you mention (hard to work around missing stubs) is specific to packages whose top-level folder is in typeshed but with some specific submodules missing. Can you look for a mypy bug tracking that, or file one if you can't find one?

**Comment by JelleZijlstra** [comment]
These stubs are sufficiently stubby that I'm OK with just removing them now. Starting a new thrift-stubs project from scratch wouldn't be significantly more work than starting from scratch. @gvanrossum any objections to merging this now?

**Comment by gvanrossum** [comment]
OK, sounds good.

**Comment by carljm** [comment]
I've started things rolling on FB-hosted thrift stubs, it makes sense for us to own them. But merging this PR now doesn't make that any harder :-)

Couldn't find an existing issue for the `ignore-missing-imports` problem; filed https://github.com/python/mypy/issues/4515

**Pull request merged**
