### PR TITLE
Add re fullmatch() information

### PR DESCRIPTION
**Pull request by jstasiak**
One thing I'm not sure about here - I added ``Optional`` around ``Match[AnyStr]`` because the function can return ``None``, yet the other functions are specified to return just ``Match[AnyStr]`` - am I missing something here? Should there be ``Optional`` around return types of other functions too?

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Either way, you'll need to do `from typing import Optional` at the top to avoid breaking mypy.

**Comment by jstasiak** [comment]
Ugh, yeah, sorry about that. Let me update it.

**Comment by jstasiak** [comment]
I just updated one more thing (indentation), is there anything else I need to do?

**Comment by gvanrossum** [comment]
Can you open an issue regarding whether the other functions need Optional[] added? This may become more important once mypy starts enforcing strict optional checking.

**Pull request merged**
