### PR TITLE
Update jsonschema protocols.pyi

### PR DESCRIPTION
**Pull request by spagh-eddie**
These take in an instance, which need not be a JSON object. They could, for example, be arrays. See [this example](https://python-jsonschema.readthedocs.io/en/stable/api/jsonschema/protocols/#jsonschema.protocols.Validator.iter_errors) on the jsonschema docs.

```python
>>> schema = {"maxItems" : 2}
>>> Draft202012Validator(schema).is_valid([2, 3, 4])
False
```

### CODE REVIEW

**Comment by AlexWaygood** [comment]
@sirosen, mind taking a look? :)

"spagh-eddie" is a great GitHub username btw.

**Comment by sirosen** [comment]
> "spagh-eddie" is a great GitHub username btw.

Seconded. ❤️ 

---

I agree that a big union would be better than `Any`. I think it would be
```python
str | int | float | bool | None | Mapping[str, Any] | Sequence[Any]
```

I am in favor of this change though. I'll look at applying a near-equivalent change to `jsonschema` to reflect this.

**Comment by AlexWaygood** [comment]
> I agree that a big union would be better than `Any`. I think it would be
> 
> ```python
> str | int | float | bool | None | Mapping[str, Any] | Sequence[Any]
> ```

Since `Mapping` is covariant in its argument type, and `Sequence` is fully covariant, we can actually maybe do even better here, by using a fancy recursive type alias here:

```python
from typing_extensions import TypeAlias

_JsonParameter: TypeAlias = str | int | float | bool | None | Mapping[str, _JsonParameter] | Sequence[_JsonParameter]
```

And then use `_JsonParameter` as the annotation for all three methods.

@spagh-eddie, would you mind making the change?

**Comment by sirosen** [comment]
> recursive type alias

I wasn't aware that we had this capability! Looks like recent `mypy` versions have this problem solved.

I agree; the recursive type would be best.

**Comment by spagh-eddie** [comment]
> recursive type alias

I knew that of last year it was not supported. Glad to see support is starting!

**Pull request merged**
