### PR TITLE
Improve annotation for `tabular_data` parameter of `tabulate.tabulate`

### PR DESCRIPTION
**Pull request by kaibr**
The type of keys does not matter when a dict of columns is passed to tabulate. 

In particular, I have a case where I pass a dict with int keys, and it works fine, but is flagged by mypy.

### CODE REVIEW

**Comment by srittau** [comment]
The significant line is here: https://github.com/astanin/python-tabulate/blob/537d7b03932263062d37a7e747f19a385709b9f7/tabulate/__init__.py#L1502

So technically any value is supported as key, so `object` would be correct. But I don't think this is helpful. Instead, we should use `Any` as key with a comment what the expectations for keys are.

**Comment by JelleZijlstra** [comment]
Since Mapping is invariant in the key type, using `object` as the key type is likely inconvenient for many users.

**Comment by kaibr** [comment]
I wasn't aware of the invariance... Thanks for your patience @srittau and @JelleZijlstra.

I'm not sure about a potential comment wrt. the expectations on the key type. Since str can be called on any object there aren't any I'm aware of.

**Review by srittau — APPROVED** [review]
Thanks!

**Pull request merged**
