### PR TITLE
Changed: Return type of spec_from_loader and spec_from_file_location.

### LINKED ISSUE #5117: Wrong signature of "importlib.util.spec_from_loader" and "spec_from_file_location"
`spec_from_loader` and `spec_from_file_location` should return `Optional[importlib.machinery.ModuleSpec]`, just like `find_spec` does.

Currently, MyPy complains that my none check is unreachable.

### PR DESCRIPTION
**Pull request by 01-vyom**
Closes #5117

### CODE REVIEW

**Review by srittau — APPROVED** [review]
Looking at the new mypy_primer failures: It seems the code in question could actually benefit from a `None` check.

**Comment by 01-vyom** [comment]
> Looking at the new mypy_primer failures: It seems the code in question could actually benefit from a `None` check.

@srittau 

Where should the `None` check be added? I cannot find its location.

**Comment by Akuli** [comment]
For the first mypy_primer failure, the code is [here](https://github.com/freqtrade/freqtrade/blob/191a31d/freqtrade/resolvers/iresolver.py#L60-L61). It doesn't check what happens if `spec_from_file_location` returns `None`, but it otherwise checks for errors.

**Comment by 01-vyom** [comment]
Found the code. How should it be handled? by just adding a if statement that checks if `spec` is `None` , go to exception?

**Pull request merged**
