### PR TITLE
Replace Optional[object] with just object

### PR DESCRIPTION
**Pull request by scop**
As noted in #3137

### CODE REVIEW

**Comment by srittau** [comment]
This patch is of course semantically equivalent. But I think the difference between `Optional[None]` in #3137 and at least some of the cases here is that `None` is a special case. Take for example `BuiltinFunctionType.__self__`. I like the fact that `Optional[object]`, while semantically equivalent to `object`, communicates the idea that `None` is special in some way (it's a top-level function, not a method.)

**Comment by scop** [comment]
No strong opinions, just learning here. FWIW the reason in addition to not grokking that `None` goes for `object` in #3137 was that I grepped around the source tree and found these examples, and decided to follow suit. 

On a related note, a bunch of functions nearby the ones touched in #3137 and marked as taking an `object` actually fail if passed `None`. Should they be annotated some other way?

**Comment by srittau** [comment]
Yes, `object` means "accepts anything". If something does not accept `None` or some other type, it should either use a more specific type or, if that is impossible, use `Any`.

**Comment by scop** [comment]
Ok, thanks for the info. I'm fine with not merging this if you prefer that way, but for `inspect` I filed PR #3155 as follow-up.

**Comment by srittau** [comment]
Closing for the reasons mentioned by me. That said, this is always a judgement call, an just using `object` is never wrong.

**Pull request closed without merging**
