### PR TITLE
Removed conditional import from _collections_abc within collections/_…

### PR DESCRIPTION
**Pull request by erictraut**
…_init__.pyi. I don't know why this conditional was added, but it breaks type checking for 3.10 because a bunch of symbols used within this file are not defined.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
This is to implement the deprecation of using ABCs from collections:

> Deprecated since version 3.3, will be removed in version 3.10: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.9.

https://github.com/python/cpython/commit/c47c78b878ff617164b2b94ff711a6103e781753#diff-c92f871cb9b4aa1583c89f82cd416d58a5d70fff41faf41e45dedf775dbe7713

**Comment by erictraut** [comment]
So what is the correct fix? If you don't import these types, there are a bunch of undefined types in this file.

The CI tests iterate through different versions of Python, but I suspect that they are not covering Python 3.10 because this would have never passed the CI tests.

**Comment by hauntsaninja** [comment]
The correct fix should be to import what is needed without re-exporting. Yes, that's correct — we currently don't run Python 3.10 in CI.

**Review by hauntsaninja — APPROVED** [review]
Thanks, latest attempt lgtm!

**Comment by erictraut** [comment]
While I think this latest attempt will pass the current CI tests, I suspect it will break as soon as you start running the mypy tests with Python 3.10.

**Comment by hauntsaninja** [comment]
Yup. I already opened a PR to fix failures in the stdlib, your test failure conveniently shows what changes need to be made in third party stubs.

**Comment by erictraut** [comment]
@hauntsaninja, I've updated this PR to (I think) fix the incompatibilities that mypy_primer identified. Is there a way to trigger a new run to verify that no more issues are found?

**Comment by hauntsaninja** [comment]
Thanks for this!

**Pull request merged**
