### PR TITLE
Add stubtest to Travis for windows

### PR DESCRIPTION
**Pull request by CraftSpider**
Currently, the solution on the Travis end is somewhat hacky, and the builds aren't all perfect. But:
- Can run all the versions typeshed supports
- Stubtest now has platform-specific whitelisting
- Some minor issues are fixed

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Thanks so much for doing this!

**Comment by CraftSpider** [comment]
Python 3.5 and 3.6 are still failing, but once I get all the windows builds passing I'll take this out of draft form.

**Comment by hauntsaninja** [comment]
This is awesome!!! 🎈

**Comment by hauntsaninja** [comment]
The merge conflicts are an unfortunate race; I added stubtest py39 in #4110 earlier today

**Comment by CraftSpider** [comment]
Everything but the self-test is complete, and as that's been passing, it seems that windows stubtest builds for 3.5-3.8 are green. All it requires is a bit of configuration mess to get windows working with python

**Pull request merged**
