### PR TITLE
Allow `Any` type to be acceptable for the `msg` parameter in `logging.{info, warn, error, ...}

### PR DESCRIPTION
**Pull request by rowillia**
The stdlib accepts any value here as long as it is castable to a string:

https://github.com/python/cpython/blob/3.6/Lib/logging/__init__.py#L336
https://github.com/python/cpython/blob/2.7/Lib/logging/__init__.py#L319-L330

Ideally this would use Protocols but I don't see them in use in typeshed yet.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
I think we've discussed this in the past and decided that non-str logging messages should be a type error, even though the logging module accepts them as an accident of implementation.

**Comment by rowillia** [comment]
@JelleZijlstra IMHO we should strive to not have typeshed reject valid code.  AFAICT from the CPython code the `logging` module is intentionally casting to a string in py2 and py3.  Are Protocols valid in Typeshed yet?

**Comment by JelleZijlstra** [comment]
That's fair, @gvanrossum what do you think?

Protocols can be used I believe, but they don't make much of a difference here because any type is convertible to str.

**Comment by ilevkivskyi** [comment]
FWIW, protocols are already used in typeshed (in ``typing.py``). I think it makes sense if you feel they are necessary here (I didn't follow the whole discussion).

There is special casing in mypy, so that you can write ``from typing import Protocol`` in stubs and they will work correctly (i.e. you don't need to import ``typing_extensions`` in stubs).

**Comment by gvanrossum** [comment]
In general we don't want typeshed to be stricter than the implementation --
e.g. we've ruled before that undocumented private methods still need to be
represented, at least if there are calls in the wild.

In this particular case, I'm still sad to see the logging msg argument
change from str to Any, because it will reduce opportunities to catch
errors. In my experience *usually* this is a coding mistake. It's really
too bad that there are also codebases that do this intentionally and don't
consider themselves wrong, even though the docs imply it should be a string
("The *msg* is the message format string").

How bad is this for you, Roy?

**Comment by gvanrossum** [comment]
Merged conflict, will land when tests pass.

**Comment by gvanrossum** [comment]
Also, @rowilloa, sorry for the slow response!

**Pull request merged**
