### PR TITLE
make WindowsError an alias of OSError (new in Python 3.3)

### LINKED ISSUE #5028: missing winerror attribute
```python
import errno
import sys

def error_says_socket_not_connected(error: OSError) -> bool:
    if sys.platform == 'win32':
        return (error.winerror == 10057)
    else:
        return (error.errno == errno.ENOTCONN)
```

```
$ mypy --platform=linux a.py
Success: no issues found in 1 source file
$ mypy --platform=win32 a.py
a.py:7: error: "OSError" has no attribute "winerror"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

### PR DESCRIPTION
**Pull request by Akuli**
fixes #5028

### CODE REVIEW

**Comment by Akuli** [comment]
Mypy's test suite [assumes that using WindowsError is not a mypy error even when it's not available](https://github.com/python/mypy/blob/645ea62c1acf0c1751e698651ba1d6a6b64ef254/test-data/stdlib-samples/3.2/shutil.py#L66), so I can't make it available only on Windows, like it should be.

**Comment by Akuli** [comment]
Both of those errors come from this exact code (which is copy/pasted into a couple places in those files):

```
try:
    WindowsError
except NameError:
    WindowsError = None
```

I don't know why this has not been an error before and how to make it work again.

**Comment by srittau** [comment]
I don't think we need to worry about that error.

**Review by srittau — APPROVED** [review]
> Mypy's test suite assumes that using WindowsError is not a mypy error even when it's not available, so I can't make it available only on Windows, like it should be.

In that case the mypy test suite should be fixed. That said, as the PR doesn't change the status quo for that case, this looks good to me.

**Pull request merged**
