### PR TITLE
Add @typing.type_check_only

### PR DESCRIPTION
**Pull request by srittau**
Part of python/typing#597

### CODE REVIEW

**Comment by rchen152** [comment]
LGTM, but pytype doesn't use typeshed's typing.pyi, so someone else should probably review this.

**Comment by JelleZijlstra** [comment]
Let's wait for the typing PR first.

**Comment by JelleZijlstra** [comment]
Never mind, there is no typing PR, and I suppose this feature won't exist at runtime at all. I think to implement this we need an update to PEP 484 and to the Python docs first.

**Comment by srittau** [comment]
* python/peps#858
* python/cpython#11312
* [bpo-35581](https://bugs.python.org/issue35581)

**Pull request merged**
