### PR TITLE
PurePath.parent[s] should be properties

### LINKED ISSUE #701: parent(s) in pathlib no longer a property
In order to use self types, 49a8a28c297be475d5e2c8296f4000f8e22d3694 made `PurePath.parent` into a method. But it needs to be a property still. Maybe we could use `@property` here, so we can still use the self type?

### PR DESCRIPTION
**Pull request by gvanrossum**
Fixes #701.

### CODE REVIEW

**Comment by thomascellerier** [comment]
Using your fixed pathlib.pyi and my repro code from https://github.com/python/mypy/issues/2481 I get this now:
```Python
MYPYPATH=../mypy-stubs ./virtualenv/bin/python3 -m mypy repro.py 
repro.py:3: error: Invalid method type
```

**Comment by gvanrossum** [comment]
Thanks for testing! Apparently properties still cannot be used with a self-type.

@elazarg Do you understand why? Would it be easy to fix?

In the meantime I can change this PR to revert back to the original situation.

**Comment by elazarg** [comment]
Looks like mypy is right. It should be 
```python
_P = TypeVar('_P', bound='PurePath')
```
But the error message is confusing.

**Comment by elazarg** [comment]
(Instead of `_P = TypeVar('_P', 'PurePath')`)

**Comment by elazarg** [comment]
I guess there's something to be said here about catching it at the point of declaration. Value restriction is like saying the class is "final", or something.

**Comment by gvanrossum** [comment]
Hm, that message is definitely too short... :-) The error if the type variable's bound is not a superclass is much clearer. I presume the short error is somewhat coincidental?

Also, it seems using self-type with an unbounded type variable gives the same error. Why is this? Why can't I say this (at least in a stub)?
```python
T = TypeVar('T')
class C:
    def meth(self: T) -> T: ...
```
Anyway, if the current version of `pathlib.pyi` seems okay please say so.

**Comment by ambv** [comment]
I just noticed this problem on some of my code. The pull request fixes it for me.

**Pull request merged**
