### PR TITLE
fix redis str types

### PR DESCRIPTION
**Pull request by jtschoonhoven**
Currently the `redis` client library is typed to assume that methods that return a string-type response are encoded as `bytes`. However the client provides a `decode_responses` option that configures the client to automatically decode them to unicode. Manually decoding strings is tedious so this is a popular option. But enabling it currently invalidates the types defined in Typeshed.

This is an attempt to make the default string type configurable using generics and overloads.

The gist of this PR is to make the `Redis` class a generic that accepts either a `Text` or `bytes` type variable. It attempts to select between these automatically by detecting whether `encode_responses` is True, in which case it self-defines as a `Redis[Text]` rather than `Redis[bytes]` (the default).

This is my first Typeshed PR and I'm fairly new to generics and overloads, so comments and suggestions are very welcome.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This seems like a good idea but you'll also need overloads with `bool`, in case the user passes a variable of type bool that can't be inferred as True or False.

Looking at the primer failures, most of them are just minor changes in the signature, but the zerver ones (which are here: https://github.com/zulip/zulip/blob/master/zerver/lib/redis_utils.py#L22) are real; these mean that users upgrading to this PR and using strict mypy options will need to make some changes. On balance that seems fine though.

**Comment by JelleZijlstra** [comment]
(pushed the wrong button)

**Comment by hauntsaninja** [comment]
I'd really like something like https://mail.python.org/archives/list/typing-sig@python.org/thread/SZRXAEF2JO5RKOKS7V4JFT7LZOAOOMUU/ or https://github.com/python/typing/issues/307 for these kinds of situations

**Comment by jtschoonhoven** [comment]
@JelleZijlstra updated per your comment.
@hauntsaninja fully agree.

Thanks for your suggestions! LMK if there's any other changes or if you think it's ready to ship.

**Pull request merged**
