### PR TITLE
add types to logging

### PR DESCRIPTION
**Pull request by tharvik**
Add types to the `logging` module, in a python 2-3 compatible version.

### CODE REVIEW

**Comment by gvanrossum** [comment]
That's a lot of code... I will have to check whether it really works. If I find a flaw I can't quickly fix I may have to roll back. But for now, benefit of the doubt. Thanks!

**Comment by gvanrossum** [comment]
I found a few things.
- instead of TextIO, it should use IO[str] (since sys.stdout is the latter in 2.7)
- lots of code uses logging.WARN instead of logging.WARNING. I fixed these in d75e2ab224476d595b5c91494c50a5b8e8d5054f

A few more I'm not sure whether to fix:
- the message argument to error() etc. can be unicode in Python 2
- the message argument to error() etc. can be a non-string (apparently str() is applied somewhere)
- there are undocumented public-seeming attributes that are commonly used, e.g. Logger.level

I think I'll fix the unicode one (it's easy to use typing.Text instead) but I'm not sure about the others. It's true these are undocumented but if they are actual behavior that lots of code relies on I think we may have to add them.

**Comment by gvanrossum** [comment]
Also, log() takes an initial argument `lvl: int` -- I'll add this while I'm at it.

**Comment by tharvik** [comment]
> * lots of code uses logging.WARN instead of logging.WARNING. I fixed these in d75e2ab
> * there are undocumented public-seeming attributes that are commonly used, e.g. Logger.level

Theses codes are wrong, sadly, but for now, I'll add them. Do you have a list of wanted attributes?

> * the message argument to error() etc. can be unicode in Python 2

Let's switch to `Text` then.

> * the message argument to error() etc. can be a non-string (apparently str() is applied somewhere)

And from `Text`, here goes `Any`. But it is still wrong code (which, in a way, is supposed to be found by mypy).

**Comment by gvanrossum** [comment]
I fixed the one place I found that used logger.level in our code; I think it's pretty clear they were just taking a shortcut.

Regarding the message argument, I think it should be Text everywhere (and I've already made it that -- it should work because Text is defined in typing.pyi in typeshed, even though it's not yet in most runtimes since we're waiting for 3.5.2 to push out a new version).

**Pull request merged**
