### PR TITLE
Fix Python 3 round() signature

### PR DESCRIPTION
**Pull request by osandov**
In Python 3, the ndigits argument of round() defaults to None. If
ndigits is excluded or explicitly None, the result is always an int. If
ndigits is not None, the result should be the same type as the number.

$ cat test.py
from fractions import Fraction

print(type(round(0.1)))
print(type(round(0.1, None)))
print(type(round(0.1, 0)))

print(type(round(Fraction(1, 10))))
print(type(round(Fraction(1, 10), None)))
print(type(round(Fraction(1, 10), 0)))
$ python3 ./test.py
<class 'int'>
<class 'int'>
<class 'float'>
<class 'int'>
<class 'int'>
<class 'fractions.Fraction'>

Update the signatures to allow for an ndigits of None.

### CODE REVIEW

**Comment by osandov** [comment]
Ah my mistake, I forgot to run tests, although I don't understand the problem:
```
/tmp/tmp3oy8p8y2/mypy/typeshed/stdlib/3/builtins.pyi:923: error: Overloaded function signatures 5 and 6 overlap with incompatible return types
```
I believe that's
```
@overload
def round(number: SupportsRound[_T], ndigits: None) -> int: ...
@overload
def round(number: SupportsRound[_T], ndigits: int) -> _T: ...
```
and I don't see how that overlaps.

**Comment by gvanrossum** [comment]
ISTM the reason is that some mypy tests explicitly turn off strict optional (see https://github.com/python/mypy/blob/bb13ecc63ec172ab6c3348a4888bbc57288c69db/mypy/test/testpythoneval.py#L53), and those are the ones which fail. Without strict optional `None` is a valid value for `int` so there is indeed an overlap between those two signatures. I agree with Ivan: just put a `# type: ignore` on line 923, then it should pass.

This is a good reminder: surely there are users who disable strict optional in their code base, and we should not introduce errors for those in typeshed. (There are probably other files where this already happens -- perhaps we could extend mypy_test.py to run each test once with strict optional on and once with it off...)

**Comment by osandov** [comment]
Thanks, @gvanrossum, that makes sense, and the tests are happy now.

@ilevkivskyi, I tried out `reveal_type()` and there definitely seems to be some funny business with the `SupportsRound[_T] -> _T` overload.

```python
from fractions import Fraction


reveal_type(round(0.1))
reveal_type(round(0.1, None))
reveal_type(round(0.1, 0))

reveal_type(round(Fraction(1, 10)))
reveal_type(round(Fraction(1, 10), None))
reveal_type(round(Fraction(1, 10), 0))
```

```
$ mypy --custom-typeshed-dir ~/dev/typeshed test.py
test.py:4: error: Revealed type is 'builtins.int'
test.py:5: error: Revealed type is 'builtins.int'
test.py:6: error: Revealed type is 'builtins.float'
test.py:8: error: Revealed type is 'builtins.int'
test.py:9: error: Revealed type is 'builtins.int'
test.py:10: error: Revealed type is 'Any'
```

We get `Any` instead of `fractions.Fraction`. This seems related:

```python
from fractions import Fraction
from typing import SupportsRound, TypeVar


_T = TypeVar('_T')
def f(x: SupportsRound[_T]) -> _T:
    return x

reveal_type(f(1))
reveal_type(f(Fraction(1, 10)))
```

```
$ mypy --custom-typeshed-dir ~/dev/typeshed test.py
test.py:7: error: Incompatible return value type (got "SupportsRound[_T]", expected "_T")
test.py:9: error: Revealed type is 'builtins.int*'
test.py:10: error: Revealed type is 'Any'
```

I couldn't find in the `typing` documentation whether it's valid to use `SupportsRound` in this way. How do we express that the function takes a `SupportsRound` and returns whatever type was passed to it?

**Comment by ilevkivskyi** [comment]
`Any` is a known bug. IIRC mypy returns `Any` if more than one overload matches. You can also try `--no-strict-optional` to see how many of those `Any`s you get. I wouldn't worry to much about this however, we are working on this right now, hopefully we will fix this bug very soon.

**Pull request merged**
