### PR TITLE
Add wsgiref.types (Python 3.11+)

### PR DESCRIPTION
**Pull request by srittau**
Use `wsgiref.types` in `_typeshed.wsgi` on Python 3.11+.

Make `_typeshed.wsgi` types match `wsgiref.types` on Python < 3.11.

### CODE REVIEW

**Comment by srittau** [comment]
Stubtest doesn't like this for obvious reasons. Should we wait until 3.11b1 or should I add this module to the allowlist?

**Comment by srittau** [comment]
Although I'm unsure why this is an error when running with Python < 3.11 as `VERSIONS` should exclude `wsgiref.types` from being checked.

**Comment by AlexWaygood** [comment]
Looks like you need to change some imports in some other modules:

https://github.com/python/typeshed/blob/master/stdlib/wsgiref/handlers.pyi#L7

Your change to `VERSIONS` means that `wsgiref.types` is no longer available on <3.11, so you'll need to change that import to import things from `_typeshed.wsgiref` instead

**Comment by srittau** [comment]
Good catch, thanks!

**Review by JelleZijlstra — APPROVED** [review]

**Comment by AlexWaygood** [comment]
> Good catch, thanks!

Np!

**Review by AlexWaygood — APPROVED** [review]

**Pull request merged**
