### PR TITLE
Add functools.cached_property

### PR DESCRIPTION
**Pull request by srittau**
Part of #3319

### CODE REVIEW

**Comment by bluetech** [comment]
Would it be correct to change the `Any`s to `Type[_S]`?

**Comment by srittau** [comment]
It wouldn't be incorrect, but I decided against it, because the implementation just ignores those arguments.

**Comment by bluetech** [comment]
I think it will be better to have the correct type. Even though the implementation currently ignores the argument, I still would want the type-checker to error out if the wrong type is passed to the argument.

Either way, LGTM.

**Comment by bluetech** [comment]
Oh, and I forgot to say thanks!

**Pull request merged**
