### PR TITLE
`distutils` package was removed in 3.12

### PR DESCRIPTION
**Pull request by sobolevn**
Source: https://github.com/python/cpython/commit/0faa0ba240e815614e5a2900e48007acac41b214

### CODE REVIEW

**Review by AlexWaygood — APPROVED** [review]

**Comment by sobolevn** [comment]
What should we do with

```
   /home/runner/work/typeshed/typeshed/stubs/babel/babel/messages/frontend.pyi:3:6 - error: Import "distutils.cmd" could not be resolved (reportMissingImports)
  /home/runner/work/typeshed/typeshed/stubs/babel/babel/messages/frontend.pyi:8:15 - error: Base class type is unknown, obscuring type of derived class (reportUntypedBaseClass)
/home/runner/work/typeshed/typeshed/stubs/cffi/cffi/api.pyi
  /home/runner/work/typeshed/typeshed/stubs/cffi/cffi/api.pyi:1:8 - error: Import "distutils.core" could not be resolved (reportMissingImports)
```

?

**Comment by sobolevn** [comment]
I think that `METADATA.toml` can be updated with `versions =` metadata field, to indicate that some python versions are not supported (yet or at all).

**Comment by AlexWaygood** [comment]
Maybe we could import those things from `setuptools._distutils`, and add a dependency on `types-setuptools` for those stubs?

**Comment by sobolevn** [comment]
Looks like `distutils` is still required for `cffi`: https://foss.heptapod.net/search?search=distutils&nav_source=navbar&project_id=92&group_id=166&search_code=true&repository_ref=branch%2Fdefault

**Comment by sobolevn** [comment]
`babel` has all imports refactored: https://github.com/search?q=repo%3Apython-babel%2Fbabel%20distutils&type=code

**Review by AlexWaygood — APPROVED** [review]
LGTM, though I'd appreciate a third opinion from somebody

**Review by hauntsaninja — APPROVED** [review]
This seems approximately fine to me and unlikely to cause regressions. We can later investigate what exactly these packages do once they claim 3.12 support.

**Pull request merged**
