### PR TITLE
Fix return type of logging.getLogger

### PR DESCRIPTION
**Pull request by FrNecas**
The returned object can be influenced by using setLoggerClass. This
change allows one to create custom logger without having problems with
type hinting

In our project we created CustomLogger class to add more levels (it inherits from logging.Logger) and we are getting mypy errors. The return type could theoretically be any object (it doesn't have to inherit from logging.Logger) but I find this to be very unlikely. From documentation:

`The class should define __init__() such that only a name argument is required, and the __init__() should call Logger.__init__()"`

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This change isn't correct because `Type[Logger]` means that it would return a class object, not an instance, and `getLogger` in fact returns an instance.

I'm not sure if there's a good way to support your use case, unfortunately. The type system doesn't have a way to express "returns the type passed to the last call to setLoggerClass".

**Comment by FrNecas** [comment]
Oh, I see, thanks for pointing it out. What a pity that there is not a good way to support this. Is it not possible to express an equivalent of `Type[Logger]` but for instances? That would help a lot

**Comment by JelleZijlstra** [comment]
I'm not sure what you mean by that `Logger` already means "an instance of Logger or of a subclass".

**Comment by FrNecas** [comment]
Sorry for not being very clear here. I created a minimal example to better demonstrate the problem, so here is the code:

```python
import logging


class CustomLogger(logging.Logger):
    def test(self):
        print(42)


logging.setLoggerClass(CustomLogger)
logger: CustomLogger = logging.getLogger('test')
logger.test()
```

Based on your last comment, I would expect type checking to pass, since I am expecting instance of CustomLogger to be returned and it inherits from Logger. However, mypy fails with the following error:

`logging_test.py:10: error: Incompatible types in assignment (expression has type "Logger", variable has type "CustomLogger")`

Is there any way how to make this work either on the side of typeshed or on our side?

**Comment by srittau** [comment]
I can't see any way to make this work in the current type system. The only thing we can do is to work around this by returning `Any` from `getLogger()`, but I am not very keen on this. What you can do in this case is using `cast`:

```python
from typing import cast

...
logger: CustomLogger = cast(CustomLogger, logging.getLogger('test'))
...
```

**Comment by FrNecas** [comment]
I agree that returning `Any` is not the way to go. I've read about `cast` in the docs but before using it I first wanted to make sure that there is no better way to fix this. Thanks for your time and help, I think we can close this PR :)

**Pull request closed without merging**
