### PR TITLE
Backport many `ParamSpec`-related changes to Python 2

### PR DESCRIPTION
**Pull request by AlexWaygood**
This PR backports many `ParamSpec`-related changes (mostly made in PRs by @sobolevn) to Python-2 stubs.

- `bdb` changes were made in #7006
- `cProfile` changes were made in #7008
- `pdb` changes were made in #7009
- `profile` changes were made in #7010
- `concurrent.futures` changes were made in #6791

I'm not sure when `ParamSpec` was added to `contextlib` and `trace`, but the relevant Python-3 source code lines are here:
- https://github.com/python/typeshed/blob/5b39d07cd9d75a5342d0fe0b9eadf7d38f80ab12/stdlib/contextlib.pyi#L50
- https://github.com/python/typeshed/blob/97c490aec0c3963640c7154944f380403aac561e/stdlib/trace.pyi#L45-L48

### CODE REVIEW

**Comment by sobolevn** [comment]
Do we need `needs-backport-to-2.7` label? So it can be at least managable in PRs?

**Review by sobolevn — APPROVED** [review]
LGTM 👍

**Comment by AlexWaygood** [comment]
> Do we need `needs-backport-to-2.7` label? So it can be at least managable in PRs?

I don't think so -- I wouldn't usually bother backporting to Python 2, but this PR helps unblock https://github.com/PyCQA/flake8-pyi/pull/150 ;)

**Comment by srittau** [comment]
> Do we need `needs-backport-to-2.7` label? So it can be at least managable in PRs?

Backports to 2.7 are purely optional.

**Pull request merged**
