### PR TITLE
Use `ParamSpec` in `unittest.mock._patch`

### PR DESCRIPTION
**Pull request by sobolevn**
This is more like an experiment to see if the CI will be fine with it.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
This is incorrect, right? `patch` adds a new parameter to the decorated function.

**Comment by srittau** [comment]
At least in the `__call__` call it should probably be something like:

```python
def __call__(self, func: Callable[_P, _R]) -> Callable[Concat[_T, _P], _R]: ...
```

**Comment by sobolevn** [comment]
Yes, I don't think this PR is valid, due to some `_patch` hackery (there are cases when the last arg of patched function can be `Mock` object itself).

But, I was testing that the CI will pass for somewhat-invalid-somewhat-questionable ParamSpec. Looks like it passes 🤔 

Any ideas on how can we improve that?

**Comment by AlexWaygood** [comment]
> But, I was testing that the CI will pass for somewhat-invalid-somewhat-questionable ParamSpec. Looks like it passes 🤔
> 
> Any ideas on how can we improve that?

That sounds tricky — I'm not sure we'll ever be able to do away with human review entirely. And hey, human review worked pretty well here 😉

**Pull request closed without merging**
