### PR TITLE
Use `3.11` instead of `3.11-dev`

### PR DESCRIPTION
**Pull request by sobolevn**
It was just released 🎉

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
You may have to fix #8984 :)

**Comment by sobolevn** [comment]
```
Run actions/setup-python@v4
Version 3.11 was not found in the local cache
Error: Version 3.11 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by srittau** [comment]
Well, it seems macos is lagging behind.

**Comment by sobolevn** [comment]
Yes, we will have to wait for `3.11` on macos for a bit more.

**Pull request merged**
