### PR TITLE
DO NOT MERGE: checking if ci fails

### PR DESCRIPTION
**Pull request by Akuli**
I get a lot of CI failures on #12629, and I want to find out whether they appear on a PR that changes nothing important.

### CODE REVIEW

**Comment by AlexWaygood** [comment]
Huh, why isn't stubtest running on this PR?

**Comment by Akuli** [comment]
I wondered the same, and I don't know. `stubtest_stdlib.yml` has `paths: - "stdlib/**"` so it should pick up this change.

I will try pushing another commit, in case it magically fixes itself.

**Comment by Akuli** [comment]
It did magically fix itself. I will check if a new PR can reproduce the problem.

**Comment by AlexWaygood** [comment]
So weird. Ours not to reason why, I guess...

**Pull request closed without merging**
