### PR TITLE
Fix importlib.resources for mypy

### PR DESCRIPTION
**Pull request by ethanhs**
These were discovered after finding that the selenium and importlib.resources stubs weren't findable. Since clearly no one was using selenium, Jelle and I offline agreed we should just remove them.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Um, before you delete the selenium stubs, IIUC they are used by some Dropbox code. What's wrong with them?

**Comment by ethanhs** [comment]
@gvanrossum they haven't been accessible via mypy for a while, so they haven't been used. If selenium is used, we can work on cleaning them up. The main issues were they importing things that don't exist, and have many untyped methods.

**Comment by gvanrossum** [comment]
Oh, at Dropbox we use `--ignore-missing-imports` so we never notice the missing dependencies. So I would like to keep selenium (and add a `__init__.pyi`).

I am okay on the solution for importlib.resources, but please put in a comment explaining that the entire module is not present before 3.7 but we can't express this easily.

**Comment by gvanrossum** [comment]
Actually I take it back. It doesn't work with the Dropbox code base when I add `__init__.pyi` files. Just get rid of the selenium package.

**Comment by JelleZijlstra** [comment]
Let's drop Selenium in a separate PR.

**Pull request merged**
