### PR TITLE
remove "= ..." from top-level values

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Unblocks turning on Y092; see https://github.com/PyCQA/flake8-pyi/issues/86

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
OK, now normal flake8 thinks all of these names are undefined :). I'll back out the changes to names used elsewhere in the stub for now, and leave only the changes to the constants.

We could do some smarter things:
- Produce this error only if the name is not used elsewhere in the stub
- Teach flake8 to accept names as defined in stubs with only an `x: T` assignment
But that feels like too much work for the minor benefit of getting rid of a few `= ...`.

**Comment by AlexWaygood** [comment]
Simpler solution: just add Y092 to the list of error codes ignored in `typing.pyi` (https://github.com/python/typeshed/blob/425ba77bb29105473adf516d349ae69fc21f28cd/.flake8#L28)

**Comment by JelleZijlstra** [comment]
It's not just typing, but also something in pkg_resources that could easily appear in other stubs. I feel like the benefit of this change is low enough that it's not worth the risk of confusing a new contributor who runs into a false positive, so I'm not planning to build anything more complicated here.

**Comment by AlexWaygood** [comment]
> It's not just typing, but also something in pkg_resources that could easily appear in other stubs.

Yes, good point.

**Review by AlexWaygood — APPROVED** [review]

**Review by Akuli — APPROVED** [review]

**Pull request merged**
