### PR TITLE
Remove maxminddb stubs in favor of upstream

### PR DESCRIPTION
**Pull request by oschwald**
Upstream has [had a py.typed file since 2020-07-08](https://github.com/maxmind/MaxMind-DB-Reader-python/blob/main/HISTORY.rst#202-2020-07-28). The typeshed types are also
overly restrictive in some cases.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
Great, thanks!

I always get confused about the process of stubs removal, it's possible we might need to make a change marking stubs as obsolete before we can rm -rf. srittau will show up and tell us if anything needs to be done :-)

**Comment by srittau** [comment]
See https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-removal-policy

We should do one more release with the version set to `1.5` (the last supported Python 2 version) and `obsolete_since` set to `2.0.2`.

**Comment by srittau** [comment]
#6055

**Comment by srittau** [comment]
@oschwald Could you merge master into your branch? This PR is now ready to be merged.

**Comment by oschwald** [comment]
Thanks! I rebased.

**Pull request merged**
