### PR TITLE
BaseException.__init__ accepts **kwargs

### PR DESCRIPTION
**Pull request by anentropic**
This is to fix https://github.com/python/mypy/issues/4183

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Can you apply the same change in Python 3, and use `object` instead of `Any`?

**Comment by anentropic** [comment]
certainly!

why does Python 3 BaseException need `object` rather than `Any`?

I don't question it, I'd just like to understand.

I see it already has `*args: object` ... but a bunch of the other builtins have `**kwargs: Any`

**Comment by JelleZijlstra** [comment]
I think they should be `object` in both Python 2 and 3. `Any` generally means "the type system is not powerful enough to describe this type", and `object` means "all instances of object are accepted". In this case, we want the latter, not the former. (I think it's purely a semantic difference here; it doesn't actually accept the code type checkers will accept right now.)

**Comment by anentropic** [comment]
wouldn't that mean in Python 2 that old-style classes were not acceptable args?

So it's maybe correct for Python 2 but in Python 3 more of the `Any`s in the typeshed should be `object`?

**Comment by JelleZijlstra** [comment]
`object` includes old-style classes in Python 2 (`isinstance(o, object)` returns True for them). I don't think Python 2 and 3 should be different here.

**Comment by anentropic** [comment]
then I am curious what, if anything, would pass a type-check for `Any` but fail for `object` or vice-versa

I appreciate there's a semantic difference but it is pretty subtle, what makes it apply here?

**Comment by JelleZijlstra** [comment]
I don't think in this case the difference will directly affect type checker output; it's more about cleanliness, because we try to minimize usage of `Any` where possible.

In some cases it can make a difference though. If you have an API that takes a callback of type `Callable[[Any], None]`, then a user can pass a callback that actually takes `int` as an argument. But if you take a callback of type `Callable[[object], None]`, then the callback with an `int` argument will be rejected by the type checker.

Would it be easier to discuss this further in the typing chatroom at https://gitter.im/python/typing?

**Pull request merged**
