### PR TITLE
correct inheritance of io.BufferedRandom

### PR DESCRIPTION
**Pull request by tungol**
does not inherit from BufferedReader/BufferedWriter at runtime

I left off the previously indirect inheritance from BinaryIO, for this initial version, so there might be some fallout related to that.

### CODE REVIEW

**Comment by tungol** [comment]
missing BinaryIO didn't even make it as far as mypy-primer before causing trouble, so let's put that back.

**Comment by tungol** [comment]
mypy_primer:

The code being flagged is:
```python
with open(self.image.path / "Dockerfile", "rb") as f:
    lines = f.readlines()
f = TemporaryFile()
```

which looks to me like a straightforward re-use of a variable for two different but related types; totally normal for mypy to flag that.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by Dreamsorcerer** [comment]
While it's not actually inherited at runtime, the docs say "BufferedRandom is capable of anything [BufferedReader](https://docs.python.org/3/library/io.html#io.BufferedReader) or [BufferedWriter](https://docs.python.org/3/library/io.html#io.BufferedWriter) can do."

So, this change stops people from using BufferedRandom instances where BufferedReader is allowed. It's unclear to me if maybe it's better for mypy to cheat the inheritance here..

**Comment by tungol** [comment]
@Dreamsorcerer The strictly-correct solution for that situation would be to use a protocol rather than class-based types, although that's not always feasible when working with libraries and not code that you fully control. At any rate, I'd say that  `BufferedRandom is capable of anything BufferedReader or BufferedWriter can do.` remains true in typeshed even after this change was applied. "capable of" implies the set of methods, not inheritance, and protocols are the tool for specifying an interface by the shape of methods on a class.

**Pull request merged**
