### PR TITLE
Update `actions/github-script` to `v5`

### PR DESCRIPTION
**Pull request by sobolevn**

### CODE REVIEW

**Comment by Akuli** [comment]
github-script is used in several places, and this PR currently updates only one of them:

```
$ git grep github-script
.github/workflows/mypy_primer_comment.yml:        uses: actions/github-script@v3
.github/workflows/mypy_primer_comment.yml:        uses: actions/github-script@v3
.github/workflows/stubtest.yml:      - uses: actions/github-script@v3
```

Why should we update github-script anyway? The current `@v3` works.

**Review by hauntsaninja — CHANGES_REQUESTED** [review]
I mentioned this in the mypy PR, but Github Actions is not running the code in your pull request for mypy_primer comment. Pretty sure this PR breaks things: https://github.com/actions/github-script#breaking-changes-in-v5

The only way to test (other than iterating on master) is on your fork.

**Comment by srittau** [comment]
I'd rather update things sooner than later, so working on this is appreciated. Not updating leads to bugs and security issues down the line that don't get fixed. And that often means it's more complicated to update (due to a larger amount of changes), while being under time pressure to do so.

**Comment by sobolevn** [comment]
Yes, @hauntsaninja, you are right. This action:
- Was not running from my branch
- Had breaking changes

After some local experiments, I've managed to make it work:
- Comment action: https://github.com/sobolevn/typeshed/pull/4#issuecomment-1032474042
- Issue action: https://github.com/sobolevn/typeshed/issues/5

I've pushed all changed I applied to my version (I ruined my fork comletely 😆).
The only difference is `.rest` suffix for `github` http jobs. It is in line with the breaking changes described [here](https://github.com/actions/github-script#breaking-changes-in-v5).

**Review by srittau — APPROVED** [review]

**Comment by hauntsaninja** [comment]
Thanks!

**Pull request merged**
