### PR TITLE
Use lowercase `set`, `frozenset` and `deque` where possible

### PR DESCRIPTION
**Pull request by AlexWaygood**
This PR solely consists of changing `typing.Set` to `set`, `typing.FrozenSet` to `frozenset`, and `typing.Deque` to `deque`. It should hopefully have no mypy_primer diff at all.

### CODE REVIEW

**Comment by risicle** [comment]
I'm trying to understand the rationale behind doing this for the return types in `typing.ItemsView` and `typing.KeysView`, forcing them to return concrete `set`s instead of merely `Set` implementations.

**Comment by srittau** [comment]
`typing.Set` is just an alias for `set`, both concrete classes. Maybe you are thinking of the (confusingly named) `collections.abc.Set`?

**Comment by risicle** [comment]
I am indeed referring to `AbstractSet`, which would seem to make more sense here.

**Comment by JelleZijlstra** [comment]
If you have a proposed change to make, better to make an issue (or PR) instead of posting on a change from five years ago; lots has changed in typeshed since then.

**Comment by risicle** [comment]
I guess I thought it was more likely I had misunderstood something 👍

**Pull request merged**
