### PR TITLE
Add stubs for cmd

### PR DESCRIPTION
**Pull request by euresti**

### CODE REVIEW

**Comment by euresti** [comment]
So one doesn't just call these methods.  These methods are mostly called internally and can be overridden if necessary.  Basically everything depends on `line = self.stdin.readline()` and the default is `sys.stdin` which will be an `IO[str]` I guess you could pass an `IO[bytes]` but that will completely break in python3.  And in python2 one could pass an `IO[unicode]` but you're still using `getattr` on the methods so you really don't gain anything by doing so.

**Comment by matthiaskramm** [comment]
How about passing an `IO[unicode]`, in Python 2? That doesn't seem completely far-fetched.

**Comment by euresti** [comment]
Hmm. Looks like using `IO[unicode]` as stdout is pretty hard because of things like:
`self.stdout.write(str(self.intro)+"\n")`
You also have to change some of the attributes to make them unicode like this:
`cmd.prompt = u'(Cmd) '`

And sadly IO[str] is not compatible with IO[unicode] so I would have to make it Generic and make these IO[AnyStr] but only in python2.  I'm not sure such trouble is needed.  Might be best to wait until a user complains about it?  Or is that the wrong approach?

**Comment by matthiaskramm** [comment]
OK, let's stay with `str`.

**Pull request merged**
