### PR TITLE
Give shutil.which a return annotation

### PR DESCRIPTION
**Pull request by FuegoFro**
Without the return annotation, importing this file breaks mypy checks running with `--warn-incomplete-stub`.

### CODE REVIEW

**Comment by gvanrossum** [comment]
Thanks! I wonder if we should invoke mypy with `warn-incomplete-stub` in tests/mypy_test.py.

**Comment by gvanrossum** [comment]
(Hm, that doesn't seem to catch this. Strange.)

**Comment by FuegoFro** [comment]
Oh my bad, I think it was `--disallow-untyped-defs`. It looks like `--warn-incomplete-stub` only does things if you also have `--check-untyped-defs`. Turning on `--disallow-untyped-defs` brings up a *lot* of stuff though :/

**Comment by gvanrossum** [comment]
Oh, yeah, that's hopeless, because stubgen generates stubs without
annotations. This makes me sad but there are a lot more important issues.

**Pull request merged**
