### PR TITLE
Permissive behavior on Mapping.get, MutableMapping.pop, and some common mapping types.

### PR DESCRIPTION
**Pull request by mikeshardmind**
This better matches the runtime behavior of these functions. 
pop without a default has been left requiring a matching keytype

### CODE REVIEW

**Comment by mikeshardmind** [comment]
This appears to remove the need for a bunch of type ignores while being more correct to runtime, there are some projects that had typings based on the less accurate stubs in the typeshed which would be affected. 

I'm not sure if this should go further and have pop always accept object.

**Comment by Daverball** [comment]
Using `Any` rather than `object` may be less disruptive to existing code, since that code may violate contravariance on `object` while achieving mostly the same result. Expecting everyone to change their `Mapping`-like constructs in their own code seems like a bit much, considering these functions should only ever return the default value if you pass in a key type the corresponding `Mapping` doesn't contain.

Also this way you will stop catching some genuine problems, where you're doing an unnecessary hash lookup, for a relatively small gain in ergonomics. Although that gap could potentially be closed by strictness settings in type checkers, similar to how you can optionally report non-overlapping equality checks in mypy.

**Comment by mikeshardmind** [comment]
The choice to use object was intentional. This matches runtime behavior. The use of Any here is both unnecessary, would hide problems with subclasses that are are more restrictive, violating LSP, and would create many cases where these stubs are incompatible with strict typechecing settings. As is shown in some of the adjusted stubs, it's possible to add a type: ignore[override] in places where such an incompatible override is intentional.

**Comment by mikeshardmind** [comment]
Also:

> Also this way you will stop catching some genuine problems, where you're doing an unnecessary hash lookup, for a relatively small gain in ergonomics. Although that gap could potentially be closed by strictness settings in type checkers, similar to how you can optionally report non-overlapping equality checks in mypy.

The hash check is cheaper than the possible isinstance check to avoid it. You should see some of the places these changes *fix*

and faster than any of them, is 

```py
try:
    value = mapping[key[
except KeyError:
    value = default
```
, `__getitem__`, was not changed (for good reasons here involving retaining the usefulness of using type analysis to handle unreachable code), the same reason `.pop` without a default was not changed.

**Comment by AlexWaygood** [comment]
(Not trying to close off discussion, just linking to previous discussion for context)

This was previously discussed at https://github.com/python/typeshed/issues/6597 and https://github.com/python/typeshed/issues/8219

**Comment by mikeshardmind** [comment]
At the end of the day, I don't think the stubs should be cutting off things that are correct at runtime and are expressible in the type system. The type system is supposed to catch type errors, the current stubs instead flag correct code incorrectly. 

There are plenty of real world cases of this, evidenced alone by libraries that spoke out against the change to what we have now (see prior issues linked above) as well as several libraries that show up in the primer run that type ignore this rather than accommodate incorrect standard library typings.

It's also worth calling attention to the fact that [user defined Mapping's](https://docs.python.org/3/reference/datamodel.html#mappings) are not required to only work on Hashable types, you can define a mapping today which doesn't use hash but uses some other means of binning + equality, and there are occasional reasons to do so, such as mappings that are backed by data stores being able to write only a subset of changes based on a stable binning function, the Hashable requirement is an implementation detail of some Mappings, of which dict is one.

This is probably another great example of why subclassing ABCs rather than having common things expressed as protocols is detrimental

**Pull request closed without merging**
