### PR TITLE
Add __getattribute__ to _ast.AST().

### PR DESCRIPTION
**Pull request by Flameeyes**
The AST objects can have arbitrary attributes (and indeed the TODO in
3's _ast lists only a subset of attributes that are not always valid).

Instead of trying to guess which attributes are allowed, let the AST
object be more flexible.

### CODE REVIEW

**Comment by srittau** [comment]
What problem are you trying to solve? The previous code ensured at least some type safety for the existing attributes. Also, AST objects have usually a well-defined set of attributes per the ast described in the docs. Allowing arbitrary attributes seems counterproductive to me.

**Comment by Flameeyes** [comment]
The problem is that the AST parser can't easily tell you what it returned, and even when you know what you are parsing, further references are… tricky.

Also it looks like creating this manually can add any random attribute making it very hard to type-check correctly: `ast.AST(foo='bar').foo` is valid (but wouldn't be type-checked as is.)

**Comment by JelleZijlstra** [comment]
Even though manually created AST objects may contain arbitrary attributes, it's still more useful for the stubs to mention only the attributes that these objects normally have when returned by the Python parser, because that way we can help people who write AST-using code match mistakes.

If there are specific AST nodes for which the attributes are incomplete, we can fix them, but I don't think it's a good idea to add a blanket `__getattribute__`.

**Comment by JelleZijlstra** [comment]
Closing per my above comment.

**Pull request closed without merging**
