### PR TITLE
py3: traceback.pyi: added format_stack

### PR DESCRIPTION
**Pull request by PAStheLoD**
I considered adding other missing functions, but some are 3.4+ or 3.5+ only. Is there a better way than copy-pasting the whole file to the relevant 3.4/ and 3.5/ directories?

### CODE REVIEW

**Comment by matthiaskramm** [comment]
You can use https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking

So it's legal to write something like

```
if sys.version_info[0] >= (3, 4):
    def foo(x: Bar) -> Baz: ...
```

Note that mypy doesn't fully support this yet (the current version will assume that foo() is always there, also you can't put two different signatures into the `if` and the `else`).

So it's like adding a comment `# Python 3.4 only`, but it'll also get semantical meaning at some point.

**Comment by gvanrossum** [comment]
Could you also update the 2.7 version? Agreed with Matthias on how to add version-specific features.

**Comment by gvanrossum** [comment]
Merging this now, but please see previous comments -- ping?

**Comment by PAStheLoD** [comment]
Hello!

Sorry for the delay; I planned to get this done on the (last) weekend, but things got in the way (as they have a tendency to do).

Shall I submit a new PR or update this?

**Comment by gvanrossum** [comment]
Please update this one -- you can just add more commits. I'll squash them when I merge.

**Pull request merged**
