### PR TITLE
Improve werkzeug stubs

### PR DESCRIPTION
**Pull request by JelleZijlstra**
Removes a few default values that were not ...; adds missing types; harmonizes the stub between Python 2 and 3. We should merge the 2 and 3 stubs for this library, but that's a bigger project.

Mostly worked off https://github.com/pallets/werkzeug/blob/master/werkzeug/wrappers.py.

### CODE REVIEW

**Comment by ambv** [comment]
Rebase and I'll take a look.

**Comment by ambv** [comment]
MutableMapping definition is missing.

**Comment by JelleZijlstra** [comment]
Sorry for the bad merge, it's fixed now.

**Comment by JelleZijlstra** [comment]
@ambv could you take another look?

**Comment by ambv** [comment]
LGTM.

**Pull request merged**
