### PR TITLE
Use float instead of Union[int, float]

### PR DESCRIPTION
**Pull request by ymyzk**
CONTRIBUTING.md says
> use float instead of Union[int, float].

I found them using `$ git grep "Union\[int, float\]"` and `$ git grep "Union\[float, int\]"`.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Hm, I'm not sure I like this recommendation. For argument types it probably doesn't make a difference, but for attribute types it does.

**Comment by ymyzk** [comment]
I'm happy if I could know the background of this recommendation. I'll wait for comments.

**Comment by gvanrossum** [comment]
According to git blame, the original recommendation was a bit subtler:
```
-* When something is declared as taking only float, it also takes `int`. See
-  https://www.python.org/dev/peps/pep-0484/#the-numeric-tower. So write `float`
-  instead of `Union[int, float]`.
```
When this recommendation was moved (in 9656febae) it was also shortened.

Then again I'm not sure how any of the changes here could be harmful.

**Comment by JelleZijlstra** [comment]
I checked a few cases and agree that these changes aren't harmful. Thanks for making these fixes!

**Pull request merged**
