### PR TITLE
Remove Jinja2

### PR DESCRIPTION
**Pull request by Dreamsorcerer**
Looks like v3 includes type annotations now. Should this be removed from typeshed?

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Not sure I understand the tests. But, does it mean that the typeshed annotations must be kept as they are a dependency on flask annotations? And we can't test flask against the actual jinja2 library?

**Comment by Dreamsorcerer** [comment]
Or, rather, that I just need to put some additional annotations into flask to cover the now missing jinja annotations?

**Comment by JelleZijlstra** [comment]
Our policy is to keep the stubs around for at least six months for the benefit of users of older versions (https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-removal-policy). Looks like Jinja2 3 was released in May, so that's some time away. 

#5618 has discussion of how to make stub packages depend on non-stub packages.

**Comment by Dreamsorcerer** [comment]
No problem.

**Comment by srittau** [comment]
Also a duplicate of #5423, so we have our eyes on this.

**Pull request closed without merging**
