### PR TITLE
http.cookies._{quote,unquote} allow None

### PR DESCRIPTION
**Pull request by Akuli**
If these functions (added in #4914 ) get None arg then they return None

### CODE REVIEW

**Comment by UncleGoogle** [comment]
What about

```python
In [4]: _unquote({'a':123})
Out[4]: {'a': 123}

In [7]: _unquote([1,2,3])
Out[7]: [1, 2, 3]
```

...

Maybe also add overload with some kind of Generic Sequence?

**Comment by Akuli** [comment]
The docstrings says "string", so I guess those should be treated as errors. But the code checks for None, so maybe that should be supported.

**Comment by UncleGoogle** [comment]
In the code both usages of the `_quote` are shielded:
- https://github.com/python/cpython/blob/master/Lib/http/cookies.py#L611
- https://github.com/python/cpython/blob/master/Lib/http/cookies.py#L411

`_unquote` has check only in the internal implementation in `BaseCookie` 
- https://github.com/python/cpython/blob/master/Lib/http/cookies.py#L569
- and though `value_decode` https://github.com/python/cpython/blob/master/Lib/http/cookies.py#L581

but `value_decode` has no check itself like `_quote` and it is still a public method so that may be enough reason to stub `None`.

**Comment by UncleGoogle** [comment]
Bay the way, looks like `value_decode` and `value_encode` stubs in BaseCookie are wrong. I would suggest something like that, but note that I'm total beginner in typeshed

```
_A = TypeVar("_A", str)

class BaseCookie(Dict[str, Morsel[_T]], Generic[_T]):
    def __init__(self, input: Optional[_DataType] = ...) -> None: ...
    def value_decode(self, val: _A) -> Tuple[_A, _A]:  ...
    def value_encode(self, val: Optional[_A]) -> Tuple[str, str]: ...  # return type is tuple of str not tuple of _A because in case of val=None, ('None`, 'None`) will be returned
```

**Comment by Akuli** [comment]
>value_decode and value_encode stubs in BaseCookie are wrong

Sounds like a separate issue and/or PR to me

**Comment by hauntsaninja** [comment]
Thanks! re: sequences, it's pretty clear to me that the intention here is `str`

**Pull request merged**
