### PR TITLE
Introduce generic logger type in loggeradapter

### PR DESCRIPTION
**Pull request by hoefling**
The reason for this PR:
```py
import logging

logger = logging.getLogger()
adapter = logging.LoggerAdapter(logger, dict())
reveal_type(adapter.logger)
adapter.logger.getChild("fizz")
```
has no issues with `mypy`, but `pyright` reports
```
  /tmp/main.py:5:13 - info: Type of "adapter.logger" is "Logger | LoggerAdapter"
  /tmp/main.py:6:16 - error: Cannot access member "getChild" for type "LoggerAdapter"
    Member "getChild" is unknown (reportGeneralTypeIssues)
```
With the proposed changes, `pyright` is able to infer the correct type of wrapped logger instance.

### CODE REVIEW

**Review by srittau — APPROVED** [review]

**Comment by srittau** [comment]
Cc @Akuli as someone affected by this change.

**Review by Akuli — APPROVED** [review]
I have some functions that take an argument of type `logging.LoggerAdapter`, and I just have to change those to `logging.LoggerAdapter[logging.Logger]`.

**Comment by hoefling** [comment]
@Akuli @srittau is it an issue that one has to distinct between type checking and runtime now? I mean, `LoggerAdapter` is not subscriptable, so the type has to be either quoted (`x: "logging.LoggerAdapter[logging.Logger]"  = ...`) or aliased via e.g.
```py
if TYPE_CHECKING:
    import logging
    LoggerAdapter = logging.LoggerAdapter[logging.Logger]
else:
    from logging import LoggerAdapter
```

**Comment by srittau** [comment]
That's a general issue, but temporary. I would recommend to use `from __future__ import annotations` if possible or quoting of not possible.

**Comment by onursatici** [comment]
@srittau @hoefling  What would be the recommendation for inheritance? From what I understand importing annotations or quoting would not be as useful here
```python
import logging

class Adapter(logging.LoggerAdapter[logging.Logger]):
    pass
```
As `LoggerAdapter` is not subscriptable, this class will fail to initialise

**Comment by Akuli** [comment]
This is a common problem, and unfortunately it's annoying to deal with. This works, but it's messy and feels like a hack:

```python3
import logging
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    _LoggerAdapter = logging.LoggerAdapter[logging.Logger]
else:
    _LoggerAdapter = logging.LoggerAdapter

class MyAdapter(_LoggerAdapter):
    pass
```

Things that would help, but don't exist yet:
- Default values for generics (https://github.com/python/mypy/issues/4236)
- Pull request to CPython that makes `logging.LoggerAdapter` generic at runtime (similar PRs have been accepted in the past)

**Comment by hauntsaninja** [comment]
Linking the relevant section of mypy docs, in case it helps people: https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

**Comment by AlexWaygood** [comment]
I've opened https://github.com/python/cpython/pull/92129 to add `__class_getitem__` to the class in 3.11+.

**Pull request merged**
