### PR TITLE
Clean up pyrightconfig.json

### PR DESCRIPTION
**Pull request by jakebailey**
Two things:

- Exclude all Python 2 only folders and separate them into a section at the top. Some already existed, but some weren't and were passing anyway (so went unnoticed); future updates would potentially end up failing in confusing ways. (Plus, save some CPU cycles...)
- Remove all stubs that were excluded because of the inclusion of a global `__getattr__` function (which isn't a part of the "unknown" rule anymore).

### CODE REVIEW

**Comment by jakebailey** [comment]
Alternatively, I can reenable the `__getattr__` flagging rule if we want to keep new stubs clean like they were checked before, but `exclude` means no messages for any other problems will get flagged, which I view as worse.

**Review by JelleZijlstra — APPROVED** [review]

**Comment by JelleZijlstra** [comment]
I feel like an error just for `__getattr__` being present isn't very useful; if we want to find that we can just grep for `^def __getattr__`. I'd prefer to have pyright's other checks enabled on these stubs.

**Comment by srittau** [comment]
I'm a bit surprised that comments work in the JSON file.

**Comment by jakebailey** [comment]
> I'm a bit surprised that comments work in the JSON file.

The config is actually JSONC (same as VS Code settings.json, tsconfig.json, eslint configs, etc). All good config formats should have comments! 😄

**Comment by jakebailey** [comment]
(I should probably send something to mark the file as JSONC for GitHub, to make the red go away...)

**Pull request merged**
