### PR TITLE
Correct `add` parameter for tkinter.Misc.bind() function

### LINKED ISSUE #6332: tkinter: bind() method type-hint incorrectly has 'add' argument as a bool
The documentation for the `bind()` method https://docs.python.org/3/library/tkinter.html#bindings-and-events shows that the `add` parameter is a string.

The work from https://github.com/python/typeshed/pull/4347 made `add` be type-hinted as a `bool`.

So type-checking fails if doing: `add=""` or `add="+"` which is the documented way to use `add` in the `bind()` method.

### PR DESCRIPTION
**Pull request by JohnVillalovos**
The documentation[1] for the `bind()` method in tkinter states that the
`add` parameter is a string argument.

Previously the type-hints had it as a boolean. The implementation[2]
actually supports either a bool or a str (or any "truthy") value.

1. https://docs.python.org/3/library/tkinter.html#bindings-and-events
2. https://github.com/python/cpython/blob/32959108f9c543e3cb9f2b68bbc782bddded6f42/Lib/tkinter/__init__.py#L1372

Fixes #6332

### CODE REVIEW

**Comment by JohnVillalovos** [comment]
Never mind. I see https://github.com/python/typeshed/pull/6334 has already been proposed.

**Comment by sobolevn** [comment]
@JohnVillalovos sorry for stealing your issue 🙂 
Please, take a look at my PR. I will appreciate your feedback!

**Comment by JohnVillalovos** [comment]
> 
> 
> @JohnVillalovos sorry for stealing your issue 🙂 Please, take a look at my PR. I will appreciate your feedback!

No worries. Actually thank you for doing it! Much appreciated 👍😊

**Comment by JohnVillalovos** [comment]
I guess I should actually say спасибо @sobolevn 😊

**Comment by sobolevn** [comment]
Oh wow! Do you happen to know Russian? 😮 😊

**Comment by JohnVillalovos** [comment]
> 
> 
> Oh wow! Do you happen to know Russian? 😮 😊

Only a little. (my-lin-kee ???) 😟 My wife is Russian 👍 So privyet Nikita!

**Pull request closed without merging**
