### PR TITLE
Allow ipaddress._BaseNetwork.overlaps take either address family

### PR DESCRIPTION
**Pull request by cooperlees**
- Runtime can accept either address family and the returned `False` is the correct response
- This allows the use of an `Union[Union[IPv4Network, IPv6Network]]` typing
- Is the the correct fix OR should type checkers learn to see that there are checks for the correct .version or isinstance for these objects?
- Example code doing so and checking IP Version: https://github.com/cooperlees/aioexabgp/pull/5/

Small repro test Code:
```python
from ipaddress import (
    IPv4Network,
    IPv6Network,
    ip_network,
)
from typing import Union

IPNetwork = Union[IPv4Network, IPv6Network]

a: IPNetwork = ip_network("69::/56")
b: IPNetwork = ip_network("6.9.6.0/24")
c: IPNetwork = ip_network("69::/64")

print(f"IPv6 can never overlap IPv4: {a.overlaps(b)}")
print(f"IPv6 can overload IPv6: {a.overlaps(c)}")
```

- mypy errors:
```
cooper-mbp1:~ cooper$ mypy /tmp/test.py
/tmp/test.py:18: error: Argument 1 to "overlaps" of "_BaseNetwork" has incompatible type "Union[IPv4Network, IPv6Network]"; expected "IPv4Network"
/tmp/test.py:18: error: Argument 1 to "overlaps" of "_BaseNetwork" has incompatible type "Union[IPv4Network, IPv6Network]"; expected "IPv6Network"
/tmp/test.py:19: error: Argument 1 to "overlaps" of "_BaseNetwork" has incompatible type "Union[IPv4Network, IPv6Network]"; expected "IPv4Network"
/tmp/test.py:19: error: Argument 1 to "overlaps" of "_BaseNetwork" has incompatible type "Union[IPv4Network, IPv6Network]"; expected "IPv6Network"
Found 4 errors in 1 file (checked 1 source file)
```

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
There's no point in using the typevars now, it should just accept a `Union` as the argument type.

Also, there's a CI failure.

**Comment by cooperlees** [comment]
> There's no point in using the typevars now, it should just accept a `Union` as the argument type.

Can we open an issue describing how to fix this and I'll do a follow up PR? Is it we want to remove the TypeVar (e.g. `TypeVar("_N", IPv4Network, IPv6Network)`) and replace with `Union[IPv4Network, IPv6Network]` and the same for `IPv*Address` ... Do I understand that correctly?

```python
_A = Union[IPv4Address, IPv6Address]
_N = Union[IPv4Network, IPv6Network]
```

^^ If it's just this, I'm happy to do that if that's what you ment 100%. 

> Also, there's a CI failure.

Fixed.

**Comment by JelleZijlstra** [comment]
Sorry for the delay. There are other places in this file where the typevars do make sense, so you don't need to replace them completely. I'm just saying that in this one function, we don't need typevars any more.

**Comment by srittau** [comment]
Fixed in #4124. Thank you for your contribution!

**Pull request closed without merging**
