### PR TITLE
Make unittest.patch.* methods static

### PR DESCRIPTION
**Pull request by srittau**
Closes: #7542

### CODE REVIEW

**Comment by srittau** [comment]
Weird primer output. In the first failure, it seems that the first overload matches:

```
urllib3 (https://github.com/urllib3/urllib3)
+ test/test_queue_monkeypatch.py:25: error: No overload variant of "object" of "_patcher" matches argument types Module, "str", "Type[BadError]"  [call-overload]
+ test/test_queue_monkeypatch.py:25: note: Possible overload variants:
+ test/test_queue_monkeypatch.py:25: note:     def [_T] object(target, attribute: str, new: _T, spec: Optional[Any] = ..., create: bool = ..., spec_set: Optional[Any] = ..., autospec: Optional[Any] = ..., new_callable: Optional[Any] = ..., **kwargs: Any) -> _patch[_T]
+ test/test_queue_monkeypatch.py:25: note:     def object(target, attribute: str, *, spec: Optional[Any] = ..., create: bool = ..., spec_set: Optional[Any] = ..., autospec: Optional[Any] = ..., new_callable: Optional[Any] = ..., **kwargs: Any) -> _patch[Union[MagicMock, AsyncMock]]
```

`_T` is not constrained. Especially when compared to #7542. Anyone got a clue what's going on here?

**Comment by srittau** [comment]
The primer problems seem due to a mypy bug: python/mypy#7781.

**Comment by JelleZijlstra** [comment]
So what should we do here? I don't think we can afford to merge this until the mypy bug is fixed.

**Comment by srittau** [comment]
I agree. I marked this PR as "deferred" for now.

**Comment by srittau** [comment]
Fixed in python/mypy#13482, so should be part of the next mypy release.

**Comment by AlexWaygood** [comment]
> Fixed in [python/mypy#13482](https://github.com/python/mypy/pull/13482), so should be part of the next mypy release.

Sadly, the mypy fix didn't *quite* make it into 0.981, so we'll have to wait a little longer. But it should be in 0.99x.

**Comment by hauntsaninja** [comment]
If this is definitely fixed on mypy master, we should merge.

**Comment by AlexWaygood** [comment]
> If we want to run primer on this with the mypy fix, let me know and I can run it ad hoc.

That would be great!

**Review by AlexWaygood — APPROVED** [review]
I tried the original snippet in the issue out using mypy master, and unfortunately it doesn't seem as though this actually fixes the problem in the issue. With this patch applied, using mypy master, here is mypy's output on @graingert's snippet:

```
test.py:6: error: No overload variant of "object" of "_patcher" matches argument types Module, "str", "Dict[str, Type[KeyboardInterrupt]]"  [call-overload]
test.py:6: note: Possible overload variants:
test.py:6: note:     def [_T] object(target: Any, attribute: str, new: _T, spec: Optional[Any] = ..., create: bool = ..., spec_set: Optional[Any] = ..., autospec: Optional[Any] = ..., new_callable: Optional[Any] = ..., **kwargs: Any) -> _patch[_T]
test.py:6: note:     def object(target: Any, attribute: str, *, spec: Optional[Any] = ..., create: bool = ..., spec_set: Optional[Any] = ..., autospec: Optional[Any] = ..., new_callable: Optional[Any] = ..., **kwargs: Any) -> _patch[Union[MagicMock, AsyncMock]]
Found 1 error in 1 file (checked 1 source file)
```

However, this PR does seem like a good thing to do regardless of whether it fixes the issue.

**Pull request merged**
