### PR TITLE
pysftp: remove stubs

### PR DESCRIPTION
**Pull request by hauntsaninja**
Helps with #7815

While these stubs were contributed to us relatively recently, a little
over a year ago, the underlying project has had no releases or commits
in the last six years and the last Python they have a classifier for is
Python 3.5

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
cc @hatal175 who added these in #5120

**Comment by hatal175** [comment]
No hard feelings :P

**Comment by hauntsaninja** [comment]
The types-pysftp package will continue to exist and help people! :-)

I am slightly confused about the CI failures in #7815 (feels like it should be picking up a new enough paramiko), so it's still a little TBD what the options are

**Review by AlexWaygood — APPROVED** [review]
I'm fine with this if @hatal175 is :)

**Comment by hauntsaninja** [comment]
Closing this till we figure out what happened in #7815

**Pull request closed without merging**
