### PR TITLE
Adds `redis/commands.pyi`

### PR DESCRIPTION
**Pull request by sobolevn**
Generated using `stubgen` from `master` version of https://github.com/redis/redis-py

### CODE REVIEW

**Comment by sobolevn** [comment]
What should we do for this case?

```

/tmp/tmp8if1xe_2/bin/pip install redis==3.5.* mypy==0.910
MYPYPATH=/home/runner/work/typeshed/typeshed/stubs/redis /tmp/tmp8if1xe_2/bin/python -m mypy.stubtest --ignore-missing-stub --custom-typeshed-dir /home/runner/work/typeshed/typeshed redis --allowlist /home/runner/work/typeshed/typeshed/stubs/redis/@tests/stubtest_allowlist.txt
error: redis.commands failed to import: No module named 'redis.commands'
Stub: at line 1
MypyFile:1(
  /home/runner/work/typeshed/typeshed/stubs/redis/redis/commands.pyi)
Runtime:
MISSING

stubtest failed for redis
```

**Comment by sobolevn** [comment]
> hold off on merging this PR until the change is released

I'm fine with that! 👍

**Comment by sobolevn** [comment]
Related https://github.com/python/typeshed/pull/6368
CC @srittau

**Comment by srittau** [comment]
I'm sorry, I missed this PR. #6368 is not complete but moved some existing definitions over from `redis/client.pyi`.

**Comment by JelleZijlstra** [comment]
Seems like #6368 superseded this, thanks for your work!

**Pull request closed without merging**
