### PR TITLE
Fix wrong connection argument name

### PR DESCRIPTION
**Pull request by kasium**
The name should be user and not username

### CODE REVIEW

**Comment by kasium** [comment]
Can someone please merge this?

**Review by JelleZijlstra — APPROVED** [review]
A bit hard to verify as this is apparently a closed-source C extension module and the docs don't cover the `Connection.__init__` interface, but `Connection(user=42)` complains about a wrong type while `Connection(username=42)`, so I think you're right.

**Comment by kasium** [comment]
@JelleZijlstra thanks for checking. I found the issue while using hdbcli and yes, C doesn't make it easier :-)

**Comment by JelleZijlstra** [comment]
I'm OK with C as long as I can actually see the source code :)

**Pull request merged**
