### PR TITLE
Add missing Optional types in urllib.parse

### PR DESCRIPTION
**Pull request by robertschweizer**
None values are accepted, and interpreted as empty (byte) strings by
some urllib.parse functions.

This is probably not the desired behavior, but can be useful especially
when passing through values that default to None in outside functions.

Signed-off-by: Schweizer, Robert <rschweizer@definiens.com>

### CODE REVIEW

**Comment by gvanrossum** [comment]
I see a problem though. When I call e.g. `parse_qs(None)` what's the return type?

**Comment by robertschweizer** [comment]
It returns an empty dictionary, which fits the return type annotation and is the same behavior as for empty strings. 

`None` is interpreted as an empty byte string though. E.g. `urlparse(None)` returns a `ParseResultBytes` instance.

**Comment by gvanrossum** [comment]
Hm, that's unfortunate (choosing bytes is arbitrary). However this should occur rarely -- usually the static type of the argument will be Optional[bytes] or Optional[Text], not None.

I'll leave it to others to approve this PR.

**Comment by srittau** [comment]
I am not sure whether we should change the types. Allowing `None` seems not to be a conscious design decision, but just a side-effect of using `if x` to check for an empty string in `_decode_args()`. Relying on this to work is one of the things that a type checker is supposed to prevent, in my opinion.

**Pull request merged**
