### PR TITLE
Remove google/__init__.pyi

### PR DESCRIPTION
**Pull request by nipunn1313**
Since google is a namespace package, it won't have an init.

Depends on https://github.com/typeshed-internal/stub_uploader/pull/33 - so the stub uploader can handle it

Should wait until
https://github.com/microsoft/pyright/commit/5e38fabc3a98fcdbda21ebac875019d2b08895a9 gets in. See [discussion](https://github.com/microsoft/pyright/issues/2113#issuecomment-932688627)

May also want to wait until https://github.com/python/mypy/pull/9636 gets in - as it'll be confusing for folks to have to add the `--namespace-packages` flag to mypy for things to work.

### CODE REVIEW

**Comment by JelleZijlstra** [comment]
Waiting for the mypy change might not be a good idea; it's likely going to take a while.

**Comment by nipunn1313** [comment]
I've made some progress with python/mypy#11257 , python/mypy#11259 , python/mypy#11261 .
I'm hoping to get python/mypy#9636 across the finish line.

That being said - this doesn't strictly depend on it, but it will confuse *everyone* using protobuf stubs - since they'll have to add this `--namespace-packages` flag for things to continue to work.

> Depends on typeshed-internal/stub_uploader#33 - so the stub uploader can handle it
> Should wait until microsoft/pyright@5e38fab gets in.

^ both of these have gotten in!

**Comment by srittau** [comment]
Is this PR viable now?

**Comment by nipunn1313** [comment]
*Ideally* https://github.com/python/mypy/pull/9636 gets in first. I think it is ready, though I sense some hesitancy in the thread there.

Otherwise, we'll have to educate a lot of folks to pass `--namespace-packages` to use this stub.

If we think https://github.com/python/mypy/pull/9636 will have a lot of delay - I can instead look into alternate ways to encourage people to set `--namespace-packages` manually (perhaps a useful error message in the right place). It feels a little embarrassing to mypy to do so, since the feature has been stable in python itself for so long.

**Comment by srittau** [comment]
Ok, lets wait for mypy 0.940, in case python/mypy#9636 goes into it. If it doesn't make 0.940 for some reason, we can merge it here first.

**Comment by hmc-cs-mdrissi** [comment]
Now that 0.940 has been released can we merge this?

My interest is that the lack of this, means pyright produces a number of errors when google libraries are imported and that google stub information gets lost. At moment I've mostly just followed a practice of type ignore and let several google libraries behave like Any.

**Comment by JelleZijlstra** [comment]
I'm OK with merging this.

@hauntsaninja do you think the namespace packages change will make it into mypy soon?

**Comment by hauntsaninja** [comment]
Probably 🤷

I'm fine with this being merged

**Pull request merged**
