### PR TITLE
mypy_primer: post failures as comments

### PR DESCRIPTION
**Pull request by hauntsaninja**

### CODE REVIEW

**Comment by srittau** [comment]
Good idea!

**Comment by JelleZijlstra** [comment]
Somebody on the Black repo (psf/black#1764) suggested using "GitHub Annotations", which seem like they serve a similar purpose. I can't find a lot of documentation for that feature  though.

**Comment by hauntsaninja** [comment]
The thing that's blocking this is that the `pull_request` event doesn't give you a token with write permissions, so the API call to comment fails.
It looks like Github recently added a way around this: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
But a) it means that this is much harder to test, b) I think some of the Github variables might change values, so would need to make sure the cloning / checking out logic in mypy_primer continues to work. All in all, a little painful — if someone else wants to pick this up, please do!

I think what Jelle is mentioning is https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#create-a-check-run. I'll take a look, might be a better fit.

**Comment by hauntsaninja** [comment]
It looks like this just worked once it was merged, so maybe that's what needs to happen here: https://github.com/hauntsaninja/typeshed/pull/1#issuecomment-716280941

**Review by srittau — APPROVED** [review]
Let's try this.

**Pull request merged**
