### PR TITLE
move and rename from `ctypes._FuncPointer` to `_ctypes.CFuncPtr`

### PR DESCRIPTION
**Pull request by junkmd**
- Please see #10132

### CODE REVIEW

**Comment by junkmd** [comment]
Stubtests are failed.

Quoting from https://github.com/python/typeshed/actions/runs/4889040813/jobs/8727237786?pr=10140#step:5:19,

> error: _ctypes.CFuncPtr cannot be subclassed at runtime, but isn't marked with @final in the stub

However, the return value of `CFUNCTYPE` is a subclass of `_ctypes.CFuncPtr` at runtime.
https://github.com/python/cpython/blob/872cbc613245db7a1fc5e6656ed0135d2e115f50/Lib/ctypes/__init__.py#L73-L107

I wonder why it occurs.

Any opinions would be appreciated.

**Comment by JelleZijlstra** [comment]
Stubtest probably just tries to do something like:

```
>>> class X(ctypes._CFuncPtr): pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: class must define _flags_ which must be an integer
```

It can only be subclassed if the subclass sets fields like `_flags_`. I think we can simply add it to the allowlist (`tests/stubtest_allowlists/py3_common.txt` probably).

**Comment by junkmd** [comment]
Both adding `_ctypes.CFuncPtr._flags_` to allowlists(6399ecd) and adding the `_flags_` attribute to `_ctypes.CFuncPtr`(caedbda) doesn't resolve this problem 😭.

**Comment by AlexWaygood** [comment]
> Both adding `_ctypes.CFuncPtr._flags_` to allowlists([6399ecd](https://github.com/python/typeshed/commit/6399ecd425efade47a6c73ba830984f58ccad094)) and adding the `_flags_` attribute to `_ctypes.CFuncPtr`([caedbda](https://github.com/python/typeshed/commit/caedbdacd082071fda86cf1fa0e2d0d6ac7ae31c)) doesn't resolve this problem 😭.

You needed to add `_ctypes.CFuncPtr` to the allowlist rather than _ctypes.CFuncPtr._flags_` — I've corrected it for you :)

**Review by AlexWaygood — APPROVED** [review]

**Comment by junkmd** [comment]
@AlexWaygood 
Thank you for the correction.

**Review by JelleZijlstra — APPROVED** [review]

**Pull request merged**
