### PR TITLE
Fixed return type for OpenSSL.crypto.X509Name.get_components()

### PR DESCRIPTION
**Pull request by jolaf**
Documentation is unclear in this matter:
https://www.pyopenssl.org/en/stable/api/crypto.html?highlight=get_components#OpenSSL.crypto.X509Name.get_components

But the implementation actually returns `[(bytes, bytes), ...]`.

### CODE REVIEW

**Comment by jolaf** [comment]
Thanks! I wonder, what is the release schedule now, when can I expect the fix to get to `pip`?

**Comment by hauntsaninja** [comment]
It's already out: https://pypi.org/project/types-pyOpenSSL/20.0.4/#files

**Comment by srittau** [comment]
@jolaf There is a new release every three hours (if there are changes), starting midnight UTC.

**Comment by jolaf** [comment]
> It's already out: https://pypi.org/project/types-pyOpenSSL/20.0.4/#files

Oh, I see. I used `pip install --upgrade types-openssl-python`.
Maybe, it would be good to remove the old package from the repository to avoid confusion?

**Pull request merged**
