### PR TITLE
Set difference strictly

### LINKED ISSUE #1840: Set difference unexpectedly permissive
Mypy passes accepts the following snippet, even though the set subtraction is guaranteed to be a no-op.

```
    a: Set[str] = set(["hello"])
    b: Set[bytes] = set([b"world"])
    b -= a
```

Would it make sense to require `Set[T]` for both arguments to a difference operation?

### PR DESCRIPTION
**Pull request by proost**
close #1840

I think sub operator too.
Because "frozenset" also strictly compare.
It makes sense for consistency.

### CODE REVIEW

**Comment by JukkaL** [comment]
This can generate false positives, since the set item types arguably only need to be overlapping, not compatible. I wouldn't be surprised if this would generate issues with our internal codebases (but I haven't verified yet). I'll run this against our internal codebases next week (if I remember to :-).

**Comment by srittau** [comment]
@JukkaL Did you remember? :)

**Comment by JukkaL** [comment]
I've been too distracted. I'll try to find some time to try this out later this week.

**Comment by srittau** [comment]
I am going ahead and merge this. If this causes too many problems down the line, we need to revert it.

**Comment by JelleZijlstra** [comment]
@hauntsaninja ran mypy-primer on recent master (python/mypy#9290) and one new false positive seems to come from this change:
`+ homeassistant/helpers/device_registry.py:568: error: Unsupported operand types for - ("Set[str]" and "Set[Optional[str]]")`

**Comment by srittau** [comment]
@JelleZijlstra Is that really a false positive, though? While we could add a special exception for `None`, the right-hand side set containing a `None` hints at a potential problem to me. Of course, it will work at runtime, but so will `Set[str] - Set[int]`.

**Comment by JelleZijlstra** [comment]
Honestly the code (which is at https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/device_registry.py#L568) doesn't seem particularly problematic to me. It's a different story if you have completely non-overlapping types like `str` and `int`, but `Set[str] - Set[Optional[str]]` doesn't seem like an unreasonable thing to do.

**Comment by JelleZijlstra** [comment]
Then again, maybe this case is rare enough that the change is still worth it; we'll have to see how often this comes up in practice.

**Pull request merged**
