### PR TITLE
Removed imported symbols that are not accessed or re-exported (third_party part 4 of 4)

### PR DESCRIPTION
**Pull request by erictraut**
Removed imported symbols that are not accessed or re-exported within third_party stubs (part 4 of 4). These were all identified as unused symbols by the pyright type checker and language server.

### CODE REVIEW

**Comment by hauntsaninja** [comment]
I'm not sure removing the reexports as done in "Fixed regression caught by CI" is correct. I might be missing something, but it seems like type checkers now just won't be able to find the things in `six.moves` / the CI complaint is a bug in pytype?

**Comment by erictraut** [comment]
It was unclear to me whether these were meant to be re-exports. They previously weren't, but I couldn't think of any reason that this import would have been included other than to indicate a re-export. Maybe someone with more knowledge of the six package could comment on the intended interface contract of the library.

**Comment by hauntsaninja** [comment]
Yup, they're intended as reexports. I think the course of action here is to revert f9fae4d and maybe @rchen152 or someone else could help figure out what pytype's complaints are.

**Comment by erictraut** [comment]
I reverted the change and will wait for someone else to help with the pytype issue.

**Comment by srittau** [comment]
For now, you can just place the affected files on the pytype exclude list.

**Pull request merged**
