### PR TITLE
add types to ssl for py2

### PR DESCRIPTION
**Pull request by tharvik**
See #239.

Python 2 and 3 version are mostly compatible, just a matter to move it to `2and3` and add some conditionals.

The tests for python 2 are not very tight, I can check for differences between 2.7.9 and 2.7.10, but then the conditionals are not really nice to read.

### CODE REVIEW

**Comment by gvanrossum** [comment]
I think it's better to leave this separate between Python 2 and 3. All these things that aren't in Python 2 will appear to exist until we finally fix mypy's platform checking. Also TBH the idiom `if not (2,) < sys.version_info < (3, 4):` is hard to get used to.

**Comment by tharvik** [comment]
Done.
And yeah, you are right, it is not a readable way to write conditional, it was only the most concise.

**Comment by gvanrossum** [comment]
I'm going to revert this, since it is missing some symbols that were defined previously. I don't have a full list yet, but here are some:
```
SSL_ERROR_EOF
SSL_ERROR_SSL
SSL_ERROR_SYSCALL
SSL_ERROR_WANT_CONNECT
SSL_ERROR_WANT_READ
SSL_ERROR_WANT_WRITE
SSL_ERROR_ZERO_RETURN
```

**Comment by tharvik** [comment]
I don't see any mention of any `SSL_ERROR_*` in the [constants](https://docs.python.org/3/library/ssl.html#constants), maybe the code based itself only on the support of `cpython`?

**Comment by gvanrossum** [comment]
These constants are mentioned in the docstring in ssl.py, see help('ssl'). I think they should be added regardless of whether they are documented on docs.python.org (docs are often not the only source of truth).

**Comment by tharvik** [comment]
I'll add these then (not right now though), but shouldn't docs.python.org reflects the standard where as the docstring is closed to the implementation?

**Pull request merged**
