### PR TITLE
Extend Py3 Queue type hints

### PR DESCRIPTION
**Pull request by Sterbic**

### CODE REVIEW

**Comment by Sterbic** [comment]
I only need `all_tasks_done` in production but added all the conditions since I was touching the file. See code snippet below: 

```
async_queue = queue.Queue()
....
def unblock_queue_callback() -> None:
     with async_queue.all_tasks_done:
         async_queue.all_tasks_done.notify_all()

timeout = MyTimeout(60, callback=unblock_queue_callback)
        
# wait for all async logging jobs to finish
try:
    with timeout:
        async_queue.join()
except MyTimeoutError as ex:
    log()
```

Is the goal of the typeshed to be a backup documentation or to be as accurate at possible and minimise type errors?

**Comment by gvanrossum** [comment]
The goal is in between. It's not meant as documentation but it is meant to
help you find problems in your code; I think using private attributes is an
example of that. Unless there's a common idiom that accesses a private or
undocumented attribute, you should just add `# type: ignore` to your code.

**Comment by Sterbic** [comment]
Fair enough, thanks for the explanation! So far I always viewed `# type: ignore` as something to be avoided at all costs.

In an ideal scenario, should those `Queue` attributes be private rather than public?

**Comment by gvanrossum** [comment]
Yeah, it was probably a mistake (made 20 years ago) to have those attributes not start with `_`.

**Pull request closed without merging**
